plugins { id 'base' }
allprojects {
    group = 'dev.abros.rivet'
    version = rootProject.property('rivetVersion')
    repositories { mavenCentral() }
}
subprojects {
    apply plugin: 'java-library'
    java { toolchain { languageVersion = JavaLanguageVersion.of(21) } }
    tasks.withType(JavaCompile).configureEach { options.encoding = 'UTF-8' }
    tasks.withType(AbstractArchiveTask).configureEach { preserveFileTimestamps = false; reproducibleFileOrder = true; includeEmptyDirs = false }
    dependencies {
        testImplementation platform('org.junit:junit-bom:5.11.4')
        testImplementation 'org.junit.jupiter:junit-jupiter'
        testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
    }
    tasks.withType(Test).configureEach { useJUnitPlatform(); testLogging { events "failed"; exceptionFormat "full" } }
}
