package dev.abros.rivet.core;
import com.google.gson.*;
import org.junit.jupiter.api.*;
import org.junit.jupiter.api.io.TempDir;
import java.nio.file.Path;
import java.util.UUID;
import static org.junit.jupiter.api.Assertions.*;
@Tag("postgres") class CommunityHudTest {
 @TempDir Path world;CommunityStore store;CommunityStore.Actor actor=new CommunityStore.Actor(UUID.randomUUID().toString(),"Player",false,false),other=new CommunityStore.Actor(UUID.randomUUID().toString(),"Other",false,false);
 @BeforeEach void start()throws Exception{store=new CommunityStore(TestDatabase.database(world),CommunityStore.defaults());store.seen(actor);store.seen(other);}
 @AfterEach void close()throws Exception{store.close();}
 JsonObject request(){var j=new JsonObject();j.addProperty("action","community");j.addProperty("section","home");j.addProperty("op","hud");j.addProperty("request",UUID.randomUUID().toString());return j;}
 @Test void initialSnapshotSummarizesBacklogAndFeedIsActorScoped()throws Exception{store.externalNotice(actor.id(),"Old");store.externalNotice(other.id(),"Private");var first=store.request(actor,request());assertEquals("hud",Json.str(first,"kind"));assertEquals(1,first.get("unread").getAsInt());assertTrue(first.getAsJsonArray("notices").isEmpty());store.externalNotice(actor.id(),"New");var next=request();next.add("since",first.get("sequence"));var reply=store.request(actor,next);assertEquals(1,reply.getAsJsonArray("notices").size());assertEquals("New",Json.str(reply.getAsJsonArray("notices").get(0).getAsJsonObject(),"title"));assertFalse(reply.get("more").getAsBoolean());}
 @Test void feedPagesWithoutDroppingNotices()throws Exception{var first=store.request(actor,request());for(int n=0;n<65;n++)store.externalNotice(actor.id(),"Notice "+n);var next=request();next.add("since",first.get("sequence"));var page=store.request(actor,next);assertEquals(50,page.getAsJsonArray("notices").size());assertTrue(page.get("more").getAsBoolean());next.add("since",page.get("sequence"));page=store.request(actor,next);assertEquals(15,page.getAsJsonArray("notices").size());assertFalse(page.get("more").getAsBoolean());}
 @Test void anotherPlayersPinNeverExpandsTaskVisibility()throws Exception{var create=new JsonObject();create.addProperty("section","home");create.addProperty("op","workSave");create.addProperty("title","Private task");create.addProperty("description","");create.addProperty("group","");var task=store.request(other,create).getAsJsonObject("task");var q=request();q.addProperty("pin",Json.str(task,"id"));assertTrue(store.request(actor,q).getAsJsonArray("tasks").isEmpty());}
 @Test void assignedTaskAppearsWithProgressAndExactNotificationRoute()throws Exception{var group=new JsonObject();group.addProperty("section","groups");group.addProperty("op","create");group.addProperty("title","Town");group.addProperty("description","Town description");group.addProperty("type","Команда");var doc=store.request(actor,group).getAsJsonObject("detail");String id=Json.str(doc,"id");store.transaction(()->{var saved=store.get(id);saved.getAsJsonObject("members").addProperty(other.id(),"member");store.put(saved);});var task=new JsonObject();task.addProperty("section","groups");task.addProperty("op","workSave");task.addProperty("group",id);task.addProperty("title","Build bridge");task.addProperty("description","");var created=store.request(actor,task).getAsJsonObject("task");var assign=new JsonObject();assign.addProperty("section","groups");assign.addProperty("op","workAssign");assign.addProperty("task",Json.str(created,"id"));assign.addProperty("group",id);assign.add("revision",created.get("revision"));assign.addProperty("assignee",other.id());store.request(actor,assign);var q=request();q.addProperty("since",0);var hud=store.request(other,q);assertEquals(Json.str(created,"id"),Json.str(hud.getAsJsonArray("tasks").get(0).getAsJsonObject(),"id"));var notice=hud.getAsJsonArray("notices").get(0).getAsJsonObject();assertEquals("workAssign",Json.str(notice,"event"));assertEquals("tasks",Json.str(notice,"routeSection"));assertEquals(id,Json.str(notice,"routeGroup"));}
 @Test void dismissReadsOnlyItsOwnNotice()throws Exception{store.transaction(()->{store.note(actor.id(),"events","same","One");store.note(actor.id(),"events","same","Two");store.note(other.id(),"events","same","Other");});var query=request();query.addProperty("since",0);var notice=store.request(actor,query).getAsJsonArray("notices").get(0).getAsJsonObject();var read=new JsonObject();read.addProperty("section","notifications");read.addProperty("op","read");read.addProperty("id",Json.str(notice,"id"));read.addProperty("exact",true);store.request(actor,read);assertEquals(1,store.unread(actor.id()));assertEquals(1,store.unread(other.id()));}
 @Test void pollingIsReadOnlyAndRejectsNegativeCursor(){assertTrue(MenuRequests.read(request()));var q=request();q.addProperty("since",-1);assertThrows(IllegalArgumentException.class,()->store.request(actor,q));}
}
