package dev.abros.rivet.core;
import com.google.gson.*;
import org.junit.jupiter.api.*;
import org.junit.jupiter.api.io.TempDir;
import java.nio.file.Path;
import java.util.*;
import static org.junit.jupiter.api.Assertions.*;
@Tag("postgres") class CommunityPlayerToolsTest {
 @TempDir Path temp;PgDatabase db;CommunityStore store;CommunityStore.Actor owner,other;
 @BeforeEach void start()throws Exception{db=TestDatabase.database(temp);store=new CommunityStore(db,CommunityStore.defaults());owner=new CommunityStore.Actor(UUID.randomUUID().toString(),"Owner",false,false);other=new CommunityStore.Actor(UUID.randomUUID().toString(),"Admin",true,true);store.seen(owner);store.seen(other);}
 JsonObject command(String op){var j=new JsonObject();j.addProperty("section","home");j.addProperty("op",op);return j;}
 @Test void privacyAlsoProtectsListStatisticsFromAdmin()throws Exception{var q=command("toolsPrivacySave");q.addProperty("mode","private");q.addProperty("statistics",false);store.request(owner,q);var rows=new JsonArray();var row=new JsonObject();row.addProperty("uuid",owner.id());row.addProperty("about","Secret");row.addProperty("interests","Secret");row.add("statistics",new JsonObject());rows.add(row);store.filterProfiles(rows,other.id());assertFalse(row.has("about"));assertFalse(row.has("statistics"));row.addProperty("about","Mine");store.filterProfiles(rows,owner.id());assertEquals("Mine",Json.str(row,"about"));}
 @Test void reportInternalNotesNeverReachOwnerAndClaimsConflict()throws Exception{var reports=new CommunityReports(store);var in=new JsonObject();in.addProperty("message","A problem");String id=reports.submit(UUID.fromString(owner.id()),owner.name(),in,System.currentTimeMillis());var q=new JsonObject();q.addProperty("id",id);q.addProperty("revision",1);q.addProperty("operation","claim");var managed=reports.manageRequest(other.id(),other.name(),q).getAsJsonObject("report");q.add("revision",managed.get("revision"));assertThrows(CommunityFailure.class,()->reports.manageRequest(UUID.randomUUID().toString(),"Second",q));q.addProperty("operation","note");q.addProperty("text","Private investigation");reports.manageRequest(other.id(),other.name(),q);assertFalse(reports.get(UUID.fromString(owner.id()),id).has("internalNotes"));assertFalse(reports.cursor(UUID.fromString(owner.id()),"").getAsJsonArray("entries").get(0).getAsJsonObject().has("assigned"));assertEquals(1,reports.dashboard().get("openReports").getAsInt());assertEquals(0,reports.dashboard().get("unassignedReports").getAsInt());}
 @Test void publicPlaceOwnershipAndRevisionEnforced()throws Exception{var q=command("toolsPlaceSave");q.addProperty("title","Spawn");var place=new JsonObject();place.addProperty("name","Spawn");place.addProperty("dimension","minecraft:overworld");place.addProperty("x",0);place.addProperty("y",64);place.addProperty("z",0);place.addProperty("membersOnly",false);q.add("location",place);store.request(owner,q);var row=store.request(owner,command("toolsPlaces")).getAsJsonArray("places").get(0).getAsJsonObject();q=command("toolsPlaceDelete");q.add("id",row.get("id"));q.addProperty("revision",0);var stale=q;assertThrows(CommunityFailure.class,()->store.request(owner,stale));q.add("revision",row.get("revision"));store.request(owner,q);assertTrue(store.request(owner,command("toolsPlaces")).getAsJsonArray("places").isEmpty());}
 @Test void mapPositionsRequireConsentAndCurrentGroupMembership()throws Exception{var q=command("create");q.addProperty("section","groups");q.addProperty("title","Group");q.addProperty("description","Description");q.addProperty("type","Команда");String group=Json.str(store.request(owner,q).getAsJsonObject("detail"),"id");var share=command("toolsMapShare");share.addProperty("group",group);share.addProperty("minutes",60);assertThrows(CommunityFailure.class,()->store.request(other,share));var invite=command("invite");invite.addProperty("section","groups");invite.addProperty("id",group);invite.addProperty("target",other.id());store.request(owner,invite);var accept=command("invitation");accept.addProperty("section","groups");accept.addProperty("id",group);accept.addProperty("accept",true);store.request(other,accept);assertTrue(store.request(owner,command("toolsMapPeers")).getAsJsonArray("peers").isEmpty());store.request(other,share);assertEquals(1,store.request(owner,command("toolsMapPeers")).getAsJsonArray("peers").size());var leave=command("leave");leave.addProperty("section","groups");leave.addProperty("id",group);store.request(other,leave);assertTrue(store.request(owner,command("toolsMapPeers")).getAsJsonArray("peers").isEmpty());}
 @Test void retentionPreviewDoesNotDeleteAndCleanupKeepsOpenReports()throws Exception{var reports=new CommunityReports(store);var input=new JsonObject();input.addProperty("message","Problem");String id=reports.submit(UUID.fromString(owner.id()),owner.name(),input,1);store.retention(1,1,100);assertEquals(0,store.retentionPreview(System.currentTimeMillis()).get("reports").getAsInt());var closed=store.record("reports",id);closed.addProperty("status","resolved");closed.addProperty("repliedAt",1);store.record("reports",id,closed);assertEquals(1,store.retentionPreview(System.currentTimeMillis()).get("reports").getAsInt());assertNotNull(store.record("reports",id));reports.prune(System.currentTimeMillis());assertNull(store.record("reports",id));}
}
