package dev.abros.rivet.core;
import com.google.gson.*;
import org.junit.jupiter.api.*;
import org.junit.jupiter.api.io.TempDir;
import java.nio.file.Path;
import java.util.*;
import static org.junit.jupiter.api.Assertions.*;
@Tag("postgres") class CommunityTasksTest {
 @TempDir Path temp;PgDatabase db;CommunityStore store;CommunityStore.Actor owner,other;
 @BeforeEach void start()throws Exception{db=TestDatabase.database(temp);store=new CommunityStore(db,CommunityStore.defaults());owner=new CommunityStore.Actor(UUID.randomUUID().toString(),"Owner",false,false);other=new CommunityStore.Actor(UUID.randomUUID().toString(),"Other",true,true);store.seen(owner);store.seen(other);}
 JsonObject input(String op){var j=new JsonObject();j.addProperty("section","home");j.addProperty("op",op);return j;}
 JsonObject create()throws Exception{var q=input("workSave");q.addProperty("title","Build");q.addProperty("description","Work");q.addProperty("operationId",UUID.randomUUID().toString());q.addProperty("issuedAt",System.currentTimeMillis());var first=store.request(owner,q);assertEquals(first.get("task"),store.request(owner,q).get("task"));return first.getAsJsonObject("task");}
 JsonObject command(JsonObject t,String op){var q=input(op);q.addProperty("task",Json.str(t,"id"));q.add("revision",t.get("revision"));return q;}
 @Test void undoUsesLatestRevisionAndCannotOverwriteNewerChanges()throws Exception{var original=create();var status=command(original,"workStatus");status.addProperty("status","working");var changed=store.request(owner,status).getAsJsonObject("task");var undo=command(changed,"workStatus");undo.addProperty("status","open");var rename=command(changed,"workSave");rename.addProperty("title","Newer title");rename.addProperty("description","Keep this");var latest=store.request(owner,rename).getAsJsonObject("task");assertThrows(CommunityFailure.class,()->store.request(owner,undo));var current=command(latest,"workStatus");current.addProperty("status","open");var reverted=store.request(owner,current).getAsJsonObject("task");assertEquals("open",Json.str(reverted,"status"));assertEquals("Newer title",Json.str(reverted,"title"));}
 @Test void personalTasksArePrivateAndCodesSurviveRename()throws Exception{var t=create();String code=Json.str(t,"code");assertEquals("Build",store.sharedEntry(owner,"tasks",Json.str(t,"id")));assertEquals("",Json.str(store.sharedReference(owner,"tasks",Json.str(t,"id")),"group"));assertThrows(CommunityFailure.class,()->store.sharedEntry(other,"tasks",Json.str(t,"id")));assertFalse(code.contains("-"));assertThrows(CommunityFailure.class,()->store.request(other,command(t,"workGet")));var q=command(t,"workSave");q.addProperty("title","Renamed");q.addProperty("description","");var renamed=store.request(owner,q).getAsJsonObject("task");assertEquals(code,Json.str(renamed,"code"));assertThrows(CommunityFailure.class,()->store.request(owner,q));assertEquals(1,store.request(owner,input("workList")).getAsJsonArray("tasks").size());}
 @Test void stockNeedsOwnerAndInventoryCannotBeCountedTwice()throws Exception{var t=create();String code=Json.str(t,"code");var tasks=new CommunityTasks(db,store);var stock=new JsonObject();stock.addProperty("inventory","chest:1");stock.addProperty("at",10);var items=new JsonObject();items.addProperty("minecraft:stone",64);stock.add("items",items);assertThrows(CommunityFailure.class,()->tasks.bind(other,"Owner",code,"sign:1",stock));tasks.bind(owner,"Owner",code,"sign:1",stock);assertThrows(CommunityFailure.class,()->tasks.bind(owner,"Owner",code,"sign:2",stock));tasks.bind(owner,"Owner",code,"sign:1",stock);var q=command(t,"workResources");var resources=new JsonArray();var need=new JsonObject();need.addProperty("item","minecraft:stone");need.addProperty("amount",100);resources.add(need);q.add("resources",resources);t=store.request(owner,q).getAsJsonObject("task");assertEquals(64,t.getAsJsonArray("stocks").get(0).getAsJsonObject().getAsJsonObject("items").get("minecraft:stone").getAsInt());tasks.stock("sign:1",new JsonObject(),true);assertEquals(0,tasks.bindings().size());}
 @Test void commentHistoryDoesNotOverflowPacketAndSubtasksPersist()throws Exception{var t=create();for(int n=0;n<40;n++){var q=command(t,"workComment");q.addProperty("text","x".repeat(500));t=store.request(owner,q).getAsJsonObject("task");}assertEquals(40,t.get("commentCount").getAsInt());assertEquals(20,t.getAsJsonArray("comments").size());assertTrue(t.toString().length()<32767);var q=command(t,"workSubtask");q.addProperty("title","First stage");t=store.request(owner,q).getAsJsonObject("task");q=command(t,"workSubtask");q.addProperty("index",0);assertTrue(store.request(owner,q).getAsJsonObject("task").getAsJsonArray("subtasks").get(0).getAsJsonObject().get("done").getAsBoolean());}
 @Test void mergedInventoriesAreCountedOnlyOnceAcrossTasks()throws Exception{var first=create();var second=create();var tasks=new CommunityTasks(db,store);var stock=new JsonObject();stock.addProperty("inventory","chest:b");stock.addProperty("at",100);var items=new JsonObject();items.addProperty("minecraft:stone",64);stock.add("items",items);tasks.bind(owner,"Owner",Json.str(second,"code"),"sign:b",stock);stock.addProperty("inventory","chest:a");tasks.bind(owner,"Owner",Json.str(first,"code"),"sign:a",stock);for(var t:List.of(first,second)){var q=command(t,"workResources");var resources=new JsonArray();var need=new JsonObject();need.addProperty("item","minecraft:stone");need.addProperty("amount",100);resources.add(need);q.add("resources",resources);store.request(owner,q);}stock.addProperty("inventory","merged");tasks.stock("sign:b",stock,false);tasks.stock("sign:a",stock,false);var a=store.request(owner,command(first,"workGet")).getAsJsonObject("task");var b=store.request(owner,command(second,"workGet")).getAsJsonObject("task");assertEquals(64,a.getAsJsonArray("stocks").get(0).getAsJsonObject().getAsJsonObject("items").get("minecraft:stone").getAsInt());assertEquals(0,b.getAsJsonArray("stocks").get(0).getAsJsonObject().getAsJsonObject("items").get("minecraft:stone").getAsInt());tasks.stock("sign:a",new JsonObject(),true);tasks.stock("sign:b",stock,false);b=store.request(owner,command(second,"workGet")).getAsJsonObject("task");assertEquals(64,b.getAsJsonArray("stocks").get(0).getAsJsonObject().getAsJsonObject("items").get("minecraft:stone").getAsInt());}
 @Test void globalSearchDoesNotRevealAnotherPlayersPersonalTasks()throws Exception{var task=create();var q=input("globalSearch");q.addProperty("query","Build");assertTrue(store.request(owner,q).getAsJsonArray("entries").asList().stream().anyMatch(e->Json.opt(e.getAsJsonObject(),"id","").equals(Json.str(task,"id"))));assertFalse(store.request(other,q).getAsJsonArray("entries").asList().stream().anyMatch(e->Json.opt(e.getAsJsonObject(),"id","").equals(Json.str(task,"id"))));}
 @Test void listFiltersBeforePaginationAndKeepsTaskDetailsPrivate()throws Exception{
  var first=create();var second=create();var change=command(second,"workSave");change.addProperty("title","Bridge");change.addProperty("description","Need glass");second=store.request(owner,change).getAsJsonObject("task");var working=command(second,"workStatus");working.addProperty("status","working");second=store.request(owner,working).getAsJsonObject("task");var stage=command(second,"workSubtask");stage.addProperty("title","Foundations");second=store.request(owner,stage).getAsJsonObject("task");stage=command(second,"workSubtask");stage.addProperty("index",0);store.request(owner,stage);
  var query=input("workList");query.addProperty("query","GLASS");query.addProperty("status","working");var rows=store.request(owner,query).getAsJsonArray("tasks");assertEquals(1,rows.size());var result=rows.get(0).getAsJsonObject();assertEquals(Json.str(second,"id"),Json.str(result,"id"));assertEquals(1,result.get("stagesDone").getAsInt());assertEquals(1,result.get("stagesTotal").getAsInt());assertFalse(result.has("comments"));assertFalse(result.has("stocks"));assertEquals(0,store.request(other,query).getAsJsonArray("tasks").size());query.addProperty("query",Json.str(second,"code"));assertEquals(1,store.request(owner,query).getAsJsonArray("tasks").size());query.addProperty("status","done");assertTrue(store.request(owner,query).getAsJsonArray("tasks").isEmpty());query.addProperty("status","invalid");assertThrows(IllegalArgumentException.class,()->store.request(owner,query));
 }

 @Test void dependenciesBlockStartAndRejectCyclesAndForeignTasks()throws Exception{
  var first=create();var second=create();var q=command(second,"workDependencies");q.addProperty("codes",Json.str(first,"code"));second=store.request(owner,q).getAsJsonObject("task");
  var start=command(second,"workStatus");start.addProperty("status","working");assertThrows(IllegalArgumentException.class,()->store.request(owner,start));
  var cycle=command(first,"workDependencies");cycle.addProperty("codes",Json.str(second,"code"));assertThrows(IllegalArgumentException.class,()->store.request(owner,cycle));
  var finish=command(first,"workStatus");finish.addProperty("status","done");store.request(owner,finish);assertEquals("working",Json.str(store.request(owner,start).getAsJsonObject("task"),"status"));
  var foreign=input("workSave");foreign.addProperty("title","Private");foreign.addProperty("description","");var hidden=store.request(other,foreign).getAsJsonObject("task");var link=command(create(),"workDependencies");link.addProperty("codes",Json.str(hidden,"code"));assertThrows(IllegalArgumentException.class,()->store.request(owner,link));
 }
 @Test void reservationsUseConfirmedStockOnceAndReleaseOnResourceChange()throws Exception{
  var first=create();var second=create();var tasks=new CommunityTasks(db,store);var stock=Json.parse("{\"inventory\":\"chest\",\"at\":1,\"items\":{\"minecraft:stone\":10}}");tasks.bind(owner,"Owner",Json.str(first,"code"),"stock",stock);
  var res=JsonParser.parseString("[{\"item\":\"minecraft:stone\",\"amount\":7}]").getAsJsonArray();var a=command(first,"workResources");a.add("resources",res);first=store.request(owner,a).getAsJsonObject("task");var b=command(second,"workResources");b.add("resources",res);second=store.request(owner,b).getAsJsonObject("task");
  first=store.request(owner,command(first,"workReserve")).getAsJsonObject("task");assertEquals(7,first.getAsJsonObject("reservations").get("minecraft:stone").getAsInt());var reserve=command(second,"workReserve");assertThrows(IllegalArgumentException.class,()->store.request(owner,reserve));
  var clear=command(first,"workResources");clear.add("resources",new JsonArray());store.request(owner,clear);assertEquals(7,store.request(owner,reserve).getAsJsonObject("task").getAsJsonObject("reservations").get("minecraft:stone").getAsInt());
 }
 @Test void repeatCreatesOneCatchUpInstanceAndHistoryIsBounded()throws Exception{
  var task=create();var repeat=command(task,"workRepeat");repeat.addProperty("days",1);task=store.request(owner,repeat).getAsJsonObject("task");long at=task.get("nextRepeatAt").getAsLong();var workflow=new CommunityTasks(db,store);db.communityTransaction(()->{workflow.repeatDue(at);workflow.repeatDue(at);return null;});assertEquals(2,store.request(owner,input("workList")).getAsJsonArray("tasks").size());
  var history=new JsonObject();for(int i=0;i<70;i++)TaskWorkflow.history(history,owner,"workStatus");assertEquals(60,history.getAsJsonArray("history").size());assertEquals("Owner",Json.str(history.getAsJsonArray("history").get(0).getAsJsonObject(),"author"));
 }


 @Test void archiveIsAtomicAndPrivate()throws Exception{var first=create();var second=create();for(var task:List.of(first,second)){var q=command(task,"workStatus");q.addProperty("status","done");store.request(owner,q);}var preview=input("workArchivePreview");var rows=store.request(owner,preview).getAsJsonArray("preview");assertEquals(2,rows.size());assertEquals(0,store.request(other,preview).getAsJsonArray("preview").size());var current=store.request(owner,command(first,"workGet")).getAsJsonObject("task");var rename=command(current,"workSave");rename.addProperty("title","Changed");rename.addProperty("description","");store.request(owner,rename);var apply=input("workArchiveApply");apply.add("items",rows);assertThrows(CommunityFailure.class,()->store.request(owner,apply));assertEquals(2,store.request(owner,input("workList")).getAsJsonArray("tasks").size());apply.add("items",store.request(owner,preview).get("preview"));assertEquals(2,store.request(owner,apply).get("affected").getAsInt());assertTrue(store.request(owner,input("workList")).getAsJsonArray("tasks").isEmpty());var archived=input("workList");archived.addProperty("status","archived");assertEquals(2,store.request(owner,archived).getAsJsonArray("tasks").size());}
 @Test void hologramsDoNotLeakPersonalStorage()throws Exception{var task=create();var resource=command(task,"workResources");resource.add("resources",JsonParser.parseString("[{\"item\":\"minecraft:stone\",\"amount\":64}]").getAsJsonArray());task=store.request(owner,resource).getAsJsonObject("task");var stock=Json.parse("{\"dimension\":\"minecraft:overworld\",\"inventory\":\"minecraft:overworld:0\",\"at\":1,\"items\":{\"minecraft:stone\":32}}");new CommunityTasks(db,store).bind(owner,"Owner",Json.str(task,"code"),"sign:0",stock);var q=new JsonObject();q.add("stockView",Json.parse("{\"dimension\":\"minecraft:overworld\",\"x\":0,\"y\":0,\"z\":0}"));assertEquals(1,db.communityTransaction(()->StockHolograms.read(db,store,owner,q)).size());assertEquals(0,db.communityTransaction(()->StockHolograms.read(db,store,other,q)).size());q.getAsJsonObject("stockView").addProperty("x",100);assertEquals(0,db.communityTransaction(()->StockHolograms.read(db,store,owner,q)).size());}
 @Test void alternativeResourcesCountAndReserveActualItems()throws Exception{var task=create();var stock=Json.parse("{\"inventory\":\"chest\",\"at\":1,\"items\":{\"minecraft:oak_log\":3,\"minecraft:birch_log\":5}}");new CommunityTasks(db,store).bind(owner,"Owner",Json.str(task,"code"),"alt-stock",stock);var q=command(task,"workResources");q.add("resources",JsonParser.parseString("[{\"item\":\"minecraft:oak_log\",\"alternatives\":[\"minecraft:birch_log\"],\"amount\":6}]").getAsJsonArray());task=store.request(owner,q).getAsJsonObject("task");var reserved=store.request(owner,command(task,"workReserve")).getAsJsonObject("task").getAsJsonObject("reservations");assertEquals(3,reserved.get("minecraft:oak_log").getAsInt());assertEquals(3,reserved.get("minecraft:birch_log").getAsInt());}
 @Test void scheduledNoticesArePublishedOnceAndPersistedTogether()throws Exception{var service=new ScheduledAnnouncements(store);long now=System.currentTimeMillis();var q=new JsonObject();q.addProperty("action","scheduledAnnouncements");q.addProperty("op","create");q.addProperty("text","Test announcement");q.addProperty("startsAt",java.time.Instant.ofEpochMilli(now+60000).toString());q=MenuCommands.prepare(q,now);assertEquals(MenuCommands.Effect.WRITE,MenuCommands.describe(q).effect());assertTrue(MenuCommands.known("scheduledAnnouncements"));assertEquals(1,service.request(owner.id(),owner.name(),q,now).getAsJsonArray("announcements").size());assertEquals(1,service.request(owner.id(),owner.name(),q,now).getAsJsonArray("announcements").size());assertEquals(0,service.publish(now,List.of(owner.id())));assertEquals(1,service.publish(now+60000,List.of(owner.id(),owner.id())));assertEquals(1,store.unread(owner.id()));assertEquals(0,service.publish(now+60000,List.of(owner.id())));assertEquals(1,store.unread(owner.id()));}
 @Test void archivedTasksCanBeRestoredWithoutLosingContent()throws Exception{var task=create();var q=command(task,"workStatus");q.addProperty("status","done");task=store.request(owner,q).getAsJsonObject("task");var apply=input("workArchiveApply");apply.add("items",store.request(owner,input("workArchivePreview")).get("preview"));store.request(owner,apply);task=store.request(owner,command(task,"workGet")).getAsJsonObject("task");task=store.request(owner,command(task,"workRestore")).getAsJsonObject("task");assertFalse(task.get("archived").getAsBoolean());assertEquals("Build",Json.str(task,"title"));assertEquals(1,store.request(owner,input("workList")).getAsJsonArray("tasks").size());}
 @Test void configuredLimitsBlockOnlyNewEntriesAndKeepExistingEditable()throws Exception{
  store=new CommunityStore(db,CommunityStore.defaults(),new TaskLimits(1,1,1));var t=create();assertFalse(store.request(owner,input("workList")).get("canCreate").getAsBoolean());assertTrue(store.request(owner,input("workList")).get("canManage").getAsBoolean());assertThrows(CommunityFailure.class,()->create());
  var q=command(t,"workComment");q.addProperty("text","First");t=store.request(owner,q).getAsJsonObject("task");var more=command(t,"workComment");more.addProperty("text","Second");assertThrows(CommunityFailure.class,()->store.request(owner,more));
  q=command(t,"workSubtask");q.addProperty("title","First");t=store.request(owner,q).getAsJsonObject("task");var extra=command(t,"workSubtask");extra.addProperty("title","Second");assertThrows(CommunityFailure.class,()->store.request(owner,extra));
  q=command(t,"workSubtask");q.addProperty("index",0);t=store.request(owner,q).getAsJsonObject("task");assertTrue(t.getAsJsonArray("subtasks").get(0).getAsJsonObject().get("done").getAsBoolean());assertEquals(1,t.get("commentCount").getAsInt());assertFalse(t.get("canComment").getAsBoolean());assertFalse(t.get("canAddSubtask").getAsBoolean());
  q=command(t,"workSave");q.addProperty("title","Renamed");q.addProperty("description","Still editable");t=store.request(owner,q).getAsJsonObject("task");assertEquals("Renamed",Json.str(t,"title"));
  store=new CommunityStore(db,CommunityStore.defaults(),new TaskLimits(0,0,0));assertNotNull(create());
  q=command(t,"workComment");q.addProperty("text","Second");t=store.request(owner,q).getAsJsonObject("task");assertEquals(2,t.get("commentCount").getAsInt());
  q=command(t,"workSubtask");q.addProperty("title","Second");assertEquals(2,store.request(owner,q).getAsJsonObject("task").getAsJsonArray("subtasks").size());
 }
 @Test void largeTaskPagesKeepIndicesAndDatabaseContents()throws Exception{
  store=new CommunityStore(db,CommunityStore.defaults(),new TaskLimits(0,0,0));var t=create();String id=Json.str(t,"id");
  db.communityTransaction(()->{var full=new CommunityTasks(db,store).task(id,true);var stages=new JsonArray();for(int n=0;n<500;n++){var row=new JsonObject();row.addProperty("title","Stage "+n);row.addProperty("done",false);row.addProperty("assignee",owner.id());stages.add(row);}full.add("subtasks",stages);new CommunityTasks(db,store).save(full);return null;});
  var q=command(t,"workGet");q.addProperty("subtaskOffset",40);t=store.request(owner,q).getAsJsonObject("task");assertEquals(500,t.get("subtaskCount").getAsInt());assertEquals("Stage 40",Json.str(t.getAsJsonArray("subtasks").get(0).getAsJsonObject(),"title"));assertTrue(t.toString().length()<30000);
  q=command(t,"workSubtask");q.addProperty("index",40);q.addProperty("subtaskOffset",40);t=store.request(owner,q).getAsJsonObject("task");assertTrue(t.getAsJsonArray("subtasks").get(0).getAsJsonObject().get("done").getAsBoolean());
  db.communityTransaction(()->{var full=new CommunityTasks(db,store).task(id,false);assertEquals(500,full.getAsJsonArray("subtasks").size());assertFalse(full.getAsJsonArray("subtasks").get(0).getAsJsonObject().get("done").getAsBoolean());assertTrue(full.getAsJsonArray("subtasks").get(40).getAsJsonObject().get("done").getAsBoolean());return null;});
 }
}
