package dev.abros.rivet.core;
import com.google.gson.*;import org.junit.jupiter.api.*;import org.junit.jupiter.api.io.TempDir;import java.nio.file.*;import static org.junit.jupiter.api.Assertions.*;
class DraftStoreTest {
 @TempDir Path dir;
 @Test void draftsSurviveRestartAndArePartitioned()throws Exception{var db=new DraftStore(dir);var j=new JsonObject();j.addProperty("text","Привет");db.save("server","alice","reply:one",j);assertEquals(j,new DraftStore(dir).load("server","alice","reply:one"));assertTrue(db.load("other","alice","reply:one").isEmpty());assertTrue(db.load("server","bob","reply:one").isEmpty());assertTrue(db.load("server","alice","reply:two").isEmpty());db.remove("server","alice","reply:one");assertTrue(db.load("server","alice","reply:one").isEmpty());}
 @Test void secretsAndCommandTargetsCannotBePersisted(){var db=new DraftStore(dir);for(String key:new String[]{"password","token","target","operationId"}){var j=new JsonObject();j.addProperty(key,"sensitive");assertThrows(IllegalArgumentException.class,()->db.save("s","a","c",j));}}
 @Test void communityToolDraftsAndPendingCommandsSurviveRestart()throws Exception{
  var db=new DraftStore(dir);var fields=new JsonObject();for(String key:new String[]{"visibility","invitees","repeat","occurrences","timezone","trade","item","quantity","terms","assignee","dueAt","reason","dimension","x","y","z","membersOnly"})fields.addProperty(key,"value");fields.addProperty("clearLocation",true);fields.add("location",JsonNull.INSTANCE);fields.add("playerNames",new JsonObject());db.save("server","alice","tools",fields);var restored=new DraftStore(dir).load("server","alice","tools");assertTrue(restored.get("clearLocation").getAsBoolean());for(String key:fields.keySet())if(!key.equals("location"))assertEquals(fields.get(key),restored.get(key));
  fields.remove("playerNames");fields.remove("location");fields.addProperty("kind","task");fields.addProperty("itemId","task-id");fields.addProperty("itemRevision",3);fields.addProperty("revision",4);fields.addProperty("operationId","operation-id");fields.addProperty("issuedAt",System.currentTimeMillis());db.pending("server","alice","tools",fields);assertEquals(fields,new DraftStore(dir).pending("server","alice","tools"));
 }
 @Test void reportIdentitySurvivesReopenAndRetries()throws Exception{
  var draft=new DraftStore(dir);var command=new JsonObject();command.addProperty("action","report");command.addProperty("message","help");command.addProperty("category","technical");command.addProperty("audit","checked");command.addProperty("coreVersion","1.0.0");command.addProperty("packHash","");var session=new RequestSession();var first=session.begin(command,true,123);draft.pending("s","a","report",session.command());
  var restored=new DraftStore(dir).pending("s","a","report");var retry=new RequestSession().begin(restored,true,456);assertEquals(first.get("operationId"),retry.get("operationId"));assertEquals(first.get("issuedAt"),retry.get("issuedAt"));assertNotEquals(first.get("request"),retry.get("request"));assertNull(draft.pending("other","a","report"));draft.pending("s","a","report",null);assertNull(draft.pending("s","a","report"));
 }
}
