package dev.abros.rivet.core;
import org.junit.jupiter.api.Test;
import java.util.concurrent.atomic.AtomicInteger;
import static org.junit.jupiter.api.Assertions.*;
class OptionalIntegrationTest {
 private OptionalIntegration adapter(boolean installed,boolean enabled,AtomicInteger errors){return new OptionalIntegration("test",()->installed,()->enabled,(id,error)->errors.incrementAndGet());}
 @Test void absentOrDisabledNeverTouchesOptionalClasses(){for(boolean installed:new boolean[]{false,true}){var errors=new AtomicInteger();var a=adapter(installed,false,errors);assertEquals("fallback",a.call(()->{throw new AssertionError("Loaded optional API");},()->"fallback"));assertFalse(a.available());assertEquals(0,errors.get());}var a=adapter(false,true,new AtomicInteger());assertEquals("Не установлен",a.status());assertEquals(false,a.call(()->{throw new NoClassDefFoundError();},()->false));}
 @Test void repeatedApiFailureIsIsolatedUntilLifecycleReset(){var errors=new AtomicInteger();var broken=adapter(true,true,errors);var good=adapter(true,true,new AtomicInteger());for(int i=0;i<8;i++)assertFalse(broken.call(()->{throw new NoClassDefFoundError("missing API");},()->false));assertEquals(3,errors.get());assertFalse(broken.available());assertEquals("Отключён после ошибок",broken.status());assertTrue(good.call(()->true,()->false));broken.reset();assertTrue(broken.available());assertTrue(broken.call(()->true,()->false));}
 @Test void permissionOrValidationRejectionDoesNotDisableIntegration(){var errors=new AtomicInteger();var a=adapter(true,true,errors);for(int i=0;i<4;i++)assertThrows(IllegalArgumentException.class,()->a.required(()->{throw new IllegalArgumentException("denied");}));assertEquals(0,errors.get());assertTrue(a.available());}
 @Test void requiredMutationsNeverReportSuccessWhenAbsentOrBroken(){assertThrows(IllegalArgumentException.class,()->adapter(false,true,new AtomicInteger()).required(()->true));var a=adapter(true,true,new AtomicInteger());assertThrows(IllegalStateException.class,()->a.required(()->{throw new ReflectiveOperationException();}));}

 @Test void contractIsProbedOnceUntilLifecycleReset(){var calls=new AtomicInteger();var a=new OptionalIntegration("mod:feature",()->true,()->true,()->"2.1",()->{calls.incrementAndGet();return "API 2";},(id,e)->{});for(int i=0;i<100;i++)assertTrue(a.available());assertEquals(1,calls.get());assertEquals("2.1",a.diagnostics().get("version").getAsString());assertEquals("API 2",a.diagnostics().get("api").getAsString());a.reset();assertTrue(a.available());assertEquals(2,calls.get());}
 @Test void installedButUnsupportedCapabilityIsNotRetriedOrReportedAvailable(){var probes=new AtomicInteger();var a=new OptionalIntegration("mod:editor",()->true,()->true,()->"3",()->{probes.incrementAndGet();throw new NoSuchMethodException("editor");},(id,e)->{});for(int i=0;i<100;i++)assertFalse(a.available());assertEquals(1,probes.get());assertEquals("Несовместимый API",a.status());assertTrue(a.diagnostics().get("reason").getAsString().contains("editor"));}
 @Test void editorFailureDoesNotDisableIndependentLayersAndPublishesRevision(){var layers=adapter(true,true,new AtomicInteger());var editor=adapter(true,true,new AtomicInteger());long before=OptionalIntegration.changes();for(int i=0;i<3;i++)editor.call(()->{throw new ReflectiveOperationException("editor failed");},()->false);assertFalse(editor.available());assertTrue(layers.available());assertTrue(OptionalIntegration.changes()>before);assertEquals(3,editor.diagnostics().get("failures").getAsInt());}
 @Test void successfulRequiredOperationClearsPreviousError()throws Exception{var a=adapter(true,true,new AtomicInteger());assertThrows(IllegalStateException.class,()->a.required(()->{throw new ReflectiveOperationException("failed");}));long before=a.revision();assertTrue(a.required(()->true));assertEquals("Доступен",a.status());assertEquals("",a.diagnostics().get("reason").getAsString());assertTrue(a.revision()>before);}
 @Test void runtimeLoadingDoesNotConsumeFailuresAndRecovers(){var errors=new AtomicInteger();var a=adapter(true,true,errors);for(int i=0;i<100;i++)assertFalse(a.call(()->{throw new OptionalIntegration.NotReadyException("Starting");},()->false));assertEquals("Загружается",a.status());assertTrue(a.available());assertEquals(0,errors.get());assertEquals(0,a.diagnostics().get("failures").getAsInt());assertEquals("Starting",a.diagnostics().get("reason").getAsString());assertTrue(a.call(()->true,()->false));assertEquals("Доступен",a.status());assertEquals("",a.diagnostics().get("reason").getAsString());}
 @Test void requiredLoadingIsAnActionableRejectionAndDoesNotDisable()throws Exception{var a=adapter(true,true,new AtomicInteger());assertThrows(IllegalArgumentException.class,()->a.required(()->{throw new OptionalIntegration.NotReadyException("Starting");}));assertEquals("Загружается",a.status());assertEquals(0,a.diagnostics().get("failures").getAsInt());assertTrue(a.required(()->true));}
}

