package dev.abros.rivet.core;
import org.junit.jupiter.api.Test;import static org.junit.jupiter.api.Assertions.*;
class ResourceRequirementsTest {
 @Test void alternativesShareOneRequirement()throws Exception{var rows=JsonParserHelper.array("[{\"item\":\"minecraft:oak_log\",\"amount\":64,\"alternatives\":[\"minecraft:birch_log\"]}]");var stock=Json.parse("{\"minecraft:oak_log\":32,\"minecraft:birch_log\":40}");ResourceRequirements.validate(rows);assertEquals(72,ResourceRequirements.count(rows.get(0).getAsJsonObject(),stock));assertEquals(0,ResourceRequirements.missing(rows.get(0).getAsJsonObject(),stock));var reserve=ResourceRequirements.reserve(rows,stock,new com.google.gson.JsonObject());assertEquals(32,reserve.get("minecraft:birch_log").getAsInt());}
 @Test void aStockCannotBeCountedTwice(){var rows=JsonParserHelper.array("[{\"item\":\"minecraft:oak_log\",\"amount\":1,\"alternatives\":[\"minecraft:birch_log\"]},{\"item\":\"minecraft:birch_log\",\"amount\":1}]");assertThrows(IllegalArgumentException.class,()->ResourceRequirements.validate(rows));}
 @Test void reservationsExcludeOtherTasks(){var rows=JsonParserHelper.array("[{\"item\":\"minecraft:stone\",\"amount\":64}]");assertThrows(IllegalArgumentException.class,()->ResourceRequirements.reserve(rows,Json.parse("{\"minecraft:stone\":70}"),Json.parse("{\"minecraft:stone\":10}")));}
 private static class JsonParserHelper{static com.google.gson.JsonArray array(String s){return com.google.gson.JsonParser.parseString(s).getAsJsonArray();}}
 @org.junit.jupiter.api.Test void deficitFirstAcrossAlternatives()throws Exception{var rows=com.google.gson.JsonParser.parseString("[{\"item\":\"minecraft:stone\",\"amount\":2},{\"item\":\"minecraft:oak_log\",\"alternatives\":[\"minecraft:birch_log\"],\"amount\":10}]").getAsJsonArray();var stock=Json.parse("{\"minecraft:stone\":2,\"minecraft:birch_log\":6}");assertEquals("minecraft:oak_log",Json.str(ResourceRequirements.ordered(rows,stock).get(0),"item"));assertEquals("minecraft:stone",Json.str(rows.get(0).getAsJsonObject(),"item"));}
}
