package dev.abros.rivet.core;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.io.TempDir;
import java.nio.file.*;
import static org.junit.jupiter.api.Assertions.*;
class ServerSettingsTest {
 @TempDir Path root;
 @Test void configReviewHidesSecretsAndReloadsOnlyMenu()throws Exception{var original=ServerSettings.parse(ServerSettings.template());var next=ServerSettings.parse(ServerSettings.template().replace("password = \"\"","password = \"never-send-secret\"").replace("helpText = \"", "helpText = \"Изменено. "));assertFalse(original.preview(next).toString().contains("never-send-secret"));var live=original.liveFrom(next);assertEquals("",live.text("database.password"));assertTrue(live.text("menu.helpText").startsWith("Изменено."));}
 @Test void defaultsCoverAllModules()throws Exception{var s=ServerSettings.load(root);assertEquals("false",s.text("auth.mode"));assertEquals(6,s.number("auth.minimumPasswordLength"));assertFalse(s.votes().enabled());assertTrue(s.statistics().deaths());assertEquals(8,s.community().getAsJsonArray("sections").size());assertTrue(s.menu().getAsJsonArray("links").isEmpty());}
 @Test void acceptsLinksAndStatsSettings()throws Exception{var s=ServerSettings.parse(ServerSettings.template().replace("links = []","links = [{name = 'Сайт', url = 'https://example.org'}]").replace("totalPlayTime = true","totalPlayTime = false"));assertFalse(s.statistics().totalTime());assertEquals("Сайт",s.menu().getAsJsonArray("links").get(0).getAsJsonObject().get("name").getAsString());assertFalse(s.menu().has("database"));}
 @Test void rejectsOldFlatConfigWithoutRewriting()throws Exception{Path f=root.resolve("config/rivet-server.toml");Files.createDirectories(f.getParent());String old="project = 'abrosdaniel/example'\nluckperms = true\n";Files.writeString(f,old);assertThrows(IllegalArgumentException.class,()->ServerSettings.load(root));assertEquals(old,Files.readString(f));}
 @Test void rejectsMissingAuthAndUnknownKeys()throws Exception{String t=ServerSettings.template();assertThrows(IllegalArgumentException.class,()->ServerSettings.parse(t.replace("mode = \"false\"","")));assertThrows(IllegalArgumentException.class,()->ServerSettings.parse(t+"\nunknown = true\n"));}
 @Test void missingOptionalSettingsUseDefaults()throws Exception{var s=ServerSettings.parse(ServerSettings.template().replace("maxSkinsPerPlayer = 2","").replace("links = []",""));assertEquals(2,s.number("skins.maxSkinsPerPlayer"));assertTrue(s.menu().getAsJsonArray("links").isEmpty());}
 @Test void rejectsInvalidTypesAndRanges()throws Exception{String t=ServerSettings.template();for(String invalid:new String[]{t.replace("mode = \"false\"","mode = false"),t.replace("minimumPlayers = 5","minimumPlayers = 4"),t.replace("minimumPlayers = 5","minimumPlayers = 5.5"),t.replace("minimumPasswordLength = 6","minimumPasswordLength = 5"),t.replace("poolSize = 8","poolSize = 99999999999"),t.replace("links = []","links = [{name='Bad',url='http://example.org'}]"),t.replace("categories = []","categories = [1]")})assertThrows(IllegalArgumentException.class,()->ServerSettings.parse(invalid));}
 @Test void syntaxErrorsNeverLeakSecrets()throws Exception{var error=assertThrows(IllegalArgumentException.class,()->ServerSettings.parse(ServerSettings.template().replace("password = \"\"","password = \"secret-marker")));assertFalse(error.toString().contains("secret-marker"));assertNull(error.getCause());}
 @Test void rejectsDuplicateKeys()throws Exception{assertThrows(IllegalArgumentException.class,()->ServerSettings.parse(ServerSettings.template()+"\nnotifyConsole = false\n"));}
 @Test void rejectsSymlink()throws Exception{Path f=root.resolve("config/rivet-server.toml");Files.createDirectories(f.getParent());Path target=root.resolve("secret");Files.writeString(target,"unchanged");Files.createSymbolicLink(f,target);assertThrows(IllegalArgumentException.class,()->ServerSettings.load(root));assertEquals("unchanged",Files.readString(target));}
 @Test void obsoletePunishmentDefaultsDoNotPreventProductionStartup()throws Exception{String t=ServerSettings.template().replace("[moderationVotes.actions]","[moderationVotes.actions]\nbanMinutes = 30\nmuteMinutes = 15");assertNotNull(ServerSettings.parse(t));assertFalse(ServerSettings.template().contains("banMinutes ="));}
 @Test void chatDefaultsPreserveExistingConfigsAndBoundRadius()throws Exception{String t=ServerSettings.template();var old=ServerSettings.parse(t.substring(0,t.indexOf("[chat]")));assertEquals(100,old.number("chat.localRadius"));assertTrue(old.flag("chat.groupEnabled"));assertTrue(old.flag("chat.enabled"));assertFalse(ServerSettings.parse(t.replace("enabled = true\n# Названия", "enabled = false\n# Названия")).flag("chat.enabled"));assertThrows(IllegalArgumentException.class,()->ServerSettings.parse(t.replace("localRadius = 100","localRadius = 0")));assertThrows(IllegalArgumentException.class,()->ServerSettings.parse(t.replace("localRadius = 100","localRadius = 1001")));}
 @Test void displayPolicyDefaultsAndValidatesServerModes()throws Exception{String t=ServerSettings.template();var old=ServerSettings.parse(t.substring(0,t.indexOf("[display]")));assertEquals("auto",old.text("display.tabMode"));assertEquals("compatible",ServerSettings.parse(t.replace("tabMode = \"auto\"","tabMode = \"compatible\"")).text("display.tabMode"));assertThrows(IllegalArgumentException.class,()->ServerSettings.parse(t.replace("tabMode = \"auto\"","tabMode = \"unknown\"")));assertNotNull(ServerSettings.parse(t+"chatMode = \"compatible\"\n"));}
 @Test void obsoleteItemSharingSettingIsIgnored()throws Exception{String template=ServerSettings.template();assertDoesNotThrow(()->ServerSettings.parse(template.replace("[chat]","[chat]\nallowItems = true")));assertDoesNotThrow(()->ServerSettings.parse(template.replace("[chat]","[chat]\nallowItems = false")));}
 @Test void chatLabelsAndSharingPermissions()throws Exception{String t=ServerSettings.template();var s=ServerSettings.parse(t.replace("localName = \"Рядом\"","localName = \"Соседи\""));assertEquals("Соседи",s.text("chat.localName"));assertFalse(ServerSettings.template().contains("allowItems ="));assertTrue(s.flag("chat.allowCoordinates"));assertThrows(IllegalArgumentException.class,()->ServerSettings.parse(t.replace("localName = \"Рядом\"","localName = \""+"x".repeat(41)+"\"")));}
 @Test void taskAndSparkPoliciesDefaultForOldConfigsAndRejectInvalidValues()throws Exception{
  String t=ServerSettings.template();String old=t.substring(0,t.indexOf("[tasks]"))+t.substring(t.indexOf("[chat]"));var settings=ServerSettings.parse(old);
  assertEquals(TaskLimits.defaults(),settings.taskLimits());assertEquals(SparkTimeline.AlertSettings.defaults(),settings.sparkAlerts());
  var changed=ServerSettings.parse(t.replace("maxPerOwner = 200","maxPerOwner = 10").replace("sustainedSeconds = 30","sustainedSeconds = 5"));assertEquals(10,changed.taskLimits().perOwner());assertEquals(5,changed.sparkAlerts().sustainedSeconds());
  for(String replacement:new String[]{"maxPerOwner = -1","maxPerOwner = 2147483648"})assertThrows(IllegalArgumentException.class,()->ServerSettings.parse(t.replace("maxPerOwner = 200",replacement)));
  assertEquals(new TaskLimits(0,0,0),ServerSettings.parse(t.replace("maxPerOwner = 200","maxPerOwner = 0").replace("maxSubtasks = 30","maxSubtasks = 0").replace("maxComments = 100","maxComments = 0")).taskLimits());assertTrue(new TaskLimits(0,0,0).allowsTask(Integer.MAX_VALUE));assertTrue(new TaskLimits(0,0,0).allowsSubtask(Integer.MAX_VALUE));assertTrue(new TaskLimits(0,0,0).allowsComment(Integer.MAX_VALUE));
  assertThrows(IllegalArgumentException.class,()->ServerSettings.parse(t.replace("minimumTps = 18","minimumTps = 21")));assertThrows(IllegalArgumentException.class,()->ServerSettings.parse(t.replace("maximumMspt = 50","maximumMspt = 0")));assertThrows(IllegalArgumentException.class,()->ServerSettings.parse(t.replace("sustainedSeconds = 30","sustainedSeconds = 0")));assertThrows(IllegalArgumentException.class,()->ServerSettings.parse(t.replace("cooldownSeconds = 300","cooldownSeconds = 86401")));
  assertEquals(settings.taskLimits(),settings.liveFrom(changed).taskLimits());assertEquals(settings.sparkAlerts(),settings.liveFrom(changed).sparkAlerts());
 }
 @Test void configurationErrorsPointToKeysWithoutExposingValues()throws Exception{
  String t=ServerSettings.template();
  var missing=assertThrows(IllegalArgumentException.class,()->ServerSettings.parse(t.replace("mode = \"false\"","")));assertTrue(missing.getMessage().contains("auth.mode"));
  var typo=assertThrows(IllegalArgumentException.class,()->ServerSettings.parse(t+"\nunknown = 'secret-marker'\n"));assertTrue(typo.getMessage().contains("display.unknown"));assertFalse(typo.getMessage().contains("secret-marker"));
  var unsafe=assertThrows(IllegalArgumentException.class,()->ServerSettings.parse(t+"\n\"private secret-marker\" = true\n"));assertFalse(unsafe.getMessage().contains("secret-marker"));
 }
 @Test void legacyIntegrationSwitchIsIgnored()throws Exception{assertNotNull(ServerSettings.parse(ServerSettings.template()+"\n[integrations]\nluckperms = false\n"));assertNotNull(ServerSettings.parse(ServerSettings.template()+"\n[integrations]\nluckperms = true\n"));}
}
