package dev.abros.rivet.core;
import dev.abros.rivet.core.skins.*;
import org.junit.jupiter.api.*;
import org.junit.jupiter.api.io.TempDir;
import java.nio.file.Path;
import java.util.UUID;
import static org.junit.jupiter.api.Assertions.*;
@Tag("postgres") class SkinStoreTest {
 @TempDir Path temp;
 @Test void ownershipDedupAndActualDeletion()throws Exception{var db=TestDatabase.database(temp);var s=new SkinStore(db,new SkinSettings(true,1,2,"false"));var a=UUID.randomUUID();var b=UUID.randomUUID();byte[] png=SkinImageTest.png(64,64);s.upload(a,"A",false,png);s.upload(b,"B",true,png);var entry=s.library(a).getAsJsonArray("entries").get(0).getAsJsonObject();String id=Json.str(entry,"id"),hash=Json.str(entry,"hash");assertThrows(IllegalArgumentException.class,()->s.change(b,"delete",id,false));s.change(a,"delete",id,false);assertEquals("",Json.str(s.appearance(a),"active"));assertTrue(s.bytes(hash).length>0);String second=Json.str(s.library(b).getAsJsonArray("entries").get(0).getAsJsonObject(),"id");s.change(b,"delete",second,false);assertThrows(IllegalArgumentException.class,()->s.bytes(hash));}
 @Test void quotaDuplicateResetAndFallback()throws Exception{var db=TestDatabase.database(temp);var s=new SkinStore(db,new SkinSettings(true,1,1,"nickname"));var a=UUID.randomUUID();s.upload(a,"A",false,SkinImageTest.png(64,64));s.upload(a,"Again",true,SkinImageTest.png(64,64));assertEquals(1,s.library(a).getAsJsonArray("entries").size());assertThrows(IllegalArgumentException.class,()->s.upload(a,"Second",false,SkinImageTest.png(64,32)));s.fallback(a,"nickname:A",SkinImageTest.png(64,32),true,123);assertFalse(Json.str(s.appearance(a),"active").isEmpty());assertFalse(Json.str(s.appearance(a),"fallbackHash").isEmpty());assertTrue(s.appearance(a).get("fallbackSlim").getAsBoolean());s.change(a,"select","",false);assertEquals(Json.str(s.appearance(a),"hash"),Json.str(s.appearance(a),"fallbackHash"));assertTrue(s.appearance(a).get("slim").getAsBoolean());assertEquals(123,s.checked(a,"nickname:A"));assertEquals(0,s.checked(a,"UUID:A"));s.fallback(a,"false:",null,false,124);assertEquals("",Json.str(s.appearance(a),"hash"));}
 @Test void renamingPreservesIdentityAndChecksOwnership()throws Exception{var s=new SkinStore(TestDatabase.database(temp),new SkinSettings(true,1,2,"false"));var owner=UUID.randomUUID();s.upload(owner,"Old",false,SkinImageTest.png(64,64));var before=s.appearance(owner);String id=Json.str(before,"active");s.rename(owner,id," New name ");assertEquals("New name",Json.str(s.library(owner).getAsJsonArray("entries").get(0).getAsJsonObject(),"name"));assertEquals(before,s.appearance(owner));assertThrows(IllegalArgumentException.class,()->s.rename(UUID.randomUUID(),id,"Other"));for(String bad:new String[]{" ","x".repeat(41),"a\nb"})assertThrows(IllegalArgumentException.class,()->s.rename(owner,id,bad));}
 @Test void disabledStoreCannotMutate()throws Exception{var s=new SkinStore(TestDatabase.database(temp),new SkinSettings(false,1,2,"false"));assertThrows(IllegalArgumentException.class,()->s.upload(UUID.randomUUID(),"A",false,SkinImageTest.png(64,64)));assertThrows(IllegalArgumentException.class,()->s.change(UUID.randomUUID(),"select","",false));}
 @Test void repeatedDeleteUsesReceiptInsteadOfDeletingAgain()throws Exception{var s=new SkinStore(TestDatabase.database(temp),new SkinSettings(true,1,2,"false"));var owner=UUID.randomUUID();s.upload(owner,"A",false,SkinImageTest.png(64,64));String id=Json.str(s.appearance(owner),"active");var request=new com.google.gson.JsonObject();request.addProperty("id",id);request.addProperty("operationId",UUID.randomUUID().toString());request.addProperty("issuedAt",System.currentTimeMillis());s.mutate(owner,"delete",request,null);var replay=s.mutate(owner,"delete",request,null);assertTrue(replay.get("replayed").getAsBoolean());assertTrue(s.library(owner).getAsJsonArray("entries").isEmpty());}
 @Test void orderingPersistsWithoutChangingActiveSkinAndRejectsOtherOwners()throws Exception{var db=TestDatabase.database(temp);var store=new SkinStore(db,new SkinSettings(true,1,4,"false"));var owner=UUID.randomUUID();store.upload(owner,"Z",false,SkinImageTest.png(64,64));String first=Json.str(store.appearance(owner),"active");store.upload(owner,"A",false,SkinImageTest.png(64,32));String second=Json.str(store.appearance(owner),"active");assertEquals(first,Json.str(store.library(owner).getAsJsonArray("entries").get(0).getAsJsonObject(),"id"));var active=store.appearance(owner);store.move(owner,second,-1);var reopened=new SkinStore(db,new SkinSettings(true,1,4,"false"));assertEquals(second,Json.str(reopened.library(owner).getAsJsonArray("entries").get(0).getAsJsonObject(),"id"));assertEquals(active,reopened.appearance(owner));store.rename(owner,first,"AAA");assertEquals(second,Json.str(store.library(owner).getAsJsonArray("entries").get(0).getAsJsonObject(),"id"));assertThrows(IllegalArgumentException.class,()->store.move(UUID.randomUUID(),first,1));store.move(owner,second,-1);store.move(owner,second,1);assertEquals(first,Json.str(store.library(owner).getAsJsonArray("entries").get(0).getAsJsonObject(),"id"));}
 @Test void queuedModelChangesPersistInSubmissionOrderWhileAnotherOwnerProceeds()throws Exception{
  var store=new SkinStore(TestDatabase.database(temp),new SkinSettings(true,1,2,"false"));var owner=UUID.randomUUID();var other=UUID.randomUUID();
  store.upload(owner,"A",false,SkinImageTest.png(64,64));store.upload(other,"B",false,SkinImageTest.png(64,64));
  String id=Json.str(store.appearance(owner),"active"),otherId=Json.str(store.appearance(other),"active");
  var pool=java.util.concurrent.Executors.newFixedThreadPool(2);var work=new KeyedSerialExecutor<UUID>(pool,4);
  var entered=new java.util.concurrent.CountDownLatch(1);var release=new java.util.concurrent.CountDownLatch(1);
  var first=new java.util.concurrent.CompletableFuture<Void>();var second=new java.util.concurrent.CompletableFuture<Void>();var independent=new java.util.concurrent.CompletableFuture<Void>();
  try{
   work.execute(owner,()->{entered.countDown();try{release.await();store.change(owner,"model",id,true);first.complete(null);}catch(Exception e){first.completeExceptionally(e);}});
   assertTrue(entered.await(2,java.util.concurrent.TimeUnit.SECONDS));
   work.execute(owner,()->{try{store.change(owner,"model",id,false);second.complete(null);}catch(Exception e){second.completeExceptionally(e);}});
   work.execute(other,()->{try{store.rename(other,otherId,"Independent");independent.complete(null);}catch(Exception e){independent.completeExceptionally(e);}});
   independent.get(3,java.util.concurrent.TimeUnit.SECONDS);assertFalse(second.isDone());
   assertEquals("Independent",Json.str(store.library(other).getAsJsonArray("entries").get(0).getAsJsonObject(),"name"));
   release.countDown();first.get(3,java.util.concurrent.TimeUnit.SECONDS);second.get(3,java.util.concurrent.TimeUnit.SECONDS);
   assertFalse(store.appearance(owner).get("slim").getAsBoolean());assertEquals(id,Json.str(store.appearance(owner),"active"));
  }finally{release.countDown();work.close();pool.shutdownNow();assertTrue(pool.awaitTermination(3,java.util.concurrent.TimeUnit.SECONDS));}
 }
}
