package dev.abros.rivet.core;
import com.google.gson.*;
import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;
class UiFoundationTest {
 private JsonObject read(String id){var q=new JsonObject();q.addProperty("action","community");q.addProperty("op","detail");q.addProperty("id",id);return q;}
 @Test void readCacheExpiresCopiesAndBoundsItsStorage(){var cache=new MenuReadCache();var q=read("one");var reply=new JsonObject();reply.addProperty("section","board");reply.addProperty("title","original");cache.put(q,reply,0);reply.addProperty("title","tampered");var hit=cache.get(q,1);assertEquals("original",Json.str(hit,"title"));hit.addProperty("title","tampered again");q.addProperty("request","other correlation");assertEquals("original",Json.str(cache.get(q,2),"title"));assertNull(cache.get(q,30001));for(int n=0;n<40;n++)cache.put(read("id"+n),reply,n);assertEquals(32,cache.size());assertNull(cache.get(read("id0"),40));cache.invalidate("board","");assertEquals(0,cache.size());}
 @Test void cacheRejectsMutationsErrorsAndOversizedReplies(){var cache=new MenuReadCache();var q=read("one");q.addProperty("op","create");cache.put(q,new JsonObject(),0);assertEquals(0,cache.size());q.addProperty("op","detail");var error=new JsonObject();error.addProperty("error",true);cache.put(q,error,0);error.remove("error");error.addProperty("text","x".repeat(131073));cache.put(q,error,0);assertEquals(0,cache.size());}
 @Test void newGenerationAndCancellationRejectLateReplies(){var state=new ScreenState<String>();long first=state.begin(),second=state.begin();assertFalse(state.resolve(first,"old",false));assertTrue(state.resolve(second,"new",false));long third=state.begin();state.cancel();assertFalse(state.fail(third,"late timeout"));assertEquals("new",state.value());assertEquals(ScreenState.Phase.READY,state.phase());assertFalse(state.resolve(third,"late",false));}
 @Test void pagesDoNotExposeMutableServerPayloads(){var source=JsonParser.parseString("{\"entries\":[{\"id\":\"one\"}],\"more\":true,\"nextCursor\":\"next\"}").getAsJsonObject();var page=MenuData.page(source,"entries");source.getAsJsonArray("entries").get(0).getAsJsonObject().addProperty("id","changed");page.entries().getFirst().addProperty("id","changed again");assertEquals("one",Json.str(page.entries().getFirst(),"id"));assertTrue(page.more());assertEquals("next",page.nextCursor());assertThrows(IllegalArgumentException.class,()->MenuData.page(JsonParser.parseString("{\"entries\":[1]}").getAsJsonObject(),"entries"));}
 @Test void notificationsGroupByObjectAndSectionNotTitle(){var source=JsonParser.parseString("[{\"id\":\"1\",\"section\":\"board\",\"target\":\"same\",\"title\":\"new title\",\"read\":true},{\"id\":\"2\",\"section\":\"board\",\"target\":\"same\",\"title\":\"old title\",\"read\":false},{\"id\":\"3\",\"section\":\"polls\",\"target\":\"same\"},{\"id\":\"4\",\"target\":\"\"},{\"id\":\"5\",\"target\":\"\"}]").getAsJsonArray();var groups=NotificationGroups.arrange(source);assertEquals(4,groups.size());assertEquals(2,groups.get(0).getAsJsonObject().get("groupCount").getAsInt());assertFalse(groups.get(0).getAsJsonObject().get("read").getAsBoolean());assertEquals("new title",Json.str(groups.get(0).getAsJsonObject(),"title"));assertFalse(source.get(0).getAsJsonObject().has("groupCount"));}
 @Test void mergeDeduplicatesMovingPagesAndReturnsCopies(){var a=JsonParser.parseString("[{\"id\":\"one\"},{\"id\":\"two\"}]").getAsJsonArray();var b=JsonParser.parseString("[{\"id\":\"two\"},{\"id\":\"three\"}]").getAsJsonArray();var merged=MenuPages.merge(java.util.List.of(a,b));assertEquals(3,merged.size());a.get(0).getAsJsonObject().addProperty("id","changed");assertEquals("one",Json.str(merged.get(0).getAsJsonObject(),"id"));}
 @Test void metricsAggregateFailuresWithoutUnboundedNames(){PerformanceMetrics.clear();PerformanceMetrics.record("database.transaction",1000000,false);PerformanceMetrics.record("database.transaction",3000000,true);var sample=PerformanceMetrics.snapshot().get("database.transaction");assertEquals(2,sample.count());assertEquals(2,sample.meanMillis());assertEquals(1,sample.failures());for(int n=0;n<100;n++)PerformanceMetrics.record("operation"+n,0,false);assertEquals(64,PerformanceMetrics.snapshot().size());PerformanceMetrics.clear();}
 @Test void invalidationKeepsUnrelatedDetailButRefreshesLists(){var cache=new MenuReadCache();var first=read("one");first.addProperty("section","board");var second=read("two");second.addProperty("section","board");var list=read("");list.addProperty("section","board");list.addProperty("op","list");var reply=new JsonObject();cache.put(first,reply,0);cache.put(second,reply,0);cache.put(list,reply,0);cache.invalidate("board","one");assertNull(cache.get(first,1));assertNull(cache.get(list,1));assertNotNull(cache.get(second,1));}
}
