package dev.abros.rivet.client;
import java.util.*;
import dev.abros.rivet.core.NativeLayout;
import net.minecraft.client.Minecraft;
import net.minecraft.client.gui.GuiGraphics;
/** Separate channel state and contextual hints, sharing one themed HUD surface. */
final class ChatHints {
 static NativeLayout.Box bounds=new NativeLayout.Box(0,0,0,0);
 static boolean enabled(String key){var state=ServerMenuClient.state;return !state.has(key)||state.get(key).getAsBoolean();}
 static List<String> lines(String text){return rawLines(text).stream().filter(line->!line.startsWith("[pos]")||enabled("chatAllowCoordinates")).toList();}
 private static List<String> rawLines(String text){if(text.startsWith("/"))return List.of();if(text.startsWith("!"))return List.of("!текст → общий чат: вас услышат все","[pos] → координаты · нажмите, чтобы идти");if(text.startsWith("#")&&!enabled("chatGroupEnabled"))return List.of("Чат объединений выключен сервером","!текст → общий чат");if(text.startsWith("#"))return List.of("#Название: текст → чат объединения","↑↓ → выбрать объединение · Tab → вставить","[pos] → координаты");if(text.contains("[pos")||text.endsWith("[p"))return List.of("[pos] → отправить ваши координаты","Нажмите на координаты в чате, чтобы начать маршрут");return List.of(enabled("chatLocalEnabled")?"текст → "+dev.abros.rivet.core.Json.opt(ServerMenuClient.state,"chatLocalName","Рядом"):"текст → общий чат","!текст → общий чат",enabled("chatGroupEnabled")?"#Название: текст → чат объединения":"Чат объединений выключен сервером","[pos] → координаты · нажмите, чтобы идти");}
 static String channel(String text){if(text.startsWith("!"))return "Общий чат";if(text.startsWith("#")){int end=text.indexOf(':');return "Объединение"+(end>1?" · "+text.substring(1,end):" · #Название:");}return enabled("chatLocalEnabled")?dev.abros.rivet.core.Json.opt(ServerMenuClient.state,"chatLocalName","Рядом"):"Общий чат";}
 static void draw(GuiGraphics g,String text,boolean preview){var mc=Minecraft.getInstance();if(!preview&&(!SocialSettings.INSTANCE.hints||!SocialSettings.chatEnabled()))return;var hints=lines(text);if(hints.isEmpty())return;int width=g.guiWidth(),height=g.guiHeight(),chatWidth=(int)Math.ceil(mc.gui.getChat().getWidth()*mc.options.chatScale().get()),free=width-chatWidth-20;int w=Math.min(free>=150?Math.min(246,free):246,width-16);var wrapped=new ArrayList<net.minecraft.util.FormattedCharSequence>();for(String line:hints)wrapped.addAll(mc.font.split(net.minecraft.network.chat.Component.literal(line),Math.max(1,w-16)));int h=Math.min(height-48,30+11*wrapped.size());var s=HudSettings.INSTANCE;int x=width-w-8,y=free>=150?height-h-48:Math.max(8,height-44-(int)Math.ceil(mc.gui.getChat().getHeight()*mc.options.chatScale().get())-h-6);bounds=HudPlacement.fit(width,height,w,h,s.hintsPositioned?s.hintAnchorX:0,s.hintsPositioned?s.hintAnchorY:0,s.hintsPositioned?s.hintOffsetX:x,s.hintsPositioned?s.hintOffsetY:y);x=bounds.x();y=bounds.y();w=bounds.width();h=bounds.height();UiKit.surface(g,x,y,w,h,(UiKit.surface()&0xFFFFFF)|((int)Math.round(SocialSettings.INSTANCE.hintOpacity*255)<<24));g.renderOutline(x,y,w,h,UiPalette.outline());g.fill(x,y+3,x+2,y+h-3,UiKit.accent());g.enableScissor(x+4,y+4,x+w-4,y+h-4);g.drawString(mc.font,UiKit.fit(mc.font,channel(text),w-16),x+8,y+6,UiKit.accent(),false);g.fill(x+8,y+19,x+w-8,y+20,UiTheme.mix(UiKit.surface(),UiKit.muted(),.25f));int yy=y+25;for(var line:wrapped){if(yy+9>y+h-4)break;g.drawString(mc.font,line,x+8,yy,UiKit.text(),false);yy+=11;}g.disableScissor();}
 private ChatHints(){}
}
