package dev.abros.rivet.client;
import java.util.*;
import dev.abros.rivet.core.NativeLayout;
import net.minecraft.client.Minecraft;
import net.minecraft.client.gui.GuiGraphics;
/** Separate channel state and contextual hints, sharing one themed HUD surface. */
final class ChatHints {
 static NativeLayout.Box bounds=new NativeLayout.Box(0,0,0,0);
 static boolean enabled(String key){var state=ServerMenuClient.state;return !state.has(key)||state.get(key).getAsBoolean();}
 static List<String> lines(String text){return rawLines(text).stream().filter(line->!line.startsWith("[pos]")||enabled("chatAllowCoordinates")).toList();}
 private static List<String> rawLines(String text){if(text.startsWith("/"))return List.of();if(text.startsWith("!"))return List.of(Client.text("ui.text_global_chat_everyone_can_hear_b57782ae"),Client.text("ui.pos_coordinates_click_to_navigate_305982e7"));if(text.startsWith("#")&&!enabled("chatGroupEnabled"))return List.of(Client.text("ui.group_chat_is_disabled_by_the_13d34ed0"),Client.text("ui.text_global_chat_41ad67a1"));if(text.startsWith("#"))return List.of(Client.text("ui.name_text_group_chat_33946d8e"),Client.text("ui.select_group_tab_insert_0ee52775"),Client.text("ui.pos_coordinates_0854012b"));if(text.contains("[pos")||text.endsWith("[p"))return List.of(Client.text("ui.pos_share_your_coordinates_b3ae510a"),Client.text("ui.click_coordinates_in_chat_to_start_5850c670"));return List.of(enabled("chatLocalEnabled")?Client.text("ui.text_cd483b5c")+dev.abros.rivet.core.Json.opt(ServerMenuClient.state,"chatLocalName",Client.text("ui.nearby_fa01903f")):Client.text("ui.text_global_chat_a0973191"),Client.text("ui.text_global_chat_41ad67a1"),enabled("chatGroupEnabled")?Client.text("ui.name_text_group_chat_33946d8e"):Client.text("ui.group_chat_is_disabled_by_the_13d34ed0"),Client.text("ui.pos_coordinates_click_to_navigate_305982e7"));}
 static String channel(String text){if(text.startsWith("!"))return Client.text("ui.global_chat_4b272a96");if(text.startsWith("#")){int end=text.indexOf(':');return Client.text("ui.group_4fb407c1")+(end>1?" · "+text.substring(1,end):Client.text("ui.name_92847cc0"));}return enabled("chatLocalEnabled")?dev.abros.rivet.core.Json.opt(ServerMenuClient.state,"chatLocalName",Client.text("ui.nearby_fa01903f")):Client.text("ui.global_chat_4b272a96");}
 static void draw(GuiGraphics g,String text,boolean preview){var mc=Minecraft.getInstance();if(!preview&&(!SocialSettings.INSTANCE.hints||!SocialSettings.chatEnabled()))return;var hints=lines(text);if(hints.isEmpty())return;int width=g.guiWidth(),height=g.guiHeight(),chatWidth=(int)Math.ceil(mc.gui.getChat().getWidth()*mc.options.chatScale().get()),free=width-chatWidth-20;var s=HudSettings.INSTANCE;float scale=Math.min(s.hintScale,Math.min((width-8f)/80,(height-8f)/80));int w=Math.min(free>=150?Math.min(246,(int)(free/scale)):246,(int)((width-16)/scale));var wrapped=new ArrayList<net.minecraft.util.FormattedCharSequence>();for(String line:hints)wrapped.addAll(mc.font.split(net.minecraft.network.chat.Component.literal(line),Math.max(1,w-16)));int h=Math.min((int)((height-48)/scale),30+11*wrapped.size());int pw=(int)Math.ceil(w*scale),ph=(int)Math.ceil(h*scale);int x=width-pw-8,y=free>=150?height-ph-48:Math.max(8,height-44-(int)Math.ceil(mc.gui.getChat().getHeight()*mc.options.chatScale().get())-ph-6);bounds=HudPlacement.fit(width,height,pw,ph,s.hintsPositioned?s.hintAnchorX:0,s.hintsPositioned?s.hintAnchorY:0,s.hintsPositioned?s.hintOffsetX:x,s.hintsPositioned?s.hintOffsetY:y);x=bounds.x();y=bounds.y();g.pose().pushPose();g.pose().translate(x,y,0);g.pose().scale(scale,scale,1);x=0;y=0;UiKit.surface(g,x,y,w,h,(UiKit.surface()&0xFFFFFF)|((int)Math.round(SocialSettings.INSTANCE.hintOpacity*255)<<24));g.renderOutline(x,y,w,h,UiPalette.outline());g.fill(x,y+3,x+2,y+h-3,UiKit.accent());g.enableScissor(bounds.x()+(int)(4*scale),bounds.y()+(int)(4*scale),bounds.right()-(int)(4*scale),bounds.bottom()-(int)(4*scale));g.drawString(mc.font,UiKit.fit(mc.font,Client.text("ui.how_to_use_chat_4e554a08"),w-16),x+8,y+6,UiKit.accent(),false);g.fill(x+8,y+19,x+w-8,y+20,UiTheme.mix(UiKit.surface(),UiKit.muted(),.25f));int yy=y+25;for(var line:wrapped){if(yy+9>y+h-4)break;g.drawString(mc.font,line,x+8,yy,UiKit.text(),false);yy+=11;}g.disableScissor();g.pose().popPose();}
 private ChatHints(){}
}
