package dev.abros.rivet.client;
import com.google.gson.*;
import dev.abros.rivet.core.*;
import net.minecraft.client.gui.GuiGraphics;
import net.minecraft.client.gui.components.*;
import net.minecraft.client.gui.screens.Screen;
import net.minecraft.network.chat.Component;
final class GlobalSearchScreen extends ScrollScreen implements CommunityScreen.Receiver {
 private final Screen parent;private String query="",notice="Введите хотя бы два символа";private JsonArray entries=new JsonArray();private final RequestSession session=new RequestSession();private boolean busy,failed;private long changed,generation;private final ScreenState<MenuData.Page> model=new ScreenState<>();
 GlobalSearchScreen(Screen parent){super(Component.literal("Поиск по серверу"));this.parent=parent;}
 private UiDialog dialog(){return UiDialog.fit(width,height,410,300);}private int w(){return dialog().body().width();}private int x(){return dialog().body().x();}private int top(){return dialog().frame().y();}private int bottom(){return dialog().frame().bottom();}
 private void search(){if(busy){session.cancel();model.cancel();ServerMenuClient.cancelReads(this);busy=false;}if(query.strip().length()<2){changed=0;notice="Введите хотя бы два символа";return;}var j=new JsonObject();j.addProperty("action","community");j.addProperty("section","home");j.addProperty("op","globalSearch");j.addProperty("query",query);generation=model.begin();busy=true;failed=false;notice="Поиск…";changed=0;ServerMenuClient.request(session.begin(j,false,System.currentTimeMillis()));rebuildWidgets();}
 @Override protected void init(){UiSearchToolbar.query(font,new dev.abros.rivet.core.NativeLayout.Box(x(),top()+32,UiSearchToolbar.contentWidth(w()),20),"Поиск по серверу",query,this::addRenderableWidget,v->{query=v;changed=System.currentTimeMillis()+500;},this::search,true);scrollArea(entries.size(),new dev.abros.rivet.core.NativeLayout.Box(x(),top()+62,Math.max(0,w()),Math.max(0,(bottom()-54)-(top()+62))),26);for(int n=firstRow;n<Math.min(entries.size(),firstRow+visibleRows);n++){var e=entries.get(n).getAsJsonObject();addRenderableWidget(UiActions.button(Component.literal(font.plainSubstrByWidth((Json.str(e,"section").equals("players")?"Игрок":Json.str(e,"section").equals("tasks")?"Задача":CommunityScreen.name(Json.str(e,"section")))+" · "+Json.str(e,"title"),w()-20)),UiActions.Tone.NORMAL,"",b->{String section=Json.str(e,"section");if(section.equals("players"))FeatureListScreen.searchPlayer(this,Json.str(e,"title"));else if(section.equals("tasks"))minecraft.setScreen(new TaskScreen(this,Json.opt(e,"group",""),Json.str(e,"id")));else minecraft.setScreen(new CommunityScreen(this,section,Json.str(e,"id")));}).bounds(x(),top()+62+(n-firstRow)*26,w(),22).build());}UiActions.close(new dev.abros.rivet.core.NativeLayout.Box(x(),bottom()-28,w(),20),this::addRenderableWidget,this::onClose);}
 public void receiveCommunity(JsonObject j){if(!session.receive(j))return;busy=false;failed=j.has("error");if(failed)model.fail(generation,MenuData.failure(j).message());else model.resolve(generation,MenuData.page(j,"entries"),!j.has("entries")||j.getAsJsonArray("entries").isEmpty());notice=j.has("error")?model.error():j.getAsJsonArray("entries").isEmpty()?"Ничего не найдено":"Найдено: "+j.getAsJsonArray("entries").size();if(j.has("entries")&&!entries.equals(j.get("entries"))){entries=j.getAsJsonArray("entries");resetScroll();}rebuildWidgets();}
 @Override public void tick(){if(changed>0&&System.currentTimeMillis()>=changed)search();if(session.timeout(System.currentTimeMillis())){model.fail(generation,"Нет ответа сервера");busy=false;failed=true;notice="Нет ответа. Нажмите «Найти».";rebuildWidgets();}}
 @Override public boolean keyPressed(int key,int scan,int modifiers){if((key==257||key==335)&&getFocused() instanceof EditBox){search();return true;}return super.keyPressed(key,scan,modifiers);}
 @Override public void renderBackground(GuiGraphics g,int mx,int my,float d){UiDialog.draw(g,width,w(),top(),bottom());}
 @Override public void render(GuiGraphics g,int mx,int my,float d){UiDialog.render(parent,this,g,d,()->{super.render(g,mx,my,d);UiHeading.dialog(g,font,title,x(),top(),w());if(entries.isEmpty())UiState.draw(g,font,failed?UiState.Kind.ERROR:busy?UiState.Kind.LOADING:query.strip().length()<2?UiState.Kind.EMPTY:UiState.Kind.FILTERED,failed?"Поиск недоступен":busy?"Ищем на сервере…":query.strip().length()<2?"Что найти?":"Ничего не найдено",failed?notice:busy?"Получаем игроков, задачи и записи.":query.strip().length()<2?"Введите хотя бы два символа в строке поиска.":"Попробуйте другой запрос.",x(),top()+64,w(),bottom()-56);else Ui.status(g,font,notice,x(),bottom()-50,w(),bottom()-30);});}
 @Override public void onClose(){session.cancel();model.cancel();ServerMenuClient.cancelReads(this);minecraft.setScreen(parent);}
 @Override public boolean isPauseScreen(){return false;}
}
