package dev.abros.rivet.client;
import dev.abros.rivet.core.NativeLayout;
/** Anchors survive resolution changes. Only the user chooses placement. */
final class HudPlacement {
 static NativeLayout.Box fit(int width,int height,int w,int h,int ax,int ay,int ox,int oy){w=Math.max(0,Math.min(w,width-8));h=Math.max(0,Math.min(h,height-8));int x=ax==0?ox:ax==2?width-w-ox:(width-w)/2+ox;int y=ay==0?oy:ay==2?height-h-oy:(height-h)/2+oy;return new NativeLayout.Box(Math.max(4,Math.min(width-w-4,x)),Math.max(4,Math.min(height-h-4,y)),w,h);}
 static void move(String item,int x,int y,int w,int h,int width,int height){var s=HudSettings.INSTANCE;int ax=x+w/2<width/3?0:x+w/2>width*2/3?2:1,ay=y+h/2<height/3?0:y+h/2>height*2/3?2:1;int ox=ax==2?width-x-w:ax==1?x-(width-w)/2:x,oy=ay==2?height-y-h:ay==1?y-(height-h)/2:y;if(Math.abs(ox)<12)ox=ax==1?0:8;if(Math.abs(oy)<12)oy=ay==1?0:8;switch(item){case "chat"->{s.hintsPositioned=true;s.hintAnchorX=ax;s.hintAnchorY=ay;s.hintOffsetX=ox;s.hintOffsetY=oy;}case "minimap"->{MapSettings.INSTANCE.hud.mapAnchorX=ax;MapSettings.INSTANCE.hud.mapAnchorY=ay;MapSettings.INSTANCE.hud.mapOffsetX=ox;MapSettings.INSTANCE.hud.mapOffsetY=oy;}case "direction"->{MapSettings.INSTANCE.hud.directionAnchorX=ax;MapSettings.INSTANCE.hud.directionAnchorY=ay;MapSettings.INSTANCE.hud.directionOffsetX=ox;MapSettings.INSTANCE.hud.directionOffsetY=oy;}default->{s.anchorX=ax;s.anchorY=ay;s.offsetX=ox;s.offsetY=oy;}}}
 static boolean resize(String item,double delta){var s=HudSettings.INSTANCE;float factor=(float)Math.pow(1.1,Math.clamp(delta,-4,4));switch(item){case "minimap"->{var map=MapSettings.INSTANCE;map.size=Math.clamp(map.size+(int)Math.round(delta*8),80,192);map.save();Minimap.invalidate();}case "widget"->s.scale=HudSettings.clamp(s.scale*factor,.65f,1.5f);case "chat"->s.hintScale=HudSettings.clamp(s.hintScale*factor,.65f,2);case "direction"->MapSettings.INSTANCE.hud.directionScale=HudSettings.clamp(MapSettings.INSTANCE.hud.directionScale*factor,.65f,2);case "notices"->s.toastScale=HudSettings.clamp(s.toastScale*factor,.65f,2);default->{return false;}}s.save();MapSettings.INSTANCE.save();return true;}
 static void reset(){var s=HudSettings.INSTANCE;s.scale=HudSettings.DEFAULT_SCALE;s.hintScale=s.toastScale=1;MapSettings.INSTANCE.hud.directionScale=1;MapSettings.INSTANCE.size=MapSettings.DEFAULT_SIZE;MapSettings.INSTANCE.save();Minimap.invalidate();MapSettings.INSTANCE.hud.mapAnchorX=0;MapSettings.INSTANCE.hud.mapAnchorY=0;MapSettings.INSTANCE.hud.mapOffsetX=8;MapSettings.INSTANCE.hud.mapOffsetY=8;s.anchorX=2;s.anchorY=1;s.offsetX=8;s.offsetY=0;s.hintsPositioned=false;s.hintAnchorX=2;s.hintAnchorY=2;s.hintOffsetX=8;s.hintOffsetY=48;MapSettings.INSTANCE.hud.directionAnchorX=1;MapSettings.INSTANCE.hud.directionAnchorY=1;MapSettings.INSTANCE.hud.directionOffsetX=0;MapSettings.INSTANCE.hud.directionOffsetY=28;s.save();MapSettings.INSTANCE.save();}
 private HudPlacement(){}
}
