package dev.abros.rivet.client;

import com.google.gson.*;
import dev.abros.rivet.core.*;
import net.minecraft.client.Minecraft;
import net.minecraft.client.gui.GuiGraphics;
import java.util.*;

/** Shared compound HUD surfaces: layout, clipped text, marks, progress and hit regions. */
final class HudRenderer {
 static dev.abros.rivet.core.NativeLayout.Box noticeBounds=new dev.abros.rivet.core.NativeLayout.Box(0,0,0,0);
 private static final HudNoticeQueue PREVIEW_NOTICES=new HudNoticeQueue();
 record Block(String title,String text,String section,String target,String group,double progress){}
 record Hit(double x,double y,double w,double h,Runnable action){boolean contains(double px,double py){return px>=x&&py>=y&&px<x+w&&py<y+h;}}
 private static final List<Hit> hits=new ArrayList<>();static int lastX,lastY,lastW,lastH,lastRadius;private static long drawn;private static int widgetHits;private static float motionOpacity=1;private static long lastMotionFrame;private static Object motionConnection;private static final Map<String,Double> progressValues=new HashMap<>();private static final Map<String,Long> progressChanged=new HashMap<>();
 static List<Block> blocks(boolean preview){var out=new ArrayList<Block>();var data=RivetHud.snapshot;var state=ServerMenuClient.state;var settings=HudSettings.INSTANCE;
  for(String key:settings.order){if(!settings.enabled&&!preview||settings.hidden.contains(key))continue;switch(key){
   case "profile"->{if(HudProfile.height(preview)>0)out.add(new Block("","","profile","","",-1));}
   case "server"->{String title=Minecraft.getInstance().getCurrentServer()==null?"Rivet":Minecraft.getInstance().getCurrentServer().name;out.add(new Block(title,state.has("online")?state.get("online")+" / "+state.get("maximum"):Client.text("ui.connecting_40b27edf"),"server","","",-1));}
   case "task"->{if(data.has("tasks")&&!data.getAsJsonArray("tasks").isEmpty()){var task=data.getAsJsonArray("tasks").get(0).getAsJsonObject();long due=task.has("dueAt")?task.get("dueAt").getAsLong():0;int total=task.get("total").getAsInt(),done=task.get("done").getAsInt();String text=(total>0?done+" / "+total+Client.text("ui.steps_ad413b8a"):Client.text("ui.no_steps_08c3b583"))+(due>0?" · "+RivetHud.relative(due):"");out.add(new Block(Json.str(task,"title"),text,"tasks",Json.str(task,"id"),Json.opt(task,"group",""),total>0?done/(double)total:-1));}else if(preview)out.add(new Block(Client.text("ui.the_task_will_appear_here_e7279326"),Client.text("ui.deadline_and_step_progress_4a230a5c"),"tasks","","",.4));}
   case "event"->{if(data.has("events")&&!data.getAsJsonArray("events").isEmpty()){var event=data.getAsJsonArray("events").get(0).getAsJsonObject();out.add(new Block(Json.str(event,"title"),RivetHud.relative(event.get("startsAt").getAsLong()),"events",Json.str(event,"id"),"",-1));}else if(preview)out.add(new Block(Client.text("ui.next_event_8291a90b"),Client.text("ui.in_30_min_bcc60b62"),"events","","",-1));}
   case "groups"->{if(data.has("groups")&&!data.getAsJsonArray("groups").isEmpty()){var labels=new ArrayList<String>();for(var e:data.getAsJsonArray("groups"))labels.add(Json.str(e.getAsJsonObject(),"title"));out.add(new Block(Client.text("ui.groups_903e08f2"),String.join(" · ",labels),"groups","","",-1));}else if(preview)out.add(new Block(Client.text("ui.groups_903e08f2"),Client.text("ui.your_group_names_783b5961"),"groups","","",-1));}
   case "unread"->{int count=state.has("unread")?state.get("unread").getAsInt():0;if(count>0||preview)out.add(new Block(Client.text("ui.notifications_ee3c35f3"),count+Client.text("ui.unread_e955542b"),"notifications","","",-1));}
  }}
  long restart=state.has("restartAt")?state.get("restartAt").getAsLong():0;if(ServerMenuClient.enabled(2)&&restart>System.currentTimeMillis())out.add(0,new Block(Client.text("ui.server_restart_1def2a80"),RivetHud.relative(restart),"server","","",-1));
  if((settings.hidden.contains("task")||!settings.enabled)&&data.has("tasks")&&!data.getAsJsonArray("tasks").isEmpty()){var task=data.getAsJsonArray("tasks").get(0).getAsJsonObject();long due=task.has("dueAt")?task.get("dueAt").getAsLong():0;if(due>0&&due<System.currentTimeMillis())out.add(0,new Block(Client.text("ui.overdue_6322314b")+Json.str(task,"title"),RivetHud.relative(due),"tasks",Json.str(task,"id"),Json.opt(task,"group",""),-1));}
  if(preview&&out.isEmpty())out.add(new Block(Client.text("ui.blocks_disabled_3d0d9ef1"),Client.text("ui.enable_them_in_hud_settings_359a84b4"),"notifications","","",-1));return out;
 }
 static void render(GuiGraphics g,boolean widget,boolean preview){hits.clear();widgetHits=0;drawn=net.minecraft.Util.getMillis();var mc=Minecraft.getInstance();var settings=HudSettings.INSTANCE;long frame=net.minecraft.Util.getMillis();if(motionConnection!=mc.getConnection()){motionConnection=mc.getConnection();motionOpacity=1;progressValues.clear();progressChanged.clear();}float wanted=settings.dimMoving&&!preview&&mc.screen==null&&mc.player!=null&&mc.player.getDeltaMovement().horizontalDistanceSqr()>.0004?.55f:1;if(!AccessibilityScreen.animations())motionOpacity=wanted;motionOpacity+=(wanted-motionOpacity)*Math.min(1,Math.max(0,frame-lastMotionFrame)/220f);lastMotionFrame=frame;float density=(float)Math.min(1,1.5/mc.getWindow().getGuiScale());
  boolean showing=ServerMenuClient.enabled(0)&&!mc.options.hideGui;float toastScale=Math.min(settings.toastScale,Math.max(.3f,(g.guiHeight()-16f)/82));int capacity=Math.max(1,(int)((g.guiHeight()-16)/(87*toastScale)));var notices=RivetHud.QUEUE.advance(net.minecraft.Util.getMillis(),Math.min(settings.toastCount,capacity),showing);if(preview){PREVIEW_NOTICES.clear();PREVIEW_NOTICES.add(new HudNoticeQueue.Notice("","notifications","","summary",Client.text("ui.notification_3a42cfeb"),Client.text("ui.a_server_message_will_appear_here_7266a661"),HudNoticeQueue.Priority.ORDINARY),frame-1000,1);notices=PREVIEW_NOTICES.advance(frame,1,true);showing=true;}int toastWidth=Math.min(260,(int)((preview?Math.max(80,g.guiWidth()/3):g.guiWidth()-16)/toastScale));noticeBounds=new NativeLayout.Box(g.guiWidth()-(int)Math.ceil(toastWidth*toastScale)-8,8,(int)Math.ceil(toastWidth*toastScale),(int)Math.ceil(notices.size()*87*toastScale));
  if(widget){var blocks=blocks(preview);if(!blocks.isEmpty()){int h=12;for(var block:blocks)h+=blockHeight(block,preview);float scale=Math.min(settings.scale*density,Math.max(.3f,(g.guiHeight()-16f)/h));int w=Math.min(214,Math.max(80,(int)((g.guiWidth()-16)/scale)));int pw=(int)Math.ceil(w*scale),ph=(int)Math.ceil(h*scale);int x=settings.anchorX==0?settings.offsetX:settings.anchorX==2?g.guiWidth()-pw-settings.offsetX:(g.guiWidth()-pw)/2+settings.offsetX;int y=settings.anchorY==0?settings.offsetY:settings.anchorY==2?g.guiHeight()-ph-settings.offsetY:(g.guiHeight()-ph)/2+settings.offsetY;x=Math.max(4,Math.min(g.guiWidth()-pw-4,x));y=Math.max(4,Math.min(g.guiHeight()-ph-4,y));if(!notices.isEmpty()){int toastLeft=(int)(g.guiWidth()-toastWidth*toastScale-8),toastBottom=(int)Math.ceil(8+notices.size()*87*toastScale);if(x+pw>toastLeft&&y<toastBottom&&y+ph>8){if(toastBottom+ph+8<=g.guiHeight())y=toastBottom+4;else if(toastLeft-pw-8>=4)x=toastLeft-pw-8;else{scale=Math.max(.15f,(g.guiHeight()-toastBottom-8f)/h);pw=(int)Math.ceil(w*scale);ph=(int)Math.ceil(h*scale);x=Math.max(4,Math.min(g.guiWidth()-pw-4,x));y=toastBottom+4;}}}lastX=x;lastY=y;lastW=pw;lastH=ph;lastRadius=Math.max(2,Math.round(UiHudSurface.RADIUS*scale));
   g.pose().pushPose();g.pose().translate(x,y,0);g.pose().scale(scale,scale,1);
   UiHudSurface.panel(g,w,h,settings.opacity*motionOpacity);
   int row=6;for(var block:blocks){int rh=blockHeight(block,preview);if(block.progress()>=0&&!preview){String key=block.group()+"|"+block.target();if(progressValues.size()>=128&&!progressValues.containsKey(key)){progressValues.clear();progressChanged.clear();}Double previous=progressValues.put(key,block.progress());if(previous!=null&&Double.compare(previous,block.progress())!=0)progressChanged.put(key,frame);long changed=progressChanged.getOrDefault(key,0L);if(changed>0&&frame-changed<1800&&AccessibilityScreen.animations())g.fill(3,row+2,5,row+rh-3,alpha(UiKit.accent(),.35*(1-(frame-changed)/1800d)));}
    if(block.section().equals("profile"))HudProfile.draw(g,0,row,w,preview);
    else if(block.section().equals("server")&&!block.title().equals(Client.text("ui.server_restart_1def2a80"))){String online=UiKit.fit(mc.font,block.text(),Math.max(30,w/2-12));int ow=mc.font.width(online);text(g,block.title(),10,row+5,Math.max(0,w-ow-28),UiKit.text());text(g,online,w-ow-10,row+5,ow,UiKit.muted());}
    else{String icon=block.section().equals("tasks")?UiIcons.CHECK:block.section().equals("events")?UiIcons.REFRESH:UiIcons.RIGHT;UiIcons.draw(g,icon,9,row+6,UiKit.accent());text(g,block.title(),26,row+4,w-38,UiKit.text());text(g,block.text(),26,row+17,w-38,UiKit.muted());if(block.progress()>=0){g.fill(26,row+29,w-10,row+31,UiPalette.scrollTrack());g.fill(26,row+29,26+(int)((w-36)*block.progress()),row+31,UiKit.accent());}}
    if(row+rh<h-6)g.fill(10,row+rh-1,w-10,row+rh,alpha(UiKit.border(),.55));
    int index=row;int px=x,py=y;float factor=scale;hits.add(new Hit(px,py+index*factor,pw,rh*factor,()->{if(!block.section().equals("profile"))RivetHud.open(block.section(),block.target(),block.group());}));row+=rh;}g.pose().popPose();
  }}
  widgetHits=hits.size();
  if(!showing)return;int width=toastWidth;float y=8;for(var entry:notices){if(y+82*toastScale>g.guiHeight()-8)break;long now=net.minecraft.Util.getMillis();double fade=!preview&&AccessibilityScreen.animations()?Math.min(1,Math.min(entry.age(now)/140d,entry.remaining(now)*entry.duration()/220d)):1;float x=g.guiWidth()-width*toastScale-8+(float)((1-fade)*12);int h=82;var n=entry.notice();g.pose().pushPose();g.pose().translate(x,y,0);g.pose().scale(toastScale,toastScale,1);surface(g,0,0,width,h,.94f*(float)fade);int accent=n.priority()==HudNoticeQueue.Priority.URGENT?UiPalette.color(0xFFDB7777):UiKit.accent();g.fill(0,4,2,h-4,alpha(accent,fade));UiNoticeIcon.draw(g,n,7,7,alpha(accent,fade));text(g,entry.count()>1?Client.text("ui.updates_1fdbeae3")+entry.count()+" · "+n.title():n.title(),22,8,width-48,alpha(UiKit.text(),fade));var wrapped=mc.font.getSplitter().splitLines(n.body(),width-24,net.minecraft.network.chat.Style.EMPTY);for(int line=0;line<Math.min(2,wrapped.size());line++)text(g,wrapped.get(line).getString(),9,24+line*11,width-24,alpha(UiKit.muted(),fade));UiIcons.draw(g,UiIcons.CLEAR,width-18,7,alpha(UiKit.muted(),fade));g.fill(6,h-4,6+(int)((width-12)*entry.remaining(now)),h-3,alpha(UiKit.accent(),fade));String quick=RivetHud.actionLabel(entry);if(!quick.isEmpty())text(g,quick,9,62,width/2-10,alpha(UiKit.accent(),fade));if(n.priority()!=HudNoticeQueue.Priority.URGENT)text(g,Client.text("ui.in_10_min_3d31e053"),quick.isEmpty()?9:width/2,62,quick.isEmpty()?width-20:width/2-9,alpha(UiKit.accent(),fade));g.pose().popPose();
   if(!quick.isEmpty())hits.add(new Hit(x,y+56*toastScale,width/2f*toastScale,20*toastScale,()->RivetHud.act(entry)));if(n.priority()!=HudNoticeQueue.Priority.URGENT)hits.add(new Hit(x+(quick.isEmpty()?0:width/2f)*toastScale,y+56*toastScale,(quick.isEmpty()?width:width/2f)*toastScale,20*toastScale,()->RivetHud.QUEUE.defer(entry,net.minecraft.Util.getMillis(),600000)));
   hits.add(new Hit(x+(width-24)*toastScale,y,24*toastScale,22*toastScale,()->RivetHud.acknowledge(RivetHud.QUEUE.dismiss(entry))));hits.add(new Hit(x,y,width*toastScale,h*toastScale,()->{RivetHud.acknowledge(RivetHud.QUEUE.dismiss(entry));RivetHud.open(n.section(),n.target(),n.group());}));y+=(h+5)*toastScale;
  }
 }
 private static int blockHeight(Block b,boolean preview){return b.section().equals("profile")?HudProfile.height(preview):b.section().equals("server")&&!b.title().equals(Client.text("ui.server_restart_1def2a80"))?24:38;}
 private static int alpha(int color,double fade){return color&0xFFFFFF|Math.max(5,(int)(255*fade))<<24;}
 private static void surface(GuiGraphics g,int x,int y,int w,int h,float opacity){int color=UiKit.surface()&0xFFFFFF|((int)(255*opacity)<<24);UiKit.surface(g,x,y,w,h,color);}
 private static void text(GuiGraphics g,String value,int x,int y,int w,int color){g.drawString(Minecraft.getInstance().font,UiKit.fit(Minecraft.getInstance().font,value,w),x,y,color,false);}
 static boolean click(double x,double y,boolean widget){if(Minecraft.getInstance().options.hideGui||net.minecraft.Util.getMillis()-drawn>250)return false;for(int n=widgetHits;n<hits.size();n++){var hit=hits.get(n);if(hit.contains(x,y)){hit.action().run();return true;}}if(widget)for(int n=0;n<widgetHits;n++){var hit=hits.get(n);if(hit.contains(x,y)){hit.action().run();return true;}}return false;}
}
