package dev.abros.rivet.client;

import dev.abros.rivet.core.NativeLayout;
import net.minecraft.client.gui.GuiGraphics;
import net.minecraft.client.gui.screens.Screen;
import net.minecraft.network.chat.Component;
import java.util.*;

/** Compound settings dialog with one bounded list for every density and GUI scale. */
final class HudSettingsScreen extends ScrollScreen {
 private final Screen parent;private int tab;private String eventCategory="";private UiDialog layout;
 private record Row(String label,String value,Boolean checked,Runnable action){}
 private final List<Row> rows=new ArrayList<>();private final HudSettings s=HudSettings.INSTANCE;
 HudSettingsScreen(Screen parent){super(Component.literal("HUD и уведомления"));this.parent=parent;}
 void previewTab(int n){tab=n;rebuildWidgets();}
 private void change(Runnable action){action.run();s.save();RivetHud.refresh();rebuildWidgets();}
 private void toggle(String label,boolean value,Runnable action){rows.add(new Row(label,"",value,()->change(action)));}
 private void choice(String label,List<String> labels,int selected,java.util.function.IntConsumer action){rows.add(new Row(label,labels.get(selected),null,()->minecraft.setScreen(new ChoicePopup(this,label,labels,n->change(()->action.accept(n))).current(selected))));}
 @Override protected void init(){layout=UiDialog.fit(width,height,400,360);var body=layout.body();rows.clear();
  UiTabs.build(this,font,new NativeLayout.Box(body.x(),layout.header().bottom(),body.width(),20),List.of("Виджет","Профиль","Блоки","Плашки","События"),tab,this::addRenderableWidget,n->{tab=n;resetScroll();rebuildWidgets();},true);
  if(tab==0){toggle("Показывать виджет",s.enabled,()->s.enabled=!s.enabled);rows.add(new Row("Расположение","Изменить…",null,()->minecraft.setScreen(new HudInteractionScreen(true,this))));choice("Масштаб",List.of("75%","100%","125%","150%"),s.scale<.9?0:s.scale<1.15?1:s.scale<1.4?2:3,n->s.scale=new float[]{.75f,1,1.25f,1.5f}[n]);choice("Плотность фона",List.of("50%","65%","80%","100%"),s.opacity<.6?0:s.opacity<.75?1:s.opacity<.9?2:3,n->s.opacity=new float[]{.5f,.65f,.8f,1}[n]);toggle("В чате",s.chat,()->s.chat=!s.chat);toggle("В инвентаре",s.inventory,()->s.inventory=!s.inventory);toggle("В меню паузы",s.pause,()->s.pause=!s.pause);toggle("При открытом F3",s.debug,()->s.debug=!s.debug);toggle("Голограммы привязанных складов",s.holograms,()->s.holograms=!s.holograms);toggle("Приглушать фон при движении",s.dimMoving,()->s.dimMoving=!s.dimMoving);rows.add(new Row("Клавиша взаимодействия","Настроить…",null,()->minecraft.setScreen(new net.minecraft.client.gui.screens.options.controls.KeyBindsScreen(this,minecraft.options))));}
  else if(tab==1){var labels=List.of("Голова игрока","Никнейм","Префикс LuckPerms","Суффикс LuckPerms","Время текущей сессии","Задержка соединения");for(int n=0;n<HudSettings.PROFILE_FIELDS.size();n++){String field=HudSettings.PROFILE_FIELDS.get(n);toggle(labels.get(n),!s.profileHidden.contains(field),()->{if(!s.profileHidden.add(field))s.profileHidden.remove(field);});}}
  else if(tab==2){for(String block:s.order){toggle(HudSettings.label(block),!s.hidden.contains(block),()->{if(!s.hidden.add(block))s.hidden.remove(block);});rows.add(new Row("Порядок: "+HudSettings.label(block),"Переместить…",null,()->minecraft.setScreen(new ChoicePopup(this,"Позиция блока",java.util.stream.IntStream.rangeClosed(1,s.order.size()).mapToObj(Integer::toString).toList(),n->change(()->{s.order.remove(block);s.order.add(n,block);})).current(s.order.indexOf(block)))));}}
  else if(tab==3){toggle("Показывать плашки",ServerMenuClient.enabled(0),()->ServerMenuClient.toggle(0));toggle("Звук",ServerMenuClient.enabled(1),()->ServerMenuClient.toggle(1));toggle("Тихие часы обычных уведомлений",s.quietHours,()->s.quietHours=!s.quietHours);var hours=java.util.stream.IntStream.range(0,24).mapToObj(n->String.format("%02d:00",n)).toList();choice("Начало тихих часов",hours,s.quietStart,n->s.quietStart=n);choice("Конец тихих часов",hours,s.quietEnd,n->s.quietEnd=n);toggle("Предупреждения о перезапуске",ServerMenuClient.enabled(2),()->ServerMenuClient.toggle(2));choice("Одновременно на экране",List.of("1","2","3","4","5"),s.toastCount-1,n->s.toastCount=n+1);for(String section:List.of("server","home","groups","events","board","polls","ideas","help"))toggle("Плашки: "+(section.equals("server")?"Сервер":section.equals("home")?"Личные задачи":CommunityScreen.name(section)),!s.muted.contains(section),()->{if(!s.muted.add(section))s.muted.remove(section);});}
  else{var categories=List.of("","server","home","groups","events","board","polls","ideas","help");var categoryLabels=List.of("Все разделы","Сервер","Личные задачи","Объединения","События","Доска объявлений","Голосования","Предложения","Обращения");choice("Фильтр событий",categoryLabels,categories.indexOf(eventCategory),n->eventCategory=categories.get(n));var events=List.of("invite","apply","application","response","workAssign","workDue","reminder","cancel","reschedule","comment","plusComment","workComment","role","plusRemoveMember","plusEventInvite","plusTaskStatus");var labels=List.of("Приглашения","Заявки","Решения по заявкам","Отклики","Назначение задачи","Изменение срока","Напоминания","Отмена события","Перенос события","Комментарии","Комментарии к записи","Комментарии задачи","Изменение роли","Исключение из объединения","Приглашение на событие","Статус задачи");for(int n=0;n<events.size();n++){String event=events.get(n);String category=eventCategory;String key=category.isEmpty()?"event:"+event:category+":"+event;String allowKey=category.isEmpty()?"allow:"+event:"allow:"+category+":"+event;boolean value=dev.abros.rivet.core.HudDeliveryPolicy.allowed(s.muted,category,event,RivetHud.defaultEvent(event));toggle(labels.get(n),value,()->{if(value){s.muted.add(key);s.muted.remove(allowKey);}else{s.muted.remove(key);s.muted.add(allowKey);}});}}
  var viewport=new NativeLayout.Box(body.x(),body.y()+20,body.width(),Math.max(0,body.height()-20));var geometry=scrollArea(rows.size(),viewport,30);for(int i=firstRow;i<Math.min(rows.size(),firstRow+visibleRows);i++){var row=rows.get(i);int y=viewport.y()+(i-firstRow)*30,w=geometry.content().width();if(row.checked()!=null)addRenderableWidget(new UiToggle(row.label(),viewport.x(),y,w,row.checked(),row.action()));else addRenderableWidget(UiActions.button(Component.literal(row.label()+": "+row.value()),UiActions.Tone.NORMAL,"",b->row.action().run()).bounds(viewport.x(),y,w,24).build());}
  addRenderableWidget(UiActions.button(Component.literal("Готово"),UiActions.Tone.NORMAL,"",b->onClose()).bounds(layout.footer().right()-96,layout.footer().bottom()-20,96,20).build());
 }
 @Override public void renderBackground(GuiGraphics g,int x,int y,float d){UiDialog.surface(g,layout.frame().x(),layout.frame().y(),layout.frame().width(),layout.frame().height());}
 @Override public void render(GuiGraphics g,int x,int y,float delta){UiDialog.render(parent,this,g,delta,()->{super.render(g,x,y,delta);UiHeading.dialog(g,font,title,layout.header().x(),layout.frame().y(),layout.header().width());Ui.status(g,font,s.error.isEmpty()?"Общие настройки для всех серверов · Esc закрывает · F1 скрывает":s.error,layout.footer().x(),layout.footer().y(),layout.footer().width(),layout.footer().bottom()-24);});}
 @Override public boolean isPauseScreen(){return false;}
 @Override public void onClose(){minecraft.setScreen(parent);}
}
