package dev.abros.rivet.client;

import dev.abros.rivet.core.NativeLayout;
import net.minecraft.client.gui.GuiGraphics;
import net.minecraft.client.gui.screens.Screen;
import net.minecraft.network.chat.Component;
import java.util.*;

/** Compound settings dialog with one bounded list for every density and GUI scale. */
final class HudSettingsScreen extends ScrollScreen {
 private final Screen parent;private int tab;private String eventCategory="";private UiDialog layout;
 private record Row(String label,String value,Boolean checked,Runnable action){}
 private final List<Row> rows=new ArrayList<>();private final HudSettings s=HudSettings.INSTANCE;
 HudSettingsScreen(Screen parent){super(Component.literal("Настройки Rivet"));this.parent=parent;}
 HudSettingsScreen(Screen parent,int tab){this(parent);this.tab=tab;}
 void previewTab(int n){tab=n;rebuildWidgets();}
 private void change(Runnable action){action.run();s.save();RivetHud.refresh();rebuildWidgets();}
 private void toggle(String label,boolean value,Runnable action){rows.add(new Row(label,"",value,()->change(action)));}
 private void choice(String label,List<String> labels,int selected,java.util.function.IntConsumer action){rows.add(new Row(label,labels.get(selected),null,()->minecraft.setScreen(new ChoicePopup(this,label,labels,n->change(()->action.accept(n))).current(selected))));}
 @Override protected void init(){layout=UiSettingsShell.build(width,height,tab<=2?1:2,parent,this,this::addRenderableWidget,()->UiSettingsShell.confirm(this,this::resetSection),this::onClose);var body=layout.body();rows.clear();
  if(tab==0){toggle("Показывать виджет",s.enabled,()->s.enabled=!s.enabled);choice("Масштаб",List.of("75%","100%","125%","150%"),s.scale<.9?0:s.scale<1.15?1:s.scale<1.4?2:3,n->s.scale=new float[]{.75f,1,1.25f,1.5f}[n]);choice("Плотность фона",List.of("50%","65%","80%","100%"),s.opacity<.6?0:s.opacity<.75?1:s.opacity<.9?2:3,n->s.opacity=new float[]{.5f,.65f,.8f,1}[n]);toggle("В чате",s.chat,()->s.chat=!s.chat);toggle("В инвентаре",s.inventory,()->s.inventory=!s.inventory);toggle("В меню паузы",s.pause,()->s.pause=!s.pause);toggle("При открытом F3",s.debug,()->s.debug=!s.debug);toggle("Голограммы привязанных складов",s.holograms,()->s.holograms=!s.holograms);toggle("Приглушать фон при движении",s.dimMoving,()->s.dimMoving=!s.dimMoving);rows.add(new Row("Клавиша взаимодействия","Настроить…",null,()->minecraft.setScreen(new net.minecraft.client.gui.screens.options.controls.KeyBindsScreen(this,minecraft.options))));}
  if(tab<=2){var labels=List.of("Голова игрока","Никнейм","Префикс LuckPerms","Суффикс LuckPerms","Время текущей сессии","Задержка соединения");for(int n=0;n<HudSettings.PROFILE_FIELDS.size();n++){String field=HudSettings.PROFILE_FIELDS.get(n);toggle(labels.get(n),!s.profileHidden.contains(field),()->{if(!s.profileHidden.add(field))s.profileHidden.remove(field);});}}
  if(tab<=2){rows.add(new Row("Порядок блоков","Перетащить…",null,()->minecraft.setScreen(new HudOrderScreen(this))));for(String block:s.order)toggle(HudSettings.label(block),!s.hidden.contains(block),()->{if(!s.hidden.add(block))s.hidden.remove(block);});}
  if(tab>=3){toggle("Сводка пропущенных при входе",s.digest,()->s.digest=!s.digest);toggle("Показывать плашки",ServerMenuClient.enabled(0),()->ServerMenuClient.toggle(0));toggle("Звук",ServerMenuClient.enabled(1),()->ServerMenuClient.toggle(1));toggle("Тихие часы обычных уведомлений",s.quietHours,()->s.quietHours=!s.quietHours);var hours=java.util.stream.IntStream.range(0,24).mapToObj(n->String.format("%02d:00",n)).toList();choice("Начало тихих часов",hours,s.quietStart,n->s.quietStart=n);choice("Конец тихих часов",hours,s.quietEnd,n->s.quietEnd=n);toggle("Предупреждения о перезапуске",ServerMenuClient.enabled(2),()->ServerMenuClient.toggle(2));choice("Одновременно на экране",List.of("1","2","3","4","5"),s.toastCount-1,n->s.toastCount=n+1);for(String section:List.of("server","home","groups","events","board","polls","ideas","help"))toggle("Плашки: "+(section.equals("server")?"Сервер":section.equals("home")?"Личные задачи":CommunityScreen.name(section)),!s.muted.contains(section),()->{if(!s.muted.add(section))s.muted.remove(section);});}
  if(tab>=3){var categories=List.of("","server","home","groups","events","board","polls","ideas","help");var categoryLabels=List.of("Все разделы","Сервер","Личные задачи","Объединения","События","Доска объявлений","Голосования","Предложения","Обращения");choice("Фильтр событий",categoryLabels,categories.indexOf(eventCategory),n->eventCategory=categories.get(n));var events=List.of("invite","apply","application","response","workAssign","workDue","reminder","cancel","reschedule","comment","plusComment","workComment","role","plusRemoveMember","plusEventInvite","plusTaskStatus","spark");var labels=List.of("Приглашения","Заявки","Решения по заявкам","Отклики","Назначение задачи","Изменение срока","Напоминания","Отмена события","Перенос события","Комментарии","Комментарии к записи","Комментарии задачи","Изменение роли","Исключение из объединения","Приглашение на событие","Статус задачи","Диагностика spark");for(int n=0;n<events.size();n++){String event=events.get(n);String category=eventCategory;String key=category.isEmpty()?"event:"+event:category+":"+event;String allowKey=category.isEmpty()?"allow:"+event:"allow:"+category+":"+event;boolean value=dev.abros.rivet.core.HudDeliveryPolicy.allowed(s.muted,category,event,RivetHud.defaultEvent(event));toggle(labels.get(n),value,()->{if(value){s.muted.add(key);s.muted.remove(allowKey);}else{s.muted.remove(key);s.muted.add(allowKey);}});}}
  var viewport=new NativeLayout.Box(body.x(),body.y(),body.width(),Math.max(0,body.height()-(tab<=2?72:0)));var geometry=scrollArea(rows.size(),viewport,30);for(int i=firstRow;i<Math.min(rows.size(),firstRow+visibleRows);i++){var row=rows.get(i);int y=viewport.y()+(i-firstRow)*30,w=geometry.content().width();if(row.checked()!=null)addRenderableWidget(new UiToggle(row.label(),viewport.x(),y,w,row.checked(),row.action()));else addRenderableWidget(UiActions.button(Component.literal(row.label()+": "+row.value()),UiActions.Tone.NORMAL,"",b->row.action().run()).bounds(viewport.x(),y,w,24).build());}

 }
 private void resetSection(){if(tab<=2){s.enabled=true;s.chat=true;s.inventory=false;s.pause=false;s.debug=false;s.dimMoving=true;s.holograms=true;s.scale=1;s.opacity=.82f;s.anchorX=2;s.anchorY=1;s.offsetX=8;s.offsetY=0;s.order.clear();s.order.addAll(HudSettings.BLOCKS);s.hidden.clear();s.profileHidden.clear();s.profileHidden.addAll(List.of("session","ping"));}else{s.digest=true;s.quietHours=false;s.quietStart=22;s.quietEnd=8;s.toastCount=2;s.muted.clear();for(int n=0;n<3;n++)if(!ServerMenuClient.enabled(n))ServerMenuClient.toggle(n);}s.save();RivetHud.refresh();}
 @Override public void renderBackground(GuiGraphics g,int x,int y,float d){UiDialog.surface(g,layout.frame().x(),layout.frame().y(),layout.frame().width(),layout.frame().height());}
 @Override public void render(GuiGraphics g,int x,int y,float delta){UiDialog.render(parent,this,g,delta,()->{super.render(g,x,y,delta);UiHeading.dialog(g,font,title,layout.header().x(),layout.frame().y(),layout.header().width());if(tab<=2)UiSettingsPreview.widget(g,layout.body());if(!s.error.isEmpty())Ui.status(g,font,s.error,layout.body().x(),layout.footer().y(),layout.body().width(),layout.footer().bottom()-24);});}
 @Override public boolean isPauseScreen(){return false;}
 @Override public void onClose(){minecraft.setScreen(parent);}
}
