package dev.abros.rivet.client;
import com.google.gson.*;
import dev.abros.rivet.core.*;
import net.minecraft.client.gui.GuiGraphics;
import net.minecraft.client.gui.components.*;
import net.minecraft.client.gui.screens.Screen;
import net.minecraft.network.chat.Component;
import java.util.function.Consumer;
/** Small optional location editor; coordinates are published only after the parent form is sent. */
final class LocationEditor extends Screen {
 private final Screen parent;private final Consumer<JsonElement> save;private final boolean mayHide;private boolean privatePlace;private final JsonObject values;private String error="";
 LocationEditor(Screen parent,JsonElement value,boolean mayHide,Consumer<JsonElement> save){super(Client.tr("ui.location_8e2fe025"));this.parent=parent;this.mayHide=mayHide;this.save=save;values=value!=null&&value.isJsonObject()?value.getAsJsonObject().deepCopy():new JsonObject();privatePlace=values.has("membersOnly")&&values.get("membersOnly").getAsBoolean();}
 private static String dimensionName(String id){return switch(id){case "minecraft:overworld"->Client.text("ui.overworld_16dc0eed");case "minecraft:the_nether"->Client.text("ui.the_nether_ef07d123");case "minecraft:the_end"->Client.text("ui.the_end_47a4a1ca");default->id;};}
 private int top(){return Math.max(22,(height-220)/2);}private int left(){return (width-Math.min(360,width-24))/2;}
 @Override public void renderBackground(GuiGraphics g,int x,int y,float d){UiDialog.draw(g,width,Math.min(360,width-24),Math.max(4,top()-28),Math.min(height-4,top()+220));}
 @Override protected void init(){int x=left(),w=width-2*x,y=top();var coordinates=NativeLayout.row(new NativeLayout.Box(x,y+56,w,20),4,NativeLayout.Track.flex(1),NativeLayout.Track.flex(1),NativeLayout.Track.flex(1));String[] keys={"name","dimension","x","y","z"};String[] hints={Client.text("ui.location_name_08d08a2d"),Client.text("ui.dimension_e_g_minecraft_overworld_3f219017"),"X","Y","Z"};
  for(int i=0;i<keys.length;i++){String key=keys[i];if(key.equals("dimension")){var dimensions=new java.util.TreeSet<String>();dimensions.addAll(java.util.List.of("minecraft:overworld","minecraft:the_nether","minecraft:the_end"));if(minecraft.getConnection()!=null)for(var level:minecraft.getConnection().levels())dimensions.add(level.location().toString());String current=Json.opt(values,key,minecraft.level==null?"minecraft:overworld":minecraft.level.dimension().location().toString());values.addProperty(key,current);dimensions.add(current);var choices=java.util.List.copyOf(dimensions);addRenderableWidget(UiActions.button(Component.literal(dimensionName(current)+" ▾"),UiActions.Tone.NORMAL,"",b->minecraft.setScreen(new ChoicePopup(this,Client.text("map.tool.dimension"),choices.stream().map(LocationEditor::dimensionName).toList(),n->{values.addProperty(key,choices.get(n));rebuildWidgets();},b))).bounds(x,y+28,w,20).build());continue;}int boxX=i<2?x:coordinates.get(i-2).x(),boxY=y+(i<2?i*28:56),boxW=i<2?w:coordinates.get(i-2).width();var box=addRenderableWidget(UiFields.text(font,boxX,boxY,boxW,20,Component.literal(hints[i])));box.setHint(Component.literal(hints[i]));box.setMaxLength(i==0?80:i==1?160:10);box.setValue(values.has(key)?values.get(key).getAsString():"");box.setResponder(v->values.addProperty(key,v));}
  addRenderableWidget(UiActions.button(Client.tr("ui.my_position_2f4c98a9"),UiActions.Tone.NORMAL,"",b->{if(minecraft.player==null||minecraft.level==null)return;var pos=minecraft.player.blockPosition();values.addProperty("x",pos.getX());values.addProperty("y",pos.getY());values.addProperty("z",pos.getZ());values.addProperty("dimension",minecraft.level.dimension().location().toString());if(Json.opt(values,"name","").isBlank())values.addProperty("name",Client.text("ui.meeting_place_dea538ee"));rebuildWidgets();}).bounds(x,y+84,Math.min(150,w),20).build());
  if(mayHide)addRenderableWidget(UiActions.button(Component.literal(privatePlace?Client.text("ui.group_members_4e559a7d"):Client.text("ui.visible_to_everyone_a2ebd591")),UiActions.Tone.NORMAL,"",b->minecraft.setScreen(new ChoicePopup(this,Client.text("ui.who_can_see_the_location_a8f90710"),java.util.List.of(Client.text("ui.all_players_7b6d95ec"),Client.text("map.layer.peers")),n->{privatePlace=n==1;rebuildWidgets();},b))).bounds(x,y+108,w,20).build());
  addRenderableWidget(UiActions.button(Client.tr("done"),UiActions.Tone.NORMAL,"",b->{try{var j=values.deepCopy();for(String k:new String[]{"x","y","z"})j.addProperty(k,Integer.parseInt(values.has(k)?values.get(k).getAsString().strip():""));j.addProperty("membersOnly",mayHide&&privatePlace);save.accept(CommunityLocation.read(j).json());minecraft.setScreen(parent);}catch(Exception ex){error=ex.getMessage();}}).bounds(x,y+144,Math.min(120,w/2-3),20).build());
  addRenderableWidget(UiActions.button(Client.tr("ui.remove_location_d37c6be6"),UiActions.Tone.NORMAL,"",b->{save.accept(JsonNull.INSTANCE);minecraft.setScreen(parent);}).bounds(x+Math.min(120,w/2-3)+6,y+144,Math.min(140,w/2-3),20).build());UiActions.close(new dev.abros.rivet.core.NativeLayout.Box(x+(w-Math.min(120,w))/2,y+170,Math.min(120,w),20),this::addRenderableWidget,this::onClose);
 }
 @Override public void render(GuiGraphics g,int x,int y,float delta){UiDialog.render(parent,this,g,delta,()->{super.render(g,x,y,delta);UiHeading.dialog(g,font,title,left(),Math.max(4,top()-28),width-2*left());Ui.status(g,font,error,left(),top()+195,width-2*left(),height-2);});}
 @Override public void tick(){if(!ServerMenuClient.available())minecraft.setScreen(null);}
 @Override public void onClose(){minecraft.setScreen(parent);}
 @Override public boolean isPauseScreen(){return false;}
}
