package dev.abros.rivet.client;
import com.google.gson.*;
import dev.abros.rivet.core.*;
import net.minecraft.client.Minecraft;
import net.minecraft.resources.ResourceLocation;
import java.util.*;
/** Only Rivet's third-party origins are touched. Xaero retains the user's local hide overrides. */
final class ManagedXaeroLayer {
 private static final ResourceLocation PLACES=ResourceLocation.fromNamespaceAndPath("rivet","places"),PLAYERS=ResourceLocation.fromNamespaceAndPath("rivet","group_players");
 private static final Map<ResourceLocation,Object> previous=new HashMap<>();private static Boolean supported;private static final Map<ResourceLocation,String> payloads=new HashMap<>();
 static boolean available(){if(supported!=null)return supported;if(!net.neoforged.fml.ModList.get().isLoaded("xaerominimap"))return supported=false;try{Class.forName("xaero.hud.minimap.waypoint.thirdparty.ThirdPartyWaypoints").getMethod("add",String.class,Class.forName("xaero.common.minimap.waypoints.Waypoint"));return supported=true;}catch(Exception|LinkageError ex){return supported=false;}}
 static void clear(){payloads.clear();for(var origin:List.of(PLACES,PLAYERS)){Object rows=previous.remove(origin);if(rows!=null)try{XaeroBridge.call(rows,"clear");}catch(Exception ignored){}}}
 static void update(JsonArray places,JsonArray players)throws ReflectiveOperationException{if(!available())return;var mc=Minecraft.getInstance();if(mc.level==null){clear();return;}Object session=Class.forName("xaero.common.XaeroMinimapSession").getMethod("getCurrentSession").invoke(null);if(session==null)return;Object manager=XaeroBridge.call(XaeroBridge.call(session,"getWaypointsManager"),"getWorldManager"),world=XaeroBridge.call(manager,"getAutoWorld");if(world==null)return;Object third=XaeroBridge.call(XaeroBridge.call(world,"getContainer"),"getThirdPartyWaypointManager");String dimension=mc.level.dimension().location().toString();sync(third,PLACES,places,dimension,false);sync(third,PLAYERS,players,dimension,true);}
 private static void sync(Object manager,ResourceLocation origin,JsonArray rows,String dimension,boolean players)throws ReflectiveOperationException{Object dataset=XaeroBridge.call(manager,"get",origin),old=previous.put(origin,dataset);if(old!=null&&old!=dataset)XaeroBridge.call(old,"clear");String payload=dimension+rows.toString();if(!players)for(var row:rows)payload+=MapLayerClient.hidden(Json.str(row.getAsJsonObject(),"id"));if(old==dataset&&payload.equals(payloads.get(origin)))return;var active=new HashSet<String>();for(var e:rows){var row=e.getAsJsonObject();JsonObject location=players?row:row.getAsJsonObject("location");if(!Json.opt(location,"dimension","").equals(dimension))continue;String id=Json.str(row,players?"uuid":"id");if(!players&&(MapLayerClient.hidden(id)||!Json.opt(row,"status","open").equals("open")))continue;active.add(id);Object point=XaeroBridge.call(dataset,"get",id);int x=location.get("x").getAsInt(),y=location.get("y").getAsInt(),z=location.get("z").getAsInt();String name=Json.str(row,players?"name":"title");if(point==null){point=Class.forName("xaero.common.minimap.waypoints.Waypoint").getConstructor(int.class,int.class,int.class,String.class,String.class,int.class).newInstance(x,y,z,name,players?"●":"A",players?10:14);XaeroBridge.call(point,"setTemporary",true);XaeroBridge.call(dataset,"add",id,point);}else{XaeroBridge.call(point,"setX",x);XaeroBridge.call(point,"setY",y);XaeroBridge.call(point,"setZ",z);XaeroBridge.call(point,"setName",name);}}var gone=new ArrayList<String>();for(Object id:(Iterable<?>)XaeroBridge.call(dataset,"getIds"))if(!active.contains(id.toString()))gone.add(id.toString());for(String id:gone)XaeroBridge.call(dataset,"remove",id);payloads.put(origin,payload);}
}
