package dev.abros.rivet.client;
import com.google.gson.*;
import dev.abros.rivet.core.*;
import net.minecraft.client.Minecraft;
import java.util.*;
/** Opt-in live display. Coordinates stay in memory and expire even if a packet is lost. */
final class MapLayerClient {
 private static final RequestSession placesSession=new RequestSession(),peersSession=new RequestSession();private static JsonArray places=new JsonArray(),pendingPlaces=new JsonArray(),peers=new JsonArray();private static boolean placesBusy,peersBusy,showPlaces=true,showPeers;private static String server="";private static long nextPlaces,nextPeers,peersExpire,lastApply;private static final Set<String> hidden=new HashSet<>();
 static boolean placesShown(){return showPlaces;}static boolean peersShown(){return showPeers;}static boolean hidden(String id){return hidden.contains(id);}static void hide(String id){if(!hidden.add(id))hidden.remove(id);save();lastApply=0;}static void togglePlaces(){showPlaces=!showPlaces;save();refreshPlaces();}static void togglePeers(){showPeers=!showPeers;save();nextPeers=0;peers=new JsonArray();lastApply=0;}static void refreshPlaces(){nextPlaces=0;}
 private static java.nio.file.Path file(){return Minecraft.getInstance().gameDirectory.toPath().resolve("rivet/map-layers.json");}
 private static void save(){try{var all=java.nio.file.Files.exists(file())?Json.read(file()):new JsonObject();var value=new JsonObject();value.addProperty("places",showPlaces);value.addProperty("peers",showPeers);var ids=new JsonArray();hidden.forEach(ids::add);value.add("hidden",ids);all.add(server,value);Json.write(file(),all);}catch(Exception ex){ServerMenuClient.result="Не удалось сохранить настройки карты";}}
 private static void load(){showPlaces=true;showPeers=false;hidden.clear();try{var all=Json.read(file());if(all.has(server)){var value=all.getAsJsonObject(server);showPlaces=value.has("places")&&value.get("places").getAsBoolean();showPeers=value.has("peers")&&value.get("peers").getAsBoolean();if(value.has("hidden"))for(var id:value.getAsJsonArray("hidden"))hidden.add(id.getAsString());}}catch(Exception ignored){}}
 static void tick(){var mc=Minecraft.getInstance();String current=mc.getCurrentServer()==null?"":mc.getCurrentServer().ip;if(!current.equals(server)){server=current;placesSession.cancel();peersSession.cancel();placesBusy=peersBusy=false;places=peers=pendingPlaces=new JsonArray();nextPlaces=nextPeers=lastApply=0;ClientCompatibilityRegistry.clearMap();load();}if(!ClientCompatibilityRegistry.xaeroAvailable()){placesSession.cancel();peersSession.cancel();placesBusy=peersBusy=false;places=peers=pendingPlaces=new JsonArray();ClientCompatibilityRegistry.clearMap();return;}if(mc.level==null||!ServerMenuClient.available()||!ServerMenuClient.supports("player-tools")){ClientCompatibilityRegistry.clearMap();peers=new JsonArray();return;}long now=System.currentTimeMillis();if(placesSession.timeout(now)){placesBusy=false;nextPlaces=now+30000;}if(peersSession.timeout(now)){peersBusy=false;nextPeers=now+5000;}if(showPlaces&&!placesBusy&&now>=nextPlaces){pendingPlaces=new JsonArray();requestPlaces("");}if(showPeers&&!peersBusy&&now>=nextPeers){peersBusy=true;nextPeers=now+3000;send(peersSession,"toolsMapPeers","");}if(now>peersExpire&&!peers.isEmpty()){peers=new JsonArray();lastApply=0;}if(now-lastApply>=1000){lastApply=now;try{ClientCompatibilityRegistry.updateMap(showPlaces?places:new JsonArray(),showPeers?peers:new JsonArray());}catch(Exception|LinkageError ex){com.mojang.logging.LogUtils.getLogger().debug("Rivet map layer unavailable",ex);}}}
 private static void send(RequestSession session,String op,String cursor){var j=new JsonObject();j.addProperty("action","community");j.addProperty("section","home");j.addProperty("op",op);j.addProperty("cursor",cursor);ServerMenuClient.requestBackground(session.begin(j,false,System.currentTimeMillis()));}
 private static void requestPlaces(String cursor){placesBusy=true;nextPlaces=System.currentTimeMillis()+30000;send(placesSession,"toolsPlaces",cursor);}
 static boolean receive(JsonObject j){if(placesSession.receive(j)){placesBusy=false;if(j.has("places")){pendingPlaces.addAll(j.getAsJsonArray("places"));String next=Json.opt(j,"nextCursor","");if(!next.isEmpty()&&pendingPlaces.size()<1000)requestPlaces(next);else{if(!places.equals(pendingPlaces)){places=pendingPlaces;lastApply=0;}}}return true;}if(peersSession.receive(j)){peersBusy=false;if(j.has("peers")){peers=j.getAsJsonArray("peers");peersExpire=System.currentTimeMillis()+7000;lastApply=0;}return true;}return false;}
}
