package dev.abros.rivet.client;
import com.google.gson.*;
import dev.abros.rivet.core.*;
import net.minecraft.client.gui.GuiGraphics;
import net.minecraft.client.gui.components.*;
import net.minecraft.client.gui.screens.*;
import net.minecraft.network.chat.Component;
import java.util.*;
/** Public places remain server-owned; map visibility is a separate local preference. */
final class PlacesScreen extends ScrollScreen implements CommunityScreen.Receiver {
 private final Screen parent;private final RequestSession session=new RequestSession();private JsonArray places=new JsonArray();private boolean loaded,busy,retry;private String cursor="",next="",notice="";
 PlacesScreen(Screen parent){super(Client.tr("ui.public_locations_c368f520"));this.parent=parent;}
 private int w(){return Math.min(470,width-40);}private int x(){return (width-w())/2;}private int top(){return UiDialog.top(height,360);}private int bottom(){return height-top();}
 private void request(String op,JsonObject body){if(busy)return;body.addProperty("action","community");body.addProperty("section","home");body.addProperty("op",op);busy=true;retry=false;ServerMenuClient.request(session.begin(body,!op.equals("toolsPlaces"),System.currentTimeMillis()));rebuildWidgets();}
 private void load(){var j=new JsonObject();j.addProperty("cursor",cursor);request("toolsPlaces",j);}
 private void edit(JsonObject row){minecraft.setScreen(new LocationEditor(this,row==null?null:row.get("location"),false,value->{if(value==null||value.isJsonNull()){notice=Client.text("ui.use_the_action_on_the_location_2e505fae");return;}var j=row==null?new JsonObject():row.deepCopy();j.add("location",value);j.addProperty("title",Json.str(value.getAsJsonObject(),"name"));request("toolsPlaceSave",j);}));}
 private Button button(String label,int xx,int y,int width,Runnable action){var b=addRenderableWidget(UiActions.button(Component.literal(label),UiActions.Tone.NORMAL,"",v->action.run()).bounds(xx,y,width,20).build());b.active=!busy&&!retry;return b;}
 @Override protected void init(){button(Client.text("ui.add_location_135eac40"),x(),top()+32,(w()-8)/2,()->edit(null));button(Client.tr("map.layers").getString(),x()+(w()+8)/2,top()+32,(w()-8)/2,()->minecraft.setScreen(new MapLayersScreen(this)));scrollArea(places.size(),new dev.abros.rivet.core.NativeLayout.Box(x(),top()+64,Math.max(0,w()),Math.max(0,(bottom()-80)-(top()+64))),72);for(int n=firstRow;n<Math.min(places.size(),firstRow+visibleRows);n++){var row=places.get(n).getAsJsonObject();int y=top()+64+(n-firstRow)*72;String id=Json.str(row,"id");button(Client.text("ui.location_d1df6543"),x()+6,y+26,Math.min(100,(w()-24)/3),()->minecraft.setScreen(new ChoicePopup(this,Client.text("ui.location_8e2fe025"),List.of(Client.text("map.navigate"),Client.text("map.copy")),choice->{var place=CommunityLocation.read(row.getAsJsonObject("location"));if(choice==0){DirectionCue.start(place);minecraft.setScreen(null);}else{minecraft.keyboardHandler.setClipboard(place.coordinates());minecraft.setScreen(this);}})));button(MapLayerClient.hidden(id)?Client.text("ui.show_on_map_86f399f2"):Client.text("ui.hide_on_map_e082ea7b"),x()+12+Math.min(100,(w()-24)/3),y+26,w()-24-2*Math.min(100,(w()-24)/3),()->{MapLayerClient.hide(id);rebuildWidgets();});if(row.get("manage").getAsBoolean())button(Client.text("ui.edit_9120e6a4"),x()+w()-6-Math.min(100,(w()-24)/3),y+26,Math.min(100,(w()-24)/3),()->minecraft.setScreen(new ChoicePopup(this,Client.text("ui.location_8e2fe025"),List.of(Client.text("ui.name_and_coordinates_7d41ae08"),Client.text("ui.location_status_f0d4046e"),Client.text("ui.delete_from_server_632f6e57")),i->{if(i==0)edit(row);else if(i==1)minecraft.setScreen(new ChoicePopup(this,Client.text("ui.status_f7f293b5"),List.of(Client.text("ui.available_f925cafd"),Client.text("ui.temporarily_unavailable_eb4007a2"),Client.text("ui.closed_fc98a6f2")),s->{var j=row.deepCopy();j.addProperty("status",List.of("open","unavailable","closed").get(s));request("toolsPlaceSave",j);}));else minecraft.setScreen(new UiConfirmDialog(yes->{minecraft.setScreen(this);if(yes)request("toolsPlaceDelete",row.deepCopy());},Client.tr("ui.delete_public_location_09da49b9"),Component.literal(Json.str(row,"title"))).dangerous());})));}
 if(retry)button(Client.text("retry"),x(),bottom()-54,w(),()->{busy=true;retry=false;ServerMenuClient.request(session.retry(System.currentTimeMillis()));rebuildWidgets();}).active=true;else if(!next.isEmpty())button(Client.text("ui.next_page_881773b9"),x(),bottom()-54,w(),()->{cursor=next;resetScroll();load();});else if(!cursor.isEmpty())button(Client.text("ui.top_of_list_a28e0e21"),x(),bottom()-54,w(),()->{cursor="";resetScroll();load();});UiActions.close(new dev.abros.rivet.core.NativeLayout.Box(x(),bottom()-28,w(),20),this::addRenderableWidget,this::onClose);if(!loaded){loaded=true;load();}}
 public void receiveCommunity(JsonObject j){if(!session.receive(j))return;busy=false;if(j.has("error")){notice=Json.opt(j,"text",Client.text("ui.could_not_load_locations_6d172284"));retry=true;}else if(j.has("places")){places=j.getAsJsonArray("places");next=Json.opt(j,"nextCursor","");notice=places.isEmpty()?Client.text("ui.no_locations_yet_45cb2c76"):"";}else{MapLayerClient.refreshPlaces();load();return;}rebuildWidgets();}
 @Override public void tick(){if(session.timeout(System.currentTimeMillis())){busy=false;retry=true;notice=Client.text("ui.no_response_it_is_safe_to_27824cb3");rebuildWidgets();}}
 @Override public void renderBackground(GuiGraphics g,int mx,int my,float d){UiDialog.draw(g,width,w(),top(),bottom());for(int n=firstRow;n<Math.min(places.size(),firstRow+visibleRows);n++){int y=top()+64+(n-firstRow)*72;UiKit.plate(g,x(),y,w(),64,AccessibilityScreen.background(UiPalette.color(0xE41D2933)));}}
 @Override public void render(GuiGraphics g,int mx,int my,float d){UiDialog.render(parent,this,g,d,()->{super.render(g,mx,my,d);UiHeading.dialog(g,font,title,x(),top(),w());for(int n=firstRow;n<Math.min(places.size(),firstRow+visibleRows);n++){var row=places.get(n).getAsJsonObject();int y=top()+64+(n-firstRow)*72;String status=switch(Json.opt(row,"status","open")){case "closed"->Client.text("ui.closed_fc98a6f2");case "unavailable"->Client.text("ui.unavailable_949ac1f2");default->Client.text("ui.available_f925cafd");};Ui.text(g,font,font.plainSubstrByWidth(Json.str(row,"title")+" · "+status,w()-16),x()+6,y+6,UiPalette.color(0xD7E2EC));Ui.text(g,font,font.plainSubstrByWidth(Client.text("ui.author_d8cfdbaf")+Json.str(row,"author"),w()-44),x()+6,y+52,UiPalette.color(0xBAC7D2));}Ui.status(g,font,notice,x(),bottom()-78,w(),bottom()-56);});}
 @Override public void onClose(){session.cancel();minecraft.setScreen(parent);}
 @Override public boolean isPauseScreen(){return false;}
}
