package dev.abros.rivet.client;
import com.google.gson.*;
import dev.abros.rivet.core.*;
import net.minecraft.client.gui.GuiGraphics;
import net.minecraft.client.gui.components.*;
import net.minecraft.client.gui.screens.Screen;
import net.minecraft.network.chat.Component;
import java.util.*;
/** One administrative work queue, with concrete filters and selection for reviewed bulk actions. */
final class ReportQueueScreen extends ScrollScreen implements CommunityScreen.Receiver {
 private final Screen parent;private final RequestSession session=new RequestSession();private final MenuSidebar nav=new MenuSidebar(this);private final Map<String,JsonObject> chosen=new LinkedHashMap<>();
 private JsonArray rows=new JsonArray();private String filter,query="",cursor="",next="",notice="";private boolean loaded,busy,failed;private long searchAt;
 ReportQueueScreen(Screen parent,String filter){super(Client.tr("ui.report_queue_459f8424"));this.parent=parent;this.filter=filter;}
 private int w(){return UiWorkspace.fit(width,height).page().width();}
 private void load(){if(busy)return;var j=new JsonObject();j.addProperty("action","reports");j.addProperty("page",0);j.addProperty("filter",filter);j.addProperty("query",query);j.addProperty("cursor",cursor);busy=true;failed=false;ServerMenuClient.request(session.begin(j,false,System.currentTimeMillis()));rebuildWidgets();}
 void invalidate(){cursor="";chosen.clear();load();}
 private void reset(){cursor="";chosen.clear();resetScroll();load();}
 private void toggle(JsonObject row){String id=Json.str(row,"id");if(chosen.remove(id)==null){if(chosen.size()>=20){notice=Client.text("ui.select_up_to_20_reports_a4937527");return;}chosen.put(id,row);}rebuildWidgets();}
 private void bulk(AbstractWidget anchor){minecraft.setScreen(new ChoicePopup(this,Client.text("ui.for_selected_reports_932835a4"),List.of(Client.text("ui.take_ownership_13ded02b"),Client.text("ui.close_reports_9dc4e38f"),Client.text("ui.high_priority_9ad02c50")),n->{var items=new JsonArray();for(var r:chosen.values()){var ref=new JsonObject();ref.add("id",r.get("id"));ref.add("revision",r.get("revision"));items.add(ref);}minecraft.setScreen(new ReportBulkScreen(this,List.of("claim","resolved","high").get(n),items));},anchor));}
 @Override protected void init(){nav.build("admin",this::addRenderableWidget);var labels=List.of(Client.text("ui.new_db9d03da"),Client.text("ui.mine_61edc217"),Client.text("ui.waiting_9cf13148"),Client.text("ui.closed_e47b4228"));var values=List.of("new","mine","waiting","resolved");UiTabs.build(this,font,new NativeLayout.Box(nav.left(),42,UiSearchToolbar.contentWidth(w()),20),labels,values.indexOf(filter),this::addRenderableWidget,n->{filter=values.get(n);reset();},!busy);

  var search=addRenderableWidget(UiFields.text(font,nav.left(),72,Math.max(1,UiSearchToolbar.contentWidth(w())-110),20,Client.tr("map.tool.search")));search.setHint(Client.tr("ui.player_or_report_text_3fe39019"));search.setMaxLength(100);search.setValue(query);search.setResponder(v->{query=v;searchAt=System.currentTimeMillis()+500;});search.active=!busy;
  addRenderableWidget(UiActions.button(Client.tr("ui.filter_ae68c1e9"),UiActions.Tone.NORMAL,"",b->minecraft.setScreen(new ChoicePopup(this,Client.text("map.tool.visibility"),List.of(Client.text("ui.all_fd08da7a"),Client.text("ui.unassigned_72af7971"),Client.text("ui.high_priority_9ad02c50")),n->{filter=List.of("all","unassigned","high").get(n);reset();},b))).bounds(nav.left()+UiSearchToolbar.contentWidth(w())-104,72,104,20).build()).active=!busy;
  var bulk=addRenderableWidget(UiActions.button(Component.literal(Client.text("ui.selected_3ef8b742")+chosen.size()+" ▾"),UiActions.Tone.NORMAL,"",b->bulk(b)).bounds(nav.left(),100,Math.max(1,UiSearchToolbar.contentWidth(w())-84),20).build());bulk.active=!busy&&!chosen.isEmpty();addRenderableWidget(UiActions.button(Client.tr("map.tool.reset"),UiActions.Tone.NORMAL,"",b->{query="";filter="new";reset();}).bounds(nav.left()+Math.max(1,UiSearchToolbar.contentWidth(w())-84)+6,100,78,20).build()).active=!busy;
  int stride=Math.min(76,Math.max(30,height-62-130));scrollArea(rows.size(),new dev.abros.rivet.core.NativeLayout.Box(nav.left(),130,Math.max(0,w()),Math.max(0,(height-62)-(130))),stride);for(int n=firstRow;n<Math.min(rows.size(),firstRow+visibleRows);n++){var r=rows.get(n).getAsJsonObject();int y=130+(n-firstRow)*stride;addRenderableWidget(new UiChoiceRow(nav.left(),y,24,"",chosen.containsKey(Json.str(r,"id")),-1,UiKit.ACCENT,()->toggle(r))).active=!busy;var card=r.deepCopy();card.addProperty("section","moderation");card.addProperty("title",Json.str(r,"player"));card.addProperty("attention",Json.opt(r,"status","open").equals("waiting")?Client.text("ui.awaiting_response_dacc6a50"):Json.opt(r,"priority","normal").equals("high")?Client.text("ui.high_priority_9ad02c50"):Json.opt(r,"status","open").equals("resolved")?Client.text("ui.closed_fc98a6f2"):Client.text("server.status.open"));card.addProperty("preview",Json.str(r,"message"));card.addProperty("footer",Json.opt(r,"nextStep","").isBlank()?Json.opt(r,"assignedName","").isBlank()?Client.text("ui.assign_an_owner_b1fd2fc5"):Client.text("ui.assigned_to_31372c54")+Json.opt(r,"assignedName",""):Client.text("ui.next_e28f48b1")+Json.str(r,"nextStep"));addRenderableWidget(new CommunityCard(nav.left()+30,y,w()-30,stride-6,card,()->minecraft.setScreen(new ReportDetailScreen(this,r,true)))).active=!busy;}
  if(!next.isEmpty())addRenderableWidget(UiActions.button(Client.tr("server.next"),UiActions.Tone.NORMAL,"",b->{cursor=next;resetScroll();load();}).bounds(nav.left(),height-54,110,20).build()).active=!busy;
  var footer=UiPageFooter.workspace(width,height);footer.start(UiActions.Command.REFRESH,this::addRenderableWidget,this::invalidate).active=!busy;footer.end(UiActions.Command.BACK,this::addRenderableWidget,this::onClose);if(!loaded){loaded=true;load();}}
 public void receiveCommunity(JsonObject j){if(!session.receive(j))return;busy=false;failed=j.has("error");if(j.has("error"))notice=Json.opt(j,"text",Client.text("ui.could_not_load_the_queue_ff15631f"));else if(j.has("reports")){rows=j.getAsJsonArray("reports");next=Json.opt(j,"nextCursor","");notice=rows.isEmpty()?Client.text("ui.no_reports_in_this_queue_2473c74b"):"";}rebuildWidgets();}
 @Override public void tick(){if(searchAt>0&&!busy&&System.currentTimeMillis()>=searchAt){searchAt=0;reset();}if(session.timeout(System.currentTimeMillis())){busy=false;failed=true;notice=Client.text("ui.no_response_refresh_the_queue_6749a2db");rebuildWidgets();}if(!ServerMenuClient.may("rivet.reports"))onClose();}
 @Override public boolean mouseScrolled(double x,double y,double dx,double dy){if(nav.scroll(x,y,dy)){rebuildWidgets();return true;}return super.mouseScrolled(x,y,dx,dy);}
 @Override public void renderBackground(GuiGraphics g,int mx,int my,float d){super.renderBackground(g,mx,my,d);UiTheme.shell(this,g);}
 @Override public void render(GuiGraphics g,int mx,int my,float d){super.render(g,mx,my,d);UiHeading.page(g,font,title,width);nav.drawFrame(g);if(rows.isEmpty())UiState.draw(g,font,failed?UiState.Kind.ERROR:busy?UiState.Kind.LOADING:query.isBlank()?UiState.Kind.EMPTY:UiState.Kind.FILTERED,failed?Client.text("ui.queue_unavailable_179bad9b"):busy?Client.text("ui.loading_reports_959f2a46"):query.isBlank()?Client.text("ui.no_reports_in_this_queue_1412d18d"):Client.text("ui.no_reports_found_6e8a724c"),failed?notice:busy?Client.text("ui.fetching_current_data_from_the_server_1e212f93"):query.isBlank()?Client.text("ui.new_reports_will_appear_here_d0736940"):Client.text("ui.change_the_search_or_filter_9ed6b6f2"),nav.left()+8,138,w()-16,height-64);Ui.status(g,font,notice,nav.left(),height-56,w(),height-34);}
 @Override public void onClose(){session.cancel();minecraft.setScreen(parent);}
 @Override public boolean isPauseScreen(){return false;}
}
