package dev.abros.rivet.client;
import com.google.gson.*;
import dev.abros.rivet.core.Json;
import net.minecraft.client.gui.GuiGraphics;
import net.minecraft.client.gui.components.*;
import net.minecraft.client.gui.screens.*;
final class ReportDetailScreen extends Screen implements CommunityScreen.Receiver {
    private final TextDraft draft;private final Screen parent;private final JsonObject report;private final boolean editable;private final ContentPane pane=new ContentPane();private MultiLineEditBox reply;private Button sendButton,statusButton,manageButton;private boolean resolved,busy;private String status="";private final dev.abros.rivet.core.RequestSession session=new dev.abros.rivet.core.RequestSession();private JsonObject attempted;
    ReportDetailScreen(Screen parent,JsonObject report,boolean editable){super(Client.tr("ui.player_report_7d86043d"));this.parent=parent;this.report=report;this.draft=new TextDraft("report-reply:"+Json.str(report,"id"));this.editable=editable;resolved=Json.opt(report,"status","open").equals("resolved");attempted=draft.pending();if(!draft.pendingReadable)status=Client.text("ui.could_not_restore_the_pending_submission_3b3a7f68");if(attempted!=null)resolved=attempted.get("resolved").getAsBoolean();}
    void updateReport(JsonObject value){for(var entry:value.entrySet())report.add(entry.getKey(),entry.getValue().deepCopy());}
    private int panelTop(){return UiDialog.top(height,370);}
    private int panelBottom(){return height-panelTop();}
    private int left(){return (width-Math.min(520,width-40))/2;}
    private int contentWidth(){return Math.min(520,width-40);}
    @Override public void renderBackground(GuiGraphics g,int x,int y,float d){UiDialog.draw(g,width,contentWidth(),panelTop(),panelBottom());}
 @Override protected void init(){pane.bounds(left(),panelTop()+(editable?64:36),contentWidth(),Math.max(24,panelBottom()-panelTop()-(editable?232:76)));pane.text(Client.text("ui.report_26c7dcd8")+Json.str(report,"player")+" · "+Client.tr("server.status."+Json.opt(report,"status","open")).getString()+"\n"+Json.str(report,"message")+(Json.opt(report,"reply","").isBlank()?"":Client.text("ui.staff_reply_36703d04")+Json.opt(report,"replyAuthor","")+"\n"+Json.opt(report,"reply",""))+"\n\n"+Json.opt(report,"audit",""));
        if(editable){if(ServerMenuClient.supports("player-tools"))manageButton=addRenderableWidget(UiActions.button(Client.tr("ui.manage_report_7ff0a333"),UiActions.Tone.NORMAL,"",b->{if(!busy&&attempted==null)minecraft.setScreen(new ReportManagementScreen(this,report));}).bounds(left(),panelTop()+34,Math.min(180,contentWidth()),20).build());String draftText=reply==null?(attempted==null?draft.load(Json.opt(report,"reply","")):Json.opt(attempted,"text","")):reply.getValue();reply=addRenderableWidget(UiFields.multiline(font,left(),panelBottom()-152,contentWidth(),62,Client.tr("server.reply"),Client.tr("server.reply")));reply.setCharacterLimit(1500);reply.setValue(draftText);
            statusButton=addRenderableWidget(new UiChoiceRow(left(),panelBottom()-72,contentWidth()-114,Client.text("ui.close_after_replying_748061e8"),resolved,-1,UiKit.ACCENT,()->{resolved=!resolved;rebuildWidgets();}));
            sendButton=addRenderableWidget(UiActions.button(Client.tr("ui.reply_c6f4665b"),UiActions.Tone.NORMAL,"",b->{if(busy||!draft.pendingReadable||reply.getValue().isBlank())return;var j=new JsonObject();j.addProperty("action","reply");j.addProperty("id",Json.str(report,"id"));j.addProperty("text",reply.getValue());j.addProperty("resolved",resolved);j.add("revision",report.get("revision"));var packet=session.begin(attempted==null?j:attempted,true,System.currentTimeMillis());attempted=session.command();draft.save(reply.getValue());busy=true;status=Client.text("server.sending");draft.pending(attempted,()->{if(minecraft.screen==this&&ServerMenuClient.available())ServerMenuClient.request(packet);else{session.cancel();busy=false;}},error->{session.cancel();busy=false;status=Client.text("ui.could_not_save_the_pending_submission_bd6b5453");});}).bounds(left()+contentWidth()-100,panelBottom()-72,100,20).build());}
        UiActions.close(new dev.abros.rivet.core.NativeLayout.Box(left(),panelBottom()-26,contentWidth(),20),this::addRenderableWidget,this::onClose);}
    @Override public void render(GuiGraphics g,int x,int y,float d){UiDialog.render(parent,this,g,d,()->{super.render(g,x,y,d);UiHeading.dialog(g,font,title,(width-(contentWidth()))/2,panelTop(),contentWidth());pane.render(g,font);if(editable)Ui.text(g,font,Client.text("server.reply"),left(),panelBottom()-166,UiKit.muted(),false);Ui.status(g,font,status,left(),panelBottom()-48,contentWidth(),panelBottom()-28);});}
    @Override public boolean mouseScrolled(double x,double y,double dx,double dy){return pane.scroll(x,y,dy)||super.mouseScrolled(x,y,dx,dy);}
    @Override public boolean mouseClicked(double x,double y,int b){return b==0&&pane.click(x,y)||super.mouseClicked(x,y,b);}
    @Override public boolean mouseDragged(double x,double y,int b,double dx,double dy){return b==0&&pane.drag(y)||super.mouseDragged(x,y,b,dx,dy);}
    @Override public boolean mouseReleased(double x,double y,int b){pane.release();return super.mouseReleased(x,y,b);}
    public void receiveCommunity(JsonObject response){if(!session.receive(response))return;busy=false;status=Json.opt(response,"text","");if(!response.has("error")){draft.pending(null,()->{},Client::failure);draft.clear();attempted=null;reply.setValue("");if(response.has("report")){updateReport(response.getAsJsonObject("report"));resolved=Json.opt(report,"status","open").equals("resolved");rebuildWidgets();}}else if(java.util.Set.of("CONFLICT","INVALID","FORBIDDEN","EXPIRED","NOT_FOUND").contains(Json.opt(response,"code",""))){attempted=null;draft.pending(null,()->{},Client::failure);}}
    @Override public void tick(){if(reply!=null){if(manageButton!=null)manageButton.active=!busy&&attempted==null;reply.active=!busy&&attempted==null;sendButton.active=!busy&&draft.pendingReadable&&!reply.getValue().isBlank();statusButton.active=!busy&&attempted==null;sendButton.setMessage(busy?Client.tr("server.sending"):Client.tr("ui.reply_c6f4665b"));}if(session.timeout(System.currentTimeMillis())){busy=false;status=Client.text("ui.no_response_try_sending_again_your_2d5f645e");}if(!ServerMenuClient.available())minecraft.setScreen(null);else if(editable&&!ServerMenuClient.may("rivet.reports")){session.cancel();minecraft.setScreen(parent);}}
    @Override public boolean isPauseScreen(){return false;}
    @Override public void onClose(){if(busy){status=Client.text("ui.wait_for_the_server_to_respond_43e44ea8");return;}if(reply!=null)draft.save(reply.getValue());session.cancel();minecraft.setScreen(parent);}
}
