package dev.abros.rivet.client;
import com.google.gson.*;
import dev.abros.rivet.core.*;
import net.minecraft.client.gui.GuiGraphics;
import net.minecraft.client.gui.components.*;
import net.minecraft.client.gui.screens.Screen;
import net.minecraft.network.chat.Component;
import java.util.*;
final class ReportManagementScreen extends ScrollScreen implements CommunityScreen.Receiver {
 private final ReportDetailScreen parent;private JsonObject report;private final RequestSession session=new RequestSession();private boolean busy,loaded;private JsonArray staff=new JsonArray();private String notice="";
 ReportManagementScreen(ReportDetailScreen parent,JsonObject report){super(Component.literal("Управление обращением"));this.parent=parent;this.report=report.deepCopy();}
 private int w(){return Math.min(420,width-40);}private int x(){return (width-w())/2;}private int top(){return UiDialog.top(height,320);}private int bottom(){return height-top();}
 private void send(String operation,JsonObject body){if(busy)return;body.addProperty("action","reportManage");body.addProperty("operation",operation);body.addProperty("id",Json.str(report,"id"));body.add("revision",report.get("revision"));busy=true;ServerMenuClient.request(session.begin(body,true,System.currentTimeMillis()));rebuildWidgets();}
 private void classify(String key,List<String> values,List<String> labels,AbstractWidget anchor){minecraft.setScreen(new ChoicePopup(this,"Классификация",labels,index->{var j=new JsonObject();j.addProperty("category",key.equals("category")?values.get(index):Json.opt(report,"category","other"));j.addProperty("priority",key.equals("priority")?values.get(index):Json.opt(report,"priority","normal"));send("classify",j);},anchor));}
 @Override protected void init(){if(!loaded){loaded=true;var q=new JsonObject();q.addProperty("action","reportManage");q.addProperty("operation","staff");busy=true;ServerMenuClient.request(session.begin(q,false,System.currentTimeMillis()));}String assigned=Json.opt(report,"assigned","");var claim=addRenderableWidget(UiActions.button(Component.literal(assigned.equals(CommunityScreen.me())?"Снять моё назначение":assigned.isEmpty()?"Взять в работу":"Ответственный: "+Json.opt(report,"assignedName","")),UiActions.Tone.NORMAL,"",b->send(assigned.isEmpty()?"claim":"release",new JsonObject())).bounds(x(),top()+34,w(),20).build());claim.active=!busy&&(assigned.isEmpty()||assigned.equals(CommunityScreen.me()));var assign=addRenderableWidget(UiActions.button(Component.literal("Назначить администратора ▾"),UiActions.Tone.NORMAL,"",b->minecraft.setScreen(new ChoicePopup(this,"Администраторы в сети",staff.asList().stream().map(e->Json.str(e.getAsJsonObject(),"name")).toList(),index->{var q=new JsonObject();q.add("target",staff.get(index).getAsJsonObject().get("id"));send("assign",q);},b))).bounds(x(),top()+62,w(),20).build());assign.active=!busy&&!staff.isEmpty();assign.setTooltip(Tooltip.create(Component.literal("Выберите администратора в сети с доступом к обращениям.")));var category=addRenderableWidget(UiActions.button(Component.literal("Категория ▾"),UiActions.Tone.NORMAL,"",b->classify("category",List.of("technical","player","appeal","other"),List.of("Техническая проблема","Жалоба на игрока","Обжалование","Другое"),b)).bounds(x(),top()+88,(w()-8)/2,20).build());category.active=!busy;var priority=addRenderableWidget(UiActions.button(Component.literal("Приоритет: "+switch(Json.opt(report,"priority","normal")){case "low"->"низкий";case "high"->"высокий";default->"обычный";}+" ▾"),UiActions.Tone.NORMAL,"",b->classify("priority",List.of("low","normal","high"),List.of("Низкий","Обычный","Высокий"),b)).bounds(x()+(w()+8)/2,top()+88,(w()-8)/2,20).build());priority.active=!busy;
  if(ServerMenuClient.supports("community-extensions")){addRenderableWidget(UiActions.button(Component.literal("Следующий шаг…"),UiActions.Tone.NORMAL,"",b->{var preset=new JsonObject();preset.addProperty("nextStep",Json.opt(report,"nextStep",""));minecraft.setScreen(new TaskEditScreen(this,"Следующий шаг",List.of(new CommunityScreen.Field("nextStep","Что требуется сделать",300)),preset,v->{var q=new JsonObject();q.addProperty("status",Json.opt(report,"status","open"));q.add("nextStep",v.get("nextStep"));send("state",q);}));}).bounds(x(),top()+114,(w()-8)/2,20).build()).active=!busy;addRenderableWidget(UiActions.button(Component.literal("Состояние ▾"),UiActions.Tone.NORMAL,"",b->minecraft.setScreen(new ChoicePopup(this,"Состояние обращения",List.of("Открыто","Ожидаем ответ","Закрыто"),n->{var q=new JsonObject();q.addProperty("status",List.of("open","waiting","resolved").get(n));q.addProperty("nextStep",Json.opt(report,"nextStep",""));send("state",q);},b))).bounds(x()+(w()+8)/2,top()+114,(w()-8)/2,20).build()).active=!busy;}
  var notes=report.has("internalNotes")?report.getAsJsonArray("internalNotes"):new JsonArray();scrollArea(notes.size(),new dev.abros.rivet.core.NativeLayout.Box(x(),top()+144,Math.max(0,w()),Math.max(0,(bottom()-86)-(top()+144))),38);for(int n=firstRow;n<Math.min(notes.size(),firstRow+visibleRows);n++){var note=notes.get(n).getAsJsonObject();addRenderableWidget(UiActions.button(Component.literal(font.plainSubstrByWidth(Json.str(note,"author")+": "+Json.str(note,"text"),w()-16)),UiActions.Tone.NORMAL,"",b->minecraft.setScreen(new TextScreen(this,Component.literal("Внутренняя заметка"),Json.str(note,"author")+"\n\n"+Json.str(note,"text")))).bounds(x(),top()+144+(n-firstRow)*38,w(),30).build());}var add=addRenderableWidget(UiActions.button(Component.literal("+ Внутренняя заметка"),UiActions.Tone.NORMAL,UiIcons.PLUS,b->minecraft.setScreen(new TaskEditScreen(this,"Заметка · видна только администрации",List.of(new CommunityScreen.Field("text","Текст заметки",1000)),new JsonObject(),j->send("note",j)))).bounds(x(),bottom()-54,w(),20).build());add.active=!busy;UiActions.close(new dev.abros.rivet.core.NativeLayout.Box(x(),bottom()-28,w(),20),this::addRenderableWidget,this::onClose);}
 public void receiveCommunity(JsonObject j){if(!session.receive(j))return;busy=false;if(j.has("staff"))staff=j.getAsJsonArray("staff");notice=Json.opt(j,"text","");if(j.has("report")){report=j.getAsJsonObject("report");parent.updateReport(report);}rebuildWidgets();}
 @Override public void tick(){if(session.timeout(System.currentTimeMillis())){busy=false;notice="Нет ответа. Откройте обращение заново.";rebuildWidgets();}}
 @Override public void renderBackground(GuiGraphics g,int mx,int my,float d){UiDialog.draw(g,width,w(),top(),bottom());}
 @Override public void render(GuiGraphics g,int mx,int my,float d){UiDialog.render(parent,this,g,d,()->{super.render(g,mx,my,d);UiHeading.dialog(g,font,title,x(),top(),w());Ui.status(g,font,notice,x(),bottom()-80,w(),bottom()-58);});}
 @Override public void onClose(){if(!busy){session.cancel();minecraft.setScreen(parent);}}
 @Override public boolean isPauseScreen(){return false;}
}
