package dev.abros.rivet.client;
import com.google.gson.*;import dev.abros.rivet.core.*;import net.minecraft.client.gui.GuiGraphics;import net.minecraft.client.gui.screens.Screen;import net.minecraft.network.chat.Component;import java.util.*;
final class ScheduledAnnouncementsScreen extends ScrollScreen implements CommunityScreen.Receiver {
 private final Screen parent;private final RequestSession session=new RequestSession();private JsonArray rows=new JsonArray();private JsonObject draft;private boolean busy,loaded,uncertain;private String notice="";private UiDialog layout;
 ScheduledAnnouncementsScreen(Screen parent){super(Client.tr("ui.scheduled_announcements_d35ca997"));this.parent=parent;}
 private void request(JsonObject j){if(busy||uncertain)return;j.addProperty("action","scheduledAnnouncements");busy=true;ServerMenuClient.request(session.begin(j,MenuCommands.describe(j).effect()==MenuCommands.Effect.WRITE,System.currentTimeMillis()));rebuildWidgets();}
 private void load(){if(uncertain){busy=true;uncertain=false;ServerMenuClient.request(session.retry(System.currentTimeMillis()));rebuildWidgets();return;}var j=new JsonObject();j.addProperty("op","list");request(j);}
 private void create(){var preset=new JsonObject();preset.addProperty("text","");preset.addProperty("startsAt",java.time.Instant.now().plusSeconds(3600).toString());minecraft.setScreen(new TaskEditScreen(this,Client.text("ui.new_notice_466874b0"),List.of(new CommunityScreen.Field("text",Client.text("ui.announcement_text_01ddb4ba"),500),new CommunityScreen.Field("startsAt",Client.text("ui.utc_time_2026_10_02t18_00_33231ffe"),40)),preset,values->{draft=values.deepCopy();draft.addProperty("op","preview");request(draft);}));}
 @Override protected void init(){layout=UiDialog.fit(width,height,460,340);var body=layout.body();scrollArea(rows.size()*3+1,new NativeLayout.Box(body.x(),body.y()+26,body.width(),Math.max(0,body.height()-48)),22);addRenderableWidget(UiActions.button(Client.tr("ui.schedule_announcement_d73e5bfc"),UiActions.Tone.PRIMARY,"",b->create()).bounds(body.x(),body.y(),UiSearchToolbar.contentWidth(body.width()),20).build()).active=!busy&&!uncertain;for(int n=0;n<rows.size();n++){int start=n*3;if(start<firstRow||start+2>=firstRow+visibleRows)continue;var row=rows.get(n).getAsJsonObject();int y=body.y()+26+(start-firstRow)*22;addRenderableWidget(UiActions.button(Component.literal(Client.text("ui.cancel_24dc2f01")+UiKit.fit(font,Json.str(row,"text"),body.width()-90)),UiActions.Tone.NORMAL,"",b->minecraft.setScreen(new UiConfirmDialog(yes->{minecraft.setScreen(this);if(yes){var q=new JsonObject();q.addProperty("op","cancel");q.add("id",row.get("id"));q.add("revision",row.get("revision"));request(q);}},Client.tr("ui.cancel_announcement_ac23047d"),Component.literal(Json.str(row,"text"))))).bounds(body.x(),y+22,body.width(),20).build()).active=!busy&&!uncertain;}
 var footer=UiPageFooter.fit(layout.footer());footer.start(uncertain?UiActions.Command.RETRY:UiActions.Command.REFRESH,this::addRenderableWidget,this::load).active=!busy;footer.end(UiActions.Command.CLOSE,this::addRenderableWidget,this::onClose).active=!busy;if(!loaded){loaded=true;load();}}
 public void receiveCommunity(JsonObject j){if(!session.receive(j))return;busy=false;if(j.has("error")){notice=Json.opt(j,"text",Client.text("ui.could_not_perform_the_action_de7fb956"));rebuildWidgets();return;}if(j.has("announcements")){rows=j.getAsJsonArray("announcements");notice=rows.isEmpty()?Client.text("ui.no_scheduled_announcements_28bb1d65"):Client.text("ui.recipients_are_players_connected_at_the_49b20fa9");rebuildWidgets();}else if(j.has("at")&&draft!=null){var changes=new JsonArray();for(String key:List.of("text","at")){var row=new JsonObject();row.addProperty("label",key.equals("text")?Client.text("server.announce"):Client.text("ui.publication_eb8ec703") );row.add("before",JsonNull.INSTANCE);row.addProperty("after",key.equals("text")?Json.str(j,key):java.time.Instant.ofEpochMilli(j.get(key).getAsLong()).atZone(AccessibilityScreen.zone()).toString());changes.add(row);}minecraft.setScreen(new ChangePreviewScreen(this,changes,()->{var create=draft.deepCopy();create.addProperty("op","create");request(create);}));}}
 @Override public void tick(){if(session.timeout(System.currentTimeMillis())){busy=false;uncertain=session.command()!=null&&MenuCommands.describe(session.command()).effect()==MenuCommands.Effect.WRITE;notice=uncertain?Client.text("ui.no_response_received_retry_will_check_7afe6459"):Client.text("ui.no_response_refresh_the_list_b39ca34b");rebuildWidgets();}}
 @Override public void renderBackground(GuiGraphics g,int x,int y,float d){UiDialog.surface(g,layout.frame().x(),layout.frame().y(),layout.frame().width(),layout.frame().height());}
 @Override public void render(GuiGraphics g,int x,int y,float d){UiDialog.render(parent,this,g,d,()->{super.render(g,x,y,d);UiHeading.dialog(g,font,title,layout.header().x(),layout.frame().y(),layout.header().width());for(int n=0;n<rows.size();n++){int start=n*3;if(start<firstRow||start+2>=firstRow+visibleRows)continue;var row=rows.get(n).getAsJsonObject();Ui.text(g,font,java.time.Instant.ofEpochMilli(row.get("at").getAsLong()).atZone(AccessibilityScreen.zone()).format(java.time.format.DateTimeFormatter.ofPattern("dd.MM HH:mm"))+" · "+Json.opt(row,"author",""),layout.body().x(),layout.body().y()+26+(start-firstRow)*22,UiKit.muted());}Ui.status(g,font,notice,layout.body().x(),layout.body().bottom()-18,layout.body().width(),layout.body().bottom());});}
 @Override public void onClose(){if(busy)return;session.cancel();minecraft.setScreen(parent);}
 @Override public boolean isPauseScreen(){return false;}
}
