package dev.abros.rivet.client;
import com.google.gson.*;import dev.abros.rivet.core.*;import net.minecraft.client.gui.GuiGraphics;import net.minecraft.client.gui.screens.Screen;import net.minecraft.network.chat.Component;import java.util.*;
final class ScheduledAnnouncementsScreen extends ScrollScreen implements CommunityScreen.Receiver {
 private final Screen parent;private final RequestSession session=new RequestSession();private JsonArray rows=new JsonArray();private JsonObject draft;private boolean busy,loaded,uncertain;private String notice="";private UiDialog layout;
 ScheduledAnnouncementsScreen(Screen parent){super(Component.literal("Запланированные объявления"));this.parent=parent;}
 private void request(JsonObject j){if(busy||uncertain)return;j.addProperty("action","scheduledAnnouncements");busy=true;ServerMenuClient.request(session.begin(j,MenuCommands.describe(j).effect()==MenuCommands.Effect.WRITE,System.currentTimeMillis()));rebuildWidgets();}
 private void load(){if(uncertain){busy=true;uncertain=false;ServerMenuClient.request(session.retry(System.currentTimeMillis()));rebuildWidgets();return;}var j=new JsonObject();j.addProperty("op","list");request(j);}
 private void create(){var preset=new JsonObject();preset.addProperty("text","");preset.addProperty("startsAt",java.time.Instant.now().plusSeconds(3600).toString());minecraft.setScreen(new TaskEditScreen(this,"Новое объявление",List.of(new CommunityScreen.Field("text","Текст объявления",500),new CommunityScreen.Field("startsAt","Время UTC (2026-10-02T18:00:00Z)",40)),preset,values->{draft=values.deepCopy();draft.addProperty("op","preview");request(draft);}));}
 @Override protected void init(){layout=UiDialog.fit(width,height,460,340);var body=layout.body();scrollArea(rows.size()*3+1,new NativeLayout.Box(body.x(),body.y()+26,body.width(),Math.max(0,body.height()-48)),22);addRenderableWidget(UiActions.button(Component.literal("Запланировать объявление"),UiActions.Tone.PRIMARY,"",b->create()).bounds(body.x(),body.y(),body.width(),20).build()).active=!busy&&!uncertain;for(int n=0;n<rows.size();n++){int start=n*3;if(start<firstRow||start+2>=firstRow+visibleRows)continue;var row=rows.get(n).getAsJsonObject();int y=body.y()+26+(start-firstRow)*22;addRenderableWidget(UiActions.button(Component.literal("Отменить · "+UiKit.fit(font,Json.str(row,"text"),body.width()-90)),UiActions.Tone.NORMAL,"",b->minecraft.setScreen(new UiConfirmDialog(yes->{minecraft.setScreen(this);if(yes){var q=new JsonObject();q.addProperty("op","cancel");q.add("id",row.get("id"));q.add("revision",row.get("revision"));request(q);}},Component.literal("Отменить объявление?"),Component.literal(Json.str(row,"text"))))).bounds(body.x(),y+22,body.width(),20).build()).active=!busy&&!uncertain;}
 var footer=UiPageFooter.fit(layout.footer());footer.start(uncertain?UiActions.Command.RETRY:UiActions.Command.REFRESH,this::addRenderableWidget,this::load).active=!busy;footer.end(UiActions.Command.CLOSE,this::addRenderableWidget,this::onClose).active=!busy;if(!loaded){loaded=true;load();}}
 public void receiveCommunity(JsonObject j){if(!session.receive(j))return;busy=false;if(j.has("error")){notice=Json.opt(j,"text","Не удалось выполнить действие");rebuildWidgets();return;}if(j.has("announcements")){rows=j.getAsJsonArray("announcements");notice=rows.isEmpty()?"Нет запланированных объявлений":"Получатели — игроки, подключённые в момент публикации.";rebuildWidgets();}else if(j.has("at")&&draft!=null){var changes=new JsonArray();for(String key:List.of("text","at")){var row=new JsonObject();row.addProperty("label",key.equals("text")?"Объявление":"Публикация" );row.add("before",JsonNull.INSTANCE);row.addProperty("after",key.equals("text")?Json.str(j,key):java.time.Instant.ofEpochMilli(j.get(key).getAsLong()).atZone(AccessibilityScreen.zone()).toString());changes.add(row);}minecraft.setScreen(new ChangePreviewScreen(this,changes,()->{var create=draft.deepCopy();create.addProperty("op","create");request(create);}));}}
 @Override public void tick(){if(session.timeout(System.currentTimeMillis())){busy=false;uncertain=session.command()!=null&&MenuCommands.describe(session.command()).effect()==MenuCommands.Effect.WRITE;notice=uncertain?"Ответ не получен. Повторить проверит то же действие без дубликата.":"Нет ответа. Обновите список.";rebuildWidgets();}}
 @Override public void renderBackground(GuiGraphics g,int x,int y,float d){UiDialog.surface(g,layout.frame().x(),layout.frame().y(),layout.frame().width(),layout.frame().height());}
 @Override public void render(GuiGraphics g,int x,int y,float d){UiDialog.render(parent,this,g,d,()->{super.render(g,x,y,d);UiHeading.dialog(g,font,title,layout.header().x(),layout.frame().y(),layout.header().width());for(int n=0;n<rows.size();n++){int start=n*3;if(start<firstRow||start+2>=firstRow+visibleRows)continue;var row=rows.get(n).getAsJsonObject();Ui.text(g,font,java.time.Instant.ofEpochMilli(row.get("at").getAsLong()).atZone(AccessibilityScreen.zone()).format(java.time.format.DateTimeFormatter.ofPattern("dd.MM HH:mm"))+" · "+Json.opt(row,"author",""),layout.body().x(),layout.body().y()+26+(start-firstRow)*22,UiKit.muted());}Ui.status(g,font,notice,layout.body().x(),layout.body().bottom()-18,layout.body().width(),layout.body().bottom());});}
 @Override public void onClose(){if(busy)return;session.cancel();minecraft.setScreen(parent);}
 @Override public boolean isPauseScreen(){return false;}
}
