package dev.abros.rivet.client;
import dev.abros.rivet.core.Json;
import net.minecraft.client.gui.GuiGraphics;
import net.minecraft.client.gui.components.Button;
import net.minecraft.client.gui.screens.Screen;
final class ServerInfoScreen extends Screen {
 private final MenuSidebar nav=new MenuSidebar(this);private final Screen parent;private final ContentPane news=new ContentPane(),rules=new ContentPane();private boolean requested;
 ServerInfoScreen(Screen parent){super(Client.tr("server.tab.info"));this.parent=parent;news.text(Client.tr("server.loading").getString());rules.text(Client.tr("server.loading").getString());}
 @Override protected void init(){nav.build("info",this::addRenderableWidget);int left=nav.left(),w=(nav.right()-left-28)/2;news.bounds(left,68,w,Math.max(36,height-144));rules.bounds(left+12+w,68,w,Math.max(36,height-144));addRenderableWidget(UiActions.button(Client.tr("server.links"),UiActions.Tone.NORMAL,"",b->FeatureListScreen.open(this,"links")).bounds(nav.left(),height-28,Math.min(100,(nav.right()-nav.left()-24)/2),20).build());UiPageFooter.workspace(width,height).end(UiActions.Command.BACK,this::addRenderableWidget,this::onClose);addRenderableWidget(UiActions.button(Client.tr("server.packStatus"),UiActions.Tone.NORMAL,"",b->checkPack()).bounds(nav.left(),height-54,Math.max(80,nav.right()-nav.left()-12),20).build());if(!requested){requested=true;String repository=Json.opt(ServerMenuClient.state,"repository","");Client.IO.submit(()->{try{var release=Client.hub.repositories.fetchOrCached(repository);String n=Client.hub.content(release.manifest(),"news"),r=Client.hub.content(release.manifest(),"rules");minecraft.execute(()->{news.text(n);rules.text(r);});}catch(Exception ex){minecraft.execute(()->{news.text(Errors.message(ex));rules.text(Errors.message(ex));});}});}}
 private void checkPack(){Client.IO.submit(()->{try{String version=Client.hub.active()==null?"—":Client.hub.active().version();String required=Json.opt(ServerMenuClient.state,"packVersion","—"),hash=Json.opt(ServerMenuClient.state,"requiredHash","");var issues=Client.hub.audit();String text=Client.tr("server.installed",version).getString()+"\n"+Client.tr("server.required",required).getString()+"\n\n"+Client.tr(hash.isEmpty()?"server.packUnknown":hash.equals(Client.hub.activeHash())&&issues.isEmpty()?"healthy":"server.packMismatch").getString()+"\n"+String.join("\n",issues);minecraft.execute(()->{if(minecraft.screen==this&&ServerMenuClient.available())minecraft.setScreen(new TextScreen(this,Client.tr("server.packStatus"),text));});}catch(Exception ex){minecraft.execute(()->{if(minecraft.screen==this)minecraft.setScreen(new TextScreen(this,Client.tr("server.packStatus"),Errors.message(ex)));});}});}
 @Override public void render(GuiGraphics g,int x,int y,float d){super.render(g,x,y,d);UiHeading.page(g,font,title,width);nav.drawFrame(g);Ui.text(g,font,font.plainSubstrByWidth(Json.opt(ServerMenuClient.state,"description",""),nav.right()-nav.left()-12),nav.left(),34,UiPalette.color(0xEEEEEE));Ui.text(g,font,Client.tr("news"),nav.left(),54,UiPalette.color(0xE2BE75));Ui.text(g,font,Client.tr("rules"),nav.left()+12+(nav.right()-nav.left()-28)/2,54,UiPalette.color(0xE2BE75));news.render(g,font);rules.render(g,font);}
 @Override public boolean mouseScrolled(double x,double y,double dx,double dy){if(nav.scroll(x,y,dy)){rebuildWidgets();return true;}return news.scroll(x,y,dy)||rules.scroll(x,y,dy)||super.mouseScrolled(x,y,dx,dy);}
 @Override public boolean mouseClicked(double x,double y,int b){if(b==0){if(news.click(x,y)||rules.click(x,y))return true;for(var pane:new ContentPane[]{news,rules}){var style=pane.link(font,x,y);if(style!=null&&style.getClickEvent()!=null)return handleComponentClicked(style);}}return super.mouseClicked(x,y,b);}
 @Override public boolean mouseDragged(double x,double y,int b,double dx,double dy){return b==0&&(news.drag(y)||rules.drag(y))||super.mouseDragged(x,y,b,dx,dy);}
 @Override public boolean mouseReleased(double x,double y,int b){news.release();rules.release();return super.mouseReleased(x,y,b);}
 @Override public void tick(){if(!ServerMenuClient.available())minecraft.setScreen(null);}
 @Override public void onClose(){minecraft.setScreen(parent);}
 @Override public boolean isPauseScreen(){return false;}
}
