package dev.abros.rivet.client;
import java.util.List;
import net.minecraft.client.gui.GuiGraphics;
import net.minecraft.client.gui.screens.Screen;
import net.minecraft.network.chat.Component;
/** TAB/chat preferences share compound dialog and controls with all Rivet settings. */
final class SocialSettingsScreen extends ScrollScreen implements SettingsTarget {
 private final Screen parent;private UiDialog dialog;private int tab;
 SocialSettingsScreen(Screen parent){super(Client.tr("server.settings"));this.parent=parent;}
 SocialSettingsScreen(Screen parent,int tab){this(parent);this.tab=tab;}
 Screen parentScreen(){return parent;}
 @Override protected void init(){dialog=UiSettingsShell.build(width,height,tab+3,parent,this,this::addRenderableWidget,()->UiSettingsShell.confirm(this,this::resetSection),this::onClose);var b=dialog.body();var s=SocialSettings.INSTANCE;int count=tab==0?8:5;scrollArea(count,new dev.abros.rivet.core.NativeLayout.Box(b.x(),b.y(),b.width(),Math.max(0,b.height()-UiSettingsPreview.space(b))),32);int y=b.y();for(int n=firstRow;n<Math.min(count,firstRow+visibleRows);n++,y+=32){int row=n;int yy=y;
  if(tab==1&&row==4){addRenderableWidget(UiActions.button(Component.literal(Client.text("ui.chat_history_a94495c7")+s.history+Client.text("ui.messages_5af724d6")),UiActions.Tone.NORMAL,"",v->minecraft.setScreen(new ChoicePopup(this,Client.text("ui.chat_history_688c4e28"),List.of("100","1 000","10 000","65 536"),i->{s.history=new int[]{100,1000,10000,65536}[i];s.save();ClientChat.applyHistoryLimit();minecraft.setScreen(this);},v))).bounds(b.x(),yy,scrollLayout().content().width(),24).build());continue;}
  if(tab==1&&row==3){addRenderableWidget(UiActions.button(Component.literal(Client.text("ui.suggestion_opacity_19338bd5")+Math.round((1-s.hintOpacity)*100)+"%"),UiActions.Tone.NORMAL,"",v->minecraft.setScreen(new ChoicePopup(this,Client.text("ui.suggestion_opacity_29869dc8"),List.of("0%","25%","50%","75%","100%"),i->{s.hintOpacity=1-i/4d;s.save();minecraft.setScreen(this);},v))).bounds(b.x(),yy,scrollLayout().content().width(),24).build());continue;}
  if(row==0)continue; // Server policy is shown as a read-only label, never as a selector.
  if(tab==0&&row==1){addRenderableWidget(UiActions.button(Component.literal(Client.text("ui.grouping_a3201499")+List.of(Client.text("ui.alphabetical_c0555440"),Client.text("ui.roles_265068a5"),Client.text("ui.groups_903e08f2")).get(s.grouping)+" ▾"),UiActions.Tone.NORMAL,"",v->minecraft.setScreen(new ChoicePopup(this,Client.text("ui.player_grouping_ecb1c517"),List.of(Client.text("ui.alphabetical_c0555440"),Client.text("ui.roles_265068a5"),Client.text("ui.groups_903e08f2")),i->{s.grouping=i;s.save();minecraft.setScreen(this);},v).current(s.grouping))).bounds(b.x(),yy,scrollLayout().content().width(),24).build());continue;}
  if(tab==0&&row>=5){String label=row==5?Client.text("ui.background_opacity_bd7b345f"):row==6?Client.text("ui.row_density_e23b1a96"):Client.text("ui.column_width_5e7519d1");String value=row==5?Math.round((1-s.tabOpacity)*100)+"%":row==6?List.of(Client.text("ui.compact_f6a45a26"),Client.text("ui.normal_4cc62905"),Client.text("ui.spacious_e20f4478")).get(s.density):s.columnWidth+" px";List<String> choices=row==5?List.of("0%","20%",Client.text("ui.35_default_ce6e06a2"),"50%","70%","100%"):row==6?List.of(Client.text("ui.compact_f6a45a26"),Client.text("ui.normal_4cc62905"),Client.text("ui.spacious_e20f4478")):List.of("160 px","190 px","220 px","260 px");addRenderableWidget(UiActions.button(Component.literal(label+": "+value+" ▾"),UiActions.Tone.NORMAL,"",v->minecraft.setScreen(new ChoicePopup(this,label,choices,i->{if(row==5)s.tabOpacity=new double[]{1,.8,.65,.5,.3,0}[i];else if(row==6)s.density=i;else s.columnWidth=new int[]{160,190,220,260}[i];s.save();minecraft.setScreen(this);},v))).bounds(b.x(),yy,scrollLayout().content().width(),24).build());continue;}
  String label;boolean enabled;Runnable action;
  if(tab==0){label=row==2?Client.text("ui.player_heads_36d52fe8"):row==3?Client.text("ui.exact_ping_1c9fe4bd"):Client.text("ui.tab_footer_context_a4379eff");enabled=row==2?s.heads:row==3?s.ping:s.footer;action=()->{if(row==2)s.heads=!s.heads;else if(row==3)s.ping=!s.ping;else s.footer=!s.footer;s.save();rebuildWidgets();};}
  else{label=row==2?Client.text("ui.input_suggestions_5918166e"):Client.text("ui.combine_repeated_system_messages_11967403");enabled=row==2?s.hints:s.dedupe;action=()->{if(row==2)s.hints=!s.hints;else s.dedupe=!s.dedupe;s.save();rebuildWidgets();};}
  addRenderableWidget(new UiToggle(label,b.x(),yy,scrollLayout().content().width(),enabled,action));
 } }
 public void revealSetting(String id){revealRow(SettingsCatalog.row(tab+3,id));rebuildWidgets();}
 private void resetSection(){var s=SocialSettings.INSTANCE;if(tab==0){s.grouping=0;s.density=1;s.columnWidth=190;s.tabOpacity=.65;s.heads=true;s.ping=false;s.footer=true;}else{s.history=1000;ClientChat.applyHistoryLimit();s.dedupe=true;s.hints=true;s.hintOpacity=.95;}s.save();}

 @Override public void renderBackground(GuiGraphics g,int x,int y,float d){UiDialog.surface(g,dialog.frame().x(),dialog.frame().y(),dialog.frame().width(),dialog.frame().height());}
 @Override public void render(GuiGraphics g,int x,int y,float d){UiDialog.render(parent,this,g,d,()->{super.render(g,x,y,d);UiHeading.dialog(g,font,title,dialog.header().x(),dialog.frame().y(),dialog.header().width());if(firstRow==0){String mode=SocialSettings.serverMode("tabMode");String label=tab==1?(SocialSettings.chatEnabled()?Client.text("ui.rivet_chat_enabled_edee29e0"):Client.text("ui.rivet_chat_disabled_749bc7da")):switch(mode){case "rivet"->"Rivet";case "auto"->Client.text("ui.automatic_266d9651");default->Client.text("ui.compatible_e1c0f5bc");};Ui.text(g,font,UiKit.fit(font,Client.text("ui.server_mode_fde0643a")+label,dialog.body().width()-12),dialog.body().x()+6,dialog.body().y()+8,UiKit.muted(),false);}UiSettingsPreview.social(g,dialog.body(),tab);});}
 @Override public boolean isPauseScreen(){return false;}
 @Override public void onClose(){UiNavigation.back(this,parent);}
}
