package dev.abros.rivet.client;
import com.google.gson.*;
import dev.abros.rivet.core.Json;
import net.minecraft.client.Minecraft;
import net.minecraft.network.chat.*;
import net.neoforged.neoforge.common.NeoForge;
import java.util.*;
/** Data is fetched while TAB is visible; request epochs and connection resets discard stale replies. */
public final class SocialClient {
 static final Map<UUID,JsonObject> players=new HashMap<>();private static final Map<UUID,JsonObject> staging=new HashMap<>();
 static List<String> chatGroups=List.of();static boolean chatGroupsReady;
 private static HoverEvent.EntityTooltipInfo sender(Component message){var hover=message.getStyle().getHoverEvent();if(hover==null)return null;var value=hover.getValue(HoverEvent.Action.SHOW_ENTITY);return value!=null&&value.type==net.minecraft.world.entity.EntityType.PLAYER?value:null;}
 private static Component withHead(Component message,UUID id){if(!SocialSettings.INSTANCE.heads)return message;return Component.empty().append(Component.literal("   ").withStyle(style->style.withHoverEvent(new HoverEvent(HoverEvent.Action.SHOW_ENTITY,new HoverEvent.EntityTooltipInfo(net.minecraft.world.entity.EntityType.PLAYER,id,java.util.Optional.empty()))))).append(message); }
 public static UUID chatHead(net.minecraft.util.FormattedCharSequence sequence){var id=new UUID[1];sequence.accept((i,style,code)->{if(code==' '&&style.getHoverEvent()!=null){var entity=style.getHoverEvent().getValue(HoverEvent.Action.SHOW_ENTITY);if(entity!=null&&entity.type==net.minecraft.world.entity.EntityType.PLAYER&&entity.name.isEmpty()){id[0]=entity.id;return false;}}return true;});return available()&&SocialSettings.INSTANCE.heads&&SocialSettings.INSTANCE.chat()?id[0]:null;}
 public static void drawChatHead(net.minecraft.client.gui.GuiGraphics g,net.minecraft.client.gui.Font font,net.minecraft.util.FormattedCharSequence sequence,int x,int y){var id=chatHead(sequence);if(id==null)return;var preceding=Component.empty();sequence.accept((i,style,code)->{if(code==' '&&style.getHoverEvent()!=null){var entity=style.getHoverEvent().getValue(HoverEvent.Action.SHOW_ENTITY);if(entity!=null&&entity.type==net.minecraft.world.entity.EntityType.PLAYER&&entity.name.isEmpty())return false;}preceding.append(Component.literal(new String(Character.toChars(code))).withStyle(style));return true;});drawHead(g,id,x+font.width(preceding),y);}
 private static Component decorateSender(Component message,UUID id){var identity=sender(message);if(identity!=null&&identity.id.equals(id)&&identity.name.isPresent())return withHead(message,id);var out=message.plainCopy().withStyle(message.getStyle());for(var child:message.getSiblings())out.append(decorateSender(child,id));return out;}
 public static void drawHead(net.minecraft.client.gui.GuiGraphics g,UUID id,int x,int y){net.minecraft.client.gui.components.PlayerFaceRenderer.draw(g,SkinClient.skin(id),x,y,8);}
 private static boolean tabOpen;
 private static Object connection;private static long next,pendingAt;private static String pending="";private static int page;
 static void install(net.neoforged.bus.api.IEventBus bus){NeoForge.EVENT_BUS.addListener((net.neoforged.neoforge.client.event.ClientTickEvent.Post e)->tick());NeoForge.EVENT_BUS.addListener(SocialClient::layer);NeoForge.EVENT_BUS.addListener(SocialClient::chat);NeoForge.EVENT_BUS.addListener(SocialClient::system);SocialChatControls.install();PlayerNameplates.install();NeoForge.EVENT_BUS.addListener((net.neoforged.neoforge.client.event.RenderGuiEvent.Post e)->DirectionCue.draw(e.getGuiGraphics()));NeoForge.EVENT_BUS.addListener((net.neoforged.neoforge.client.event.InputEvent.MouseScrollingEvent e)->{if(Minecraft.getInstance().screen==null&&visible()){RivetTab.scroll(e.getScrollDeltaY());e.setCanceled(true);}});}
 static boolean available(){return ServerMenuClient.available()&&ServerMenuClient.supports("social-display");}
 static boolean visible(){var mc=Minecraft.getInstance();return available()&&mc.player!=null&&mc.options.keyPlayerList.isDown();}
 private static void tick(){var mc=Minecraft.getInstance();if(connection!=mc.getConnection()){connection=mc.getConnection();players.clear();chatGroups=List.of();chatGroupsReady=false;staging.clear();pending="";next=0;page=0;tabOpen=false;lastSystem="";RivetTab.reset();DirectionCue.clear();}if(!available())return;long now=System.currentTimeMillis();boolean shown=visible()||mc.screen instanceof HudInteractionScreen cursor&&cursor.tabVisible();if(shown&&!tabOpen)next=now+300;tabOpen=shown;if(!pending.isEmpty()&&now-pendingAt>8000){pending="";page=0;staging.clear();next=now+3000;}if((visible()||mc.screen instanceof HudInteractionScreen cursor&&cursor.tabVisible()||mc.screen instanceof net.minecraft.client.gui.screens.ChatScreen||players.isEmpty()||PlayerNameplates.enabled()&&mc.level!=null&&mc.level.players().size()>1)&&pending.isEmpty()&&now>=next){var j=new JsonObject();pending=UUID.randomUUID().toString();pendingAt=now;j.addProperty("request",pending);j.addProperty("action","social");j.addProperty("page",page);ServerMenuClient.requestBackground(j);next=now+(PlayerNameplates.enabled()&&mc.level!=null&&mc.level.players().size()>1?5000:visible()||mc.screen instanceof HudInteractionScreen cursor&&cursor.tabVisible()?5000:mc.screen instanceof net.minecraft.client.gui.screens.ChatScreen?2000:30000);}}
 static boolean receive(JsonObject j){if(Json.opt(j,"kind","").equals("socialDirection")){DirectionCue.receive(j);return true;}if(!Json.opt(j,"kind","").equals("social"))return false;if(!Json.opt(j,"request","").equals(pending))return true;pending="";if(j.has("chatGroups")){var previousGroups=chatGroups;boolean previousReady=chatGroupsReady;chatGroups=j.getAsJsonArray("chatGroups").asList().stream().map(com.google.gson.JsonElement::getAsString).toList();chatGroupsReady=j.has("chatGroupsReady")&&j.get("chatGroupsReady").getAsBoolean();if((!previousGroups.equals(chatGroups)||previousReady!=chatGroupsReady)&&Minecraft.getInstance().screen instanceof net.minecraft.client.gui.screens.ChatScreen chat)((dev.abros.rivet.mixin.ChatInputAccessor)chat).rivet$suggestions().updateCommandInfo();}for(var e:j.getAsJsonArray("players")){var row=e.getAsJsonObject();try{staging.put(UUID.fromString(Json.str(row,"id")),row.deepCopy());}catch(IllegalArgumentException ignored){}}if(j.get("more").getAsBoolean()&&page<100){page++;next=System.currentTimeMillis()+300;}else{players.clear();players.putAll(staging);staging.clear();page=0;}return true;}
 private static void layer(net.neoforged.neoforge.client.event.RenderGuiLayerEvent.Pre e){if(e.getName().equals(net.neoforged.neoforge.client.gui.VanillaGuiLayers.TAB_LIST)&&SocialSettings.INSTANCE.tab()&&visible()&&Minecraft.getInstance().screen==null){e.setCanceled(true);RivetTab.draw(e.getGuiGraphics(),-1,-1);}}
 private static void chat(net.neoforged.neoforge.client.event.ClientChatReceivedEvent.Player e){
  if(!available()||!SocialSettings.INSTANCE.chat()||e.isCanceled())return;
  var original=e.getPlayerChatMessage().decoratedContent();var author=sender(original);var row=players.get(e.getSender());
  Component name;if(author!=null&&author.id.equals(e.getSender())&&author.name.isPresent())name=author.name.get();
  else {String prefix=row==null?"":Json.opt(row,"prefix",""),suffix=row==null?"":Json.opt(row,"suffix","");var info=Minecraft.getInstance().getConnection().getPlayerInfo(e.getSender());name=dev.abros.rivet.network.ChatPresentation.identity(prefix,row==null?(info==null?"Игрок":info.getProfile().getName()):Json.opt(row,"name","Игрок"),suffix);}
  original=original.copy().withStyle(style->style.withHoverEvent(null));
  var line=dev.abros.rivet.network.ChatPresentation.format(Json.opt(ServerMenuClient.state,"chatFormat",dev.abros.rivet.core.ChatFormat.DEFAULT),Json.opt(ServerMenuClient.state,"chatChannelFormat",dev.abros.rivet.core.ChatFormat.CHANNEL_DEFAULT),Json.opt(ServerMenuClient.state,"chatGlobalName",""),e.getSender(),name,original,ChatChannelIndicator.color(dev.abros.rivet.core.ChatChannels.Channel.GLOBAL));
  e.setMessage(dev.abros.rivet.network.ChatPresentation.heads(line,SocialSettings.INSTANCE.heads));
 }
 private static String lastSystem="";private static long lastAt;private static int repeat;
 private static void system(net.neoforged.neoforge.client.event.ClientChatReceivedEvent.System e){if(!available()||!SocialSettings.chatEnabled()||e.isCanceled()||e.isOverlay())return;var mc=Minecraft.getInstance();var author=sender(e.getMessage());if(author!=null&&SocialSettings.INSTANCE.chat())e.setMessage(ServerMenuClient.state.has("chatFormat")?dev.abros.rivet.network.ChatPresentation.heads(e.getMessage().copy().withStyle(style->style.withHoverEvent(null)),SocialSettings.INSTANCE.heads):decorateSender(e.getMessage().copy().withStyle(style->style.withHoverEvent(null)),author.id));String text=e.getMessage().getString();long now=System.currentTimeMillis();if(author==null&&SocialSettings.INSTANCE.dedupe&&text.equals(lastSystem)&&now-lastAt<3000&&removeNewestSystem(mc,lastSystem)){repeat++;e.setCanceled(true);mc.gui.getChat().addMessage(e.getMessage().copy().append(Component.literal(" ×"+repeat)));}else{lastSystem=text;repeat=1;}lastAt=now;}

 private static boolean removeNewestSystem(Minecraft mc,String raw){var history=(dev.abros.rivet.mixin.ChatHistoryAccessor)mc.gui.getChat();var rows=history.rivet$messages();if(rows.isEmpty())return false;var newest=rows.getFirst();String s=newest.content().getString();if(newest.signature()==null&&(s.equals(raw)||s.matches(java.util.regex.Pattern.quote(raw)+" ×[0-9]+"))){rows.removeFirst();history.rivet$refresh();return true;}return false;}
}
