package dev.abros.rivet.client;
import java.util.List;
import net.minecraft.client.gui.GuiGraphics;
import net.minecraft.client.gui.screens.Screen;
import net.minecraft.network.chat.Component;
/** TAB/chat preferences share compound dialog and controls with all Rivet settings. */
final class SocialSettingsScreen extends ScrollScreen {
 private final Screen parent;private UiDialog dialog;private int tab;
 SocialSettingsScreen(Screen parent){super(Component.literal("Настройки Rivet"));this.parent=parent;}
 SocialSettingsScreen(Screen parent,int tab){this(parent);this.tab=tab;}
 @Override protected void init(){dialog=UiSettingsShell.build(width,height,tab+3,parent,this,this::addRenderableWidget,()->UiSettingsShell.confirm(this,this::resetSection),this::onClose);var b=dialog.body();var s=SocialSettings.INSTANCE;scrollArea(8,new dev.abros.rivet.core.NativeLayout.Box(b.x(),b.y(),b.width(),Math.max(0,b.height()-72)),32);int y=b.y();for(int n=firstRow;n<Math.min(8,firstRow+visibleRows);n++,y+=32){int row=tab==1&&n>=1?n+1:n;int yy=y;
  if(tab==1&&row==8){addRenderableWidget(UiActions.button(Component.literal("Прозрачность подсказок: "+Math.round((1-s.hintOpacity)*100)+"%"),UiActions.Tone.NORMAL,"",v->minecraft.setScreen(new ChoicePopup(this,"Прозрачность подсказок",List.of("0%","25%","50%","75%","100%"),i->{s.hintOpacity=1-i/4d;s.save();minecraft.setScreen(this);},v))).bounds(b.x(),yy,scrollLayout().content().width(),24).build());continue;}
  if(row==0)continue; // Server policy is shown as a read-only label, never as a selector.
  if(tab==0&&row==1){addRenderableWidget(UiActions.button(Component.literal("Группировка: "+List.of("Алфавит","Роли","Объединения").get(s.grouping)+" ▾"),UiActions.Tone.NORMAL,"",v->minecraft.setScreen(new ChoicePopup(this,"Группировка игроков",List.of("Алфавит","Роли","Объединения"),i->{s.grouping=i;s.save();minecraft.setScreen(this);},v).current(s.grouping))).bounds(b.x(),yy,scrollLayout().content().width(),24).build());continue;}
  if(tab==0&&row>=5){String label=row==5?"Прозрачность фона":row==6?"Плотность строк":"Ширина колонок";String value=row==5?Math.round((1-s.tabOpacity)*100)+"%":row==6?List.of("Компактная","Обычная","Свободная").get(s.density):s.columnWidth+" px";List<String> choices=row==5?List.of("0%","20%","35% (по умолчанию)","50%","70%","100%"):row==6?List.of("Компактная","Обычная","Свободная"):List.of("160 px","190 px","220 px","260 px");addRenderableWidget(UiActions.button(Component.literal(label+": "+value+" ▾"),UiActions.Tone.NORMAL,"",v->minecraft.setScreen(new ChoicePopup(this,label,choices,i->{if(row==5)s.tabOpacity=new double[]{1,.8,.65,.5,.3,0}[i];else if(row==6)s.density=i;else s.columnWidth=new int[]{160,190,220,260}[i];s.save();minecraft.setScreen(this);},v))).bounds(b.x(),yy,scrollLayout().content().width(),24).build());continue;}
  String label;boolean enabled;Runnable action;
  if(tab==0){label=row==2?"Головы игроков":row==3?"Точный пинг":"Нижний контекст TAB";enabled=row==2?s.heads:row==3?s.ping:s.footer;action=()->{if(row==2)s.heads=!s.heads;else if(row==3)s.ping=!s.ping;else s.footer=!s.footer;s.save();rebuildWidgets();};}
  else if(row==2||row==7){label=row==7?"Подсказки ввода":"Объединять системные повторы";enabled=row==7?s.hints:s.dedupe;action=()->{if(row==7)s.hints=!s.hints;else s.dedupe=!s.dedupe;s.save();rebuildWidgets();};}
  else{label=switch(row){case 3->"Размер текста";case 4->"Расстояние между строками";case 5->"Прозрачность текста";default->"Прозрачность фона";};var option=switch(row){case 3->minecraft.options.chatScale();case 4->minecraft.options.chatLineSpacing();case 5->minecraft.options.chatOpacity();default->minecraft.options.textBackgroundOpacity();};addRenderableWidget(UiActions.button(Component.literal(label+": "+Math.round(option.get()*100)+"% ▾"),UiActions.Tone.NORMAL,"",v->minecraft.setScreen(new ChoicePopup(this,label,List.of("25%","50%","75%","100%"),i->{option.set((i+1)/4d);minecraft.options.save();minecraft.gui.getChat().rescaleChat();minecraft.setScreen(this);},v))).bounds(b.x(),yy,scrollLayout().content().width(),24).build());continue;}
  addRenderableWidget(new UiToggle(label,b.x(),yy,scrollLayout().content().width(),enabled,action));
 } }
 private void resetSection(){var s=SocialSettings.INSTANCE;if(tab==0){s.grouping=0;s.density=1;s.columnWidth=190;s.tabOpacity=.65;s.heads=true;s.ping=false;s.footer=true;}else{s.dedupe=true;s.hints=true;s.hintOpacity=.95;minecraft.options.chatScale().set(1d);minecraft.options.chatLineSpacing().set(0d);minecraft.options.chatOpacity().set(1d);minecraft.options.textBackgroundOpacity().set(.5d);minecraft.options.save();minecraft.gui.getChat().rescaleChat();}s.save();}

 @Override public void renderBackground(GuiGraphics g,int x,int y,float d){UiDialog.surface(g,dialog.frame().x(),dialog.frame().y(),dialog.frame().width(),dialog.frame().height());}
 @Override public void render(GuiGraphics g,int x,int y,float d){UiDialog.render(parent,this,g,d,()->{super.render(g,x,y,d);UiHeading.dialog(g,font,title,dialog.header().x(),dialog.frame().y(),dialog.header().width());if(firstRow==0){String mode=SocialSettings.serverMode("tabMode");String label=tab==1?(SocialSettings.chatEnabled()?"Чат Rivet включён":"Чат Rivet выключен"):switch(mode){case "rivet"->"Rivet";case "auto"->"Автоматический";default->"Совместимый";};Ui.text(g,font,UiKit.fit(font,"Режим сервера: "+label,dialog.body().width()-12),dialog.body().x()+6,dialog.body().y()+8,UiKit.muted(),false);}UiSettingsPreview.social(g,dialog.body(),tab);});}
 @Override public boolean isPauseScreen(){return false;}
 @Override public void onClose(){minecraft.setScreen(parent);}
}
