package dev.abros.rivet.client;
import com.google.gson.*;import dev.abros.rivet.core.*;import java.util.*;import java.util.function.Consumer;import net.minecraft.client.gui.GuiGraphics;import net.minecraft.client.gui.components.*;import net.minecraft.client.gui.screens.*;import net.minecraft.network.chat.Component;import net.minecraft.core.registries.BuiltInRegistries;import net.minecraft.resources.ResourceLocation;
final class TaskResourcesScreen extends ScrollScreen implements CommunityScreen.Receiver {
 private final Screen parent;private final Consumer<JsonArray> saved;private final JsonArray rows;private final JsonArray original;private String notice="";private boolean busy,uncertain;private long sentAt;
 TaskResourcesScreen(Screen parent,JsonArray rows,Consumer<JsonArray> saved){super(Client.tr("ui.task_resources_52a0f8f6"));this.parent=parent;this.rows=rows.deepCopy();original=rows.deepCopy();this.saved=saved;}
 static String name(String id){var key=ResourceLocation.tryParse(id);return key!=null&&BuiltInRegistries.ITEM.containsKey(key)?BuiltInRegistries.ITEM.get(key).getDescription().getString():id;}
 static void icon(GuiGraphics g,String id,int x,int y){var key=ResourceLocation.tryParse(id);if(key!=null&&BuiltInRegistries.ITEM.containsKey(key))g.renderItem(BuiltInRegistries.ITEM.get(key).getDefaultInstance(),x,y);}
 private int w(){return Math.min(460,width-40);}private int x(){return(width-w())/2;}private int top(){return UiDialog.top(height,330);}private int bottom(){return height-top();}
 private void editRow(String id,JsonObject row){minecraft.setScreen(new ChoicePopup(this,name(id),List.of(Client.text("ui.quantity_a94061bf"),Client.text("ui.add_allowed_substitute_0bc624c1"),Client.text("ui.remove_all_substitutes_835f39dc")),n->{if(n==0)amount(id,row);else if(n==1&&!ServerMenuClient.supports("resource-alternatives")){notice=Client.text("ui.substitutions_require_an_updated_rivet_on_2153b1d1");rebuildWidgets();}else if(n==1)minecraft.setScreen(new ItemPickerScreen(this,alternative->{try{var values=row.has("alternatives")?row.getAsJsonArray("alternatives"):new JsonArray();values.add(alternative);row.add("alternatives",values);ResourceRequirements.validate(rows);notice="";}catch(Exception error){var values=row.getAsJsonArray("alternatives");if(values!=null&&!values.isEmpty())values.remove(values.size()-1);notice=error.getMessage();}rebuildWidgets();}));else{row.remove("alternatives");rebuildWidgets();}}));}
 private void amount(String id,JsonObject existing){var preset=new JsonObject();preset.addProperty("amount",existing==null?64:existing.get("amount").getAsInt());minecraft.setScreen(new TaskEditScreen(this,name(id),List.of(new CommunityScreen.Field("amount",Client.text("ui.required_quantity_c23b32bc"),7)),preset,j->{try{int count=Integer.parseInt(Json.str(j,"amount"));if(count<1||count>1000000)throw new IllegalArgumentException();var row=existing==null?new JsonObject():existing;row.addProperty("item",id);row.addProperty("amount",count);if(existing==null){for(var e:rows)if(Json.str(e.getAsJsonObject(),"item").equals(id))throw new IllegalArgumentException(Client.text("ui.this_item_is_already_on_the_f06281f0"));rows.add(row);}notice="";}catch(Exception ex){notice=Client.text("ui.quantity_1_1000000_each_item_can_7944b961");}rebuildWidgets();}));}
 @Override protected void init(){var list=scrollArea(rows.size(),new NativeLayout.Box(x(),top()+36,w(),Math.max(0,bottom()-94-(top()+36))),28);for(int i=firstRow;i<Math.min(rows.size(),firstRow+visibleRows);i++){var row=rows.get(i).getAsJsonObject();String id=Json.str(row,"item");addRenderableWidget(UiActions.button(Component.literal(name(id)+" · "+row.get("amount")+(row.has("alternatives")?Client.text("ui.replacements_5ba74cf8")+row.getAsJsonArray("alternatives").size():"")),UiActions.Tone.NORMAL,"",b->editRow(id,row)).bounds(x()+24,top()+36+(i-firstRow)*28,list.content().width()-96,20).build());addRenderableWidget(UiActions.button(Client.tr("ui.remove_9c7449bf"),UiActions.Tone.NORMAL,"",b->{rows.remove(row);rebuildWidgets();}).bounds(list.content().right()-66,top()+36+(i-firstRow)*28,66,20).build());}var add=addRenderableWidget(UiActions.button(Client.tr("ui.select_item_de29608c"),UiActions.Tone.NORMAL,UiIcons.PLUS,b->minecraft.setScreen(new ItemPickerScreen(this,id->amount(id,null)))).bounds(x(),bottom()-78,w(),20).build());add.active=rows.size()<30;add.setTooltip(Tooltip.create(Component.literal(rows.size()<30?Client.text("ui.search_for_an_item_by_name_139b669f"):Client.text("ui.a_task_can_specify_up_to_c47207d5"))));for(var child:children())if(child instanceof AbstractWidget widget)widget.active=widget.active&&!busy;addRenderableWidget(UiActions.button(Component.literal(busy?Client.text("ui.saving_73bfb5e4"):Client.text("map.tool.save")),UiActions.Tone.PRIMARY,UiIcons.SAVE,b->{if(busy||uncertain)return;if(parent instanceof TaskScreen){var before=new JsonObject();before.add("resources",original);var after=new JsonObject();after.add("resources",rows);var changes=ChangeSummary.between(before,after,Map.of("resources",Client.text("ui.resources_and_allowed_substitutes_9def7ed8")));if(changes.isEmpty())return;minecraft.setScreen(new ChangePreviewScreen(this,changes,()->{busy=true;sentAt=System.currentTimeMillis();rebuildWidgets();saved.accept(rows.deepCopy());}));}else{minecraft.setScreen(parent);saved.accept(rows.deepCopy());}}).bounds(x(),bottom()-28,(w()-8)/2,20).build()).active=!busy&&!uncertain;UiActions.close(new dev.abros.rivet.core.NativeLayout.Box(x()+(w()+8)/2,bottom()-28,(w()-8)/2,20),this::addRenderableWidget,this::onClose);}
 @Override public void renderBackground(GuiGraphics g,int mx,int my,float d){UiDialog.draw(g,width,w(),top(),bottom());}
 @Override public void render(GuiGraphics g,int mx,int my,float d){UiDialog.render(parent,this,g,d,()->{super.render(g,mx,my,d);UiHeading.dialog(g,font,title,x(),top(),w());Ui.status(g,font,notice,x(),bottom()-54,w(),bottom()-32);for(int i=firstRow;i<Math.min(rows.size(),firstRow+visibleRows);i++)icon(g,Json.str(rows.get(i).getAsJsonObject(),"item"),x()+2,top()+38+(i-firstRow)*28);if(rows.isEmpty())Ui.text(g,font,Client.text("ui.select_items_for_the_task_fff0bd7a"),x(),top()+40,UiPalette.color(0xAEBBC8));});}
 @Override public void onClose(){if(busy){notice=Client.text("ui.wait_for_the_server_to_respond_43e44ea8");return;}if(rows.equals(original))minecraft.setScreen(parent);else minecraft.setScreen(new UiConfirmDialog(yes->minecraft.setScreen(yes?parent:this),Client.tr("ui.exit_without_saving_3ac6ec3d"),Client.tr("ui.changes_to_the_resource_list_have_36cf1162")));}public void receiveCommunity(JsonObject j){if(!(parent instanceof TaskScreen task)||!busy||!task.matches(j))return;task.receiveCommunity(j);busy=false;if(j.has("error")){notice=Json.opt(j,"text",Client.text("ui.could_not_save_resources_a091e432"));rebuildWidgets();}else minecraft.setScreen(parent);}
 @Override public void tick(){if(busy&&System.currentTimeMillis()-sentAt>=15000){if(parent instanceof TaskScreen task)task.tick();busy=false;uncertain=true;notice=Client.text("ui.no_response_return_to_the_task_8d68ebbe");rebuildWidgets();}}
 @Override public boolean isPauseScreen(){return false;}
}
