package dev.abros.rivet.client;
import com.google.gson.*;import dev.abros.rivet.core.*;import net.minecraft.client.gui.GuiGraphics;import net.minecraft.network.chat.Component;import java.util.*;
final class TaskArchiveScreen extends ScrollScreen implements CommunityScreen.Receiver {
 private final TaskScreen parent;private final String group;private final int days;private final RequestSession session=new RequestSession();private JsonArray rows=new JsonArray();private boolean loaded,busy;private String notice="";private UiDialog layout;
 TaskArchiveScreen(TaskScreen parent,String group,int days){super(Client.tr("ui.completed_tasks_archive_c3ccdbf5"));this.parent=parent;this.group=group;this.days=days;}
 private void request(boolean apply){if(busy)return;var j=new JsonObject();j.addProperty("action","community");j.addProperty("section",group.isEmpty()?"home":"groups");j.addProperty("group",group);j.addProperty("op",apply?"workArchiveApply":"workArchivePreview");j.addProperty("days",days);if(apply)j.add("items",rows);busy=true;ServerMenuClient.request(session.begin(j,apply,System.currentTimeMillis()));rebuildWidgets();}
 @Override protected void init(){layout=UiDialog.fit(width,height,440,330);var body=layout.body();scrollArea(rows.size(),new NativeLayout.Box(body.x(),body.y()+28,body.width(),Math.max(0,body.height()-48)),18);UiActions.row(layout.footer(),this::addRenderableWidget,UiActions.primary(Client.text("ui.archive_c7824aa0"),()->request(true),!busy&&!rows.isEmpty()),UiActions.action(Client.text("cancel"),this::onClose,!busy));if(!loaded){loaded=true;request(false);}}
 public void receiveCommunity(JsonObject j){if(!session.receive(j))return;busy=false;if(j.has("error")){notice=Json.opt(j,"text",Client.text("ui.could_not_archive_b620f236"));rows=new JsonArray();}else if(j.has("applied")&&j.get("applied").getAsBoolean()){parent.invalidate(group.isEmpty()?"home":"groups",group);minecraft.setScreen(parent);return;}else{rows=j.getAsJsonArray("preview");notice=j.has("more")?Client.text("ui.first_200_tasks_the_rest_can_372312f9"):Client.text("ui.tasks_will_remain_available_through_the_fe8cad4b");}rebuildWidgets();}
 @Override public void tick(){if(session.timeout(System.currentTimeMillis())){busy=false;rows=new JsonArray();notice=Client.text("ui.no_response_reopen_the_preview_before_e9ec4f26");rebuildWidgets();}}
 @Override public void renderBackground(GuiGraphics g,int x,int y,float d){UiDialog.surface(g,layout.frame().x(),layout.frame().y(),layout.frame().width(),layout.frame().height());}
 @Override public void render(GuiGraphics g,int x,int y,float d){UiDialog.render(parent,this,g,d,()->{super.render(g,x,y,d);UiHeading.dialog(g,font,title,layout.header().x(),layout.frame().y(),layout.header().width());Ui.text(g,font,busy?Client.text("ui.checking_350473a9"):Client.text("ui.will_be_archived_700210a5")+rows.size(),layout.body().x(),layout.body().y(),UiKit.text());for(int n=firstRow;n<Math.min(rows.size(),firstRow+visibleRows);n++)Ui.text(g,font,UiKit.fit(font,Json.str(rows.get(n).getAsJsonObject(),"title"),scrollLayout().content().width()),layout.body().x(),layout.body().y()+28+(n-firstRow)*18,UiKit.muted());Ui.status(g,font,notice,layout.body().x(),layout.body().bottom()-18,layout.body().width(),layout.body().bottom());});}
 @Override public void onClose(){if(busy)return;session.cancel();minecraft.setScreen(parent);}
 @Override public boolean isPauseScreen(){return false;}
}
