package dev.abros.rivet.client;
import com.google.gson.*;import dev.abros.rivet.core.*;import java.util.*;import java.util.function.Consumer;import net.minecraft.client.gui.GuiGraphics;import net.minecraft.client.gui.components.*;import net.minecraft.client.gui.screens.*;import net.minecraft.network.chat.Component;import net.minecraft.core.registries.BuiltInRegistries;import net.minecraft.resources.ResourceLocation;
final class TaskResourcesScreen extends ScrollScreen implements CommunityScreen.Receiver {
 private final Screen parent;private final Consumer<JsonArray> saved;private final JsonArray rows;private final JsonArray original;private String notice="";private boolean busy,uncertain;private long sentAt;
 TaskResourcesScreen(Screen parent,JsonArray rows,Consumer<JsonArray> saved){super(Component.literal("Ресурсы задачи"));this.parent=parent;this.rows=rows.deepCopy();original=rows.deepCopy();this.saved=saved;}
 static String name(String id){var key=ResourceLocation.tryParse(id);return key!=null&&BuiltInRegistries.ITEM.containsKey(key)?BuiltInRegistries.ITEM.get(key).getDescription().getString():id;}
 static void icon(GuiGraphics g,String id,int x,int y){var key=ResourceLocation.tryParse(id);if(key!=null&&BuiltInRegistries.ITEM.containsKey(key))g.renderItem(BuiltInRegistries.ITEM.get(key).getDefaultInstance(),x,y);}
 private int w(){return Math.min(460,width-40);}private int x(){return(width-w())/2;}private int top(){return UiDialog.top(height,330);}private int bottom(){return height-top();}
 private void editRow(String id,JsonObject row){minecraft.setScreen(new ChoicePopup(this,name(id),List.of("Количество…","Добавить допустимую замену…","Убрать все замены"),n->{if(n==0)amount(id,row);else if(n==1&&!ServerMenuClient.supports("resource-alternatives")){notice="Для замен нужен обновлённый Rivet на сервере";rebuildWidgets();}else if(n==1)minecraft.setScreen(new ItemPickerScreen(this,alternative->{try{var values=row.has("alternatives")?row.getAsJsonArray("alternatives"):new JsonArray();values.add(alternative);row.add("alternatives",values);ResourceRequirements.validate(rows);notice="";}catch(Exception error){var values=row.getAsJsonArray("alternatives");if(values!=null&&!values.isEmpty())values.remove(values.size()-1);notice=error.getMessage();}rebuildWidgets();}));else{row.remove("alternatives");rebuildWidgets();}}));}
 private void amount(String id,JsonObject existing){var preset=new JsonObject();preset.addProperty("amount",existing==null?64:existing.get("amount").getAsInt());minecraft.setScreen(new TaskEditScreen(this,name(id),List.of(new CommunityScreen.Field("amount","Необходимое количество",7)),preset,j->{try{int count=Integer.parseInt(Json.str(j,"amount"));if(count<1||count>1000000)throw new IllegalArgumentException();var row=existing==null?new JsonObject():existing;row.addProperty("item",id);row.addProperty("amount",count);if(existing==null){for(var e:rows)if(Json.str(e.getAsJsonObject(),"item").equals(id))throw new IllegalArgumentException("Этот предмет уже есть в списке");rows.add(row);}notice="";}catch(Exception ex){notice="Количество: 1–1000000. Каждый предмет добавляется один раз.";}rebuildWidgets();}));}
 @Override protected void init(){var list=scrollArea(rows.size(),new NativeLayout.Box(x(),top()+36,w(),Math.max(0,bottom()-94-(top()+36))),28);for(int i=firstRow;i<Math.min(rows.size(),firstRow+visibleRows);i++){var row=rows.get(i).getAsJsonObject();String id=Json.str(row,"item");addRenderableWidget(UiActions.button(Component.literal(name(id)+" · "+row.get("amount")+(row.has("alternatives")?" · замен: "+row.getAsJsonArray("alternatives").size():"")),UiActions.Tone.NORMAL,"",b->editRow(id,row)).bounds(x()+24,top()+36+(i-firstRow)*28,list.content().width()-96,20).build());addRenderableWidget(UiActions.button(Component.literal("Убрать"),UiActions.Tone.NORMAL,"",b->{rows.remove(row);rebuildWidgets();}).bounds(list.content().right()-66,top()+36+(i-firstRow)*28,66,20).build());}var add=addRenderableWidget(UiActions.button(Component.literal("+ Выбрать предмет"),UiActions.Tone.NORMAL,UiIcons.PLUS,b->minecraft.setScreen(new ItemPickerScreen(this,id->amount(id,null)))).bounds(x(),bottom()-78,w(),20).build());add.active=rows.size()<30;add.setTooltip(Tooltip.create(Component.literal(rows.size()<30?"Найдите предмет по названию или его идентификатору":"В задаче можно указать до 30 видов ресурсов")));for(var child:children())if(child instanceof AbstractWidget widget)widget.active=widget.active&&!busy;addRenderableWidget(UiActions.button(Component.literal(busy?"Сохраняем…":"Сохранить"),UiActions.Tone.PRIMARY,UiIcons.SAVE,b->{if(busy||uncertain)return;if(parent instanceof TaskScreen){var before=new JsonObject();before.add("resources",original);var after=new JsonObject();after.add("resources",rows);var changes=ChangeSummary.between(before,after,Map.of("resources","Список ресурсов и допустимых замен"));if(changes.isEmpty())return;minecraft.setScreen(new ChangePreviewScreen(this,changes,()->{busy=true;sentAt=System.currentTimeMillis();rebuildWidgets();saved.accept(rows.deepCopy());}));}else{minecraft.setScreen(parent);saved.accept(rows.deepCopy());}}).bounds(x(),bottom()-28,(w()-8)/2,20).build()).active=!busy&&!uncertain;UiActions.close(new dev.abros.rivet.core.NativeLayout.Box(x()+(w()+8)/2,bottom()-28,(w()-8)/2,20),this::addRenderableWidget,this::onClose);}
 @Override public void renderBackground(GuiGraphics g,int mx,int my,float d){UiDialog.draw(g,width,w(),top(),bottom());}
 @Override public void render(GuiGraphics g,int mx,int my,float d){UiDialog.render(parent,this,g,d,()->{super.render(g,mx,my,d);UiHeading.dialog(g,font,title,x(),top(),w());Ui.status(g,font,notice,x(),bottom()-54,w(),bottom()-32);for(int i=firstRow;i<Math.min(rows.size(),firstRow+visibleRows);i++)icon(g,Json.str(rows.get(i).getAsJsonObject(),"item"),x()+2,top()+38+(i-firstRow)*28);if(rows.isEmpty())Ui.text(g,font,"Выберите предметы для задачи",x(),top()+40,UiPalette.color(0xAEBBC8));});}
 @Override public void onClose(){if(busy){notice="Дождитесь ответа сервера";return;}if(rows.equals(original))minecraft.setScreen(parent);else minecraft.setScreen(new UiConfirmDialog(yes->minecraft.setScreen(yes?parent:this),Component.literal("Выйти без сохранения?"),Component.literal("Изменения списка ресурсов ещё не сохранены.")));}public void receiveCommunity(JsonObject j){if(!(parent instanceof TaskScreen task)||!busy||!task.matches(j))return;task.receiveCommunity(j);busy=false;if(j.has("error")){notice=Json.opt(j,"text","Не удалось сохранить ресурсы");rebuildWidgets();}else minecraft.setScreen(parent);}
 @Override public void tick(){if(busy&&System.currentTimeMillis()-sentAt>=15000){if(parent instanceof TaskScreen task)task.tick();busy=false;uncertain=true;notice="Нет ответа. Вернитесь к задаче и повторите отправку.";rebuildWidgets();}}
 @Override public boolean isPauseScreen(){return false;}
}
