package dev.abros.rivet.client;
import com.google.gson.*;
import dev.abros.rivet.core.*;
import net.minecraft.client.gui.GuiGraphics;
import net.minecraft.client.gui.components.*;
import net.minecraft.client.gui.screens.Screen;
import net.minecraft.network.chat.Component;
import java.util.*;
/** Task view; application state and request transitions live in TaskWorkspace. */
final class TaskScreen extends ScrollScreen implements CommunityScreen.Receiver {
 private final Screen parent;private final String group;private final TaskWorkspace workspace;private JsonObject data=new JsonObject();private JsonArray tasks=new JsonArray();private String taskTab="Обзор";private boolean loaded;private String query="",statusFilter="",listedQuery="",listedStatus="";private long searchAt;private final MenuSidebar nav=new MenuSidebar(this);private final RowViewport taskList=new RowViewport();
 private UiFormDraft localDraft;private long draftAt,draftGeneration;
 private UiTaskLayout layout;private boolean editing;private JsonObject draft=new JsonObject(),draftOriginal=new JsonObject();private UiFeedback.Kind draftKind=UiFeedback.Kind.ERROR;private String draftError="",titleIssue="";
 @Override protected int scrollLeft(){return layout().body().x();}
 private UiTaskLayout layout(){return layout==null?UiTaskLayout.fit(width,height,!workspace.id().isEmpty(),editing):layout;}
 private final Map<Integer,Runnable> stageMenus=new HashMap<>();private final Map<Integer,List<String>> paragraphs=new HashMap<>();private final Map<Integer,Boolean> stageChecks=new HashMap<>();private final Map<Integer,Double> resourceProgress=new HashMap<>();private final Map<Integer,String> resourceIcons=new HashMap<>();private final List<String> lines=new ArrayList<>();private final List<Runnable> actions=new ArrayList<>();
 TaskScreen(Screen parent,String group,String initialId){super(Component.literal(group.isEmpty()?"Мои задачи":"Задачи объединения"));this.parent=parent;this.group=group;this.workspace=new TaskWorkspace(group,initialId,ServerMenuClient::request,ServerMenuClient::cached,System::currentTimeMillis);}
 boolean matches(JsonObject reply){return workspace.matches(reply);}
 boolean leavePage(){if(editing){draftError="Сохраните изменения или нажмите «Отмена»";return false;}if(workspace.busy()&&!workspace.reading())return false;workspace.cancelRead();ServerMenuClient.cancelReads(this);return true;}
 boolean personal(){return group.isEmpty();}
 static boolean available(){return ServerMenuClient.supports("task-tools");}
 private boolean split(){return layout().split();}
 private int listWidth(){return layout().list().width();}
 private int x(){return layout().detail().x();}private int w(){return layout().detail().width();}
 private int top(){return layout().detail().y();}private int panelEnd(){return layout().detail().bottom();}
 private int listBottom(){return layout().rows().bottom();}
 private int contentTop(){return layout().body().y();}
 private void list(){workspace.list(query,statusFilter);if(!workspace.listLoaded())rebuildWidgets();}
 private void select(JsonObject task){if(editing){draftError="Сохраните изменения или нажмите «Отмена»";return;}if(workspace.busy()&&workspace.reading())ServerMenuClient.cancelReads(this);if(!workspace.select(Json.str(task,"id")))return;taskTab="Обзор";resetScroll();load();}
 String subscription(){return group.isEmpty()?"home|":"groups|"+group;}
 void invalidate(String section,String target){workspace.invalidate(section,target);}
 private JsonObject body(){return workspace.body();}
 private void send(String op,JsonObject body){workspace.send(op,body);if(!workspace.reading()||!workspace.listLoaded()||!workspace.id().isEmpty()&&!data.has("task"))rebuildWidgets();}
 private void load(){boolean cached=workspace.load();if(cached||!workspace.id().isEmpty()&&!data.has("task"))rebuildWidgets();}
 void row(String label,Runnable action){lines.add(label);actions.add(action);}
 void paragraph(String text){var wrapped=font.getSplitter().splitLines(text,w()-24,net.minecraft.network.chat.Style.EMPTY);for(int i=0;i<wrapped.size();i+=2){var pair=new ArrayList<String>();pair.add(wrapped.get(i).getString());if(i+1<wrapped.size())pair.add(wrapped.get(i+1).getString());paragraphs.put(lines.size(),pair);row("",null);}}
 dev.abros.rivet.core.ScrollLayout listGeometry(){return taskList.geometry();}
 private void stageMenu(JsonObject stage,int index){minecraft.setScreen(new ChoicePopup(this,"Этап",List.of("Переименовать…","Удалить этап…"),choice->{if(choice==0){var preset=new JsonObject();preset.add("title",stage.get("title"));editor("Название этапа",List.of(new CommunityScreen.Field("title","Название",100)),preset,v->{var b=body();b.addProperty("index",index);b.add("title",v.get("title"));send("workSubtask",b);});}else minecraft.setScreen(new UiConfirmDialog(yes->{minecraft.setScreen(this);if(yes){var b=body();b.addProperty("index",index);b.addProperty("remove",true);send("workSubtask",b);}},Component.literal("Удалить этап?"),Component.literal(Json.str(stage,"title"))).dangerous());}));}
 private void editor(String title,List<CommunityScreen.Field> fields,JsonObject preset,java.util.function.Consumer<JsonObject> callback){minecraft.setScreen(new TaskEditScreen(this,title,fields,preset,callback));}
 private void edit(JsonObject t){if(workspace.busy())return;editing=true;draftError="";titleIssue="";draft=new JsonObject();draft.addProperty("title",t==null?"":Json.opt(t,"title",""));draft.addProperty("description",t==null?"":Json.opt(t,"description",""));draft.addProperty("new",t==null);draftOriginal=draft.deepCopy();long generation=++draftGeneration;localDraft=new UiFormDraft("task|"+group+"|"+(t==null?"new":workspace.id()));localDraft.restore(saved->{if(!editing||generation!=draftGeneration||!draft.equals(draftOriginal)||saved.isEmpty())return;for(String field:List.of("title","description"))if(saved.has(field))draft.add(field,saved.get(field));draftKind=UiFeedback.Kind.INFO;draftError="Восстановлен черновик. Проверьте текст перед сохранением.";rebuildWidgets();},message->{if(editing&&generation==draftGeneration)draftError=message;});rebuildWidgets();}
 private void discardDraft(){draftGeneration++;draftAt=0;if(localDraft!=null)localDraft.remove(workspace::notice);}
 private void changedDraft(){draftAt=System.currentTimeMillis()+600;}
 private void persistDraft(){if(localDraft==null)return;var fields=new JsonObject();for(String key:List.of("title","description"))fields.add(key,draft.get(key));localDraft.save(fields,message->{draftKind=UiFeedback.Kind.ERROR;draftError=message;});draftAt=0;}
 private void cancelEdit(){if(workspace.busy())return;if(draft.equals(draftOriginal)){discardDraft();editing=false;rebuildWidgets();return;}minecraft.setScreen(new UiConfirmDialog(yes->{minecraft.setScreen(this);if(yes){discardDraft();editing=false;draftError="";rebuildWidgets();}},Component.literal("Отменить изменения?"),Component.literal("Введённый текст не будет сохранён.")));}
 private void saveEdit(){if(workspace.busy()||workspace.retryAvailable())return;if(Json.str(draft,"title").isBlank()){titleIssue="Введите название задачи";draftKind=UiFeedback.Kind.ERROR;draftError=titleIssue;rebuildWidgets();for(var child:children())if(child instanceof EditBox){setFocused(child);break;}return;}var b=body();if(draft.get("new").getAsBoolean()){b.remove("task");b.remove("revision");}b.add("title",draft.get("title"));b.add("description",draft.get("description"));persistDraft();var changes=ChangeSummary.between(draftOriginal,draft,new LinkedHashMap<>(Map.of("title","Название","description","Описание")));if(!draft.get("new").getAsBoolean()&&!changes.isEmpty())minecraft.setScreen(new ChangePreviewScreen(this,changes,()->send("workSave",b)));else send("workSave",b);}
 private void buildEditor(){
  var titleField=new UiTextForm.Field("Название задачи","Название задачи",100,Json.str(draft,"title"),v->{draft.addProperty("title",v);changedDraft();titleIssue="";draftError="";for(var child:children())if(child instanceof EditBox box)UiFields.issue(box,null);});
  var descriptionField=new UiTextForm.Field("Описание задачи","Что нужно сделать?",1000,Json.str(draft,"description"),v->{draft.addProperty("description",v);changedDraft();});
  UiTextForm.compose(font,layout().body(),titleField,descriptionField,!workspace.busy(),!workspace.busy()&&!workspace.retryAvailable(),workspace.busy()?"Сохраняем…":"Сохранить",this::saveEdit,this::cancelEdit,titleIssue).forEach(this::addRenderableWidget);
 }
 private void detailPages(JsonObject t,String array,String offsetKey,String countKey){if(!t.has(countKey)||!t.has(offsetKey))return;int offset=t.get(offsetKey).getAsInt(),count=t.get(countKey).getAsInt(),size=t.getAsJsonArray(array).size();if(count<=size)return;row("Показаны "+(offset+1)+"–"+(offset+size)+" из "+count,null);if(offset>0)row("← Предыдущая страница",()->detailPage(offsetKey,Math.max(0,offset-20)));if(offset+size<count)row("Следующая страница →",()->detailPage(offsetKey,offset+size));}
 private void detailPage(String key,int offset){var b=body();b.addProperty(key,offset);send("workGet",b);firstRow=0;}
 private void textAction(String title,String key,int limit,String op){editor(title,List.of(new CommunityScreen.Field(key,title,limit)),new JsonObject(),v->{var b=body();b.add(key,v.get(key));send(op,b);});}
 private boolean planning(){return ServerMenuClient.supports("community-extensions");}
 private void editDependencies(JsonObject t){var codes=new ArrayList<String>();if(t.has("dependencyDetails"))for(var e:t.getAsJsonArray("dependencyDetails"))codes.add(Json.opt(e.getAsJsonObject(),"code",""));var preset=new JsonObject();preset.addProperty("codes",String.join(", ",codes));editor("Коды блокирующих задач",List.of(new CommunityScreen.Field("codes","Коды через запятую; пусто — убрать",200)),preset,v->{var b=body();b.add("codes",v.get("codes"));send("workDependencies",b);});}
 private void editRepeat(JsonObject t){var intervals=List.of(0,1,7,30);minecraft.setScreen(new ChoicePopup(this,"Повтор задачи",List.of("Не повторять","Каждый день","Каждые 7 дней","Каждые 30 дней"),n->{var b=body();b.addProperty("days",intervals.get(n));send("workRepeat",b);}).current(intervals.indexOf(t.has("repeatDays")?t.get("repeatDays").getAsInt():0)));}
 private void taskActions(JsonObject t,AbstractWidget anchor){var labels=new ArrayList<String>();var run=new ArrayList<Runnable>();if(group.isEmpty()||minecraft.player!=null&&minecraft.player.getUUID().toString().equals(Json.opt(t,"assignee",""))){labels.add(HudSettings.INSTANCE.pin().equals(Json.str(t,"id"))?"Убрать из игрового виджета":"Закрепить в игровом виджете");run.add(()->HudSettings.INSTANCE.pin(HudSettings.INSTANCE.pin().equals(Json.str(t,"id"))?"":Json.str(t,"id")));}labels.add("Скопировать код");run.add(()->{minecraft.keyboardHandler.setClipboard(Json.str(t,"code"));workspace.notice("Код скопирован");});boolean manage=MenuData.Task.read(t).manage();if(manage){if(t.has("archived")&&t.get("archived").getAsBoolean()){labels.add("Вернуть из архива");run.add(()->send("workRestore",body()));}labels.add("Редактировать задачу");run.add(()->edit(t));if(planning()){labels.add("Зависимости…");run.add(()->editDependencies(t));labels.add("Повтор задачи…");run.add(()->editRepeat(t));}labels.add("Удалить задачу…");run.add(()->minecraft.setScreen(new UiConfirmDialog(yes->{minecraft.setScreen(this);if(yes)send("workDelete",body());},Component.literal("Удалить задачу?"),Component.literal("Этапы, комментарии и привязки складов будут удалены.")).dangerous()));}if(undoAvailable()){labels.add("Отменить последнее изменение статуса");run.add(()->{undoStatus();});}var menu=new ChoicePopup(this,"Действия с задачей",labels,n->run.get(n).run(),anchor);if(manage)menu.danger(labels.indexOf("Удалить задачу…"));minecraft.setScreen(menu);}
 private boolean undoAvailable(){return workspace.undoAvailable();}
 private void undoStatus(){workspace.undoStatus();rebuildWidgets();}
 private static String historyLabel(String op){return switch(op){case "workSave"->"Изменены название и описание";case "workStatus"->"Изменён статус";case "workAssign"->"Изменён ответственный";case "workDue"->"Изменён срок";case "workSubtask"->"Изменён этап";case "workResources"->"Изменены ресурсы";case "workDependencies"->"Изменены зависимости";case "workReserve"->"Изменён резерв";case "workRepeat"->"Изменён повтор";case "workComment"->"Добавлен комментарий";default->"Изменена задача";};}
 private void resources(){var t=data.getAsJsonObject("task");minecraft.setScreen(new TaskResourcesScreen(this,t.has("resources")?t.getAsJsonArray("resources"):new JsonArray(),rows->{var request=body();request.add("resources",rows);send("workResources",request);}));}
 @Override protected void init(){data=workspace.data();tasks=workspace.tasks();layout=UiTaskLayout.fit(width,height,!workspace.id().isEmpty(),editing);lines.clear();actions.clear();stageChecks.clear();stageMenus.clear();paragraphs.clear();resourceIcons.clear();resourceProgress.clear();
  if(!editing&&data.has("task")){var t=data.getAsJsonObject("task");boolean manage=MenuData.Task.read(t).manage();if(taskTab.equals("Обзор")){paragraph(Json.opt(t,"description",""));
   if(manage||Json.opt(t,"assignee","").equals(CommunityScreen.me()))row("Статус: "+status(t)+" ▾",()->minecraft.setScreen(new ChoicePopup(this,"Статус задачи",List.of("Открыта","В работе","Готово"),n->{var b=body();b.addProperty("status",List.of("open","working","done").get(n));send("workStatus",b);}).current(List.of("open","working","done").indexOf(Json.opt(t,"status","open")))));
   row("Ответственный: "+Json.opt(t,"assigneeName","Не назначен")+(manage?" ▾":""),manage?()->minecraft.setScreen(new ChoicePopup(this,"Ответственный",List.of("Выбрать участника","Снять назначение"),n->{if(n==1){var b=body();b.addProperty("assignee","");send("workAssign",b);}else if(group.isEmpty()){var b=body();b.addProperty("assignee",CommunityScreen.me());send("workAssign",b);}else minecraft.setScreen(new TaskMemberPicker(this,group,p->{var b=body();b.add("assignee",p.get("uuid"));send("workAssign",b);}));})):null);long due=t.has("dueAt")?t.get("dueAt").getAsLong():0;row((due==0?"Срок не задан":"Срок: "+CommunityScreen.local(due))+(manage?" ▾":""),manage?()->minecraft.setScreen(new ChoicePopup(this,"Срок задачи",List.of("Выбрать дату и время","Убрать срок"),n->{if(n==1){var b=body();b.addProperty("dueAt",0);send("workDue",b);}else minecraft.setScreen(new DateTimeScreen(this,"",v->{var b=body();b.addProperty("dueAt",java.time.LocalDateTime.parse(v,java.time.format.DateTimeFormatter.ofPattern("uuuu-MM-dd HH:mm")).atZone(AccessibilityScreen.zone()).toInstant().toEpochMilli());send("workDue",b);}));})):null);}if(planning()&&taskTab.equals("Обзор")){TaskPlanning.rows(this,t);}if(taskTab.equals("Этапы")){var stages=t.has("subtasks")?t.getAsJsonArray("subtasks"):new JsonArray();long done=java.util.stream.StreamSupport.stream(stages.spliterator(),false).filter(e->e.getAsJsonObject().get("done").getAsBoolean()).count();row(stages.isEmpty()?"Разбейте задачу на небольшие шаги":"На этой странице выполнено: "+done+" из "+stages.size(),null);int n=t.has("subtaskOffset")?t.get("subtaskOffset").getAsInt():0;for(var e:stages){int index=n++;var stage=e.getAsJsonObject();int line=lines.size();stageChecks.put(line,stage.get("done").getAsBoolean());row(Json.str(stage,"title"),manage||CommunityScreen.me().equals(Json.opt(stage,"assignee",""))?()->{var b=body();b.addProperty("index",index);send("workSubtask",b);}:null);if(manage)stageMenus.put(line,()->stageMenu(stage,index));}detailPages(t,"subtasks","subtaskOffset","subtaskCount");if(manage){boolean can=!t.has("canAddSubtask")||t.get("canAddSubtask").getAsBoolean();row(can?"Добавить этап…":"Достигнут лимит этапов: "+t.get("subtaskLimit"),can?()->textAction("Название этапа","title",100,"workSubtask"):null);}
   }if(taskTab.equals("Ресурсы")){row("Ресурсы",null);var counts=new HashMap<String,Long>();long confirmed=0;if(t.has("stocks"))for(var e:t.getAsJsonArray("stocks")){var stock=e.getAsJsonObject();confirmed=Math.max(confirmed,stock.has("at")?stock.get("at").getAsLong():0);if(stock.has("items"))for(var item:stock.getAsJsonObject("items").entrySet())counts.merge(item.getKey(),item.getValue().getAsLong(),Long::sum);}
   if(t.has("resources"))for(var res:ResourceRequirements.ordered(t.getAsJsonArray("resources"),Json.GSON.toJsonTree(counts).getAsJsonObject())){long have=ResourceRequirements.items(res).stream().mapToLong(item->counts.getOrDefault(item,0L)).sum(),need=res.get("amount").getAsLong();resourceProgress.put(lines.size(),Math.min(1,have/(double)Math.max(1,need)));resourceIcons.put(lines.size(),Json.str(res,"item"));row(TaskResourcesScreen.name(Json.str(res,"item"))+" · "+(have>=need?"Собрано":"Ещё "+(need-have))+" · "+have+" / "+need,null);}row(confirmed==0?"Склад ещё не проверен сервером":"Проверено: "+CommunityScreen.local(confirmed),null);if(manage){row("Изменить список ресурсов",this::resources);row("Как подключить сундук",()->minecraft.setScreen(new TaskStockSignScreen(this,data.getAsJsonObject("task").deepCopy())));}
   }if(planning()&&taskTab.equals("Ресурсы")){
   var pool=t.has("confirmedPool")?t.getAsJsonObject("confirmedPool"):new JsonObject();var used=t.has("reservedElsewhere")?t.getAsJsonObject("reservedElsewhere"):new JsonObject();var mine=t.has("reservations")?t.getAsJsonObject("reservations"):new JsonObject();
   row("Резерв общего запаса",null);if(t.has("resources"))for(var e:t.getAsJsonArray("resources")){var res=e.getAsJsonObject();String item=Json.str(res,"item");long total=ResourceRequirements.count(res,pool),others=ResourceRequirements.count(res,used),own=ResourceRequirements.count(res,mine);paragraph(TaskResourcesScreen.name(item)+": свободно "+Math.max(0,total-others-own)+", этой задаче "+own+", другим "+others);}
   paragraph("Резерв учитывается Rivet по последней проверке сервера. Предметы в сундуках остаются доступны игрокам.");
   if(manage)row(mine.size()>0?"Снять резерв":"Зарезервировать требуемые ресурсы",()->{var b=body();b.addProperty("release",mine.size()>0);send("workReserve",b);});
   }if(planning()&&taskTab.equals("История")){row("Последние изменения",null);var events=t.has("history")?t.getAsJsonArray("history"):new JsonArray();if(events.isEmpty())row("Изменений ещё нет",null);for(int i=events.size()-1;i>=0;i--){var event=events.get(i).getAsJsonObject();paragraph(CommunityScreen.local(event.get("at").getAsLong())+" · "+Json.str(event,"author")+"\n"+historyLabel(Json.str(event,"operation")));if(event.has("changes"))for(var c:event.getAsJsonArray("changes")){var change=c.getAsJsonObject();paragraph(Json.str(change,"label")+": "+ChangeSummary.text(change.get("before"))+" → "+ChangeSummary.text(change.get("after")));}}}
   if(taskTab.equals("Комментарии")){row("Комментарии",null);if(t.has("comments"))for(var e:t.getAsJsonArray("comments")){var c=e.getAsJsonObject();paragraph(Json.str(c,"author")+": "+Json.str(c,"text"));}detailPages(t,"comments","commentOffset","commentCount");boolean can=!t.has("canComment")||t.get("canComment").getAsBoolean();row(can?"+ Комментарий":"Достигнут лимит комментариев: "+t.get("commentLimit"),can?()->textAction("Комментарий","text",500,"workComment"):null);}
  }
  nav.build(group.isEmpty()?"tasks":"groups",this::addRenderableWidget);
  int lw=listWidth();if(layout.showList()){UiSearchToolbar.query(font,layout.search(),"Поиск задач",query,this::addRenderableWidget,v->{query=v;searchAt=System.currentTimeMillis()+500;},this::resetList,!editing&&!workspace.busy());
  addRenderableWidget(UiActions.button(Component.literal((statusFilter.isEmpty()?"Все":statusFilter.equals("working")?"В работе":statusFilter.equals("done")?"Готово":statusFilter.equals("archived")?"Архив":"Открыты")+" ▾"),UiActions.Tone.NORMAL,"",b->minecraft.setScreen(new ChoicePopup(this,"Показать задачи",List.of("Все","Открытые","В работе","Готовые","Архив"),n->{statusFilter=List.of("","open","working","done","archived").get(n);resetList();},b).current(List.of("","open","working","done","archived").indexOf(statusFilter)))).bounds(nav.left(),layout.filters().y(),lw-28,20).build()).active=!workspace.busy()&&!editing;addRenderableWidget(UiActions.button(Component.literal("×"),UiActions.Tone.NORMAL,"",b->{query="";statusFilter="";resetList();rebuildWidgets();}).bounds(nav.left()+lw-24,layout.filters().y(),24,20).tooltip(Tooltip.create(Component.literal("Сбросить поиск и фильтр задач"))).build()).active=!workspace.busy()&&!editing&&(!query.isBlank()||!statusFilter.isEmpty());var create=addRenderableWidget(UiActions.button(Component.literal("Новая задача"),UiActions.Tone.PRIMARY,UiIcons.PLUS,b->edit(null)).bounds(nav.left(),layout.create().y(),Math.min(Math.max(1,lw-28),134),20).build());create.active=!editing&&!workspace.busy()&&!workspace.retryAvailable()&&workspace.listLoaded()&&workspace.canCreate();if(ServerMenuClient.supports("task-archive")&&(group.isEmpty()||workspace.canManage()))addRenderableWidget(UiActions.button(Component.literal("⋯"),UiActions.Tone.NORMAL,"",b->minecraft.setScreen(new ChoicePopup(this,"Архивировать завершённые",List.of("Все завершённые","Завершены больше 7 дней назад","Завершены больше 30 дней назад"),n->minecraft.setScreen(new TaskArchiveScreen(this,group,List.of(0,7,30).get(n))),b))).bounds(nav.left()+lw-24,layout.create().y(),24,20).build()).active=!editing&&!workspace.busy();if(!create.active)create.setTooltip(Tooltip.create(Component.literal(editing?"Завершите редактирование задачи":workspace.busy()?"Дождитесь завершения текущего запроса":workspace.retryAvailable()?"Сначала повторите запрос к серверу":!workspace.listLoaded()?"Загрузка лимитов сервера":workspace.createReason())));
  int stride=Math.min(AccessibilityScreen.cardStride(),Math.max(30,layout.rows().height()));taskList.layout(tasks.size(),new dev.abros.rivet.core.NativeLayout.Box(nav.left(),layout.rows().y(),lw,Math.max(0,listBottom()-layout.rows().y())),stride);
  for(int n=taskList.first();n<Math.min(tasks.size(),taskList.first()+taskList.visible());n++){var task=tasks.get(n).getAsJsonObject();var card=task.deepCopy();card.addProperty("section","task");card.addProperty("attention",(Json.opt(task,"code","").isBlank()?"":Json.opt(task,"code","")+" · ")+status(task));card.addProperty("preview",Json.opt(task,"preview",Json.opt(task,"description",Json.opt(task,"assigneeName","Не назначен"))));long due=task.has("dueAt")?task.get("dueAt").getAsLong():0;card.addProperty("footer",(task.has("stagesTotal")&&task.get("stagesTotal").getAsInt()>0?"Этапы: "+task.get("stagesDone").getAsInt()+" / "+task.get("stagesTotal").getAsInt()+" · ":"")+(due>0?"До "+java.time.Instant.ofEpochMilli(due).atZone(AccessibilityScreen.zone()).format(java.time.format.DateTimeFormatter.ofPattern("dd.MM HH:mm")):"Без срока"));var widget=addRenderableWidget(new CommunityCard(nav.left(),layout.rows().y()+(n-taskList.first())*stride,taskList.geometry().content().width(),Math.min(stride-6,layout.rows().height()),card,()->select(task)));widget.selected=Json.str(task,"id").equals(workspace.id());widget.active=!workspace.busy()&&!editing;}
  }else taskList.layout(0,new dev.abros.rivet.core.NativeLayout.Box(nav.left(),layout.rows().y(),0,0),24);
  if(!editing&&data.has("task")){var t=data.getAsJsonObject("task");addRenderableWidget(UiActions.button(Component.literal("Действия ▾"),UiActions.Tone.NORMAL,"",b->taskActions(t,b)).bounds(x()+w()-92,top()+8,84,20).tooltip(Tooltip.create(Component.literal("Код задачи и дополнительные действия"))).build()).active=!workspace.busy();var tabs=planning()?List.of("Обзор","Этапы","Ресурсы","Комментарии","История"):List.of("Обзор","Этапы","Ресурсы","Комментарии");UiTabs.build(this,font,new dev.abros.rivet.core.NativeLayout.Box(x()+8,layout.tabs().y(),w()-16,20),tabs,tabs.indexOf(taskTab),this::addRenderableWidget,n->{taskTab=tabs.get(n);resetScroll();rebuildWidgets();},!workspace.busy());}

  scrollArea(editing?0:lines.size(),new dev.abros.rivet.core.NativeLayout.Box(x()+8,contentTop(),layout.showDetail()?Math.max(0,w()-16):0,layout.showDetail()?Math.max(0,(layout.body().bottom())-(contentTop())):0),24);for(int n=firstRow;n<Math.min(lines.size(),firstRow+visibleRows);n++){int y=contentTop()+(n-firstRow)*24;String rowLabel=lines.get(n);var action=actions.get(n);if(stageChecks.containsKey(n)){var check=addRenderableWidget(new UiChoiceRow(x()+8,y,w()-(stageMenus.containsKey(n)?54:24),rowLabel,stageChecks.get(n),-1,UiKit.ACCENT,()->{if(action!=null)action.run();}));check.active=action!=null&&!workspace.busy()&&!workspace.retryAvailable();if(stageMenus.containsKey(n)){var menu=stageMenus.get(n);addRenderableWidget(UiActions.button(Component.literal("⋯"),UiActions.Tone.NORMAL,"",b->{menu.run();if(minecraft.screen instanceof ChoicePopup popup)popup.attach(b);}).bounds(x()+w()-34,y,22,20).tooltip(Tooltip.create(Component.literal("Переименовать или удалить этап"))).build()).active=!workspace.busy()&&!workspace.retryAvailable();}}else if(action!=null){int bw=Math.min(w()-24,Math.max(80,Math.min(280,font.width(lines.get(n))+38)));var button=addRenderableWidget(UiActions.button(Component.literal(lines.get(n)),UiActions.Tone.NORMAL,"",b->{action.run();if(rowLabel.endsWith(" ▾")&&minecraft.screen instanceof ChoicePopup popup)popup.attach(b);}).bounds(x()+8,y,bw,20).build());if(font.width(lines.get(n))>bw-16)button.setTooltip(Tooltip.create(Component.literal(lines.get(n))));button.active=!workspace.busy()&&!workspace.retryAvailable();}}
  if(layout.showList()&&(!workspace.cursor().isEmpty()||!cursorNext().isEmpty()))addRenderableWidget(UiActions.button(Component.literal(cursorNext().isEmpty()?"К началу списка":"Следующая страница"),UiActions.Tone.NORMAL,"",b->{workspace.cursor(cursorNext());taskList.reset();list();}).bounds(nav.left(),layout.pagination().y(),Math.min(lw,150),20).build()).active=!workspace.busy();
  if(undoAvailable()&&!editing&&layout.status().width()>=72)addRenderableWidget(UiActions.button(Component.literal("Отменить"),UiActions.Tone.NORMAL,"",b->undoStatus()).bounds(layout.status().right()-72,layout.status().y(),72,20).build()).active=!workspace.busy();
  var footer=UiPageFooter.fit(layout.workspace().footer());if(workspace.retryAvailable())footer.start(UiActions.Command.RETRY,this::addRenderableWidget,()->{workspace.retry();rebuildWidgets();});else footer.start(!split()&&!workspace.id().isEmpty()?UiActions.Command.LIST:UiActions.Command.REFRESH,this::addRenderableWidget,()->{if(!split()&&!workspace.id().isEmpty()){workspace.clearSelection();resetScroll();rebuildWidgets();}else list();}).active=!workspace.busy()&&!editing;
  footer.end(UiActions.Command.CLOSE,this::addRenderableWidget,()->{workspace.close();ServerMenuClient.cancelReads(this);minecraft.setScreen(parent);}).active=!editing&&(!workspace.busy()||Set.of("workList","workGet").contains(workspace.operation()));if(editing){buildEditor();if(layout.showList())for(var child:children())if(child instanceof AbstractWidget widget&&layout.list().contains(widget.getX(),widget.getY()))widget.active=false;}if(!loaded){loaded=true;list();}
 }
 private String cursorNext(){return workspace.nextCursor();}
 private static String status(JsonObject t){return switch(MenuData.Task.read(t).status()){case "working"->"В работе";case "done"->"Готово";default->"Открыта";};}
 public void receiveCommunity(JsonObject reply){var result=workspace.receive(reply,split());if(!result.accepted())return;if(editing&&result.saved()){discardDraft();editing=false;draftError="";}if(result.conflict()&&!(minecraft.screen instanceof TaskEditScreen)&&!(minecraft.screen instanceof TaskResourcesScreen)){load();return;}if(result.changed())rebuildWidgets();if(result.loadDetail())load();}
 private void resetList(){if(editing)return;if(workspace.busy())return;if(!query.equals(listedQuery)||!statusFilter.equals(listedStatus)){workspace.clearSelection();taskTab="Обзор";resetScroll();}listedQuery=query;listedStatus=statusFilter;workspace.cursor("");searchAt=0;taskList.reset();list();}
 @Override public boolean keyPressed(int key,int scan,int modifiers){if((key==264||key==265)&&getFocused() instanceof CommunityCard focused){int at=-1;for(int n=0;n<tasks.size();n++)if(Json.str(tasks.get(n).getAsJsonObject(),"id").equals(focused.targetId())){at=n;break;}if(at>=0){int next=Math.max(0,Math.min(tasks.size()-1,at+(key==264?1:-1)));taskList.reveal(next);String target=Json.str(tasks.get(next).getAsJsonObject(),"id");rebuildWidgets();for(var c:children())if(c instanceof CommunityCard card&&card.targetId().equals(target)){setFocused(card);break;}return true;}}if(UiKeyboard.submit(this,key,modifiers)){if(editing)saveEdit();else if(getFocused() instanceof EditBox)resetList();return true;}return super.keyPressed(key,scan,modifiers);}
 @Override public void tick(){if(workspace.tick())rebuildWidgets();if(editing&&draftAt>0&&System.currentTimeMillis()>=draftAt)persistDraft();if(searchAt>0&&!editing&&!workspace.busy()&&!workspace.retryAvailable()&&System.currentTimeMillis()>=searchAt)resetList();if(!editing&&workspace.consumeDirty())list();}
 @Override public boolean mouseScrolled(double mx,double my,double dx,double dy){if(!editing&&nav.scroll(mx,my,dy)){rebuildWidgets();return true;}if(!editing&&layout.showList()&&mx>=layout.list().x()&&mx<layout.list().right()&&taskList.scroll(my,dy)){rebuildWidgets();return true;}return super.mouseScrolled(mx,my,dx,dy);}
 @Override public boolean mouseClicked(double mx,double my,int button){if(layout.showList()&&taskList.click(mx,my,button)){rebuildWidgets();return true;}return super.mouseClicked(mx,my,button);}
 @Override public boolean mouseDragged(double mx,double my,int button,double dx,double dy){if(taskList.drag(my,button)){rebuildWidgets();return true;}return super.mouseDragged(mx,my,button,dx,dy);}
 @Override public boolean mouseReleased(double mx,double my,int button){taskList.release();return super.mouseReleased(mx,my,button);}
 @Override public void renderBackground(GuiGraphics g,int mx,int my,float d){super.renderBackground(g,mx,my,d);if(layout().showDetail()){UiTheme.panel(g,x(),top(),w(),panelEnd()-top(),UiPalette.color(0xE81B252E));}}
 @Override public void render(GuiGraphics g,int mx,int my,float d){super.render(g,mx,my,d);layout.workspace().heading(g,font,title);nav.drawFrame(g);if(layout.showList())taskList.draw(g);if(layout.showList()&&tasks.isEmpty())UiState.draw(g,font,workspace.retryAvailable()?UiState.Kind.ERROR:workspace.busy()||!workspace.listLoaded()?UiState.Kind.LOADING:query.isBlank()&&statusFilter.isEmpty()?UiState.Kind.EMPTY:UiState.Kind.FILTERED,workspace.retryAvailable()?"Задачи недоступны":workspace.busy()||!workspace.listLoaded()?"Загружаем задачи…":query.isBlank()&&statusFilter.isEmpty()?"Начните с первой задачи":"Задачи не найдены",workspace.retryAvailable()?workspace.notice():workspace.busy()||!workspace.listLoaded()?"Получаем актуальный список с сервера.":query.isBlank()&&statusFilter.isEmpty()?"Нажмите «Новая задача» и добавьте первый шаг.":"Измените запрос или сбросьте фильтр кнопкой ×.",nav.left()+8,layout.rows().y()+8,listWidth()-16,listBottom());if(!editing&&data.has("task")){var task=data.getAsJsonObject("task");Ui.text(g,font,UiKit.fit(font,Json.str(task,"title"),w()-108),x()+12,top()+14,UiKit.text(),false);UiBadge.draw(g,font,Json.opt(task,"code","")+" · "+status(task),x()+12,top()+29,w()-24,Json.opt(task,"status","open").equals("done")?UiPalette.color(0xFF79CBA6):UiPalette.color(0xFFF0A77C));}if(!editing&&!data.has("task")&&split())UiEmptyState.draw(g,font,workspace.id().isEmpty()?"Ваш следующий шаг":"Открываем задачу…",workspace.id().isEmpty()?"Выберите карточку слева или создайте новую задачу.":"Получаем актуальные данные с сервера.",x()+12,top()+16,w()-24,top()+70);
  for(int n=firstRow;n<Math.min(lines.size(),firstRow+visibleRows);n++)if(actions.get(n)==null&&!stageChecks.containsKey(n)){int y=contentTop()+(n-firstRow)*24;if(paragraphs.containsKey(n)){int line=0;for(String text:paragraphs.get(n))Ui.text(g,font,text,x()+12,y+2+12*line++,UiKit.text(),false);continue;}String item=resourceIcons.get(n);if(item!=null)TaskResourcesScreen.icon(g,item,x()+8,y+2);Ui.text(g,font,font.plainSubstrByWidth(lines.get(n),w()-(item==null?24:44)),x()+(item==null?12:30),y+5,UiPalette.color(0xD7E2EC));if(resourceProgress.containsKey(n)){g.fill(x()+30,y+19,x()+w()-24,y+21,UiPalette.color(0xFF394651));g.fill(x()+30,y+19,x()+30+(int)((w()-54)*resourceProgress.get(n)),y+21,UiPalette.color(0xFF79CBA6));}}Ui.status(g,font,editing&&!draftError.isEmpty()?draftError:workspace.notice(),layout.status().x(),layout.status().y(),Math.max(0,layout.status().width()-(undoAvailable()&&!editing?80:0)),layout.status().bottom(),!draftError.isEmpty()?draftKind:workspace.retryAvailable()?UiFeedback.Kind.ERROR:workspace.notice().equals("Изменения сохранены")||workspace.notice().contains("отменено")?UiFeedback.Kind.SUCCESS:UiFeedback.Kind.INFO);if(editing){if(!titleIssue.isBlank())Ui.text(g,font,UiKit.fit(font,titleIssue,layout.body().width()-12),layout.body().x(),layout.body().y()+23,UiPalette.color(0xFFEF7777),false);Ui.text(g,font,draft.get("new").getAsBoolean()?"Новая задача":"Редактирование задачи",x()+8,top()+8,UiKit.text(),false);}}
 @Override public void onClose(){if(editing){cancelEdit();return;}if(!split()&&!workspace.id().isEmpty()){workspace.clearSelection();resetScroll();rebuildWidgets();return;}workspace.close();ServerMenuClient.cancelReads(this);minecraft.setScreen(parent);}
 @Override public boolean isPauseScreen(){return false;}
}
