package dev.abros.rivet.client;
import com.google.gson.*;
import dev.abros.rivet.core.*;
import net.minecraft.client.gui.GuiGraphics;
import net.minecraft.client.gui.components.*;
import net.minecraft.client.gui.screens.Screen;
import net.minecraft.network.chat.Component;
import java.util.*;
/** Task view; application state and request transitions live in TaskWorkspace. */
final class TaskScreen extends ScrollScreen implements CommunityScreen.Receiver {
 private final Screen parent;private final String group;private final TaskWorkspace workspace;private JsonObject data=new JsonObject();private JsonArray tasks=new JsonArray();private String taskTab=Client.text("ui.overview_39c63872");private boolean loaded;private String query="",statusFilter="",listedQuery="",listedStatus="";private long searchAt;private final MenuSidebar nav=new MenuSidebar(this);private final RowViewport taskList=new RowViewport();
 private UiFormDraft localDraft;private long draftAt,draftGeneration;
 private UiTaskLayout layout;private boolean editing;private JsonObject draft=new JsonObject(),draftOriginal=new JsonObject();private UiFeedback.Kind draftKind=UiFeedback.Kind.ERROR;private String draftError="",titleIssue="";
 @Override protected int scrollLeft(){return layout().body().x();}
 private UiTaskLayout layout(){return layout==null?UiTaskLayout.fit(width,height,!workspace.id().isEmpty(),editing):layout;}
 private final Map<Integer,Runnable> stageMenus=new HashMap<>();private final Map<Integer,List<String>> paragraphs=new HashMap<>();private final Map<Integer,Boolean> stageChecks=new HashMap<>();private final Map<Integer,Double> resourceProgress=new HashMap<>();private final Map<Integer,String> resourceIcons=new HashMap<>();private final List<String> lines=new ArrayList<>();private final List<Runnable> actions=new ArrayList<>();
 TaskScreen(Screen parent,String group,String initialId){super(Component.literal(group.isEmpty()?Client.text("ui.my_tasks_a47c14c1"):Client.text("ui.group_tasks_81191bd7")));this.parent=parent;this.group=group;this.workspace=new TaskWorkspace(group,initialId,ServerMenuClient::request,ServerMenuClient::cached,System::currentTimeMillis);}
 boolean matches(JsonObject reply){return workspace.matches(reply);}
 void cancelRead(){workspace.cancelRead();ServerMenuClient.cancelReads(this);}
 boolean pendingMutation(){return workspace.busy()&&!workspace.reading();}
 boolean leavePage(){if(editing){draftError=Client.text("ui.save_your_changes_or_select_cancel_1a2fae54");return false;}if(workspace.busy()&&!workspace.reading())return false;workspace.cancelRead();ServerMenuClient.cancelReads(this);return true;}
 boolean personal(){return group.isEmpty();}
 static boolean available(){return ServerMenuClient.module("tasks")&&ServerMenuClient.supports("task-tools");}
 private boolean split(){return layout().split();}
 private int listWidth(){return layout().list().width();}
 private int x(){return layout().detail().x();}private int w(){return layout().detail().width();}
 private int top(){return layout().detail().y();}private int panelEnd(){return layout().detail().bottom();}
 private int listBottom(){return layout().rows().bottom();}
 private int contentTop(){return layout().body().y();}
 private void list(){workspace.list(query,statusFilter);if(!workspace.listLoaded())rebuildWidgets();}
 private void select(JsonObject task){if(editing){draftError=Client.text("ui.save_your_changes_or_select_cancel_1a2fae54");return;}if(workspace.busy()&&workspace.reading())ServerMenuClient.cancelReads(this);if(!workspace.select(Json.str(task,"id")))return;taskTab=Client.text("ui.overview_39c63872");resetScroll();load();}
 String subscription(){return group.isEmpty()?"home|":"groups|"+group;}
 void invalidate(String section,String target){workspace.invalidate(section,target);}
 private JsonObject body(){return workspace.body();}
 private void send(String op,JsonObject body){workspace.send(op,body);if(!workspace.reading()||!workspace.listLoaded()||!workspace.id().isEmpty()&&!data.has("task"))rebuildWidgets();}
 private void load(){boolean cached=workspace.load();if(cached||!workspace.id().isEmpty()&&!data.has("task"))rebuildWidgets();}
 void row(String label,Runnable action){lines.add(label);actions.add(action);}
 void paragraph(String text){var wrapped=font.getSplitter().splitLines(text,w()-24,net.minecraft.network.chat.Style.EMPTY);for(int i=0;i<wrapped.size();i+=2){var pair=new ArrayList<String>();pair.add(wrapped.get(i).getString());if(i+1<wrapped.size())pair.add(wrapped.get(i+1).getString());paragraphs.put(lines.size(),pair);row("",null);}}
 dev.abros.rivet.core.ScrollLayout listGeometry(){return taskList.geometry();}
 private void stageMenu(JsonObject stage,int index){minecraft.setScreen(new ChoicePopup(this,Client.text("ui.step_73557e69"),List.of(Client.text("ui.rename_abd2de88"),Client.text("ui.delete_step_5a335e29")),choice->{if(choice==0){var preset=new JsonObject();preset.add("title",stage.get("title"));editor(Client.text("ui.step_name_19491d8e"),List.of(new CommunityScreen.Field("title",Client.text("map.name"),100)),preset,v->{var b=body();b.addProperty("index",index);b.add("title",v.get("title"));send("workSubtask",b);});}else minecraft.setScreen(new UiConfirmDialog(yes->{minecraft.setScreen(this);if(yes){var b=body();b.addProperty("index",index);b.addProperty("remove",true);send("workSubtask",b);}},Client.tr("ui.delete_step_bc782a06"),Component.literal(Json.str(stage,"title"))).dangerous());}));}
 private void editor(String title,List<CommunityScreen.Field> fields,JsonObject preset,java.util.function.Consumer<JsonObject> callback){minecraft.setScreen(new TaskEditScreen(this,title,fields,preset,callback));}
 private void edit(JsonObject t){if(workspace.busy())return;editing=true;draftError="";titleIssue="";draft=new JsonObject();draft.addProperty("title",t==null?"":Json.opt(t,"title",""));draft.addProperty("description",t==null?"":Json.opt(t,"description",""));draft.addProperty("new",t==null);draftOriginal=draft.deepCopy();long generation=++draftGeneration;localDraft=new UiFormDraft("task|"+group+"|"+(t==null?"new":workspace.id()));localDraft.restore(saved->{if(!editing||generation!=draftGeneration||!draft.equals(draftOriginal)||saved.isEmpty())return;for(String field:List.of("title","description"))if(saved.has(field))draft.add(field,saved.get(field));draftKind=UiFeedback.Kind.INFO;draftError=Client.text("ui.draft_restored_review_the_text_before_d948e5e7");rebuildWidgets();},message->{if(editing&&generation==draftGeneration)draftError=message;});rebuildWidgets();}
 private void discardDraft(){draftGeneration++;draftAt=0;if(localDraft!=null)localDraft.remove(workspace::notice);}
 private void changedDraft(){draftAt=System.currentTimeMillis()+600;}
 private void persistDraft(){if(localDraft==null)return;var fields=new JsonObject();for(String key:List.of("title","description"))fields.add(key,draft.get(key));localDraft.save(fields,message->{draftKind=UiFeedback.Kind.ERROR;draftError=message;});draftAt=0;}
 private void cancelEdit(){if(workspace.busy())return;if(draft.equals(draftOriginal)){discardDraft();editing=false;rebuildWidgets();return;}minecraft.setScreen(new UiConfirmDialog(yes->{minecraft.setScreen(this);if(yes){discardDraft();editing=false;draftError="";rebuildWidgets();}},Client.tr("ui.discard_changes_338fb3b7"),Client.tr("ui.the_text_you_entered_will_not_42577dde")));}
 private void saveEdit(){if(workspace.busy()||workspace.retryAvailable())return;if(Json.str(draft,"title").isBlank()){titleIssue=Client.text("ui.enter_a_task_name_4216525b");draftKind=UiFeedback.Kind.ERROR;draftError=titleIssue;rebuildWidgets();for(var child:children())if(child instanceof EditBox){setFocused(child);break;}return;}var b=body();if(draft.get("new").getAsBoolean()){b.remove("task");b.remove("revision");}b.add("title",draft.get("title"));b.add("description",draft.get("description"));persistDraft();var changes=ChangeSummary.between(draftOriginal,draft,new LinkedHashMap<>(Map.of("title",Client.text("map.name"),"description",Client.text("ui.description_f5441f6a"))));if(!draft.get("new").getAsBoolean()&&!changes.isEmpty())minecraft.setScreen(new ChangePreviewScreen(this,changes,()->send("workSave",b)));else send("workSave",b);}
 private void buildEditor(){
  var titleField=new UiTextForm.Field(Client.text("ui.task_name_3140460c"),Client.text("ui.task_name_3140460c"),100,Json.str(draft,"title"),v->{draft.addProperty("title",v);changedDraft();titleIssue="";draftError="";for(var child:children())if(child instanceof EditBox box)UiFields.issue(box,null);});
  var descriptionField=new UiTextForm.Field(Client.text("ui.task_description_bb133a5a"),Client.text("ui.what_needs_to_be_done_fb99b9f5"),1000,Json.str(draft,"description"),v->{draft.addProperty("description",v);changedDraft();});
  UiTextForm.compose(font,layout().body(),titleField,descriptionField,!workspace.busy(),!workspace.busy()&&!workspace.retryAvailable(),workspace.busy()?Client.text("ui.saving_73bfb5e4"):Client.text("map.tool.save"),this::saveEdit,this::cancelEdit,titleIssue).forEach(this::addRenderableWidget);
 }
 private void detailPages(JsonObject t,String array,String offsetKey,String countKey){if(!t.has(countKey)||!t.has(offsetKey))return;int offset=t.get(offsetKey).getAsInt(),count=t.get(countKey).getAsInt(),size=t.getAsJsonArray(array).size();if(count<=size)return;row(Client.text("ui.showing_0e94e2db")+(offset+1)+"–"+(offset+size)+Client.text("ui.of_6ce4fa39")+count,null);if(offset>0)row(Client.text("ui.previous_page_3289bfbc"),()->detailPage(offsetKey,Math.max(0,offset-20)));if(offset+size<count)row(Client.text("ui.next_page_ec0a643b"),()->detailPage(offsetKey,offset+size));}
 private void detailPage(String key,int offset){var b=body();b.addProperty(key,offset);send("workGet",b);firstRow=0;}
 private void textAction(String title,String key,int limit,String op){editor(title,List.of(new CommunityScreen.Field(key,title,limit)),new JsonObject(),v->{var b=body();b.add(key,v.get(key));send(op,b);});}
 private boolean planning(){return ServerMenuClient.supports("community-extensions");}
 private void editDependencies(JsonObject t){var codes=new ArrayList<String>();if(t.has("dependencyDetails"))for(var e:t.getAsJsonArray("dependencyDetails"))codes.add(Json.opt(e.getAsJsonObject(),"code",""));var preset=new JsonObject();preset.addProperty("codes",String.join(", ",codes));editor(Client.text("ui.blocking_task_codes_8ea47948"),List.of(new CommunityScreen.Field("codes",Client.text("ui.comma_separated_codes_leave_empty_to_7bed0bbf"),200)),preset,v->{var b=body();b.add("codes",v.get("codes"));send("workDependencies",b);});}
 private void editRepeat(JsonObject t){var intervals=List.of(0,1,7,30);minecraft.setScreen(new ChoicePopup(this,Client.text("ui.task_recurrence_b01c5be4"),List.of(Client.text("ui.do_not_repeat_39b20e76"),Client.text("ui.daily_37cd1561"),Client.text("ui.every_7_days_4cd9d058"),Client.text("ui.every_30_days_2e7891c2")),n->{var b=body();b.addProperty("days",intervals.get(n));send("workRepeat",b);}).current(intervals.indexOf(t.has("repeatDays")?t.get("repeatDays").getAsInt():0)));}
 private void taskActions(JsonObject t,AbstractWidget anchor){var labels=new ArrayList<String>();var run=new ArrayList<Runnable>();if(group.isEmpty()||minecraft.player!=null&&minecraft.player.getUUID().toString().equals(Json.opt(t,"assignee",""))){labels.add(HudSettings.INSTANCE.pin().equals(Json.str(t,"id"))?Client.text("ui.unpin_from_in_game_widget_bb4e8c74"):Client.text("ui.pin_to_in_game_widget_f132cb40"));run.add(()->HudSettings.INSTANCE.pin(HudSettings.INSTANCE.pin().equals(Json.str(t,"id"))?"":Json.str(t,"id")));}labels.add(Client.text("ui.copy_code_bc56422b"));run.add(()->{minecraft.keyboardHandler.setClipboard(Json.str(t,"code"));workspace.notice(Client.text("ui.code_copied_11338a19"));});boolean manage=MenuData.Task.read(t).manage();if(manage){if(t.has("archived")&&t.get("archived").getAsBoolean()){labels.add(Client.text("ui.restore_from_archive_a37228a4"));run.add(()->send("workRestore",body()));}labels.add(Client.text("ui.edit_task_d928b6f6"));run.add(()->edit(t));if(planning()){labels.add(Client.text("ui.dependencies_05123425"));run.add(()->editDependencies(t));labels.add(Client.text("ui.task_recurrence_95f267c3"));run.add(()->editRepeat(t));}labels.add(Client.text("ui.delete_task_fc5814bc"));run.add(()->minecraft.setScreen(new UiConfirmDialog(yes->{minecraft.setScreen(this);if(yes)send("workDelete",body());},Client.tr("ui.delete_task_04825a1a"),Client.tr("ui.steps_comments_and_storage_links_will_1186250f")).dangerous()));}if(undoAvailable()){labels.add(Client.text("ui.undo_last_status_change_347d9f21"));run.add(()->{undoStatus();});}var menu=new ChoicePopup(this,Client.text("ui.task_actions_d51cfd27"),labels,n->run.get(n).run(),anchor);if(manage)menu.danger(labels.indexOf(Client.text("ui.delete_task_fc5814bc")));minecraft.setScreen(menu);}
 private boolean undoAvailable(){return workspace.undoAvailable();}
 private void undoStatus(){workspace.undoStatus();rebuildWidgets();}
 private void taskLocation(JsonObject t,boolean manage){
  boolean located=t.has("location")&&t.get("location").isJsonObject();
  row(located?Client.text("ui.destination_235a51bb")+Json.opt(t.getAsJsonObject("location"),"name",""):Client.text("ui.no_destination_bc4cc30a"),null);
  if(located){var p=CommunityLocation.read(t.getAsJsonObject("location"));paragraph(p.x()+" "+p.y()+" "+p.z()+" · "+dev.abros.rivet.network.DimensionLabels.name(p.dimension()).getString());if(WorldMapClient.allowed()){row(Client.text("ui.show_on_map_86f399f2"),()->ClientMap.openLocation(this,p,false));row(Client.text("ui.navigate_to_destination_4e9fcde9"),()->{MapActivities.navigate(new MapLayerClient.Point(Json.str(t,"id"),p,false,false,"tasks",group,0));minecraft.setScreen(null);});}}
  var preset=located?t.getAsJsonObject("location").deepCopy():new JsonObject();if(!located){String name=Json.opt(t,"title","");preset.addProperty("name",name.substring(0,Math.min(80,name.length())));}
  if(manage)row(located?Client.text("ui.edit_destination_a44d3659"):Client.text("ui.add_destination_6d5d8983"),()->minecraft.setScreen(new LocationEditor(this,preset,false,p->{var b=body();b.add("location",p);send("workLocation",b);})));
 }
 private static String historyLabel(String op){return switch(op){case "workLocation"->Client.text("ui.destination_changed_d8fb0279");case "workSave"->Client.text("ui.name_and_description_changed_f3b2d647");case "workStatus"->Client.text("ui.status_changed_20adcbe4");case "workAssign"->Client.text("ui.assignee_changed_5385ee40");case "workDue"->Client.text("ui.deadline_changed_a60e1251");case "workSubtask"->Client.text("ui.step_changed_0e553667");case "workResources"->Client.text("ui.resources_changed_997addc5");case "workDependencies"->Client.text("ui.dependencies_changed_bac04dac");case "workReserve"->Client.text("ui.reservation_changed_5429118e");case "workRepeat"->Client.text("ui.recurrence_changed_87cb773a");case "workComment"->Client.text("ui.comment_added_7da34e93");default->Client.text("ui.task_changed_f94c78c8");};}
 private void resources(){var t=data.getAsJsonObject("task");minecraft.setScreen(new TaskResourcesScreen(this,t.has("resources")?t.getAsJsonArray("resources"):new JsonArray(),rows->{var request=body();request.add("resources",rows);send("workResources",request);}));}
 @Override protected void init(){data=workspace.data();tasks=workspace.tasks();layout=UiTaskLayout.fit(width,height,!workspace.id().isEmpty(),editing);lines.clear();actions.clear();stageChecks.clear();stageMenus.clear();paragraphs.clear();resourceIcons.clear();resourceProgress.clear();
  if(!editing&&data.has("task")){var t=data.getAsJsonObject("task");boolean manage=MenuData.Task.read(t).manage();if(taskTab.equals(Client.text("ui.overview_39c63872"))){paragraph(Json.opt(t,"description",""));
   if(manage||Json.opt(t,"assignee","").equals(CommunityScreen.me()))row(Client.text("ui.status_156979c7")+status(t)+" ▾",()->minecraft.setScreen(new ChoicePopup(this,Client.text("ui.task_status_7316eca9"),List.of(Client.text("ui.open_87c42edb"),Client.text("ui.in_progress_9db2ea4b"),Client.text("done")),n->{var b=body();b.addProperty("status",List.of("open","working","done").get(n));send("workStatus",b);}).current(List.of("open","working","done").indexOf(Json.opt(t,"status","open")))));
   row(Client.text("ui.assigned_to_31372c54")+Json.opt(t,"assigneeName",Client.text("ui.unassigned_ff9d739a"))+(manage?" ▾":""),manage?()->minecraft.setScreen(new ChoicePopup(this,Client.text("ui.assignee_46c1c6b4"),List.of(Client.text("ui.select_member_695fc228"),Client.text("ui.unassign_94b7e77a")),n->{if(n==1){var b=body();b.addProperty("assignee","");send("workAssign",b);}else if(group.isEmpty()){var b=body();b.addProperty("assignee",CommunityScreen.me());send("workAssign",b);}else minecraft.setScreen(new TaskMemberPicker(this,group,p->{var b=body();b.add("assignee",p.get("uuid"));send("workAssign",b);}));})):null);long due=t.has("dueAt")?t.get("dueAt").getAsLong():0;row((due==0?Client.text("ui.no_deadline_set_692b3e7e"):Client.text("ui.due_79fd6d0c")+CommunityScreen.local(due))+(manage?" ▾":""),manage?()->minecraft.setScreen(new ChoicePopup(this,Client.text("ui.task_deadline_1d20ff7e"),List.of(Client.text("ui.select_date_and_time_e9b09d70"),Client.text("ui.remove_deadline_66ab6197")),n->{if(n==1){var b=body();b.addProperty("dueAt",0);send("workDue",b);}else minecraft.setScreen(new DateTimeScreen(this,"",v->{var b=body();b.addProperty("dueAt",java.time.LocalDateTime.parse(v,java.time.format.DateTimeFormatter.ofPattern("uuuu-MM-dd HH:mm")).atZone(AccessibilityScreen.zone()).toInstant().toEpochMilli());send("workDue",b);}));})):null);}if(taskTab.equals(Client.text("ui.overview_39c63872"))&&ServerMenuClient.supports("map-activities")){taskLocation(t,manage);}if(planning()&&taskTab.equals(Client.text("ui.overview_39c63872"))){TaskPlanning.rows(this,t);}if(taskTab.equals(Client.text("ui.steps_9adda405"))){var stages=t.has("subtasks")?t.getAsJsonArray("subtasks"):new JsonArray();long done=java.util.stream.StreamSupport.stream(stages.spliterator(),false).filter(e->e.getAsJsonObject().get("done").getAsBoolean()).count();row(stages.isEmpty()?Client.text("ui.break_the_task_into_small_steps_16620760"):Client.text("ui.completed_on_this_page_7676faa4")+done+Client.text("ui.of_6ce4fa39")+stages.size(),null);int n=t.has("subtaskOffset")?t.get("subtaskOffset").getAsInt():0;for(var e:stages){int index=n++;var stage=e.getAsJsonObject();int line=lines.size();stageChecks.put(line,stage.get("done").getAsBoolean());row(Json.str(stage,"title"),manage||CommunityScreen.me().equals(Json.opt(stage,"assignee",""))?()->{var b=body();b.addProperty("index",index);send("workSubtask",b);}:null);if(manage)stageMenus.put(line,()->stageMenu(stage,index));}detailPages(t,"subtasks","subtaskOffset","subtaskCount");if(manage){boolean can=!t.has("canAddSubtask")||t.get("canAddSubtask").getAsBoolean();row(can?Client.text("ui.add_step_8aab7aaf"):Client.text("ui.step_limit_reached_5a9c24e5")+t.get("subtaskLimit"),can?()->textAction(Client.text("ui.step_name_19491d8e"),"title",100,"workSubtask"):null);}
   }if(taskTab.equals(Client.text("ui.resources_3e559b8c"))){row(Client.text("ui.resources_3e559b8c"),null);var counts=new HashMap<String,Long>();long confirmed=0;if(t.has("stocks"))for(var e:t.getAsJsonArray("stocks")){var stock=e.getAsJsonObject();confirmed=Math.max(confirmed,stock.has("at")?stock.get("at").getAsLong():0);if(stock.has("items"))for(var item:stock.getAsJsonObject("items").entrySet())counts.merge(item.getKey(),item.getValue().getAsLong(),Long::sum);}
   if(t.has("resources"))for(var res:ResourceRequirements.ordered(t.getAsJsonArray("resources"),Json.GSON.toJsonTree(counts).getAsJsonObject())){long have=ResourceRequirements.items(res).stream().mapToLong(item->counts.getOrDefault(item,0L)).sum(),need=res.get("amount").getAsLong();if(ServerMenuClient.module("storage"))resourceProgress.put(lines.size(),Math.min(1,have/(double)Math.max(1,need)));resourceIcons.put(lines.size(),Json.str(res,"item"));row(TaskResourcesScreen.name(Json.str(res,"item"))+" · "+(!ServerMenuClient.module("storage")?Client.text("ui.required_5b62c649")+need:(have>=need?Client.text("ui.collected_035cb21e"):Client.text("ui.more_279163c9")+(need-have))+" · "+have+" / "+need),null);}if(ServerMenuClient.module("storage"))row(confirmed==0?Client.text("ui.the_server_has_not_checked_this_eb373528"):Client.text("ui.checked_303fbbf7")+CommunityScreen.local(confirmed),null);if(manage){row(Client.text("ui.edit_resource_list_f1831a07"),this::resources);if(ServerMenuClient.module("storage"))row(Client.text("ui.how_to_link_a_chest_98879288"),()->minecraft.setScreen(new TaskStockSignScreen(this,data.getAsJsonObject("task").deepCopy())));}
   }if(planning()&&ServerMenuClient.module("storage")&&taskTab.equals(Client.text("ui.resources_3e559b8c"))){
   var pool=t.has("confirmedPool")?t.getAsJsonObject("confirmedPool"):new JsonObject();var used=t.has("reservedElsewhere")?t.getAsJsonObject("reservedElsewhere"):new JsonObject();var mine=t.has("reservations")?t.getAsJsonObject("reservations"):new JsonObject();
   row(Client.text("ui.shared_stock_reservation_7e125955"),null);if(t.has("resources"))for(var e:t.getAsJsonArray("resources")){var res=e.getAsJsonObject();String item=Json.str(res,"item");long total=ResourceRequirements.count(res,pool),others=ResourceRequirements.count(res,used),own=ResourceRequirements.count(res,mine);paragraph(TaskResourcesScreen.name(item)+Client.text("ui.available_799785ed")+Math.max(0,total-others-own)+Client.text("ui.this_task_1892ed41")+own+Client.text("ui.other_tasks_5a2a3c74")+others);}
   paragraph(Client.text("ui.rivet_tracks_reservations_using_the_latest_6b1d8a88"));
   if(manage&&ServerMenuClient.module("storage"))row(mine.size()>0?Client.text("ui.release_reservation_39ea7996"):Client.text("ui.reserve_required_resources_f8afe67d"),()->{var b=body();b.addProperty("release",mine.size()>0);send("workReserve",b);});
   }if(planning()&&taskTab.equals(Client.text("ui.history_d5fec747"))){row(Client.text("ui.recent_changes_9b6c1d4a"),null);var events=t.has("history")?t.getAsJsonArray("history"):new JsonArray();if(events.isEmpty())row(Client.text("ui.no_changes_yet_aed8c524"),null);for(int i=events.size()-1;i>=0;i--){var event=events.get(i).getAsJsonObject();paragraph(CommunityScreen.local(event.get("at").getAsLong())+" · "+Json.str(event,"author")+"\n"+historyLabel(Json.str(event,"operation")));if(event.has("changes"))for(var c:event.getAsJsonArray("changes")){var change=c.getAsJsonObject();paragraph(dev.abros.rivet.core.LocalizedText.render(change,"label")+": "+ChangeSummary.text(change.get("before"))+" → "+ChangeSummary.text(change.get("after")));}}}
   if(taskTab.equals(Client.text("ui.comments_5f090363"))){row(Client.text("ui.comments_5f090363"),null);if(t.has("comments"))for(var e:t.getAsJsonArray("comments")){var c=e.getAsJsonObject();paragraph(Json.str(c,"author")+": "+Json.str(c,"text"));}detailPages(t,"comments","commentOffset","commentCount");boolean can=!t.has("canComment")||t.get("canComment").getAsBoolean();row(can?Client.text("ui.comment_6d161474"):Client.text("ui.comment_limit_reached_991996cf")+t.get("commentLimit"),can?()->textAction(Client.text("ui.comment_829038c9"),"text",500,"workComment"):null);}
  }
  nav.build(group.isEmpty()?"tasks":"groups",this::addRenderableWidget);
  int lw=UiSearchToolbar.contentWidth(listWidth());if(layout.showList()){UiSearchToolbar.query(font,new dev.abros.rivet.core.NativeLayout.Box(layout.search().x(),layout.search().y(),lw,20),Client.text("ui.search_tasks_8f557a18"),query,this::addRenderableWidget,v->{query=v;searchAt=System.currentTimeMillis()+500;},this::resetList,!editing&&!workspace.busy());
  addRenderableWidget(UiActions.button(Component.literal((statusFilter.isEmpty()?Client.text("ui.all_fd08da7a"):statusFilter.equals("working")?Client.text("ui.in_progress_9db2ea4b"):statusFilter.equals("done")?Client.text("done"):statusFilter.equals("archived")?Client.text("ui.archive_3789b399"):Client.text("ui.open_89d58c50"))+" ▾"),UiActions.Tone.NORMAL,"",b->minecraft.setScreen(new ChoicePopup(this,Client.text("ui.show_tasks_eb818489"),List.of(Client.text("ui.all_fd08da7a"),Client.text("ui.open_75bcc804"),Client.text("ui.in_progress_9db2ea4b"),Client.text("ui.ready_19ca5443"),Client.text("ui.archive_3789b399")),n->{statusFilter=List.of("","open","working","done","archived").get(n);resetList();},b).current(List.of("","open","working","done","archived").indexOf(statusFilter)))).bounds(nav.left(),layout.filters().y(),lw-30,20).build()).active=!workspace.busy()&&!editing;addRenderableWidget(UiActions.button(Component.literal("×"),UiActions.Tone.NORMAL,"",b->{query="";statusFilter="";resetList();rebuildWidgets();}).bounds(nav.left()+lw-24,layout.filters().y(),24,20).tooltip(Tooltip.create(Client.tr("ui.reset_task_search_and_filter_9a553ce8"))).build()).active=!workspace.busy()&&!editing&&(!query.isBlank()||!statusFilter.isEmpty());var create=addRenderableWidget(UiActions.button(Client.tr("ui.new_task_bcfbe789"),UiActions.Tone.PRIMARY,UiIcons.PLUS,b->edit(null)).bounds(nav.left(),layout.create().y(),Math.max(1,lw-(ServerMenuClient.supports("task-archive")&&(group.isEmpty()||workspace.canManage())?30:0)),20).build());create.active=!editing&&!workspace.busy()&&!workspace.retryAvailable()&&workspace.listLoaded()&&workspace.canCreate();if(ServerMenuClient.supports("task-archive")&&(group.isEmpty()||workspace.canManage()))addRenderableWidget(UiActions.button(Component.literal("⋯"),UiActions.Tone.NORMAL,"",b->minecraft.setScreen(new ChoicePopup(this,Client.text("ui.archive_completed_2bf32742"),List.of(Client.text("ui.all_completed_e7de2a8f"),Client.text("ui.completed_over_7_days_ago_62e63e9f"),Client.text("ui.completed_over_30_days_ago_4434c872")),n->minecraft.setScreen(new TaskArchiveScreen(this,group,List.of(0,7,30).get(n))),b))).bounds(nav.left()+lw-24,layout.create().y(),24,20).tooltip(Tooltip.create(Client.tr("ui.archive_completed_tasks_86d16a2c"))).build()).active=!editing&&!workspace.busy();if(!create.active)create.setTooltip(Tooltip.create(Component.literal(editing?Client.text("ui.finish_editing_the_task_8173d8f7"):workspace.busy()?Client.text("ui.wait_for_the_current_request_to_93b8cf69"):workspace.retryAvailable()?Client.text("ui.retry_the_server_request_first_225a2a57"):!workspace.listLoaded()?Client.text("ui.loading_server_limits_4e6dab71"):workspace.createReason())));
  int stride=Math.min(AccessibilityScreen.cardStride(),Math.max(30,layout.rows().height()));taskList.layout(tasks.size(),new dev.abros.rivet.core.NativeLayout.Box(nav.left(),layout.rows().y(),listWidth(),Math.max(0,listBottom()-layout.rows().y())),stride);
  for(int n=taskList.first();n<Math.min(tasks.size(),taskList.first()+taskList.visible());n++){var task=tasks.get(n).getAsJsonObject();var card=task.deepCopy();card.addProperty("section","task");card.addProperty("attention",(Json.opt(task,"code","").isBlank()?"":Json.opt(task,"code","")+" · ")+status(task));card.addProperty("preview",Json.opt(task,"preview",Json.opt(task,"description",Json.opt(task,"assigneeName",Client.text("ui.unassigned_ff9d739a")))));long due=task.has("dueAt")?task.get("dueAt").getAsLong():0;card.addProperty("footer",(task.has("stagesTotal")&&task.get("stagesTotal").getAsInt()>0?Client.text("ui.steps_eb45e5ea")+task.get("stagesDone").getAsInt()+" / "+task.get("stagesTotal").getAsInt()+" · ":"")+(due>0?Client.text("ui.until_2c285a51")+java.time.Instant.ofEpochMilli(due).atZone(AccessibilityScreen.zone()).format(java.time.format.DateTimeFormatter.ofPattern("dd.MM HH:mm")):Client.text("ui.no_deadline_b07832d4")));var widget=addRenderableWidget(new CommunityCard(nav.left(),layout.rows().y()+(n-taskList.first())*stride,taskList.geometry().content().width(),Math.min(stride-6,layout.rows().height()),card,()->select(task)));widget.selected=Json.str(task,"id").equals(workspace.id());widget.active=!workspace.busy()&&!editing;}
  }else taskList.layout(0,new dev.abros.rivet.core.NativeLayout.Box(nav.left(),layout.rows().y(),0,0),24);
  if(!editing&&data.has("task")){var t=data.getAsJsonObject("task");addRenderableWidget(UiActions.button(Client.tr("ui.actions_928503bd"),UiActions.Tone.NORMAL,"",b->taskActions(t,b)).bounds(x()+w()-92,top()+8,84,20).tooltip(Tooltip.create(Client.tr("ui.task_code_and_additional_actions_198f55ce"))).build()).active=!workspace.busy();var tabs=planning()?List.of(Client.text("ui.overview_39c63872"),Client.text("ui.steps_9adda405"),Client.text("ui.resources_3e559b8c"),Client.text("ui.comments_5f090363"),Client.text("ui.history_d5fec747")):List.of(Client.text("ui.overview_39c63872"),Client.text("ui.steps_9adda405"),Client.text("ui.resources_3e559b8c"),Client.text("ui.comments_5f090363"));UiTabs.build(this,font,new dev.abros.rivet.core.NativeLayout.Box(x()+12,layout.tabs().y(),UiSearchToolbar.contentWidth(w()-24),20),tabs,tabs.indexOf(taskTab),this::addRenderableWidget,n->{taskTab=tabs.get(n);resetScroll();rebuildWidgets();},!workspace.busy());}

  scrollArea(editing?0:lines.size(),new dev.abros.rivet.core.NativeLayout.Box(x()+(editing?8:12),contentTop(),!editing&&layout.showDetail()?Math.max(0,w()-24):0,!editing&&layout.showDetail()?Math.max(0,(layout.body().bottom())-(contentTop())):0),24);for(int n=firstRow;n<Math.min(lines.size(),firstRow+visibleRows);n++){int y=contentTop()+(n-firstRow)*24;String rowLabel=lines.get(n);var action=actions.get(n);if(stageChecks.containsKey(n)){var check=addRenderableWidget(new UiChoiceRow(x()+12,y,UiSearchToolbar.contentWidth(w()-24)-(stageMenus.containsKey(n)?28:0),rowLabel,stageChecks.get(n),-1,UiKit.ACCENT,()->{if(action!=null)action.run();}));check.active=action!=null&&!workspace.busy()&&!workspace.retryAvailable();if(stageMenus.containsKey(n)){var menu=stageMenus.get(n);addRenderableWidget(UiActions.button(Component.literal("⋯"),UiActions.Tone.NORMAL,"",b->{menu.run();if(minecraft.screen instanceof ChoicePopup popup)popup.attach(b);}).bounds(x()+w()-44,y,22,20).tooltip(Tooltip.create(Client.tr("ui.rename_or_delete_step_526a7d8e"))).build()).active=!workspace.busy()&&!workspace.retryAvailable();}}else if(action!=null){int bw=Math.max(1,scrollLayout().content().width());var button=addRenderableWidget(UiActions.button(Component.literal(lines.get(n)),UiActions.Tone.NORMAL,"",b->{action.run();if(rowLabel.endsWith(" ▾")&&minecraft.screen instanceof ChoicePopup popup)popup.attach(b);}).bounds(x()+12,y,bw,20).build());if(font.width(lines.get(n))>bw-16)button.setTooltip(Tooltip.create(Component.literal(lines.get(n))));button.active=!workspace.busy()&&!workspace.retryAvailable();}}
  if(layout.showList()&&(!workspace.cursor().isEmpty()||!cursorNext().isEmpty()))addRenderableWidget(UiActions.button(Component.literal(cursorNext().isEmpty()?Client.text("ui.top_of_list_a28e0e21"):Client.text("ui.next_page_881773b9")),UiActions.Tone.NORMAL,"",b->{workspace.cursor(cursorNext());taskList.reset();list();}).bounds(nav.left(),layout.pagination().y(),Math.min(lw,150),20).build()).active=!workspace.busy();
  if(undoAvailable()&&!editing&&layout.status().width()>=72)addRenderableWidget(UiActions.button(Client.tr("ui.cancel_555ad1c0"),UiActions.Tone.NORMAL,"",b->undoStatus()).bounds(layout.status().right()-72,layout.status().y(),72,20).build()).active=!workspace.busy();
  var footer=UiPageFooter.fit(layout.workspace().footer());if(workspace.retryAvailable())footer.start(UiActions.Command.RETRY,this::addRenderableWidget,()->{workspace.retry();rebuildWidgets();});else footer.start(!split()&&!workspace.id().isEmpty()?UiActions.Command.LIST:UiActions.Command.REFRESH,this::addRenderableWidget,()->{if(!split()&&!workspace.id().isEmpty()){workspace.clearSelection();resetScroll();rebuildWidgets();}else list();}).active=!workspace.busy()&&!editing;
  footer.end(editing||!split()&&!workspace.id().isEmpty()?UiActions.Command.BACK:UiNavigation.exitCommand(this,parent),this::addRenderableWidget,this::onClose).active=!editing&&(!workspace.busy()||Set.of("workList","workGet").contains(workspace.operation()));if(editing){buildEditor();if(layout.showList())for(var child:children())if(child instanceof AbstractWidget widget&&layout.list().contains(widget.getX(),widget.getY()))widget.active=false;}if(!loaded){loaded=true;list();}
 }
 private String cursorNext(){return workspace.nextCursor();}
 private static String status(JsonObject t){return switch(MenuData.Task.read(t).status()){case "working"->Client.text("ui.in_progress_9db2ea4b");case "done"->Client.text("done");default->Client.text("ui.open_87c42edb");};}
 public void receiveCommunity(JsonObject reply){var result=workspace.receive(reply,split());if(!result.accepted())return;if(editing&&result.saved()){discardDraft();editing=false;draftError="";}if(result.conflict()&&!(minecraft.screen instanceof TaskEditScreen)&&!(minecraft.screen instanceof TaskResourcesScreen)){load();return;}if(result.changed())rebuildWidgets();if(result.loadDetail())load();}
 private void resetList(){if(editing)return;if(workspace.busy())return;if(!query.equals(listedQuery)||!statusFilter.equals(listedStatus)){workspace.clearSelection();taskTab=Client.text("ui.overview_39c63872");resetScroll();}listedQuery=query;listedStatus=statusFilter;workspace.cursor("");searchAt=0;taskList.reset();list();}
 @Override public boolean keyPressed(int key,int scan,int modifiers){if((key==264||key==265)&&getFocused() instanceof CommunityCard focused){int at=-1;for(int n=0;n<tasks.size();n++)if(Json.str(tasks.get(n).getAsJsonObject(),"id").equals(focused.targetId())){at=n;break;}if(at>=0){int next=Math.max(0,Math.min(tasks.size()-1,at+(key==264?1:-1)));taskList.reveal(next);String target=Json.str(tasks.get(next).getAsJsonObject(),"id");rebuildWidgets();for(var c:children())if(c instanceof CommunityCard card&&card.targetId().equals(target)){setFocused(card);break;}return true;}}if(UiKeyboard.submit(this,key,modifiers)){if(editing)saveEdit();else if(getFocused() instanceof EditBox)resetList();return true;}return super.keyPressed(key,scan,modifiers);}
 @Override public void tick(){if(workspace.tick())rebuildWidgets();if(editing&&draftAt>0&&System.currentTimeMillis()>=draftAt)persistDraft();if(searchAt>0&&!editing&&!workspace.busy()&&!workspace.retryAvailable()&&System.currentTimeMillis()>=searchAt)resetList();if(!editing&&workspace.consumeDirty())list();}
 @Override public boolean mouseScrolled(double mx,double my,double dx,double dy){if(!editing&&nav.scroll(mx,my,dy)){rebuildWidgets();return true;}if(!editing&&layout.showList()&&mx>=layout.list().x()&&mx<layout.list().right()&&taskList.scroll(my,dy)){rebuildWidgets();return true;}return super.mouseScrolled(mx,my,dx,dy);}
 @Override public boolean mouseClicked(double mx,double my,int button){if(layout.showList()&&taskList.click(mx,my,button)){rebuildWidgets();return true;}return super.mouseClicked(mx,my,button);}
 @Override public boolean mouseDragged(double mx,double my,int button,double dx,double dy){if(taskList.drag(my,button)){rebuildWidgets();return true;}return super.mouseDragged(mx,my,button,dx,dy);}
 @Override public boolean mouseReleased(double mx,double my,int button){taskList.release();return super.mouseReleased(mx,my,button);}
 @Override public void renderBackground(GuiGraphics g,int mx,int my,float d){super.renderBackground(g,mx,my,d);if(layout().showDetail()){UiTheme.panel(g,x(),top(),w(),panelEnd()-top(),UiPalette.color(0xE81B252E));}}
 @Override public void render(GuiGraphics g,int mx,int my,float d){super.render(g,mx,my,d);layout.workspace().heading(g,font,title);nav.drawFrame(g);if(layout.showList())taskList.draw(g);if(layout.showList()&&tasks.isEmpty())UiState.draw(g,font,workspace.retryAvailable()?UiState.Kind.ERROR:workspace.busy()||!workspace.listLoaded()?UiState.Kind.LOADING:query.isBlank()&&statusFilter.isEmpty()?UiState.Kind.EMPTY:UiState.Kind.FILTERED,workspace.retryAvailable()?Client.text("ui.tasks_unavailable_f20a8c6d"):workspace.busy()||!workspace.listLoaded()?Client.text("ui.loading_tasks_def1e393"):query.isBlank()&&statusFilter.isEmpty()?Client.text("ui.start_with_your_first_task_c6086288"):Client.text("ui.no_tasks_found_b0fe8d0a"),workspace.retryAvailable()?workspace.notice():workspace.busy()||!workspace.listLoaded()?Client.text("ui.fetching_the_current_list_from_the_16b68aa6"):query.isBlank()&&statusFilter.isEmpty()?Client.text("ui.select_new_task_and_add_the_d39b14fc"):Client.text("ui.change_your_search_or_reset_the_13f7fe08"),nav.left()+8,layout.rows().y()+8,listWidth()-16,listBottom());if(!editing&&data.has("task")){var task=data.getAsJsonObject("task");Ui.text(g,font,UiKit.fit(font,Json.str(task,"title"),w()-108),x()+12,top()+14,UiKit.text(),false);UiBadge.draw(g,font,Json.opt(task,"code","")+" · "+status(task),x()+12,top()+29,w()-24,Json.opt(task,"status","open").equals("done")?UiPalette.color(0xFF79CBA6):UiPalette.color(0xFFF0A77C));}if(!editing&&!data.has("task")&&split())UiEmptyState.draw(g,font,workspace.id().isEmpty()?Client.text("ui.your_next_step_d298f8c1"):Client.text("ui.opening_task_79bf7205"),workspace.id().isEmpty()?Client.text("ui.select_a_card_on_the_left_fd82d1cb"):Client.text("ui.fetching_current_data_from_the_server_1e212f93"),x()+12,top()+16,w()-24,top()+70);
  for(int n=firstRow;n<Math.min(lines.size(),firstRow+visibleRows);n++)if(actions.get(n)==null&&!stageChecks.containsKey(n)){int y=contentTop()+(n-firstRow)*24;if(paragraphs.containsKey(n)){int line=0;for(String text:paragraphs.get(n))Ui.text(g,font,text,x()+12,y+2+12*line++,UiKit.text(),false);continue;}String item=resourceIcons.get(n);if(item!=null)TaskResourcesScreen.icon(g,item,x()+8,y+2);Ui.text(g,font,font.plainSubstrByWidth(lines.get(n),w()-(item==null?24:44)),x()+(item==null?12:30),y+5,UiPalette.color(0xD7E2EC));if(resourceProgress.containsKey(n)){g.fill(x()+30,y+19,x()+w()-24,y+21,UiPalette.color(0xFF394651));g.fill(x()+30,y+19,x()+30+(int)((w()-54)*resourceProgress.get(n)),y+21,UiPalette.color(0xFF79CBA6));}}Ui.status(g,font,editing&&!draftError.isEmpty()?draftError:workspace.notice(),layout.status().x(),layout.status().y(),Math.max(0,layout.status().width()-(undoAvailable()&&!editing?80:0)),layout.status().bottom(),!draftError.isEmpty()?draftKind:workspace.retryAvailable()?UiFeedback.Kind.ERROR:workspace.notice().equals(Client.text("ui.changes_saved_9bf756bd"))||workspace.notice().contains(Client.text("ui.cancelled_47a5c88a"))?UiFeedback.Kind.SUCCESS:UiFeedback.Kind.INFO);if(editing){if(!titleIssue.isBlank())Ui.text(g,font,UiKit.fit(font,titleIssue,layout.body().width()-12),layout.body().x(),layout.body().y()+23,UiPalette.color(0xFFEF7777),false);Ui.text(g,font,draft.get("new").getAsBoolean()?Client.text("ui.new_task_bcfbe789"):Client.text("ui.editing_task_b24221bb"),x()+8,top()+8,UiKit.text(),false);}}
 @Override public void onClose(){if(workspace.busy()&&!workspace.reading())return;if(editing){cancelEdit();return;}if(!split()&&!workspace.id().isEmpty()){workspace.clearSelection();resetScroll();rebuildWidgets();return;}workspace.close();ServerMenuClient.cancelReads(this);UiNavigation.back(this,parent);}
 @Override public boolean isPauseScreen(){return false;}
}
