package dev.abros.rivet.client;
import net.minecraft.client.gui.GuiGraphics;
import net.minecraft.client.gui.components.Button;
import net.minecraft.client.gui.screens.Screen;
import net.minecraft.network.chat.Component;
/** Internal component catalogue; enabled only by the developer UI harness. */
final class UiKitShowcaseScreen extends ScrollScreen {
 private final Screen parent;private boolean checked=true;
 UiKitShowcaseScreen(Screen parent){super(Component.literal("UI Kit · компоненты"));this.parent=parent;}
 private int x(){return (width-Math.min(400,width-32))/2;}private int w(){return Math.min(400,width-32);}
 @Override protected void init(){scrollArea(12,new dev.abros.rivet.core.NativeLayout.Box(x(),52,Math.max(0,w()),Math.max(0,(height-42)-(52))),38);for(int n=firstRow;n<Math.min(12,firstRow+visibleRows);n++){int y=52+(n-firstRow)*38;switch(n){case 0->addRenderableWidget(UiActions.button(Component.literal("Тема: "+UiPalette.name()+" ▾"),UiActions.Tone.NORMAL,"",b->minecraft.setScreen(new ChoicePopup(this,"Тема",UiPalette.names(),i->{UiPalette.preview(i);rebuildWidgets();},b))).bounds(x(),y,w()-14,24).build());case 1->addRenderableWidget(new UiChoiceRow(x(),y,w()-14,"Единая отметка · этап / голос / выбор",checked,0.7,UiKit.ACCENT,()->{checked=!checked;rebuildWidgets();}));case 2->addRenderableWidget(new UiToggle("Переключатель",x(),y,w()-14,checked,()->{checked=!checked;rebuildWidgets();}));case 3->{var b=addRenderableWidget(UiActions.button(Component.literal("Недоступное действие"),UiActions.Tone.NORMAL,"",v->{}).bounds(x(),y,w()-14,24).build());b.active=false;}case 4->addRenderableWidget(UiFields.text(font,x(),y,w()-14,24,Component.literal("Поиск")));case 5->{var b=UiFields.multiline(font,x(),y,w()-22,30,Component.literal("Описание"),Component.literal("Описание"));b.setValue("Редактируемый текст и перенос строки");addRenderableWidget(b);}case 6->addRenderableWidget(UiActions.button(Component.literal("+ Создать"),UiActions.Tone.PRIMARY,UiIcons.PLUS,b->{}).bounds(x(),y,130,24).build());case 8->addRenderableWidget(UiActions.button(Component.literal("Сохранить"),UiActions.Tone.PRIMARY,UiIcons.SAVE,button->{}).bounds(x(),y,130,24).build());case 9->UiFields.issue(addRenderableWidget(UiFields.text(font,x(),y,w()-14,24,Component.literal("Ошибка поля"))),"Проверьте значение");case 10->addRenderableWidget(UiActions.button(Component.literal("Пустой список"),UiActions.Tone.NORMAL,"",button->minecraft.setScreen(new TextScreen(this,Component.literal("Пустой список"),"Здесь появятся записи после создания."))).bounds(x(),y,w()-14,24).build());case 11->addRenderableWidget(UiActions.button(Component.literal("Загрузка / ошибка / фокус"),UiActions.Tone.NORMAL,"",button->minecraft.setScreen(new UiStatesShowcase(this))).bounds(x(),y,w()-14,24).build());case 7->addRenderableWidget(UiActions.button(Component.literal("Удалить…"),UiActions.Tone.DANGER,UiIcons.DELETE,b->{}).bounds(x(),y,130,24).build());}}UiActions.close(new dev.abros.rivet.core.NativeLayout.Box(x(),height-28,w()-14,20),this::addRenderableWidget,this::onClose);}
 @Override public void renderBackground(GuiGraphics g,int x,int y,float d){UiDialog.draw(g,width,w()+24,8,height-8);}
 @Override public void render(GuiGraphics g,int x,int y,float d){UiDialog.render(parent,this,g,d,()->{super.render(g,x,y,d);UiHeading.dialog(g,font,title,x(),12,w());});}
 @Override public void onClose(){minecraft.setScreen(parent);}
}
