package dev.abros.rivet.core;
import com.google.gson.*;
import java.util.*;
/** Shared personal/group tasks. All reads authorize against current group membership. */
public final class CommunityTasks {
 private final PgDatabase db;private final CommunityStore store;
 public CommunityTasks(PgDatabase db,CommunityStore store){this.db=db;this.store=store;}
 private static void require(boolean ok){if(!ok)throw new CommunityFailure(CommunityFailure.Code.FORBIDDEN,"Задача недоступна");}
 private static String text(JsonObject j,String k,int max){String s=Json.opt(j,k,"").strip();if(s.length()>max||s.codePoints().anyMatch(c->Character.isISOControl(c)&&c!='\n'))throw new IllegalArgumentException("Некорректное поле: "+k);return s;}
 public String code(String id)throws Exception{try(var q=db.connection().prepareStatement("SELECT code FROM community_task_codes WHERE task_id=?")){q.setString(1,id);try(var rs=q.executeQuery()){if(rs.next())return rs.getString(1);}}long n;try(var q=db.connection().createStatement();var rs=q.executeQuery("SELECT nextval('community_task_code_sequence')")){rs.next();n=rs.getLong(1);}String code=TaskCodes.encode(n);try(var q=db.connection().prepareStatement("INSERT INTO community_task_codes VALUES(?,?) ON CONFLICT(task_id) DO NOTHING")){q.setString(1,id);q.setString(2,code);q.executeUpdate();}try(var q=db.connection().prepareStatement("SELECT code FROM community_task_codes WHERE task_id=?")){q.setString(1,id);try(var rs=q.executeQuery()){rs.next();return rs.getString(1);}}}
 JsonObject task(String id,boolean lock)throws Exception{try(var q=db.connection().prepareStatement("SELECT body,group_id,owner,revision FROM community_group_items WHERE id=? AND kind='task'"+(lock?" FOR UPDATE":""))){q.setString(1,id);try(var rs=q.executeQuery()){if(!rs.next())throw new CommunityFailure(CommunityFailure.Code.NOT_FOUND,"Задача не найдена");var j=Json.parse(rs.getString(1));j.addProperty("id",id);j.addProperty("group",Objects.toString(rs.getString(2),""));j.addProperty("owner",Objects.toString(rs.getString(3),""));j.addProperty("revision",rs.getLong(4));return j;}}}
 boolean access(CommunityStore.Actor a,JsonObject t,boolean manage)throws Exception{String group=Json.opt(t,"group","");if(group.isEmpty())return Json.opt(t,"owner","").equals(a.id());var g=store.get(group);if(!Json.str(g,"status").equals("open"))return false;return manage?store.manager(g,a):a.admin()||g.getAsJsonObject("members").has(a.id());}
 void save(JsonObject t)throws Exception{String id=Json.str(t,"id"),group=Json.opt(t,"group","");var body=t.deepCopy();body.remove("code");body.remove("stocks");long rev=t.get("revision").getAsLong()+1;try(var q=db.connection().prepareStatement("INSERT INTO community_group_items(id,group_id,kind,body,revision,owner) VALUES(?,?,'task',?::jsonb,?,?) ON CONFLICT(id) DO UPDATE SET body=excluded.body,revision=excluded.revision")){q.setString(1,id);q.setString(2,group.isEmpty()?null:group);q.setString(3,body.toString());q.setLong(4,rev);q.setString(5,Json.str(t,"owner"));q.executeUpdate();}t.addProperty("revision",rev);code(id);CommunityOutbox.add(db,group.isEmpty()?"home":"groups",group,audience(t));}
 private String audience(JsonObject t){return Json.opt(t,"group","").isEmpty()?Json.str(t,"owner"):"";}
 JsonObject enrich(JsonObject t)throws Exception{
  t.addProperty("code",code(Json.str(t,"id")));String group=Json.opt(t,"group","");t.addProperty("stockLabel",group.isEmpty()?store.personName(Json.str(t,"owner")):Json.str(store.get(group),"title"));if(!Json.opt(t,"assignee","").isEmpty())t.addProperty("assigneeName",store.personName(Json.str(t,"assignee")));var totals=new JsonObject();long confirmed=0;int containers=0;var inventories=new HashSet<String>();var wanted=new HashSet<String>();if(t.has("resources"))for(var e:t.getAsJsonArray("resources"))wanted.addAll(ResourceRequirements.items(e.getAsJsonObject()));
  try(var q=db.connection().prepareStatement("SELECT body FROM community_task_stocks WHERE task_id=? ORDER BY location LIMIT 64")){q.setString(1,Json.str(t,"id"));try(var rs=q.executeQuery()){while(rs.next()){var stock=Json.parse(rs.getString(1));if(!inventories.add(Json.opt(stock,"inventory",UUID.randomUUID().toString())))continue;containers++;long at=stock.has("at")?stock.get("at").getAsLong():0;confirmed=confirmed==0?at:Math.min(confirmed,at);if(stock.has("items"))for(String item:wanted){long count=stock.getAsJsonObject("items").has(item)?stock.getAsJsonObject("items").get(item).getAsLong():0;totals.addProperty(item,(totals.has(item)?totals.get(item).getAsLong():0)+count);}}}
  }
  var summary=new JsonObject();summary.add("items",totals);summary.addProperty("at",confirmed);summary.addProperty("containers",containers);var stocks=new JsonArray();stocks.add(summary);t.add("stocks",stocks);
  var workflow=new TaskWorkflow(db,store);t.add("dependencyDetails",workflow.dependencies(t));t.add("confirmedPool",workflow.stock(t));t.add("reservedElsewhere",workflow.reserved(t));
  if(t.has("history")){var all=t.getAsJsonArray("history");var recent=new JsonArray();for(int n=Math.max(0,all.size()-10);n<all.size();n++)recent.add(all.get(n));t.add("history",recent);}
  if(t.has("comments")){var all=t.getAsJsonArray("comments");var recent=new JsonArray();for(int n=Math.max(0,all.size()-20);n<all.size();n++)recent.add(all.get(n));t.addProperty("commentCount",all.size());t.add("comments",recent);}return t;
 }
 public JsonObject request(CommunityStore.Actor a,JsonObject in)throws Exception{
  String op=Json.str(in,"op"),id=Json.opt(in,"task","");var out=new JsonObject();out.addProperty("kind","community");out.addProperty("section","home");out.addProperty("request",Json.opt(in,"request",""));if(!Set.of("workList","workGet","workMembers","workArchivePreview").contains(op)){db.lock("task-workflow");db.lock("tasks:"+a.id());}
  if(op.startsWith("workArchive"))return TaskArchive.request(db,this,a,in);
  if(op.equals("workMembers")){String group=text(in,"group",100),query=text(in,"query",32),cursor=text(in,"cursor",100);var probe=new JsonObject();probe.addProperty("group",group);require(!group.isEmpty()&&access(a,probe,true));var rows=new JsonArray();try(var q=db.connection().prepareStatement("SELECT p.id,p.name FROM people p JOIN community_relations r ON r.actor=p.id WHERE r.document=? AND r.kind='members' AND strpos(lower(p.name),lower(?))>0 AND p.id>? ORDER BY p.id LIMIT 21")){q.setString(1,group);q.setString(2,query);q.setString(3,cursor);try(var rs=q.executeQuery()){while(rs.next()){if(rows.size()==20){out.addProperty("nextCursor",Json.str(rows.get(19).getAsJsonObject(),"uuid"));break;}var row=new JsonObject();row.addProperty("uuid",rs.getString(1));row.addProperty("name",rs.getString(2));rows.add(row);}}}out.add("members",rows);return out;}
  if(op.equals("workList")){String group=text(in,"group",100),cursor=text(in,"cursor",100),query=text(in,"query",100),status=text(in,"status",16);if(!Set.of("","open","working","done","archived").contains(status))throw new IllegalArgumentException("Некорректный статус задачи");if(!cursor.isEmpty())UUID.fromString(cursor);if(!group.isEmpty()){var probe=new JsonObject();probe.addProperty("group",group);require(access(a,probe,false));}var rows=new JsonArray();try(var q=db.connection().prepareStatement("SELECT id,body,revision,owner,c.code FROM community_group_items LEFT JOIN community_task_codes c ON c.task_id=id WHERE kind='task' AND ((?='' AND group_id IS NULL AND owner=?) OR group_id=?) AND id>? AND ((?='archived' AND body->>'archived'='true') OR (coalesce(body->>'archived','false')<>'true' AND (?='' OR body->>'status'=?))) AND strpos(lower(coalesce(body->>'title','') || ' ' || coalesce(body->>'description','') || ' ' || coalesce(c.code,'')),lower(?))>0 ORDER BY id LIMIT 21")){q.setString(1,group);q.setString(2,a.id());q.setString(3,group);q.setString(4,cursor);q.setString(5,status);q.setString(6,status);q.setString(7,status);q.setString(8,query);try(var rs=q.executeQuery()){while(rs.next()){if(rows.size()==20){out.addProperty("nextCursor",Json.str(rows.get(19).getAsJsonObject(),"id"));break;}var t=Json.parse(rs.getString(2));String taskId=rs.getString(1);t.addProperty("id",taskId);t.addProperty("code",rs.getString(5)==null?code(taskId):rs.getString(5));t.addProperty("group",group);t.addProperty("owner",rs.getString(4));t.addProperty("revision",rs.getLong(3));int total=t.has("subtasks")?t.getAsJsonArray("subtasks").size():0,done=0;if(t.has("subtasks"))for(var stage:t.getAsJsonArray("subtasks"))if(stage.getAsJsonObject().get("done").getAsBoolean())done++;t.addProperty("stagesTotal",total);t.addProperty("stagesDone",done);t.addProperty("resourceTypes",t.has("resources")?t.getAsJsonArray("resources").size():0);String preview=Json.opt(t,"description","");t.addProperty("preview",preview.substring(0,preview.offsetByCodePoints(0,Math.min(160,preview.codePointCount(0,preview.length())))));for(String key:List.of("comments","subtasks","resources","stocks","description","history","dependencies","reservations"))t.remove(key);rows.add(t);}}}out.add("tasks",rows);var permissions=new JsonObject();permissions.addProperty("group",group);out.addProperty("canCreate",group.isEmpty()||access(a,permissions,true));return out;}
  JsonObject t;if(op.equals("workSave")&&id.isEmpty()){t=new JsonObject();t.addProperty("id",UUID.randomUUID().toString());t.addProperty("group",text(in,"group",100));t.addProperty("owner",a.id());t.addProperty("kind","task");t.addProperty("status","open");t.addProperty("dueAt",0);t.addProperty("assignee",a.id());t.addProperty("revision",0);t.add("comments",new JsonArray());t.add("subtasks",new JsonArray());t.add("resources",new JsonArray());require(access(a,t,true));try(var q=db.connection().prepareStatement("SELECT count(*) FROM community_group_items WHERE owner=? AND kind='task'")){q.setString(1,a.id());try(var rs=q.executeQuery()){rs.next();require(rs.getInt(1)<200);}}}else{t=task(id,!op.equals("workGet"));require(access(a,t,false));if(!op.equals("workGet")&&(!in.has("revision")||in.get("revision").getAsLong()!=t.get("revision").getAsLong()))throw new CommunityFailure(CommunityFailure.Code.CONFLICT,"Задача изменилась. Обновите её перед сохранением");}
  var beforeChange=t.deepCopy();boolean manage=access(a,t,true);var workflow=new TaskWorkflow(db,store);if(!op.equals("workGet"))TaskWorkflow.history(t,a,op);
  switch(op){
   case "workGet" -> {}
   case "workRestore" -> {require(manage);t.addProperty("archived",false);t.remove("archivedAt");save(t);}
   case "workDependencies" -> {require(manage);workflow.dependencies(t,text(in,"codes",200));save(t);}
   case "workReserve" -> {require(manage);workflow.reserve(t,in.has("release")&&in.get("release").getAsBoolean());save(t);}
   case "workRepeat" -> {require(manage);TaskWorkflow.repeat(t,in.get("days").getAsInt(),System.currentTimeMillis());save(t);}

   case "workSave" -> {require(manage);String title=text(in,"title",100);require(!title.isEmpty());t.addProperty("title",title);t.addProperty("description",text(in,"description",1000));save(t);}
   case "workDelete" -> {require(manage);try(var q=db.connection().prepareStatement("DELETE FROM community_group_items WHERE id=?")){q.setString(1,id);q.executeUpdate();}CommunityOutbox.add(db,Json.opt(t,"group","").isEmpty()?"home":"groups",Json.opt(t,"group","").isEmpty()?id:Json.str(t,"group"),audience(t));out.addProperty("deleted",true);return out;}
   case "workStatus" -> {require(manage||a.id().equals(Json.opt(t,"assignee","")));String status=text(in,"status",20);require(Set.of("open","working","done").contains(status));if(!status.equals("open"))workflow.start(t);t.addProperty("status",status);t.addProperty("completedAt",status.equals("done")?System.currentTimeMillis():0);if(status.equals("done"))t.add("reservations",new JsonObject());save(t);}
   case "workAssign" -> {require(manage);String assignee=text(in,"assignee",100);if(!assignee.isEmpty()){UUID.fromString(assignee);if(Json.opt(t,"group","").isEmpty())require(assignee.equals(a.id()));else require(store.get(Json.str(t,"group")).getAsJsonObject("members").has(assignee));}String previous=Json.opt(t,"assignee","");t.addProperty("assignee",assignee);save(t);if(!assignee.isEmpty()&&!assignee.equals(previous)&&!assignee.equals(a.id()))store.taskNote(assignee,t,"workAssign","Вам назначена задача: "+Json.str(t,"title"));}
   case "workDue" -> {require(manage);long due=in.get("dueAt").getAsBigDecimal().longValueExact();require(due>=0&&due<=System.currentTimeMillis()+3650L*86400000);long previous=t.get("dueAt").getAsLong();t.addProperty("dueAt",due);save(t);String assignee=Json.opt(t,"assignee","");if(previous!=due&&!assignee.equals(a.id()))store.taskNote(assignee,t,"workDue","Изменён срок задачи: "+Json.str(t,"title"));}
   case "workComment" -> {String message=text(in,"text",500);require(!message.isEmpty());var comments=t.has("comments")?t.getAsJsonArray("comments"):new JsonArray();require(comments.size()<100);var row=new JsonObject();row.addProperty("author",a.name());row.addProperty("text",message);row.addProperty("at",System.currentTimeMillis());comments.add(row);t.add("comments",comments);save(t);}
   case "workSubtask" -> {var rows=t.has("subtasks")?t.getAsJsonArray("subtasks"):new JsonArray();if(in.has("index")){int index=in.get("index").getAsInt();require(index>=0&&index<rows.size());var row=rows.get(index).getAsJsonObject();require(manage||a.id().equals(Json.opt(row,"assignee","")));if(in.has("remove")&&in.get("remove").getAsBoolean()){require(manage);rows.remove(index);}else if(in.has("title")){require(manage);String title=text(in,"title",100);require(!title.isBlank());row.addProperty("title",title);}else row.addProperty("done",!row.get("done").getAsBoolean());}else{require(manage&&rows.size()<30);String title=text(in,"title",100),assignee=text(in,"assignee",100);require(!title.isBlank());if(!assignee.isEmpty()){UUID.fromString(assignee);if(Json.opt(t,"group","").isEmpty())require(assignee.equals(a.id()));else require(store.get(Json.str(t,"group")).getAsJsonObject("members").has(assignee));}var row=new JsonObject();row.addProperty("title",title);row.addProperty("done",false);row.addProperty("assignee",assignee);rows.add(row);}t.add("subtasks",rows);save(t);}
   case "workResources" -> {require(manage);var rows=in.getAsJsonArray("resources");require(rows!=null&&rows.size()<=30);ResourceRequirements.validate(rows);t.add("resources",rows.deepCopy());t.add("reservations",new JsonObject());save(t);}
   default -> throw new IllegalArgumentException("Неизвестное действие задачи");
  }
  if(!op.equals("workGet")&&t.has("history")&&!t.getAsJsonArray("history").isEmpty()){var changes=ChangeSummary.between(beforeChange,t,Map.of("title","Название","description","Описание","status","Статус","assignee","Ответственный","dueAt","Срок","resources","Ресурсы","dependencies","Зависимости","subtasks","Этапы","archived","В архиве"));var last=t.getAsJsonArray("history").get(t.getAsJsonArray("history").size()-1).getAsJsonObject();last.add("changes",changes);try(var q=db.connection().prepareStatement("UPDATE community_group_items SET body=jsonb_set(body,'{history}',?::jsonb) WHERE id=?")){q.setString(1,t.getAsJsonArray("history").toString());q.setString(2,Json.str(t,"id"));q.executeUpdate();}}t=enrich(t);t.addProperty("manage",manage);out.add("task",t);return out;
 }
 /** Generate at most one catch-up occurrence per schedule, without loading world chunks. */
 public void repeatDue(long now)throws Exception{
  db.lock("task-workflow");var due=new ArrayList<String>();try(var q=db.connection().prepareStatement("SELECT id FROM community_group_items WHERE kind='task' AND coalesce((body->>'nextRepeatAt')::bigint,0)>0 AND (body->>'nextRepeatAt')::bigint<=? ORDER BY id LIMIT 20")){q.setLong(1,now);try(var rs=q.executeQuery()){while(rs.next())due.add(rs.getString(1));}}
  for(String id:due){var original=task(id,true);int days=original.get("repeatDays").getAsInt();String owner=Json.str(original,"owner"),group=Json.opt(original,"group","");boolean allowed=group.isEmpty();if(!group.isEmpty())try{allowed=Json.str(store.get(group),"status").equals("open");}catch(CommunityFailure missing){allowed=false;}try(var q=db.connection().prepareStatement("SELECT count(*) FROM community_group_items WHERE owner=? AND kind='task'")){q.setString(1,owner);try(var rs=q.executeQuery()){rs.next();allowed&=rs.getInt(1)<200;}}
   if(allowed){var next=original.deepCopy();for(String key:List.of("code","stocks","history","reservations","dependencies","dependencyDetails","repeatDays","nextRepeatAt","project"))next.remove(key);next.addProperty("id",UUID.randomUUID().toString());next.addProperty("revision",0);next.addProperty("status","open");next.addProperty("recurrenceOf",id);next.addProperty("dueAt",now+days*86400000L);next.add("comments",new JsonArray());if(!group.isEmpty()){var members=store.get(group).getAsJsonObject("members");if(!members.has(Json.opt(next,"assignee","")))next.addProperty("assignee","");if(next.has("subtasks"))for(var e:next.getAsJsonArray("subtasks"))if(!members.has(Json.opt(e.getAsJsonObject(),"assignee","")))e.getAsJsonObject().addProperty("assignee","");}if(next.has("subtasks"))for(var stage:next.getAsJsonArray("subtasks"))stage.getAsJsonObject().addProperty("done",false);save(next);store.note(owner,group.isEmpty()?"home":"groups",group.isEmpty()?Json.str(next,"id"):group,"Создана повторяющаяся задача: "+Json.str(next,"title"));}
   if(!allowed)store.note(owner,group.isEmpty()?"home":"groups",group,"Повтор задачи остановлен: объединение закрыто или достигнут лимит задач");
   original.addProperty("nextRepeatAt",allowed?now+days*86400000L:0);save(original);
  }
 }
 /** The sign author must have management rights, even if they know somebody else's code. */
 public String bind(CommunityStore.Actor actor,String label,String code,String location,JsonObject body)throws Exception{return db.communityTransaction(()->{String id;try(var q=db.connection().prepareStatement("SELECT task_id FROM community_task_codes WHERE code=?")){q.setString(1,TaskCodes.normalize(code));try(var rs=q.executeQuery()){if(!rs.next())throw new IllegalArgumentException("Код задачи не найден");id=rs.getString(1);}}var t=task(id,false);require(access(actor,t,true));String group=Json.opt(t,"group","");String expected=group.isEmpty()?store.personName(Json.str(t,"owner")):Json.str(store.get(group),"title");require(label.strip().equalsIgnoreCase(expected));db.lock("task-stock:"+location);db.lock("task-stock-task:"+id);String inventory=Json.opt(body,"inventory",location);db.lock("task-inventory:"+inventory);try(var q=db.connection().prepareStatement("SELECT location FROM community_task_stocks WHERE body->>'inventory'=? AND location<>?")){q.setString(1,inventory);q.setString(2,location);try(var rs=q.executeQuery()){require(!rs.next());}}try(var q=db.connection().prepareStatement("SELECT task_id FROM community_task_stocks WHERE location=?")){q.setString(1,location);try(var rs=q.executeQuery()){if(rs.next())require(id.equals(rs.getString(1)));}}try(var q=db.connection().prepareStatement("SELECT count(*) FROM community_task_stocks WHERE task_id=? AND location<>?")){q.setString(1,id);q.setString(2,location);try(var rs=q.executeQuery()){rs.next();require(rs.getInt(1)<64);}}db.lock("task-stock-quota");try(var q=db.connection().createStatement();var rs=q.executeQuery("SELECT count(*) FROM community_task_stocks")){rs.next();require(rs.getInt(1)<4096||existingBinding(location));}try(var q=db.connection().prepareStatement("INSERT INTO community_task_stocks VALUES(?,?,?::jsonb) ON CONFLICT(location) DO NOTHING")){q.setString(1,location);q.setString(2,id);q.setString(3,body.toString());if(q.executeUpdate()>0)CommunityOutbox.add(db,group.isEmpty()?"home":"groups",group.isEmpty()?id:group,audience(t));}return id;});}
 private boolean existingBinding(String location)throws Exception{try(var q=db.connection().prepareStatement("SELECT 1 FROM community_task_stocks WHERE location=?")){q.setString(1,location);try(var rs=q.executeQuery()){return rs.next();}}}
 public JsonArray bindings()throws Exception{return db.communityTransaction(()->{var out=new JsonArray();try(var q=db.connection().createStatement();var rs=q.executeQuery("SELECT location,task_id,body FROM community_task_stocks ORDER BY location LIMIT 4096")){while(rs.next()){var j=Json.parse(rs.getString(3));j.addProperty("key",rs.getString(1));j.addProperty("task",rs.getString(2));out.add(j);}}return out;});}
 public boolean stock(String location,JsonObject incoming,boolean remove)throws Exception{return db.communityTransaction(()->{JsonObject body=incoming.deepCopy();db.lock("task-stock-quota");String taskId="";JsonObject previous=null;try(var q=db.connection().prepareStatement("SELECT task_id,body FROM community_task_stocks WHERE location=? FOR UPDATE")){q.setString(1,location);try(var rs=q.executeQuery()){if(rs.next()){taskId=rs.getString(1);previous=Json.parse(rs.getString(2));}}}if(taskId.isEmpty())return false;if(!remove){String inventory=Json.opt(body,"inventory",location);try(var q=db.connection().prepareStatement("SELECT location FROM community_task_stocks WHERE body->>'inventory'=? AND location<? ORDER BY location LIMIT 1")){q.setString(1,inventory);q.setString(2,location);try(var rs=q.executeQuery()){if(rs.next()){body=body.deepCopy();body.add("items",new JsonObject());}}}}if(!remove){try(var q=db.connection().prepareStatement("UPDATE community_task_stocks SET body=jsonb_set(body,'{items}','{}'::jsonb) WHERE body->>'inventory'=? AND location>? AND body->'items'<>'{}'::jsonb RETURNING task_id")){q.setString(1,Json.opt(body,"inventory",location));q.setString(2,location);try(var rows=q.executeQuery()){while(rows.next()){var affected=task(rows.getString(1),false);String group=Json.opt(affected,"group","");CommunityOutbox.add(db,group.isEmpty()?"home":"groups",group.isEmpty()?Json.str(affected,"id"):group,audience(affected));}}}}try(var q=db.connection().prepareStatement(remove?"DELETE FROM community_task_stocks WHERE location=?":"UPDATE community_task_stocks SET body=?::jsonb WHERE location=?")){if(remove)q.setString(1,location);else{q.setString(1,body.toString());q.setString(2,location);}q.executeUpdate();}var t=task(taskId,false);if(remove||previous==null||!Objects.equals(previous.get("items"),body.get("items"))||!Objects.equals(previous.get("inventory"),body.get("inventory")))CommunityOutbox.add(db,Json.opt(t,"group","").isEmpty()?"home":"groups",Json.opt(t,"group","").isEmpty()?taskId:Json.str(t,"group"),audience(t));return true;});}
}
