package dev.abros.rivet.core;
import com.google.gson.*;
import java.util.*;
/** Player tools retain ownership server-side and do not grant rights from client flags. */
final class CommunityPlayerTools {
 private final PgDatabase db;private final CommunityStore store;
 CommunityPlayerTools(PgDatabase db,CommunityStore store){this.db=db;this.store=store;}
 private static void require(boolean value){if(!value)throw new CommunityFailure(CommunityFailure.Code.FORBIDDEN,"Действие недоступно");}
 JsonObject request(CommunityStore.Actor a,JsonObject in)throws Exception{String op=Json.str(in,"op"),id=Json.opt(in,"id","");var out=new JsonObject();out.addProperty("kind","community");out.addProperty("section","home");out.addProperty("request",Json.opt(in,"request",""));
  switch(op){
   case "toolsMapSettings","toolsMapShare" -> {if(op.equals("toolsMapShare")){String group=Json.opt(in,"group","");int minutes=in.has("minutes")?in.get("minutes").getAsBigDecimal().intValueExact():0;require(minutes>=0&&minutes<=120);if(minutes>0){var g=store.get(group);require(Json.str(g,"section").equals("groups")&&Json.str(g,"status").equals("open")&&g.getAsJsonObject("members").has(a.id()));}var setting=new JsonObject();setting.addProperty("group",group);setting.addProperty("until",minutes==0?0:System.currentTimeMillis()+minutes*60000L);store.record("map-sharing",a.id(),setting);}var setting=store.record("map-sharing",a.id());out.add("sharing",setting==null?new JsonObject():setting);var groups=new JsonArray();try(var q=db.connection().prepareStatement("SELECT d.body FROM documents d JOIN community_relations r ON r.document=d.id WHERE d.section='groups' AND d.body->>'status'='open' AND r.kind='members' AND r.actor=? ORDER BY d.id LIMIT 20")){q.setString(1,a.id());try(var rs=q.executeQuery()){while(rs.next()){var g=Json.parse(rs.getString(1));var row=new JsonObject();row.add("id",g.get("id"));row.add("title",g.get("title"));groups.add(row);}}}out.add("groups",groups);}
   case "toolsMapPeers" -> {var peers=new JsonArray();try(var q=db.connection().prepareStatement("SELECT DISTINCT s.id,p.name FROM records s JOIN documents d ON d.id=s.body->>'group' JOIN community_relations v ON v.document=d.id JOIN community_relations m ON m.document=d.id AND m.actor=s.id JOIN people p ON p.id=s.id WHERE s.namespace='map-sharing' AND (s.body->>'until')::bigint>? AND d.section='groups' AND d.body->>'status'='open' AND v.kind='members' AND v.actor=? AND m.kind='members' AND s.id<>? ORDER BY s.id LIMIT 100")){q.setLong(1,System.currentTimeMillis());q.setString(2,a.id());q.setString(3,a.id());try(var rs=q.executeQuery()){while(rs.next()){var row=new JsonObject();row.addProperty("uuid",rs.getString(1));row.addProperty("name",rs.getString(2));peers.add(row);}}}out.add("peers",peers);}
   case "toolsFollowing" -> {var rows=new JsonArray();try(var q=db.connection().prepareStatement("SELECT f.body->>'organizer',p.name FROM records f JOIN people p ON p.id=f.body->>'organizer' WHERE f.namespace='organizer-follow' AND f.body->>'player'=? ORDER BY p.name LIMIT 100")){q.setString(1,a.id());try(var rs=q.executeQuery()){while(rs.next()){var row=new JsonObject();row.addProperty("uuid",rs.getString(1));row.addProperty("name",rs.getString(2));rows.add(row);}}}out.add("following",rows);}
   case "toolsPrivacy","toolsPrivacySave" -> {if(op.endsWith("Save")){String mode=Json.str(in,"mode");require(Set.of("public","members","private").contains(mode));var setting=new JsonObject();setting.addProperty("mode",mode);setting.addProperty("statistics",in.has("statistics")&&in.get("statistics").getAsBoolean());store.record("profile-privacy",a.id(),setting);CommunityOutbox.add(db,"players",a.id(),"");}var value=store.record("profile-privacy",a.id());if(value==null){value=new JsonObject();value.addProperty("mode","public");value.addProperty("statistics",true);}out.add("settings",value);}
   case "toolsFollow" -> {UUID.fromString(id);require(!id.equals(a.id()));boolean remove=in.has("remove")&&in.get("remove").getAsBoolean();String key=a.id()+":"+id;if(remove)store.deleteRecord("organizer-follow",key);else{db.lock("organizer-follow:"+a.id());db.lock("organizer-follow-target:"+id);try(var q=db.connection().prepareStatement("SELECT count(*) FROM records WHERE namespace='organizer-follow' AND body->>'organizer'=?")){q.setString(1,id);try(var rs=q.executeQuery()){rs.next();require(rs.getInt(1)<300||store.record("organizer-follow",key)!=null);}}try(var q=db.connection().prepareStatement("SELECT count(*) FROM records WHERE namespace='organizer-follow' AND body->>'player'=?")){q.setString(1,a.id());try(var rs=q.executeQuery()){rs.next();require(rs.getInt(1)<100||store.record("organizer-follow",key)!=null);}}require(!store.personName(id).equals(id));var row=new JsonObject();row.addProperty("player",a.id());row.addProperty("organizer",id);store.record("organizer-follow",key,row);}out.addProperty("following",!remove);}
   case "toolsTemporary" -> {var group=store.get(id,true);require(Json.str(group,"section").equals("groups")&&store.manager(group,a));int days=in.get("days").getAsBigDecimal().intValueExact();require(days>=0&&days<=90);group.addProperty("expiresAt",days==0?0:System.currentTimeMillis()+days*86400000L);store.put(group);var read=in.deepCopy();read.addProperty("op","detail");read.addProperty("section","groups");return store.execute(a,read,"detail","groups");}
   case "toolsAttendance" -> {var event=store.get(id,true);require(Json.str(event,"section").equals("events")&&(a.admin()||Json.str(event,"owner").equals(a.id())));String player=Json.str(in,"target");require(!Json.str(event,"status").equals("cancelled")&&event.getAsJsonObject("participants").has(player));require(System.currentTimeMillis()>=event.get("startsAt").getAsLong());var rows=event.has("attendance")?event.getAsJsonObject("attendance"):new JsonObject();var row=new JsonObject();row.addProperty("present",in.get("present").getAsBoolean());row.addProperty("by",a.name());row.addProperty("at",System.currentTimeMillis());rows.add(player,row);event.add("attendance",rows);store.put(event);var read=in.deepCopy();read.addProperty("op","detail");read.addProperty("section","events");return store.execute(a,read,"detail","events");}
   case "toolsPlaces" -> {String after=Json.opt(in,"cursor","");if(!after.isEmpty())UUID.fromString(after);var rows=new JsonArray();try(var q=db.connection().prepareStatement("SELECT id,body FROM records WHERE namespace='public-place' AND id>? ORDER BY id LIMIT 21")){q.setString(1,after);try(var rs=q.executeQuery()){while(rs.next()){if(rows.size()==20){out.addProperty("nextCursor",Json.str(rows.get(rows.size()-1).getAsJsonObject(),"id"));break;}var place=Json.parse(rs.getString(2));place.addProperty("id",rs.getString(1));place.addProperty("manage",a.admin()||Json.str(place,"owner").equals(a.id()));rows.add(place);}}}out.add("places",rows);}
   case "toolsPlaceSave","toolsPlaceDelete" -> {JsonObject place;if(id.isEmpty()){require(op.endsWith("Save"));id=UUID.randomUUID().toString();db.lock("public-place-quota:"+a.id());try(var q=db.connection().prepareStatement("SELECT count(*) FROM records WHERE namespace='public-place' AND body->>'owner'=?")){q.setString(1,a.id());try(var rs=q.executeQuery()){rs.next();require(rs.getInt(1)<50);}}place=new JsonObject();place.addProperty("owner",a.id());place.addProperty("author",a.name());place.addProperty("revision",0);}else{db.lock("public-place:"+id);place=store.record("public-place",id);require(place!=null&&(a.admin()||Json.str(place,"owner").equals(a.id())));if(!in.has("revision")||in.get("revision").getAsLong()!=place.get("revision").getAsLong())throw new CommunityFailure(CommunityFailure.Code.CONFLICT,"Место изменилось. Откройте его заново");}if(op.endsWith("Delete"))store.deleteRecord("public-place",id);else{String title=Json.str(in,"title").strip(),status=Json.opt(in,"status","open");require(!title.isEmpty()&&title.length()<=80&&Set.of("open","unavailable","closed").contains(status));place.addProperty("title",title);place.addProperty("status",status);var location=CommunityLocation.read(in.getAsJsonObject("location"));require(!location.membersOnly());place.add("location",location.json());place.addProperty("revision",place.get("revision").getAsLong()+1);store.record("public-place",id,place);}CommunityOutbox.add(db,"groups",id,"");out.addProperty("saved",true);}
   default -> throw new IllegalArgumentException("Неизвестное действие");
  }return out;
 }
 boolean visible(String target,String viewer)throws Exception{if(target.equals(viewer))return true;var settings=store.record("profile-privacy",target);if(settings==null)return true;return switch(Json.opt(settings,"mode","public")){case "private"->false;case "members"->{try(var q=db.connection().prepareStatement("SELECT 1 FROM community_relations a JOIN community_relations b ON a.document=b.document JOIN documents d ON d.id=a.document WHERE a.kind='members' AND b.kind='members' AND a.actor=? AND b.actor=? AND d.body->>'status'='open' LIMIT 1")){q.setString(1,target);q.setString(2,viewer);try(var rs=q.executeQuery()){yield rs.next();}}}default->true;};}
 void createdEvent(CommunityStore.Actor actor,JsonObject event)throws Exception{try(var q=db.connection().prepareStatement("SELECT body->>'player' FROM records WHERE namespace='organizer-follow' AND body->>'organizer'=? LIMIT 300")){q.setString(1,actor.id());try(var rs=q.executeQuery()){while(rs.next()){String player=rs.getString(1);if(new CommunityPlus(db,store).visible(new CommunityStore.Actor(player,"",false,false),event))store.note(player,"events",Json.str(event,"id"),"Новое событие организатора: "+Json.str(event,"title"));}}}}
 void expire(long now)throws Exception{try(var q=db.connection().prepareStatement("SELECT id FROM documents WHERE section='groups' AND body->>'status'='open' AND coalesce((body->>'expiresAt')::bigint,0)>0 AND (body->>'expiresAt')::bigint<=? ORDER BY id LIMIT 100 FOR UPDATE")){q.setLong(1,now);try(var rs=q.executeQuery()){while(rs.next()){var group=store.get(rs.getString(1));group.addProperty("status","closed");store.put(group);for(String member:group.getAsJsonObject("members").keySet())store.note(member,"groups",Json.str(group,"id"),"Временное объединение завершено: "+Json.str(group,"title"));}}}}
}
