package dev.abros.rivet.core;
import com.google.gson.*;
import java.nio.charset.StandardCharsets;
import java.util.*;
/** Read models with keyset continuations, visibility checks and explicit archive filtering. */
final class CommunityQueries {
 private final PgDatabase db;
 CommunityQueries(PgDatabase db){this.db=db;}
 private String scope(CommunityStore.Actor actor,JsonObject input,String section){return Hashes.sha256((actor.id()+"|"+actor.admin()+"|"+section+"|"+Json.opt(input,"query","")+"|"+Json.opt(input,"member","")+"|"+Json.opt(input,"sort","default")+"|"+Boolean.toString(input.has("mine")&&input.get("mine").getAsBoolean())+"|"+Boolean.toString(input.has("participating")&&input.get("participating").getAsBoolean())+"|"+Boolean.toString(input.has("archive")&&input.get("archive").getAsBoolean())+"|"+Boolean.toString(input.has("trash")&&input.get("trash").getAsBoolean())).getBytes(StandardCharsets.UTF_8));}
 private long ceiling(String table)throws Exception{try(var q=db.connection().createStatement();var row=q.executeQuery("SELECT coalesce(max("+(table.equals("notices")?"id":"sequence")+"),0) FROM "+table)){row.next();return row.getLong(1);}}
 JsonArray list(CommunityStore.Actor actor,JsonObject input,String section,long now,JsonObject config)throws Exception {
  String scope=scope(actor,input,section),token=Json.opt(input,"cursor","");CommunityCursor after=token.isEmpty()?null:CommunityCursor.decode(token,scope);long cap=after==null?ceiling("documents"):after.ceiling();
  var sources=new ArrayList<String>();for(String source:section.equals("home")?List.of("events"):List.of(section))if(config.getAsJsonArray("sections").contains(new JsonPrimitive(source)))sources.add(source);
  if(sources.isEmpty())return new JsonArray();
  var args=new ArrayList<Object>();args.add(actor.admin());args.add(actor.id());args.add(input.has("mine")&&input.get("mine").getAsBoolean());args.add(actor.id());args.add(Json.opt(input,"member",""));args.add(Json.opt(input,"member",""));args.add(Json.opt(input,"query",""));args.add(cap);
  String sql="SELECT id,sequence,body FROM documents WHERE section=ANY(?) AND (body->>'status'<>'hidden' OR ? OR body->>'owner'=?) AND (NOT ? OR body->>'owner'=?) AND (?='' OR section<>'groups' OR EXISTS(SELECT 1 FROM community_relations rel WHERE rel.document=documents.id AND rel.kind='members' AND rel.actor=?)) AND strpos(lower(body->>'title'),lower(?))>0 AND sequence<=?";
  sql+=" AND (section<>'events' OR ? OR body->>'owner'=? OR coalesce(body->>'visibility','public')='public' OR body->>'visibility'='group' AND "+(config.getAsJsonArray("sections").contains(new JsonPrimitive("groups"))?"true":"false")+" AND EXISTS(SELECT 1 FROM community_relations cr JOIN documents cg ON cg.id=cr.document WHERE cr.document=documents.body->>'group' AND cr.kind='members' AND cr.actor=? AND cg.body->>'status'='open') OR body->>'visibility'='invited' AND jsonb_exists(body->'eventInvites',?))";
  args.add(actor.admin());args.add(actor.id());args.add(actor.id());args.add(actor.id());
  String archived="(body->>'status' IN ('closed','done','declined','cancelled','hidden') OR section IN ('board','polls') AND (body->>'endsAt')::bigint<=? OR section='events' AND (body->>'startsAt')::bigint<=?)";
  boolean trash=input.has("trash")&&input.get("trash").getAsBoolean();
  sql+=" AND "+(trash?"body->>'status'='deleted' AND (? OR body->>'owner'=?)":"body->>'status'<>'deleted'");if(trash){args.add(actor.admin());args.add(actor.id());}
  boolean archive=input.has("archive")&&input.get("archive").getAsBoolean();if(!trash){sql+=" AND "+(archive?"":"NOT ")+archived;args.add(now);args.add(now);}
  if(input.has("participating")&&input.get("participating").getAsBoolean()){
   sql+=" AND (section='board' AND EXISTS(SELECT 1 FROM community_relations rel WHERE rel.document=documents.id AND rel.kind='responses' AND rel.actor=?) OR section='groups' AND (EXISTS(SELECT 1 FROM community_relations rel WHERE rel.document=documents.id AND rel.kind='members' AND rel.actor=?) OR EXISTS(SELECT 1 FROM community_relations rel WHERE rel.document=documents.id AND rel.kind='applications' AND rel.actor=?) OR EXISTS(SELECT 1 FROM community_relations rel WHERE rel.document=documents.id AND rel.kind='invitations' AND rel.actor=?)) OR section='events' AND EXISTS(SELECT 1 FROM community_relations rel WHERE rel.document=documents.id AND rel.kind='participants' AND rel.actor=?) OR section='polls' AND EXISTS(SELECT 1 FROM community_relations rel WHERE rel.document=documents.id AND rel.kind='votes' AND rel.actor=?) OR section='ideas' AND EXISTS(SELECT 1 FROM community_relations rel WHERE rel.document=documents.id AND rel.kind='supporters' AND rel.actor=?))";
   for(int n=0;n<7;n++)args.add(actor.id());
  }
  if(section.equals("home")){
   sql+=" AND (body->>'owner'=? OR EXISTS(SELECT 1 FROM community_relations rel WHERE rel.document=documents.id AND rel.kind='participants' AND rel.actor=?) OR EXISTS(SELECT 1 FROM community_event_preferences ep WHERE ep.event=documents.id AND ep.player=? AND ep.minutes>=0))";args.add(actor.id());args.add(actor.id());args.add(actor.id());
  }
  String sort=Json.opt(input,"sort","default");if(!Set.of("default","recent","oldest").contains(sort))throw new IllegalArgumentException(dev.abros.rivet.core.Messages.text("rivet.core.unknown_entry_order_1f3ef4aa"));
  boolean events=section.equals("events")||section.equals("home"),ascending=events?!sort.equals("recent"):sort.equals("oldest");String sortTime=section.equals("home")?"coalesce((body->>'startsAt')::bigint,0)":"(body->>'startsAt')::bigint";
  if(after!=null){if(events){sql+=" AND ("+sortTime+(ascending?">?":"<?")+" OR "+sortTime+"=? AND sequence<?)";args.add(after.time());args.add(after.time());}else sql+=" AND sequence"+(ascending?">?":"<?");args.add(after.sequence());}
  sql+=events?" ORDER BY "+sortTime+(ascending?" ASC":" DESC")+",sequence DESC LIMIT 11":" ORDER BY sequence"+(ascending?" ASC":" DESC")+" LIMIT 11";
  // Filter and limit base documents before reconstructing child collections.
  // MATERIALIZED prevents the planner from repeating relation aggregates in predicates.
  String pageOrder=events?"("+(section.equals("home")?"coalesce((selected.body->>'startsAt')::bigint,0)":"(selected.body->>'startsAt')::bigint")+")"+(ascending?" ASC":" DESC")+",selected.sequence DESC":"selected.sequence"+(ascending?" ASC":" DESC");
  sql="WITH selected AS MATERIALIZED ("+sql+") SELECT (SELECT body FROM community_documents full_document WHERE full_document.id=selected.id),selected.sequence FROM selected ORDER BY "+pageOrder;
  var out=new JsonArray();long last=0,time=0;boolean more=false;
  try(var q=db.connection().prepareStatement(sql)){q.setArray(1,db.connection().createArrayOf("text",sources.toArray()));for(int i=0;i<args.size();i++)q.setObject(i+2,args.get(i));try(var rows=q.executeQuery()){while(rows.next()){if(out.size()==(section.equals("home")?3:10)){more=!section.equals("home");break;}var document=Json.parse(rows.getString(1));var preview=CommunityPreview.of(document);if(section.equals("home"))preview.addProperty("isSubscribed",true);if(section.equals("home"))preview.addProperty("attention",switch(Json.str(document,"section")){case "groups"->document.getAsJsonObject("invitations").has(actor.id())?Messages.text("rivet.ui.you_have_been_invited_78128de8"):Messages.text("rivet.core.applications_awaiting_a_response_84d3a0d9");case "board"->Json.str(document,"owner").equals(actor.id())?Messages.text("rivet.core.new_responses_3a25d0bf"):Messages.text("rivet.core.your_response_has_received_a_reply_743e6c2f");case "polls"->Messages.text("rivet.core.you_have_not_voted_yet_ef33b146");default->Messages.text("rivet.ui.next_event_8291a90b");});if(events){int index=new ArrayList<>(document.getAsJsonObject("participants").keySet()).indexOf(actor.id());if(document.has("participantOrder"))index=document.getAsJsonArray("participantOrder").asList().indexOf(new JsonPrimitive(actor.id()));int capacity=document.get("capacity").getAsInt();preview.addProperty("waitlistPosition",index<0||capacity==0||index<capacity?0:index-capacity+1);}
   preview.addProperty("isOwner",Json.str(document,"owner").equals(actor.id()));preview.addProperty("isParticipant",document.has("participants")&&document.getAsJsonObject("participants").has(actor.id()));preview.addProperty("supported",document.has("supporters")&&document.getAsJsonObject("supporters").has(actor.id()));out.add(preview);last=rows.getLong(2);time=events&&document.has("startsAt")?document.get("startsAt").getAsLong():0;}}}
  if(more)out.get(out.size()-1).getAsJsonObject().addProperty("_nextCursor",new CommunityCursor(last,time,cap,scope).encode());return out;
 }
 JsonArray notices(CommunityStore.Actor actor,JsonObject input)throws Exception {
  String category=Json.opt(input,"category","");if(!category.isEmpty()&&!CommunityStore.SECTIONS.contains(category))throw new IllegalArgumentException(dev.abros.rivet.core.Messages.text("rivet.core.unknown_category_0a688127"));String scope=scope(actor,input,"notifications")+category,token=Json.opt(input,"cursor","");CommunityCursor after=token.isEmpty()?null:CommunityCursor.decode(token,scope);long cap=after==null?ceiling("notices"):after.ceiling();var out=new JsonArray();long last=0;boolean more=false;
  try(var q=db.connection().prepareStatement("SELECT id,body,read FROM notices WHERE recipient=? AND id<=? AND id<? AND (?='' OR body->>'section'=?) ORDER BY id DESC LIMIT 11")){q.setString(1,actor.id());q.setLong(2,cap);q.setLong(3,after==null?Long.MAX_VALUE:after.sequence());q.setString(4,category);q.setString(5,category);try(var rows=q.executeQuery()){while(rows.next()){if(out.size()==10){more=true;break;}last=rows.getLong(1);var j=Json.parse(rows.getString(2));j.addProperty("id",Long.toString(last));j.addProperty("read",rows.getBoolean(3));out.add(j);}}}
  if(more)out.get(out.size()-1).getAsJsonObject().addProperty("_nextCursor",new CommunityCursor(last,0,cap,scope).encode());return out;
 }
}
