package dev.abros.rivet.core;
import com.google.gson.*;
import java.util.*;
/** Shared personal/group tasks. All reads authorize against current group membership. */
public final class CommunityTasks {
 static final String LIST_SQL="WITH task_page AS MATERIALIZED (SELECT id,body,revision,owner,c.code FROM community_group_items LEFT JOIN community_task_codes c ON c.task_id=id WHERE kind='task' AND ((?='' AND group_id IS NULL AND owner=?) OR group_id=?) AND id>? AND ((?='archived' AND task_archived='true') OR (coalesce(task_archived,'false')<>'true' AND (?='' OR task_status=?))) AND strpos(lower(task_search || ' ' || coalesce(c.code,'')),lower(?))>0 ORDER BY id LIMIT 21) SELECT id,body - ARRAY['comments','stocks','history','dependencies','reservations']::text[],revision,owner,code FROM task_page ORDER BY id";
 private final PgDatabase db;private final CommunityStore store;
 public CommunityTasks(PgDatabase db,CommunityStore store){this.db=db;this.store=store;}
 private static void require(boolean ok){if(!ok)throw new CommunityFailure(CommunityFailure.Code.FORBIDDEN,dev.abros.rivet.core.Messages.text("rivet.core.task_unavailable_d9700c28"));}
 private static String text(JsonObject j,String k,int max){String s=Json.opt(j,k,"").strip();if(s.length()>max||s.codePoints().anyMatch(c->Character.isISOControl(c)&&c!='\n'))throw new IllegalArgumentException(dev.abros.rivet.core.Messages.text("rivet.core.invalid_field_1184c511")+k);return s;}
 public String code(String id)throws Exception{try(var q=db.connection().prepareStatement("SELECT code FROM community_task_codes WHERE task_id=?")){q.setString(1,id);try(var rs=q.executeQuery()){if(rs.next())return rs.getString(1);}}long n;try(var q=db.connection().createStatement();var rs=q.executeQuery("SELECT nextval('community_task_code_sequence')")){rs.next();n=rs.getLong(1);}String code=TaskCodes.encode(n);try(var q=db.connection().prepareStatement("INSERT INTO community_task_codes VALUES(?,?) ON CONFLICT(task_id) DO NOTHING")){q.setString(1,id);q.setString(2,code);q.executeUpdate();}try(var q=db.connection().prepareStatement("SELECT code FROM community_task_codes WHERE task_id=?")){q.setString(1,id);try(var rs=q.executeQuery()){rs.next();return rs.getString(1);}}}
 JsonObject task(String id,boolean lock)throws Exception{try(var q=db.connection().prepareStatement("SELECT body,group_id,owner,revision FROM community_group_items WHERE id=? AND kind='task'"+(lock?" FOR UPDATE":""))){q.setString(1,id);try(var rs=q.executeQuery()){if(!rs.next())throw new CommunityFailure(CommunityFailure.Code.NOT_FOUND,dev.abros.rivet.core.Messages.text("rivet.core.task_not_found_43c5e77e"));var j=Json.parse(rs.getString(1));j.addProperty("id",id);j.addProperty("group",Objects.toString(rs.getString(2),""));j.addProperty("owner",Objects.toString(rs.getString(3),""));j.addProperty("revision",rs.getLong(4));return j;}}}
 boolean access(CommunityStore.Actor a,JsonObject t,boolean manage)throws Exception{
  String group=Json.opt(t,"group","");if(!store.modules().enabled("tasks")||!group.isEmpty()&&!store.modules().enabled("groups"))return false;if(group.isEmpty())return Json.opt(t,"owner","").equals(a.id());
  // Read current membership on every check without rebuilding every member's JSON.
  try(var q=db.connection().prepareStatement("SELECT d.body->>'status',d.body->>'owner',r.value FROM documents d LEFT JOIN community_relations r ON r.document=d.id AND r.kind='members' AND r.actor=? WHERE d.id=?")){
   q.setString(1,a.id());q.setString(2,group);try(var rs=q.executeQuery()){
    if(!rs.next())throw new CommunityFailure(CommunityFailure.Code.NOT_FOUND,dev.abros.rivet.core.Messages.text("rivet.core.entry_not_found_82764bdc"));if(!"open".equals(rs.getString(1)))return false;
    String role=rs.getString(3);return manage?a.admin()||a.id().equals(rs.getString(2))||role!=null&&JsonParser.parseString(role).getAsString().equals("assistant"):a.admin()||role!=null;
   }
  }
 }

 void save(JsonObject t)throws Exception{String id=Json.str(t,"id"),group=Json.opt(t,"group","");var body=t.deepCopy();body.remove("code");body.remove("stocks");long rev=t.get("revision").getAsLong()+1;try(var q=db.connection().prepareStatement("INSERT INTO community_group_items(id,group_id,kind,body,revision,owner) VALUES(?,?,'task',?::jsonb,?,?) ON CONFLICT(id) DO UPDATE SET body=excluded.body,revision=excluded.revision")){q.setString(1,id);q.setString(2,group.isEmpty()?null:group);q.setString(3,body.toString());q.setLong(4,rev);q.setString(5,Json.str(t,"owner"));q.executeUpdate();}t.addProperty("revision",rev);code(id);CommunityOutbox.add(db,group.isEmpty()?"home":"groups",group,audience(t));}
 private String audience(JsonObject t){return Json.opt(t,"group","").isEmpty()?Json.str(t,"owner"):"";}
 JsonObject enrich(JsonObject t)throws Exception{return enrich(t,null);}
 private JsonObject enrich(JsonObject t,TaskWorkflow.ReservationSnapshot reservation)throws Exception{
  t.addProperty("code",code(Json.str(t,"id")));String group=Json.opt(t,"group","");t.addProperty("stockLabel",group.isEmpty()?store.personName(Json.str(t,"owner")):Json.str(store.get(group),"title"));if(!Json.opt(t,"assignee","").isEmpty())t.addProperty("assigneeName",store.personName(Json.str(t,"assignee")));var totals=new JsonObject();long confirmed=0;int containers=0;var inventories=new HashSet<String>();var wanted=new HashSet<String>();if(t.has("resources"))for(var e:t.getAsJsonArray("resources"))wanted.addAll(ResourceRequirements.items(e.getAsJsonObject()));
  if(store.modules().enabled("storage"))try(var q=db.connection().prepareStatement("SELECT body FROM community_task_stocks WHERE task_id=? ORDER BY location LIMIT 64")){q.setString(1,Json.str(t,"id"));try(var rs=q.executeQuery()){while(rs.next()){var stock=Json.parse(rs.getString(1));if(!inventories.add(Json.opt(stock,"inventory",UUID.randomUUID().toString())))continue;containers++;long at=stock.has("at")?stock.get("at").getAsLong():0;confirmed=confirmed==0?at:Math.min(confirmed,at);if(stock.has("items"))for(String item:wanted){long count=stock.getAsJsonObject("items").has(item)?stock.getAsJsonObject("items").get(item).getAsLong():0;totals.addProperty(item,(totals.has(item)?totals.get(item).getAsLong():0)+count);}}}
  }
  var summary=new JsonObject();summary.add("items",totals);summary.addProperty("at",confirmed);summary.addProperty("containers",containers);var stocks=new JsonArray();stocks.add(summary);t.add("stocks",stocks);
  var workflow=new TaskWorkflow(db,store);t.add("dependencyDetails",workflow.dependencies(t));t.add("confirmedPool",reservation==null?workflow.stock(t):reservation.stock());t.add("reservedElsewhere",reservation==null?workflow.reserved(t):reservation.reserved());
  if(t.has("history")){var all=t.getAsJsonArray("history");var recent=new JsonArray();for(int n=Math.max(0,all.size()-10);n<all.size();n++)recent.add(all.get(n));t.add("history",recent);}
return t;
 }
 private int ownerTaskCount(String owner)throws Exception{try(var q=db.connection().prepareStatement("SELECT count(*) FROM community_group_items WHERE owner=? AND kind='task'")){q.setString(1,owner);try(var rs=q.executeQuery()){rs.next();return rs.getInt(1);}}}
 public JsonObject request(CommunityStore.Actor a,JsonObject in)throws Exception{
  store.modules().require("tasks");String op=Json.str(in,"op"),id=Json.opt(in,"task","");var out=new JsonObject();out.addProperty("kind","community");out.addProperty("section","home");out.addProperty("request",Json.opt(in,"request",""));if(!Set.of("workList","workGet","workMembers","workArchivePreview").contains(op)){db.lock("task-workflow");db.lock("tasks:"+a.id());}
  if(op.startsWith("workArchive"))return TaskArchive.request(db,this,a,in);
  if(op.equals("workMembers")){String group=text(in,"group",100),query=text(in,"query",32),cursor=text(in,"cursor",100);var probe=new JsonObject();probe.addProperty("group",group);require(!group.isEmpty()&&access(a,probe,true));var rows=new JsonArray();try(var q=db.connection().prepareStatement("SELECT p.id,p.name FROM people p JOIN community_relations r ON r.actor=p.id WHERE r.document=? AND r.kind='members' AND strpos(lower(p.name),lower(?))>0 AND p.id>? ORDER BY p.id LIMIT 21")){q.setString(1,group);q.setString(2,query);q.setString(3,cursor);try(var rs=q.executeQuery()){while(rs.next()){if(rows.size()==20){out.addProperty("nextCursor",Json.str(rows.get(19).getAsJsonObject(),"uuid"));break;}var row=new JsonObject();row.addProperty("uuid",rs.getString(1));row.addProperty("name",rs.getString(2));rows.add(row);}}}out.add("members",rows);return out;}
  // Materialize one page before stripping detail-only JSON; never transform every matching task.
  if(op.equals("workList")){String group=text(in,"group",100),cursor=text(in,"cursor",100),query=text(in,"query",100),status=text(in,"status",16);if(!Set.of("","open","working","done","archived").contains(status))throw new IllegalArgumentException(dev.abros.rivet.core.Messages.text("rivet.core.invalid_task_status_cc3259c3"));if(!cursor.isEmpty())UUID.fromString(cursor);if(!group.isEmpty()){var probe=new JsonObject();probe.addProperty("group",group);require(access(a,probe,false));}var rows=new JsonArray();try(var q=db.connection().prepareStatement(LIST_SQL)){q.setString(1,group);q.setString(2,a.id());q.setString(3,group);q.setString(4,cursor);q.setString(5,status);q.setString(6,status);q.setString(7,status);q.setString(8,query);try(var rs=q.executeQuery()){while(rs.next()){if(rows.size()==20){out.addProperty("nextCursor",Json.str(rows.get(19).getAsJsonObject(),"id"));break;}var t=Json.parse(rs.getString(2));String taskId=rs.getString(1);t.addProperty("id",taskId);t.addProperty("code",rs.getString(5)==null?code(taskId):rs.getString(5));t.addProperty("group",group);t.addProperty("owner",rs.getString(4));t.addProperty("revision",rs.getLong(3));int total=t.has("subtasks")?t.getAsJsonArray("subtasks").size():0,done=0;if(t.has("subtasks"))for(var stage:t.getAsJsonArray("subtasks"))if(stage.getAsJsonObject().get("done").getAsBoolean())done++;t.addProperty("stagesTotal",total);t.addProperty("stagesDone",done);t.addProperty("resourceTypes",t.has("resources")?t.getAsJsonArray("resources").size():0);String preview=Json.opt(t,"description","");t.addProperty("preview",preview.substring(0,preview.offsetByCodePoints(0,Math.min(160,preview.codePointCount(0,preview.length())))));for(String key:List.of("comments","subtasks","resources","stocks","description","history","dependencies","reservations"))t.remove(key);rows.add(t);}}}out.add("tasks",rows);var permissions=new JsonObject();permissions.addProperty("group",group);boolean mayCreate=group.isEmpty()||access(a,permissions,true);boolean quota=store.taskLimits().allowsTask(ownerTaskCount(a.id()));out.addProperty("canManage",mayCreate);out.addProperty("canCreate",mayCreate&&quota);out.addProperty("createReason",!mayCreate?Messages.text("rivet.core.only_group_leaders_can_create_tasks_6238c437"):!quota?Messages.text("rivet.core.task_limit_reached_9b56eb6c")+store.taskLimits().perOwner():"");return out;}
  JsonObject t;if(op.equals("workSave")&&id.isEmpty()){t=new JsonObject();t.addProperty("id",UUID.randomUUID().toString());t.addProperty("group",text(in,"group",100));t.addProperty("owner",a.id());t.addProperty("kind","task");t.addProperty("status","open");t.addProperty("dueAt",0);t.addProperty("assignee",a.id());t.addProperty("revision",0);t.add("comments",new JsonArray());t.add("subtasks",new JsonArray());t.add("resources",new JsonArray());require(access(a,t,true));try(var q=db.connection().prepareStatement("SELECT count(*) FROM community_group_items WHERE owner=? AND kind='task'")){q.setString(1,a.id());try(var rs=q.executeQuery()){rs.next();require(store.taskLimits().allowsTask(rs.getInt(1)));}}}else{t=task(id,!op.equals("workGet"));require(access(a,t,false));if(!op.equals("workGet")&&(!in.has("revision")||in.get("revision").getAsLong()!=t.get("revision").getAsLong()))throw new CommunityFailure(CommunityFailure.Code.CONFLICT,dev.abros.rivet.core.Messages.text("rivet.core.task_changed_refresh_it_before_saving_c7a67130"));}
  TaskWorkflow.ReservationSnapshot reservation=null;var beforeChange=t.deepCopy();boolean manage=access(a,t,true);var workflow=new TaskWorkflow(db,store);if(!op.equals("workGet"))TaskWorkflow.history(t,a,op);
  switch(op){
   case "workGet" -> {}
   case "workLocation" -> {require(manage);if(!in.has("location"))throw new IllegalArgumentException(dev.abros.rivet.core.Messages.text("rivet.core.no_destination_specified_f25ae7b0"));if(in.get("location").isJsonNull())t.remove("location");else {var p=CommunityLocation.read(in.getAsJsonObject("location"));t.add("location",new CommunityLocation(p.name(),p.dimension(),p.x(),p.y(),p.z(),false).json());}save(t);}
   case "workRestore" -> {require(manage);t.addProperty("archived",false);t.remove("archivedAt");save(t);}
   case "workDependencies" -> {require(manage);workflow.dependencies(t,text(in,"codes",200));save(t);}
   case "workReserve" -> {require(manage);reservation=workflow.reserve(t,in.has("release")&&in.get("release").getAsBoolean());save(t);}
   case "workRepeat" -> {require(manage);TaskWorkflow.repeat(t,in.get("days").getAsInt(),System.currentTimeMillis());save(t);}

   case "workSave" -> {require(manage);String title=text(in,"title",100);require(!title.isEmpty());t.addProperty("title",title);t.addProperty("description",text(in,"description",1000));save(t);}
   case "workDelete" -> {require(manage);try(var q=db.connection().prepareStatement("DELETE FROM community_group_items WHERE id=?")){q.setString(1,id);q.executeUpdate();}CommunityOutbox.add(db,Json.opt(t,"group","").isEmpty()?"home":"groups",Json.opt(t,"group","").isEmpty()?id:Json.str(t,"group"),audience(t));out.addProperty("deleted",true);return out;}
   case "workStatus" -> {require(manage||a.id().equals(Json.opt(t,"assignee","")));String status=text(in,"status",20);require(Set.of("open","working","done").contains(status));if(!status.equals("open"))workflow.start(t);t.addProperty("status",status);t.addProperty("completedAt",status.equals("done")?System.currentTimeMillis():0);if(status.equals("done"))t.add("reservations",new JsonObject());save(t);}
   case "workAssign" -> {require(manage);String assignee=text(in,"assignee",100);if(!assignee.isEmpty()){UUID.fromString(assignee);if(Json.opt(t,"group","").isEmpty())require(assignee.equals(a.id()));else require(store.get(Json.str(t,"group")).getAsJsonObject("members").has(assignee));}String previous=Json.opt(t,"assignee","");t.addProperty("assignee",assignee);save(t);if(!assignee.isEmpty()&&!assignee.equals(previous)&&!assignee.equals(a.id()))store.taskNote(assignee,t,"workAssign",LocalizedText.parts(LocalizedText.key("rivet.core.you_have_been_assigned_a_task_f45dfd13"),LocalizedText.literal(Json.str(t,"title"))));}
   case "workDue" -> {require(manage);long due=in.get("dueAt").getAsBigDecimal().longValueExact();require(due>=0&&due<=System.currentTimeMillis()+3650L*86400000);long previous=t.get("dueAt").getAsLong();t.addProperty("dueAt",due);save(t);String assignee=Json.opt(t,"assignee","");if(previous!=due&&!assignee.equals(a.id()))store.taskNote(assignee,t,"workDue",LocalizedText.parts(LocalizedText.key("rivet.core.task_deadline_changed_f78a89c4"),LocalizedText.literal(Json.str(t,"title"))));}
   case "workComment" -> {String message=text(in,"text",500);require(!message.isEmpty());var comments=t.has("comments")?t.getAsJsonArray("comments"):new JsonArray();require(store.taskLimits().allowsComment(comments.size()));var row=new JsonObject();row.addProperty("author",a.name());row.addProperty("text",message);row.addProperty("at",System.currentTimeMillis());comments.add(row);t.add("comments",comments);save(t);}
   case "workSubtask" -> {var rows=t.has("subtasks")?t.getAsJsonArray("subtasks"):new JsonArray();if(in.has("index")){int index=in.get("index").getAsInt();require(index>=0&&index<rows.size());var row=rows.get(index).getAsJsonObject();require(manage||a.id().equals(Json.opt(row,"assignee","")));if(in.has("remove")&&in.get("remove").getAsBoolean()){require(manage);rows.remove(index);}else if(in.has("title")){require(manage);String title=text(in,"title",100);require(!title.isBlank());row.addProperty("title",title);}else row.addProperty("done",!row.get("done").getAsBoolean());}else{require(manage&&store.taskLimits().allowsSubtask(rows.size()));String title=text(in,"title",100),assignee=text(in,"assignee",100);require(!title.isBlank());if(!assignee.isEmpty()){UUID.fromString(assignee);if(Json.opt(t,"group","").isEmpty())require(assignee.equals(a.id()));else require(store.get(Json.str(t,"group")).getAsJsonObject("members").has(assignee));}var row=new JsonObject();row.addProperty("title",title);row.addProperty("done",false);row.addProperty("assignee",assignee);rows.add(row);}t.add("subtasks",rows);save(t);}
   case "workResources" -> {require(manage);var rows=in.getAsJsonArray("resources");require(rows!=null&&rows.size()<=30);ResourceRequirements.validate(rows);t.add("resources",rows.deepCopy());t.add("reservations",new JsonObject());save(t);}
   default -> throw new IllegalArgumentException(dev.abros.rivet.core.Messages.text("rivet.core.unknown_task_action_e97a5a6d"));
  }
  if(!op.equals("workGet")&&t.has("history")&&!t.getAsJsonArray("history").isEmpty()){var changes=ChangeSummary.betweenLocalized(beforeChange,t,Map.of("title",LocalizedText.key("rivet.map.name"),"description",LocalizedText.key("rivet.ui.description_f5441f6a"),"status",LocalizedText.key("rivet.ui.status_f7f293b5"),"assignee",LocalizedText.key("rivet.ui.assignee_46c1c6b4"),"dueAt",LocalizedText.key("rivet.core.deadline_71e1ea68"),"resources",LocalizedText.key("rivet.ui.resources_3e559b8c"),"dependencies",LocalizedText.key("rivet.core.dependencies_898afdf0"),"subtasks",LocalizedText.key("rivet.ui.steps_9adda405"),"archived",LocalizedText.key("rivet.core.archived_1cefdbc2"),"location",LocalizedText.key("rivet.core.destination_c55feeaf")));var last=t.getAsJsonArray("history").get(t.getAsJsonArray("history").size()-1).getAsJsonObject();last.add("changes",changes);try(var q=db.connection().prepareStatement("UPDATE community_group_items SET body=jsonb_set(body,'{history}',?::jsonb) WHERE id=?")){q.setString(1,t.getAsJsonArray("history").toString());q.setString(2,Json.str(t,"id"));q.executeUpdate();}}t=enrich(t,reservation);t.addProperty("manage",manage);t.addProperty("canAddSubtask",manage&&store.taskLimits().allowsSubtask(t.has("subtasks")?t.getAsJsonArray("subtasks").size():0));t.addProperty("canComment",store.taskLimits().allowsComment(t.has("comments")?t.getAsJsonArray("comments").size():0));t.addProperty("subtaskLimit",store.taskLimits().subtasks());t.addProperty("commentLimit",store.taskLimits().comments());TaskDetailPage.apply(t,in);out.add("task",t);boolean quota=store.taskLimits().perOwner()==0||store.taskLimits().allowsTask(ownerTaskCount(a.id()));out.addProperty("canCreate",(Json.opt(t,"group","").isEmpty()||manage)&&quota);out.addProperty("createReason",!quota?Messages.text("rivet.core.task_limit_reached_9b56eb6c")+store.taskLimits().perOwner():!manage?Messages.text("rivet.core.only_group_leaders_can_create_tasks_6238c437"):"");return out;
 }
 /** Generate at most one catch-up occurrence per schedule, without loading world chunks. */
 public void repeatDue(long now)throws Exception{
  db.lock("task-workflow");var due=new ArrayList<String>();try(var q=db.connection().prepareStatement("SELECT id FROM community_group_items WHERE kind='task' AND "+(store.modules().enabled("groups")?"true":"group_id IS NULL")+" AND coalesce((body->>'nextRepeatAt')::bigint,0)>0 AND (body->>'nextRepeatAt')::bigint<=? ORDER BY id LIMIT 20")){q.setLong(1,now);try(var rs=q.executeQuery()){while(rs.next())due.add(rs.getString(1));}}
  for(String id:due){var original=task(id,true);int days=original.get("repeatDays").getAsInt();String owner=Json.str(original,"owner"),group=Json.opt(original,"group","");boolean allowed=group.isEmpty();if(!group.isEmpty())try{allowed=Json.str(store.get(group),"status").equals("open");}catch(CommunityFailure missing){allowed=false;}try(var q=db.connection().prepareStatement("SELECT count(*) FROM community_group_items WHERE owner=? AND kind='task'")){q.setString(1,owner);try(var rs=q.executeQuery()){rs.next();allowed&=store.taskLimits().allowsTask(rs.getInt(1));}}
   if(allowed&& (group.isEmpty()||store.modules().enabled("groups"))){var next=original.deepCopy();for(String key:List.of("code","stocks","history","reservations","dependencies","dependencyDetails","repeatDays","nextRepeatAt","project"))next.remove(key);next.addProperty("id",UUID.randomUUID().toString());next.addProperty("revision",0);next.addProperty("status","open");next.addProperty("recurrenceOf",id);next.addProperty("dueAt",now+days*86400000L);next.add("comments",new JsonArray());if(!group.isEmpty()){var members=store.get(group).getAsJsonObject("members");if(!members.has(Json.opt(next,"assignee","")))next.addProperty("assignee","");if(next.has("subtasks"))for(var e:next.getAsJsonArray("subtasks"))if(!members.has(Json.opt(e.getAsJsonObject(),"assignee","")))e.getAsJsonObject().addProperty("assignee","");}if(next.has("subtasks"))for(var stage:next.getAsJsonArray("subtasks"))stage.getAsJsonObject().addProperty("done",false);save(next);store.note(owner,group.isEmpty()?"home":"groups",group.isEmpty()?Json.str(next,"id"):group,LocalizedText.parts(LocalizedText.key("rivet.core.recurring_task_created_e3deb838"),LocalizedText.literal(Json.str(next,"title"))));}
   if(!allowed)store.note(owner,group.isEmpty()?"home":"groups",group,LocalizedText.parts(LocalizedText.key("rivet.core.task_recurrence_stopped_group_closed_or_49663f0d")));
   original.addProperty("nextRepeatAt",allowed?now+days*86400000L:0);save(original);
  }
 }
 /** The sign author must have management rights, even if they know somebody else's code. */
 public String bind(CommunityStore.Actor actor,String label,String code,String location,JsonObject body)throws Exception{store.modules().require("storage");return db.communityTransaction(()->{String id;try(var q=db.connection().prepareStatement("SELECT task_id FROM community_task_codes WHERE code=?")){q.setString(1,TaskCodes.normalize(code));try(var rs=q.executeQuery()){if(!rs.next())throw new IllegalArgumentException(dev.abros.rivet.core.Messages.text("rivet.core.task_code_not_found_d7ab0042"));id=rs.getString(1);}}var t=task(id,false);require(access(actor,t,true));String group=Json.opt(t,"group","");String expected=group.isEmpty()?store.personName(Json.str(t,"owner")):Json.str(store.get(group),"title");require(label.strip().equalsIgnoreCase(expected));db.lock("task-stock:"+location);db.lock("task-stock-task:"+id);String inventory=Json.opt(body,"inventory",location);db.lock("task-inventory:"+inventory);try(var q=db.connection().prepareStatement("SELECT location FROM community_task_stocks WHERE body->>'inventory'=? AND location<>?")){q.setString(1,inventory);q.setString(2,location);try(var rs=q.executeQuery()){require(!rs.next());}}try(var q=db.connection().prepareStatement("SELECT task_id FROM community_task_stocks WHERE location=?")){q.setString(1,location);try(var rs=q.executeQuery()){if(rs.next())require(id.equals(rs.getString(1)));}}try(var q=db.connection().prepareStatement("SELECT count(*) FROM community_task_stocks WHERE task_id=? AND location<>?")){q.setString(1,id);q.setString(2,location);try(var rs=q.executeQuery()){rs.next();require(rs.getInt(1)<64);}}db.lock("task-stock-quota");try(var q=db.connection().createStatement();var rs=q.executeQuery("SELECT count(*) FROM community_task_stocks")){rs.next();require(rs.getInt(1)<4096||existingBinding(location));}try(var q=db.connection().prepareStatement("INSERT INTO community_task_stocks VALUES(?,?,?::jsonb) ON CONFLICT(location) DO NOTHING")){q.setString(1,location);q.setString(2,id);q.setString(3,body.toString());if(q.executeUpdate()>0)CommunityOutbox.add(db,group.isEmpty()?"home":"groups",group.isEmpty()?id:group,audience(t));}return id;});}
 private boolean existingBinding(String location)throws Exception{try(var q=db.connection().prepareStatement("SELECT 1 FROM community_task_stocks WHERE location=?")){q.setString(1,location);try(var rs=q.executeQuery()){return rs.next();}}}
 public JsonArray bindings()throws Exception{store.modules().require("storage");return db.communityTransaction(()->{var out=new JsonArray();try(var q=db.connection().createStatement();var rs=q.executeQuery("SELECT s.location,s.task_id,s.body FROM community_task_stocks s JOIN community_group_items t ON t.id=s.task_id WHERE "+(store.modules().enabled("groups")?"true":"t.group_id IS NULL")+" ORDER BY s.location LIMIT 4096")){while(rs.next()){var j=Json.parse(rs.getString(3));j.addProperty("key",rs.getString(1));j.addProperty("task",rs.getString(2));out.add(j);}}return out;});}
 public boolean stock(String location,JsonObject incoming,boolean remove)throws Exception{store.modules().require("storage");return db.communityTransaction(()->{JsonObject body=incoming.deepCopy();db.lock("task-stock-quota");String taskId="";JsonObject previous=null;try(var q=db.connection().prepareStatement("SELECT task_id,body FROM community_task_stocks WHERE location=? FOR UPDATE")){q.setString(1,location);try(var rs=q.executeQuery()){if(rs.next()){taskId=rs.getString(1);previous=Json.parse(rs.getString(2));}}}if(taskId.isEmpty())return false;if(!remove){String inventory=Json.opt(body,"inventory",location);try(var q=db.connection().prepareStatement("SELECT location FROM community_task_stocks WHERE body->>'inventory'=? AND location<? ORDER BY location LIMIT 1")){q.setString(1,inventory);q.setString(2,location);try(var rs=q.executeQuery()){if(rs.next()){body=body.deepCopy();body.add("items",new JsonObject());}}}}if(!remove){try(var q=db.connection().prepareStatement("UPDATE community_task_stocks SET body=jsonb_set(body,'{items}','{}'::jsonb) WHERE body->>'inventory'=? AND location>? AND body->'items'<>'{}'::jsonb RETURNING task_id")){q.setString(1,Json.opt(body,"inventory",location));q.setString(2,location);try(var rows=q.executeQuery()){while(rows.next()){var affected=task(rows.getString(1),false);String group=Json.opt(affected,"group","");CommunityOutbox.add(db,group.isEmpty()?"home":"groups",group.isEmpty()?Json.str(affected,"id"):group,audience(affected));}}}}try(var q=db.connection().prepareStatement(remove?"DELETE FROM community_task_stocks WHERE location=?":"UPDATE community_task_stocks SET body=?::jsonb WHERE location=?")){if(remove)q.setString(1,location);else{q.setString(1,body.toString());q.setString(2,location);}q.executeUpdate();}var t=task(taskId,false);if(remove||previous==null||!Objects.equals(previous.get("items"),body.get("items"))||!Objects.equals(previous.get("inventory"),body.get("inventory")))CommunityOutbox.add(db,Json.opt(t,"group","").isEmpty()?"home":"groups",Json.opt(t,"group","").isEmpty()?taskId:Json.str(t,"group"),audience(t));return true;});}
}
