package dev.abros.rivet.core;
import com.google.gson.*;
import java.util.*;
/** Support tickets share the server PostgreSQL database. */
public final class CommunityReports {
 private final CommunityStore db;
 public CommunityReports(CommunityStore db){this.db=db;}
 public String submit(UUID player,String name,JsonObject in,long now)throws Exception{return db.inTransaction(()->{db.checkReport(player.toString(),now);String message=Json.str(in,"message").strip();if(message.isEmpty()||message.length()>1500)throw new IllegalArgumentException("Текст обращения: 1–1500 символов");var j=new JsonObject();String id=UUID.randomUUID().toString();j.addProperty("id",id);j.addProperty("uuid",player.toString());j.addProperty("player",name);j.addProperty("createdAt",now);j.addProperty("message",message);j.addProperty("status","open");String category=Json.opt(in,"category","technical");if(!Set.of("technical","player","appeal","other").contains(category))throw new IllegalArgumentException("Неизвестная категория обращения");j.addProperty("category",category);j.addProperty("revision",1);for(String k:List.of("coreVersion","packVersion","repository","audit")){String v=Json.opt(in,k,"");if(v.length()>(k.equals("audit")?2000:512))throw new IllegalArgumentException("Поле слишком длинное");j.addProperty(k,v);}db.record("reports",id,j);return id;});}
 public JsonArray list(UUID owner,int page)throws Exception{if(page<0||page>1000)throw new IllegalArgumentException("Invalid page");var out=new JsonArray();db.recordPage("reports",owner==null?"":owner.toString(),page,5).forEach(j->out.add(owner==null?j:publicReport(j)));return out;}
 public JsonObject get(UUID owner,String id)throws Exception{UUID.fromString(id);var j=db.record("reports",id);if(j==null||!owner.toString().equals(Json.str(j,"uuid")))throw new IllegalArgumentException("Обращение не найдено");return publicReport(j);}
 public JsonArray list(int page)throws Exception{return list(null,page);}
 public void reply(String id,String author,String text,boolean resolved)throws Exception{db.transaction(()->{UUID.fromString(id);var j=db.record("reports",id);if(j==null)throw new IllegalArgumentException("Обращение не найдено");if(text.isBlank()||text.length()>1500)throw new IllegalArgumentException("Ответ: 1–1500 символов");j.addProperty("revision",j.get("revision").getAsLong()+1);j.addProperty("reply",text);j.addProperty("replyAuthor",author);j.addProperty("repliedAt",System.currentTimeMillis());j.addProperty("status",resolved?"resolved":"open");db.transaction(()->{db.record("reports",id,j);db.externalNotice(Json.str(j,"uuid"),"Ответ администрации на обращение",id);db.audit(author,"report reply",id);});});}
 public JsonObject submitRequest(UUID player,String name,JsonObject input,long now)throws Exception{return db.receipt(player.toString(),input,()->{String id=submit(player,name,input,now);var result=new JsonObject();result.addProperty("id",id);result.addProperty("text","Обращение отправлено");return result;});}
 public JsonObject replyRequest(String actor,String author,JsonObject input)throws Exception{return db.receipt(actor,input,()->{String id=Json.str(input,"id");var report=db.record("reports",id);if(report==null)throw new CommunityFailure(CommunityFailure.Code.NOT_FOUND,"Обращение не найдено");if(!input.has("revision")||input.get("revision").getAsLong()!=report.get("revision").getAsLong())throw new CommunityFailure(CommunityFailure.Code.CONFLICT,"Обращение уже изменилось. Откройте его заново; ваш ответ сохранён.");reply(id,author,Json.str(input,"text"),input.get("resolved").getAsBoolean());var out=new JsonObject();out.addProperty("text","Ответ сохранён");out.add("report",db.record("reports",id));return out;});}
 public JsonObject cursor(UUID owner,String token)throws Exception{var result=db.recordCursor("reports",owner==null?"":owner.toString(),token,5);if(owner!=null){var clean=new JsonArray();for(var e:result.getAsJsonArray("entries"))clean.add(publicReport(e.getAsJsonObject()));result.add("entries",clean);}return result;}
 public JsonObject manageRequest(String actor,String name,JsonObject input)throws Exception{if(Json.str(input,"operation").startsWith("bulk"))return bulk(actor,name,input);return db.receipt(actor,input,()->{String id=Json.str(input,"id");var report=db.record("reports",id);if(report==null)throw new CommunityFailure(CommunityFailure.Code.NOT_FOUND,"Обращение не найдено");if(!input.has("revision")||input.get("revision").getAsLong()!=report.get("revision").getAsLong())throw new CommunityFailure(CommunityFailure.Code.CONFLICT,"Обращение изменилось. Откройте его заново");var before=report.deepCopy();String operation=Json.str(input,"operation");switch(operation){
  case "claim" -> {String assigned=Json.opt(report,"assigned","");if(!assigned.isEmpty()&&!assigned.equals(actor))throw new CommunityFailure(CommunityFailure.Code.CONFLICT,"Обращением уже занимается другой администратор");report.addProperty("assigned",actor);report.addProperty("assignedName",name);}
  case "assign" -> {String target=Json.str(input,"target");UUID.fromString(target);report.addProperty("assigned",target);report.addProperty("assignedName",Json.str(input,"targetName"));}
  case "release" -> {if(!Json.opt(report,"assigned","").equals(actor))throw new CommunityFailure(CommunityFailure.Code.FORBIDDEN,"Снять назначение может ответственный администратор");report.remove("assigned");report.remove("assignedName");}
  case "classify" -> {String category=Json.str(input,"category"),priority=Json.str(input,"priority");if(!Set.of("technical","player","appeal","other").contains(category)||!Set.of("low","normal","high").contains(priority))throw new IllegalArgumentException("Некорректная категория или приоритет");report.addProperty("category",category);report.addProperty("priority",priority);}
  case "state" -> {String state=Json.str(input,"status"),step=Json.opt(input,"nextStep","").strip();if(!Set.of("open","waiting","resolved").contains(state)||step.length()>300)throw new IllegalArgumentException("Некорректный следующий шаг");report.addProperty("status",state);report.addProperty("nextStep",step);}
  case "note" -> {String text=Json.str(input,"text").strip();if(text.isBlank()||text.length()>1000)throw new IllegalArgumentException("Заметка: 1–1000 символов");var notes=report.has("internalNotes")?report.getAsJsonArray("internalNotes"):new JsonArray();if(notes.size()>=30)throw new IllegalArgumentException("Достигнут предел заметок");var note=new JsonObject();note.addProperty("author",name);note.addProperty("text",text);note.addProperty("at",System.currentTimeMillis());notes.add(note);report.add("internalNotes",notes);}
  default -> throw new IllegalArgumentException("Неизвестное действие обращения");}
  report.addProperty("revision",report.get("revision").getAsLong()+1);db.record("reports",id,report);auditChange(name,"report "+operation,id,before,report,Json.opt(input,"reason","Административное изменение"));var out=new JsonObject();out.addProperty("kind","result");out.addProperty("text","Сохранено");out.add("report",report);return out;});}

 public JsonObject queue(String actor,String filter,String query,String token)throws Exception{return db.inTransaction(()->{
  if(!Set.of("all","new","mine","waiting","resolved","unassigned","high").contains(filter)||query.length()>100)throw new IllegalArgumentException("Некорректный фильтр");
  String scope="reports:"+actor+":"+filter+":"+query;long before=Long.MAX_VALUE,ceiling=Long.MAX_VALUE;if(!token.isEmpty()){var c=CommunityCursor.decode(token,scope);before=c.sequence();ceiling=c.ceiling();}
  var rows=new JsonArray();long last=0;var out=new JsonObject();out.addProperty("nextCursor","");
  String predicate=switch(filter){case "new"->"body->>'status'='open' AND coalesce(body->>'assigned','')='' AND coalesce(body->>'reply','')=''";case "mine"->"body->>'assigned'=? AND body->>'status'<>'resolved'";case "waiting"->"body->>'status'='waiting'";case "resolved"->"body->>'status'='resolved'";case "unassigned"->"coalesce(body->>'assigned','')='' AND body->>'status'<>'resolved'";case "high"->"body->>'priority'='high' AND body->>'status'<>'resolved'";default->"TRUE";};
  try(var q=db.connection().prepareStatement("SELECT body,sequence FROM records WHERE namespace='reports' AND sequence<? AND sequence<=? AND ("+predicate+") AND strpos(lower(coalesce(body->>'player','')||' '||coalesce(body->>'message','')),lower(?))>0 ORDER BY sequence DESC LIMIT 11")){
   int n=1;q.setLong(n++,before);q.setLong(n++,ceiling);if(filter.equals("mine"))q.setString(n++,actor);q.setString(n,query);try(var rs=q.executeQuery()){while(rs.next()){if(rows.size()==10){out.addProperty("nextCursor",new CommunityCursor(last,0,ceiling,scope).encode());break;}var row=Json.parse(rs.getString(1));last=rs.getLong(2);if(rows.isEmpty()&&ceiling==Long.MAX_VALUE)ceiling=last;rows.add(row);}}
  }out.add("entries",rows);return out;
 });}
 private JsonObject bulk(String actor,String name,JsonObject input)throws Exception{
  boolean apply=Json.str(input,"operation").equals("bulkApply");if(!apply&&!Json.str(input,"operation").equals("bulkPreview"))throw new IllegalArgumentException("Неизвестное действие");
  PgDatabase.Work<JsonObject> work=()->{String change=Json.str(input,"change");if(!Set.of("claim","resolved","high").contains(change))throw new IllegalArgumentException("Некорректное массовое действие");var requested=input.getAsJsonArray("items");if(requested==null||requested.isEmpty()||requested.size()>20)throw new IllegalArgumentException("Выберите от 1 до 20 обращений");var refs=new TreeMap<String,Long>();for(var e:requested){var ref=e.getAsJsonObject();String id=Json.str(ref,"id");UUID.fromString(id);if(refs.put(id,ref.get("revision").getAsLong())!=null)throw new IllegalArgumentException("Повторяющаяся запись");}
   int affected=0,skipped=0;var rows=new JsonArray();for(var ref:refs.entrySet()){var report=db.record("reports",ref.getKey());String reason="";if(report==null)reason="Удалено";else if(report.get("revision").getAsLong()!=ref.getValue())reason="Изменилось после выбора";else if(Json.opt(report,"status","open").equals("resolved"))reason="Уже закрыто";else if(change.equals("claim")&&!Json.opt(report,"assigned","").isEmpty()&&!Json.opt(report,"assigned","").equals(actor))reason="Другой ответственный";
    var row=new JsonObject();row.addProperty("id",ref.getKey());row.addProperty("title",report==null?"Обращение удалено":Json.opt(report,"player","Игрок"));row.addProperty("reason",reason);if(report!=null){String key=change.equals("claim")?"assignedName":change.equals("resolved")?"status":"priority";row.addProperty("before",Json.opt(report,key,"Не задано"));row.addProperty("after",change.equals("claim")?name:change.equals("resolved")?"resolved":"high");}rows.add(row);if(!reason.isEmpty()){skipped++;continue;}affected++;
    if(apply){var before=report.deepCopy();if(change.equals("claim")){report.addProperty("assigned",actor);report.addProperty("assignedName",name);}else if(change.equals("resolved")){report.addProperty("status","resolved");db.externalNotice(Json.str(report,"uuid"),"Обращение закрыто администрацией",ref.getKey());}else report.addProperty("priority","high");report.addProperty("revision",ref.getValue()+1);db.record("reports",ref.getKey(),report);auditChange(name,"report bulk "+change,ref.getKey(),before,report,Json.opt(input,"reason","Массовое действие администрации"));}
   }var out=new JsonObject();out.addProperty("kind","community");out.addProperty("request",Json.opt(input,"request",""));out.addProperty("affected",affected);out.addProperty("skipped",skipped);out.addProperty("applied",apply);out.add("preview",rows);return out;
  };return apply?db.receipt(actor,input,work):db.inTransaction(work);
 }
 private void auditChange(String actor,String action,String id,JsonObject before,JsonObject after,String reason)throws Exception{if(reason.length()>300)throw new IllegalArgumentException("Причина: до 300 символов");var changes=ChangeSummary.between(before,after,Map.of("status","Статус","priority","Приоритет","category","Категория","assignedName","Ответственный","nextStep","Следующий шаг"));var parts=new ArrayList<String>();parts.add(id);for(var e:changes){var c=e.getAsJsonObject();parts.add(Json.str(c,"label")+": "+ChangeSummary.text(c.get("before"))+" → "+ChangeSummary.text(c.get("after")));}parts.add("Причина: "+reason);db.audit(actor,action,String.join(" · ",parts));}
 private static JsonObject publicReport(JsonObject j){var clean=j.deepCopy();for(String key:List.of("internalNotes","assigned","assignedName","priority"))clean.remove(key);return clean;}
 public JsonObject dashboard()throws Exception{return db.inTransaction(()->{var result=new JsonObject();try(var q=db.connection().createStatement();var rs=q.executeQuery("SELECT count(*) FILTER(WHERE body->>'status'<>'resolved'),count(*) FILTER(WHERE body->>'status'<>'resolved' AND coalesce(body->>'assigned','')=''),count(*) FILTER(WHERE body->>'status'<>'resolved' AND body->>'priority'='high') FROM records WHERE namespace='reports'")){rs.next();result.addProperty("openReports",rs.getLong(1));result.addProperty("unassignedReports",rs.getLong(2));result.addProperty("highReports",rs.getLong(3));}var attention=new JsonArray();try(var q=db.connection().createStatement();var rs=q.executeQuery("SELECT body FROM records WHERE namespace='reports' AND body->>'status'<>'resolved' ORDER BY (body->>'priority'='high') DESC NULLS LAST,(coalesce(body->>'assigned','')='') DESC,(body->>'createdAt')::bigint ASC,id ASC LIMIT 6")){while(rs.next()){var item=JsonParser.parseString(rs.getString(1)).getAsJsonObject();String why=Json.opt(item,"priority","normal").equals("high")?"Высокий приоритет":"Ожидает ответа";if(Json.opt(item,"assigned","").isBlank())why+=" · Без ответственного";item.addProperty("attentionReason",why);attention.add(item);}}result.add("attentionReports",attention);return result;});}
 public void prune(long now)throws Exception{db.pruneReports(now);}
}
