package dev.abros.rivet.core;
import com.google.gson.*;
import java.util.*;
/** One transactional vote per server database. Private electorate and ballots never enter public views. */
public final class ModerationVotes {
 public record Settings(boolean enabled,int minimumPlayers,int durationSeconds,int minimumPlayMinutes,int initiatorCooldownMinutes,int targetCooldownMinutes,boolean kick,boolean ban,boolean mute){
  public Settings{if(minimumPlayers<5||minimumPlayers>300||durationSeconds<30||durationSeconds>600||minimumPlayMinutes<0||minimumPlayMinutes>10080||initiatorCooldownMinutes<1||initiatorCooldownMinutes>10080||targetCooldownMinutes<1||targetCooldownMinutes>10080)throw new IllegalArgumentException("Invalid moderation vote settings");}
  public static Settings defaults(){return new Settings(false,5,120,120,30,60,true,true,true);}
  public static Settings read(JsonObject j){var defaults=Json.GSON.toJsonTree(defaults()).getAsJsonObject();for(String key:j.keySet())if(!defaults.has(key))throw new IllegalArgumentException("Unknown vote setting: "+key);for(var entry:j.entrySet()){var expected=defaults.get(entry.getKey()).getAsJsonPrimitive();if(!entry.getValue().isJsonPrimitive()||expected.isBoolean()&&!entry.getValue().getAsJsonPrimitive().isBoolean()||expected.isNumber()&&!entry.getValue().getAsJsonPrimitive().isNumber())throw new IllegalArgumentException("Invalid vote setting: "+entry.getKey());defaults.add(entry.getKey(),entry.getValue());}return Json.GSON.fromJson(defaults,Settings.class);}
 }
 private final PgDatabase db;private final Settings settings;
 public ModerationVotes(PgDatabase db,Settings settings){this.db=db;this.settings=settings;}
 public Settings settings(){return settings;}
 private JsonObject get(String id)throws Exception{try(var q=db.connection().prepareStatement("SELECT body FROM records WHERE namespace='moderation-votes' AND id=?")){q.setString(1,id);try(var row=q.executeQuery()){return row.next()?Json.parse(row.getString(1)):null;}}}
 private void put(String id,JsonObject j)throws Exception{try(var q=db.connection().prepareStatement("INSERT INTO records(namespace,id,body) VALUES('moderation-votes',?,?::jsonb) ON CONFLICT(namespace,id) DO UPDATE SET body=excluded.body")){q.setString(1,id);q.setString(2,Json.GSON.toJson(j));q.executeUpdate();}CommunityOutbox.add(db,"polls","","");}
 private void lock()throws Exception{db.lock("moderation-vote");}
 private static void require(boolean condition,String message){if(!condition)throw new IllegalArgumentException(message);}
 private void cooldown(String key,long now,int minutes)throws Exception{var previous=get(key);require(previous==null||now-previous.get("at").getAsLong()>=minutes*60000L,"Подождите перед следующим голосованием");var j=new JsonObject();j.addProperty("at",now);put(key,j);}
 public JsonObject start(UUID initiator,UUID target,String name,String action,String reason,Set<UUID> electorate,long playedMillis,boolean protectedTarget,boolean voiceAvailable,JsonObject request,long now)throws Exception{
  return db.communityTransaction(()->{lock();return new RequestJournal(db).execute(initiator.toString(),request,()->{
   require(settings.enabled(),"Голосования о нарушениях выключены администрацией");require(!initiator.equals(target)&&!protectedTarget,"Этого игрока нельзя выбрать");
   require(playedMillis>=settings.minimumPlayMinutes()*60000L,"Недостаточно учтённого времени игры");
   require(Set.of("kick","ban","mute").contains(action),"Неизвестная мера");require(action.equals("kick")?settings.kick():action.equals("ban")?settings.ban():settings.mute()&&voiceAvailable,"Мера недоступна");
   require(!reason.isBlank()&&reason.length()<=300&&reason.codePoints().noneMatch(Character::isISOControl),"Укажите причину до 300 символов");
   int minutes=action.equals("kick")?0:request.has("minutes")?request.get("minutes").getAsBigDecimal().intValueExact():action.equals("ban")?30:15;require(action.equals("kick")||minutes>=1&&minutes<=1440,"Срок наказания: от 1 до 1440 минут");
   var eligible=new HashSet<>(electorate);eligible.remove(target);require(eligible.contains(initiator)&&eligible.size()>=settings.minimumPlayers()&&eligible.size()<=300,"Недостаточно подходящих игроков онлайн");
   var old=get("current");require(old==null||!Set.of("open","applying").contains(Json.str(old,"status")),"Уже идёт голосование о нарушении");
   cooldown("initiator:"+initiator,now,settings.initiatorCooldownMinutes());cooldown("target:"+target,now,settings.targetCooldownMinutes());
   var j=new JsonObject();j.addProperty("id",UUID.randomUUID().toString());j.addProperty("initiator",initiator.toString());j.addProperty("target",target.toString());j.addProperty("name",name);j.addProperty("action",action);j.addProperty("reason",reason.strip());j.addProperty("status","open");j.addProperty("started",now);j.addProperty("endsAt",now+settings.durationSeconds()*1000L);j.addProperty("minutes",minutes);j.add("eligible",Json.GSON.toJsonTree(eligible.stream().map(UUID::toString).sorted().toList()));j.add("ballots",new JsonObject());put("current",j);return view(j,initiator);
  });});
 }
 public JsonObject vote(UUID player,String id,boolean yes,long now)throws Exception{return db.communityTransaction(()->{lock();var j=get("current");require(j!=null&&Json.str(j,"id").equals(id)&&Json.str(j,"status").equals("open")&&now<j.get("endsAt").getAsLong(),"Голосование завершено");require(!Json.str(j,"target").equals(player.toString()),"Нельзя голосовать по жалобе на себя");j.getAsJsonObject("ballots").addProperty(player.toString(),yes);put("current",j);return view(j,player);});}
 public JsonObject cancel(String id,String actor,String reason,long now)throws Exception{return db.communityTransaction(()->{lock();var j=get("current");require(j!=null&&Json.str(j,"id").equals(id)&&Json.str(j,"status").equals("open"),"Голосование уже завершено или применяется");require(!reason.isBlank()&&reason.length()<=300,"Укажите причину отмены");j.addProperty("status","cancelled");j.addProperty("outcome","Отменено модератором: "+reason);j.addProperty("cancelledBy",actor);j.addProperty("finishedAt",now);put("current",j);history(j,now);return view(j,null);});}
 public static boolean passed(int yes,int no,int eligible){return yes+no>0&&yes*3L>=2L*(yes+no)&&yes*2L>=eligible;}
 /** Claims once before any external side effect. Cancellation and claim use the same lock. */
 public JsonObject claim(long now)throws Exception{return db.communityTransaction(()->{lock();var j=get("current");if(j==null||!Json.str(j,"status").equals("open")||now<j.get("endsAt").getAsLong())return null;int yes=0,no=0;for(var ballot:j.getAsJsonObject("ballots").entrySet())if(ballot.getValue().getAsBoolean())yes++;else no++;
  if(!passed(yes,no,j.getAsJsonArray("eligible").size())){j.addProperty("status","rejected");j.addProperty("outcome","Недостаточно голосов за применение меры");j.addProperty("finishedAt",now);put("current",j);history(j,now);return null;}
  j.addProperty("status","applying");put("current",j);return j.deepCopy();});}
 public void finish(String id,boolean success,String outcome,long now)throws Exception{db.communityTransaction(()->{lock();var j=get("current");if(j==null||!Json.str(j,"id").equals(id)||!Json.str(j,"status").equals("applying"))return null;j.addProperty("status",success?"applied":"failed");j.addProperty("outcome",outcome);j.addProperty("finishedAt",now);put("current",j);
  history(j,now);return null;});}
 private void history(JsonObject j,long now)throws Exception{
  var audit=new JsonObject();audit.addProperty("uuid",Json.str(j,"target"));audit.addProperty("actor",Json.opt(j,"cancelledBy","Голосование игроков"));audit.addProperty("action",Json.str(j,"action"));audit.addProperty("reason",Json.str(j,"reason"));audit.addProperty("at",now);audit.addProperty("outcome",Json.opt(j,"outcome",Json.str(j,"status")));audit.addProperty("status",Json.str(j,"status"));if(Json.str(j,"status").equals("applied")&&j.get("minutes").getAsInt()>0)audit.addProperty("until",now+j.get("minutes").getAsLong()*60000);
  try(var q=db.connection().prepareStatement("INSERT INTO records(namespace,id,body) VALUES('moderation-history',?,?::jsonb) ON CONFLICT(namespace,id) DO NOTHING")){q.setString(1,Json.str(j,"id"));q.setString(2,Json.GSON.toJson(audit));q.executeUpdate();}
 }
 public void restart()throws Exception{db.communityTransaction(()->{lock();var j=get("current");if(j!=null&&Set.of("open","applying").contains(Json.str(j,"status"))){boolean applying=Json.str(j,"status").equals("applying");j.addProperty("status",applying?"uncertain":"cancelled");j.addProperty("outcome",applying?"Сервер перезапущен во время применения; результат требует проверки модератором":"Отменено из-за перезапуска сервера");put("current",j);history(j,System.currentTimeMillis());}return null;});}
 public JsonObject current(UUID viewer)throws Exception{return db.communityTransaction(()->{var j=get("current");return j==null?new JsonObject():view(j,viewer);});}
 private JsonObject view(JsonObject j,UUID viewer){var out=new JsonObject();for(String key:List.of("id","target","name","action","reason","status","endsAt","minutes","outcome"))if(j.has(key))out.add(key,j.get(key));int yes=0,no=0;for(var ballot:j.getAsJsonObject("ballots").entrySet())if(ballot.getValue().getAsBoolean())yes++;else no++;out.addProperty("yes",yes);out.addProperty("no",no);out.addProperty("eligibleCount",j.getAsJsonArray("eligible").size());out.addProperty("canVote",viewer!=null&&!Json.str(j,"target").equals(viewer.toString())&&Json.str(j,"status").equals("open")&&System.currentTimeMillis()<j.get("endsAt").getAsLong());if(viewer!=null&&j.getAsJsonObject("ballots").has(viewer.toString()))out.add("myVote",j.getAsJsonObject("ballots").get(viewer.toString()));return out;}
}
