package dev.abros.rivet.core;
import com.google.gson.*;
final class NoticeActions {
 static JsonObject apply(PgDatabase db,CommunityStore store,CommunityStore.Actor actor,JsonObject input)throws Exception {
  long id=input.get("id").getAsLong();JsonObject notice;try(var q=db.connection().prepareStatement("SELECT body FROM notices WHERE recipient=? AND id=?")){q.setString(1,actor.id());q.setLong(2,id);try(var rs=q.executeQuery()){if(!rs.next())throw new CommunityFailure(CommunityFailure.Code.NOT_FOUND,"Уведомление не найдено");notice=Json.parse(rs.getString(1));}}
  String section=Json.opt(notice,"routeSection",Json.opt(notice,"section","")),target=Json.opt(notice,"routeId",Json.opt(notice,"target",""));store.modules().require(section);String event=Json.opt(notice,"event","");boolean invitation=section.equals("groups")&&event.equals("invite");boolean join=section.equals("events")&&java.util.Set.of("plusEventInvite","reminder").contains(event);if(!invitation&&!join)throw new CommunityFailure(CommunityFailure.Code.FORBIDDEN,"Быстрое действие недоступно");var document=store.get(target,true);if(join&&(!input.has("confirmConflicts")||!input.get("confirmConflicts").getAsBoolean())){var conflicts=EventConflicts.read(db,store,actor,document);if(!conflicts.isEmpty()){var out=new JsonObject();out.addProperty("kind","community");out.addProperty("request",Json.opt(input,"request",""));out.add("conflicts",conflicts);return out;}}var command=new JsonObject();command.addProperty("id",target);command.addProperty("section",section);command.addProperty("op",invitation?"invitation":"join");command.addProperty("accept",true);command.add("revision",document.get("revision"));store.execute(actor,command,Json.str(command,"op"),section);try(var q=db.connection().prepareStatement("UPDATE notices SET read=1 WHERE recipient=? AND id=?")){q.setString(1,actor.id());q.setLong(2,id);q.executeUpdate();}var out=new JsonObject();out.addProperty("kind","community");out.addProperty("request",Json.opt(input,"request",""));out.addProperty("noticeActionApplied",true);return out;
 }
 private NoticeActions(){}
}
