package dev.abros.rivet.core;
import com.google.gson.*;import java.util.*;import java.time.Instant;
/** Durable publication: state and recipient notices commit together, so retries cannot duplicate delivery. */
public final class ScheduledAnnouncements {
 private final CommunityStore store;public ScheduledAnnouncements(CommunityStore store){this.store=store;}
 public JsonObject request(String actor,String name,JsonObject in,long now)throws Exception{
  String op=Json.str(in,"op");if(op.equals("list"))return store.inTransaction(()->list(in));if(op.equals("preview")){var out=validated(in,now);out.addProperty("request",Json.opt(in,"request",""));out.addProperty("kind","community");return out;}
  return store.receipt(actor,in,()->{store.lockAnnouncements();var rows=store.records("scheduled-announcements");if(op.equals("create")){if(rows.stream().filter(r->Json.opt(r,"status","").equals("pending")).count()>=50)throw new IllegalArgumentException("Можно запланировать не более 50 объявлений");var row=validated(in,now);String id=UUID.randomUUID().toString();row.addProperty("id",id);row.addProperty("author",name);row.addProperty("revision",1);row.addProperty("status","pending");store.record("scheduled-announcements",id,row);store.audit(name,"announcement scheduled",row.get("text").getAsString()+" · "+Instant.ofEpochMilli(row.get("at").getAsLong()));}else if(op.equals("cancel")){String id=Json.str(in,"id");UUID.fromString(id);var row=store.record("scheduled-announcements",id);if(row==null||!Json.opt(row,"status","").equals("pending"))throw new CommunityFailure(CommunityFailure.Code.CONFLICT,"Объявление уже опубликовано или отменено");if(!in.has("revision")||in.get("revision").getAsLong()!=row.get("revision").getAsLong())throw new CommunityFailure(CommunityFailure.Code.CONFLICT,"Объявление изменилось");row.addProperty("status","cancelled");row.addProperty("revision",row.get("revision").getAsLong()+1);store.record("scheduled-announcements",id,row);store.audit(name,"announcement cancelled",id);}else throw new IllegalArgumentException("Неизвестное действие");return list(in);});
 }
 private static JsonObject validated(JsonObject in,long now){String text=Json.str(in,"text").strip();if(text.isEmpty()||text.length()>500||text.codePoints().anyMatch(c->Character.isISOControl(c)&&c!='\n'))throw new IllegalArgumentException("Сообщение: 1–500 символов");long at=Instant.parse(Json.str(in,"startsAt")).toEpochMilli();if(at<now+10000||at>now+30L*86400000)throw new IllegalArgumentException("Время: от 10 секунд до 30 дней вперёд");var row=new JsonObject();row.addProperty("text",text);row.addProperty("at",at);return row;}
 private JsonObject list(JsonObject in)throws Exception{var out=new JsonObject();out.addProperty("kind","community");out.addProperty("request",Json.opt(in,"request",""));var rows=new JsonArray();store.records("scheduled-announcements").stream().filter(r->Json.opt(r,"status","").equals("pending")).sorted(Comparator.comparingLong(r->r.get("at").getAsLong())).limit(50).forEach(rows::add);out.add("announcements",rows);return out;}
 public int publish(long now,Collection<String> recipients)throws Exception{return store.inTransaction(()->{store.lockAnnouncements();int delivered=0;for(var candidate:store.records("scheduled-announcements")){if(!Json.opt(candidate,"status","").equals("pending")||candidate.get("at").getAsLong()>now)continue;String id=Json.str(candidate,"id");var current=store.record("scheduled-announcements",id);if(!Json.opt(current,"status","").equals("pending"))continue;for(String recipient:new TreeSet<>(recipients))store.announcementNotice(recipient,id,Json.str(current,"text"));current.addProperty("status","published");current.addProperty("publishedAt",now);current.addProperty("revision",current.get("revision").getAsLong()+1);store.record("scheduled-announcements",id,current);store.audit("server","announcement published",id+" · "+recipients.size()+" получателей");delivered++;}try(var q=store.connection().prepareStatement("DELETE FROM records WHERE namespace='scheduled-announcements' AND body->>'status'<>'pending' AND sequence NOT IN (SELECT sequence FROM records WHERE namespace='scheduled-announcements' AND body->>'status'<>'pending' ORDER BY sequence DESC LIMIT 100)")){q.executeUpdate();}return delivered;});}
}
