package dev.abros.rivet.core;
import com.google.gson.*;
import java.util.*;
/** Task planning rules, separate from transport and inventory scanning. Caller holds the workflow lock. */
final class TaskWorkflow {
 private final PgDatabase db;private final CommunityStore store;
 TaskWorkflow(PgDatabase db,CommunityStore store){this.db=db;this.store=store;}
 private static void check(boolean yes,String message){if(!yes)throw new IllegalArgumentException(message);}
 static boolean sameScope(JsonObject a,JsonObject b){String group=Json.opt(a,"group","");return group.equals(Json.opt(b,"group",""))&&(!group.isEmpty()||Json.str(a,"owner").equals(Json.str(b,"owner")));}
 JsonObject get(String id)throws Exception{try(var q=db.connection().prepareStatement("SELECT body,group_id,owner FROM community_group_items WHERE id=? AND kind='task'")){q.setString(1,id);try(var rs=q.executeQuery()){if(!rs.next())throw new CommunityFailure(CommunityFailure.Code.NOT_FOUND,"Задача не найдена");var t=Json.parse(rs.getString(1));t.addProperty("id",id);t.addProperty("group",Objects.toString(rs.getString(2),""));t.addProperty("owner",rs.getString(3));return t;}}}
 String fromCode(String code)throws Exception{try(var q=db.connection().prepareStatement("SELECT task_id FROM community_task_codes WHERE code=?")){q.setString(1,TaskCodes.normalize(code));try(var rs=q.executeQuery()){check(rs.next(),"Код задачи не найден");return rs.getString(1);}}}
 void dependencies(JsonObject t,String codes)throws Exception{
  var ids=new LinkedHashSet<String>();for(String code:codes.strip().split("[\\s,;]+"))if(!code.isBlank())ids.add(fromCode(code));check(ids.size()<=10,"Не более 10 зависимостей");
  for(String id:ids){check(sameScope(t,get(id)),"Зависимости должны принадлежать тому же игроку или объединению");var pending=new ArrayDeque<String>();var seen=new HashSet<String>();pending.add(id);while(!pending.isEmpty()){String next=pending.removeFirst();check(!next.equals(Json.str(t,"id")),"Зависимости образуют цикл");if(!seen.add(next))continue;check(seen.size()<=200,"Слишком длинная цепочка задач");var task=get(next);if(task.has("dependencies"))for(var e:task.getAsJsonArray("dependencies"))pending.add(e.getAsString());}}
  var rows=new JsonArray();ids.forEach(rows::add);t.add("dependencies",rows);
 }
 JsonArray dependencies(JsonObject t)throws Exception{var rows=new JsonArray();if(t.has("dependencies"))for(var e:t.getAsJsonArray("dependencies")){try{var dep=get(e.getAsString());if(!sameScope(t,dep))continue;var row=new JsonObject();row.addProperty("id",Json.str(dep,"id"));row.addProperty("title",Json.str(dep,"title"));row.addProperty("done",Json.opt(dep,"status","open").equals("done"));try(var q=db.connection().prepareStatement("SELECT code FROM community_task_codes WHERE task_id=?")){q.setString(1,Json.str(dep,"id"));try(var rs=q.executeQuery()){if(rs.next())row.addProperty("code",rs.getString(1));}}rows.add(row);}catch(CommunityFailure removed){var row=new JsonObject();row.addProperty("title","Зависимая задача удалена");row.addProperty("done",false);rows.add(row);}}return rows;}
 void start(JsonObject t)throws Exception{for(var e:dependencies(t))check(e.getAsJsonObject().get("done").getAsBoolean(),"Сначала завершите блокирующие задачи");}
 JsonObject stock(JsonObject t)throws Exception{
  var out=new JsonObject();var wanted=new HashSet<String>();if(t.has("resources"))for(var e:t.getAsJsonArray("resources"))wanted.addAll(ResourceRequirements.items(e.getAsJsonObject()));var inventories=new HashSet<String>();String group=Json.opt(t,"group","");
  try(var q=db.connection().prepareStatement("SELECT s.body,s.location FROM community_task_stocks s JOIN community_group_items t ON t.id=s.task_id WHERE t.kind='task' AND ((?='' AND t.group_id IS NULL AND t.owner=?) OR t.group_id=?) ORDER BY s.location")){q.setString(1,group);q.setString(2,Json.str(t,"owner"));q.setString(3,group);try(var rs=q.executeQuery()){while(rs.next()){var s=Json.parse(rs.getString(1));if(!inventories.add(Json.opt(s,"inventory",rs.getString(2)))||!s.has("items"))continue;for(var e:s.getAsJsonObject("items").entrySet())if(wanted.contains(e.getKey()))out.addProperty(e.getKey(),(out.has(e.getKey())?out.get(e.getKey()).getAsLong():0)+e.getValue().getAsLong());}}}return out;
 }
 JsonObject reserved(JsonObject t)throws Exception{var out=new JsonObject();String group=Json.opt(t,"group","");try(var q=db.connection().prepareStatement("SELECT body->'reservations' FROM community_group_items WHERE kind='task' AND id<>? AND coalesce(body->>'status','open')<>'done' AND ((?='' AND group_id IS NULL AND owner=?) OR group_id=?) AND jsonb_exists(body,'reservations')")){q.setString(1,Json.str(t,"id"));q.setString(2,group);q.setString(3,Json.str(t,"owner"));q.setString(4,group);try(var rs=q.executeQuery()){while(rs.next()){var j=Json.parse(rs.getString(1));for(var e:j.entrySet())out.addProperty(e.getKey(),(out.has(e.getKey())?out.get(e.getKey()).getAsLong():0)+e.getValue().getAsLong());}}}return out;}
 void reserve(JsonObject t,boolean release)throws Exception{db.lock("task-stock-quota");var rows=new JsonObject();if(!release){check(!Json.opt(t,"status","open").equals("done"),"Завершённой задаче резерв не нужен");var stock=stock(t);var used=reserved(t);if(t.has("resources"))rows=ResourceRequirements.reserve(t.getAsJsonArray("resources"),stock,used);}t.add("reservations",rows);}
 static void repeat(JsonObject t,int days,long now){check(Set.of(0,1,7,30).contains(days),"Неподдерживаемый интервал");t.addProperty("repeatDays",days);long due=t.has("dueAt")?t.get("dueAt").getAsLong():0;t.addProperty("nextRepeatAt",days==0?0:Math.max(due,now)+days*86400000L);}
 static void history(JsonObject t,CommunityStore.Actor a,String op){var rows=t.has("history")?t.getAsJsonArray("history"):new JsonArray();while(rows.size()>=60)rows.remove(0);var row=new JsonObject();row.addProperty("at",System.currentTimeMillis());row.addProperty("author",a.name());row.addProperty("actor",a.id());row.addProperty("reason",op.equals("workArchiveApply")?"Архив завершённых задач":op.equals("workRestore")?"Возврат задачи из архива":"Изменение задачи");row.addProperty("operation",op);for(String key:List.of("status","assignee","dueAt","repeatDays"))if(t.has(key))row.add(key,t.get(key));rows.add(row);t.add("history",rows);}
}
