package dev.abros.rivet.core;
import com.google.gson.*;import java.util.*;
/** Bounded preview/apply: every selected revision and current management right are rechecked. */
final class TaskArchive {
 static JsonObject request(PgDatabase db,CommunityTasks tasks,CommunityStore.Actor actor,JsonObject input)throws Exception {
  String group=Json.opt(input,"group",""),op=Json.str(input,"op");if(!Set.of("workArchivePreview","workArchiveApply").contains(op))throw new IllegalArgumentException("Unknown archive action");var probe=new JsonObject();probe.addProperty("group",group);probe.addProperty("owner",actor.id());if(!tasks.access(actor,probe,true))throw new CommunityFailure(CommunityFailure.Code.FORBIDDEN,"Нет прав управления задачами");var out=new JsonObject();out.addProperty("kind","community");out.addProperty("request",Json.opt(input,"request",""));var rows=new JsonArray();boolean apply=op.equals("workArchiveApply");
  if(!apply){int days=input.has("days")?input.get("days").getAsInt():0;if(!Set.of(0,7,30).contains(days))throw new IllegalArgumentException("Invalid archive period");long before=days==0?Long.MAX_VALUE:System.currentTimeMillis()-days*86400000L;try(var q=db.connection().prepareStatement("SELECT id,body,revision FROM community_group_items WHERE kind='task' AND ((?='' AND group_id IS NULL AND owner=?) OR group_id=?) AND body->>'status'='done' AND coalesce(body->>'archived','false')<>'true' AND (?=0 OR coalesce((body->>'completedAt')::bigint,0)>0 AND (body->>'completedAt')::bigint<=?) ORDER BY id LIMIT 201")){q.setString(1,group);q.setString(2,actor.id());q.setString(3,group);q.setInt(4,days);q.setLong(5,before);try(var rs=q.executeQuery()){while(rs.next()){var task=Json.parse(rs.getString(2));long completed=task.has("completedAt")?task.get("completedAt").getAsLong():0;if(days>0&&(completed==0||completed>before))continue;if(rows.size()==200){out.addProperty("more",true);break;}var row=new JsonObject();row.addProperty("id",rs.getString(1));row.addProperty("revision",rs.getLong(3));row.addProperty("title",Json.opt(task,"title","Задача"));rows.add(row);}}}}
  else {var selected=input.getAsJsonArray("items");if(selected==null||selected.isEmpty()||selected.size()>200)throw new IllegalArgumentException("Выберите 1–200 задач");var ids=new TreeMap<String,Long>();for(var e:selected){var ref=e.getAsJsonObject();String id=Json.str(ref,"id");UUID.fromString(id);if(ids.put(id,ref.get("revision").getAsLong())!=null)throw new IllegalArgumentException("Повторная задача");}var verified=new ArrayList<JsonObject>();for(var ref:ids.entrySet()){var task=tasks.task(ref.getKey(),true);if(!tasks.access(actor,task,true)||!group.equals(Json.opt(task,"group","")))throw new CommunityFailure(CommunityFailure.Code.FORBIDDEN,"Права на задачу изменились");if(task.get("revision").getAsLong()!=ref.getValue()||!Json.opt(task,"status","").equals("done")||task.has("archived")&&task.get("archived").getAsBoolean())throw new CommunityFailure(CommunityFailure.Code.CONFLICT,"Список изменился. Повторите предпросмотр");verified.add(task);}for(var task:verified){var previous=task.deepCopy();task.addProperty("archived",true);task.addProperty("archivedAt",System.currentTimeMillis());task.addProperty("repeatDays",0);task.addProperty("nextRepeatAt",0);TaskWorkflow.history(task,actor,"workArchiveApply");var history=task.getAsJsonArray("history");history.get(history.size()-1).getAsJsonObject().add("changes",ChangeSummary.between(previous,task,Map.of("archived","В архиве","repeatDays","Повтор задачи")));tasks.save(task);}out.addProperty("applied",true);out.addProperty("affected",verified.size());}
  out.add("preview",rows);return out;
 }
 private TaskArchive(){}
}
