package dev.abros.rivet.core.map;

import com.google.gson.*;
import dev.abros.rivet.core.*;
import java.util.*;
import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class MapPositionBatchTest {
 static JsonObject peer(int i){var row=new CommunityLocation("Player"+i,i%2==0?"minecraft:overworld":"minecraft:the_nether",i,70,-i,false).json();row.remove("membersOnly");row.addProperty("uuid",new UUID(0,i+1).toString());return row;}
 static List<JsonObject> pages(int count){var peers=new JsonArray();for(int i=0;i<count;i++)peers.add(peer(i));var out=new JsonObject();out.addProperty("kind","community");out.addProperty("request",UUID.randomUUID().toString());out.addProperty("positionRevision",5);return MapPositionPage.split(out,peers);}
 @Test void fourThousandPositionsUseOneRequestAndPublishOnlyAtTheEnd(){var pages=pages(4096);assertEquals(11,pages.size());var batch=new MapPositionBatch(1000);JsonArray result=null;for(int i=0;i<pages.size();i++){result=batch.accept(pages.get(i),1500+i*50);if(i<pages.size()-1)assertNull(result);assertTrue(MapPositionPage.wire(pages.get(i)).length()<=32767);}assertEquals(4096,result.size());assertEquals(peer(4095),result.get(4095));}
 @Test void byteBudgetSplitsLongDimensionsWithoutLosingRows(){var peers=new JsonArray();for(int i=0;i<4096;i++){var p=peer(i);p.addProperty("dimension","test:"+"a".repeat(145)+i);p.addProperty("name","<&>".repeat(5));peers.add(p);}var envelope=new JsonObject();envelope.addProperty("positionRevision",1);envelope.addProperty("request","<".repeat(128));var pages=MapPositionPage.split(envelope,peers);var batch=new MapPositionBatch(0);JsonArray result=null;for(int i=0;i<pages.size();i++){assertTrue(MapPositionPage.wire(pages.get(i)).length()<=32767);result=batch.accept(pages.get(i),500+i*50);}assertEquals(peers,result);}
 @Test void missingReorderedDuplicateOrMixedGenerationPagesNeverComplete(){var pages=pages(500);assertThrows(IllegalArgumentException.class,()->new MapPositionBatch(0).accept(pages.get(1),100));var b=new MapPositionBatch(0);assertNull(b.accept(pages.get(0),100));assertThrows(IllegalArgumentException.class,()->b.accept(pages.get(0),200));var c=new MapPositionBatch(0);c.accept(pages.get(0),100);var changed=pages.get(1).deepCopy();changed.addProperty("positionRevision",6);assertThrows(IllegalArgumentException.class,()->c.accept(changed,200));}
 @Test void deadlineIsNotExtendedByFragments(){var pages=pages(500);var batch=new MapPositionBatch(100);assertNull(batch.accept(pages.get(0),6000));assertThrows(IllegalArgumentException.class,()->batch.accept(pages.get(1),7100));}
 @Test void legacyAndUnnegotiatedFormatsAreBounded(){var legacy=new JsonObject();var rows=new JsonArray();for(int i=0;i<64;i++)rows.add(peer(i));legacy.add("peers",rows);assertEquals(rows,MapPositionPage.read(legacy,false));rows.add(peer(65));assertThrows(IllegalArgumentException.class,()->MapPositionPage.read(legacy,false));assertThrows(IllegalArgumentException.class,()->MapPositionPage.read(pages(1).getFirst(),false));}
 @Test void invalidIndicesCoordinatesAndDuplicatesAreRejected(){var p=pages(2).getFirst();var bad=p.deepCopy();bad.getAsJsonArray("positionRows").get(0).getAsJsonArray().set(2,new JsonPrimitive(.5));assertThrows(RuntimeException.class,()->new MapPositionBatch(0).accept(bad,1));var duplicate=p.deepCopy();duplicate.getAsJsonArray("positionRows").get(1).getAsJsonArray().set(0,duplicate.getAsJsonArray("positionRows").get(0).getAsJsonArray().get(0));assertThrows(IllegalArgumentException.class,()->new MapPositionBatch(0).accept(duplicate,1));var coordinate=p.deepCopy();coordinate.getAsJsonArray("positionRows").get(0).getAsJsonArray().set(3,new JsonPrimitive(30000001));assertThrows(IllegalArgumentException.class,()->new MapPositionBatch(0).accept(coordinate,1));}
 @Test void emptySnapshotCompletesAndOversizedSnapshotIsRejected(){assertEquals(0,new MapPositionBatch(0).accept(pages(0).getFirst(),1).size());assertThrows(IllegalArgumentException.class,()->pages(4097));}
}
