CREATE TABLE IF NOT EXISTS documents(id TEXT PRIMARY KEY, section TEXT NOT NULL, body JSONB NOT NULL, sequence BIGINT GENERATED ALWAYS AS IDENTITY);
CREATE INDEX IF NOT EXISTS documents_section ON documents(section,sequence DESC);
CREATE INDEX IF NOT EXISTS documents_owner ON documents(section,(body->>'owner'));
CREATE INDEX IF NOT EXISTS documents_body ON documents USING GIN(body);
CREATE TABLE IF NOT EXISTS people(id TEXT PRIMARY KEY,name TEXT NOT NULL,seen BIGINT NOT NULL,role TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS notices(id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,recipient TEXT NOT NULL,body JSONB NOT NULL,read INTEGER NOT NULL DEFAULT 0);
CREATE INDEX IF NOT EXISTS notices_recipient ON notices(recipient,id DESC);
CREATE INDEX IF NOT EXISTS notices_unread ON notices(recipient,id DESC) WHERE read=0;
CREATE TABLE IF NOT EXISTS records(namespace TEXT NOT NULL,id TEXT NOT NULL,body JSONB NOT NULL,sequence BIGINT GENERATED ALWAYS AS IDENTITY,PRIMARY KEY(namespace,id));
CREATE INDEX IF NOT EXISTS records_namespace ON records(namespace,sequence DESC);
CREATE INDEX IF NOT EXISTS reports_owner ON records((body->>'uuid'),sequence DESC) WHERE namespace='reports';
CREATE TABLE IF NOT EXISTS preferences(id TEXT PRIMARY KEY,body JSONB NOT NULL);
CREATE TABLE IF NOT EXISTS auth_accounts(name TEXT PRIMARY KEY, uuid TEXT NOT NULL UNIQUE, type TEXT NOT NULL CHECK(type IN ('local','reserved')), official TEXT UNIQUE, password TEXT, generation BIGINT NOT NULL DEFAULT 0, blocked BOOLEAN NOT NULL DEFAULT FALSE);
CREATE UNIQUE INDEX IF NOT EXISTS auth_name ON auth_accounts(lower(name));
CREATE TABLE IF NOT EXISTS auth_devices(id TEXT PRIMARY KEY, name TEXT NOT NULL REFERENCES auth_accounts(name), hash TEXT NOT NULL UNIQUE, label TEXT NOT NULL, created BIGINT NOT NULL, used BIGINT NOT NULL, expires BIGINT NOT NULL);
CREATE INDEX IF NOT EXISTS auth_devices_owner ON auth_devices(name,expires);
CREATE TABLE IF NOT EXISTS auth_resets(name TEXT PRIMARY KEY REFERENCES auth_accounts(name), hash TEXT NOT NULL, expires BIGINT NOT NULL);
CREATE TABLE IF NOT EXISTS auth_audit(id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY, at BIGINT NOT NULL, actor TEXT NOT NULL, action TEXT NOT NULL, target TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS auth_failures(name TEXT PRIMARY KEY, failures INTEGER NOT NULL, next BIGINT NOT NULL);
CREATE INDEX IF NOT EXISTS auth_failures_expiry ON auth_failures(next);

CREATE TABLE IF NOT EXISTS request_receipts(actor TEXT NOT NULL,id TEXT NOT NULL,digest TEXT NOT NULL,response JSONB NOT NULL,created BIGINT NOT NULL,PRIMARY KEY(actor,id));
CREATE INDEX IF NOT EXISTS receipts_expiry ON request_receipts(created);
