package dev.abros.rivet.core.skins;
import dev.abros.rivet.core.*;
import com.google.gson.*;
import java.util.*;
/** Shared lock makes ownership, quota checks and reference cleanup atomic. */
public final class SkinStore {
 private final PgDatabase db;private final SkinSettings settings;
 public SkinStore(PgDatabase db,SkinSettings settings){this.db=db;this.settings=settings;}
 public JsonObject mutate(UUID owner,String op,JsonObject input,byte[] bytes)throws Exception{
  var receipt=input.deepCopy();receipt.addProperty("scope","skins");receipt.addProperty("op",op);if(bytes!=null)receipt.addProperty("hash",Hashes.sha256(bytes));
  return db.communityTransaction(()->new RequestJournal(db).execute(owner.toString(),receipt,()->{
   switch(op){case "upload"->upload(owner,Json.str(input,"name"),input.get("slim").getAsBoolean(),bytes);case "moveUp","moveDown"->move(owner,Json.str(input,"id"),op.equals("moveUp")?-1:1);case "rename"->rename(owner,Json.str(input,"id"),Json.str(input,"name"));case "select","delete","model"->change(owner,op,Json.opt(input,"id",""),input.has("slim")&&input.get("slim").getAsBoolean());default->throw new IllegalArgumentException("Unknown skin command");}
   return library(owner);
  }));
 }
 private void lock()throws Exception{db.lock("skins");}
 private void profile(UUID owner)throws Exception{try(var q=db.connection().prepareStatement("INSERT INTO skin_profiles(owner) VALUES(?) ON CONFLICT DO NOTHING")){q.setObject(1,owner);q.executeUpdate();}}
 private void image(String hash,byte[] png)throws Exception{try(var q=db.connection().prepareStatement("INSERT INTO skin_images VALUES(?,?) ON CONFLICT DO NOTHING")){q.setString(1,hash);q.setBytes(2,png);q.executeUpdate();}}
 private void clean()throws Exception{try(var q=db.connection().createStatement()){q.executeUpdate("DELETE FROM skin_images i WHERE NOT EXISTS(SELECT 1 FROM skin_library l WHERE l.hash=i.hash) AND NOT EXISTS(SELECT 1 FROM skin_profiles p WHERE p.fallback=i.hash)");}}
 public JsonObject library(UUID owner)throws Exception{return db.communityTransaction(()->{var out=new JsonObject();out.addProperty("enabled",settings.enabled());out.addProperty("maxBytes",settings.maxBytes());out.addProperty("limit",settings.maxSkinsPerPlayer());var rows=new JsonArray();try(var q=db.connection().prepareStatement("SELECT id,hash,name,slim FROM skin_library WHERE owner=? ORDER BY position,name,id")){q.setObject(1,owner);try(var r=q.executeQuery()){while(r.next()){var row=new JsonObject();row.addProperty("id",r.getString(1));row.addProperty("hash",r.getString(2));row.addProperty("name",r.getString(3));row.addProperty("slim",r.getBoolean(4));rows.add(row);}}}out.add("entries",rows);out.add("profile",appearance(owner));return out;});}
 public JsonObject appearance(UUID owner)throws Exception{return db.communityTransaction(()->{var out=new JsonObject();out.addProperty("owner",owner.toString());out.addProperty("active","");out.addProperty("hash","");out.addProperty("slim",false);out.addProperty("fallbackHash","");out.addProperty("fallbackSlim",false);try(var q=db.connection().prepareStatement("SELECT p.active,coalesce(l.hash,p.fallback),CASE WHEN l.id IS NULL THEN p.slim ELSE l.slim END,p.fallback,p.slim FROM skin_profiles p LEFT JOIN skin_library l ON l.id=p.active WHERE p.owner=?")){q.setObject(1,owner);try(var r=q.executeQuery()){if(r.next()){out.addProperty("active",Objects.toString(r.getString(1),""));out.addProperty("hash",Objects.toString(r.getString(2),""));out.addProperty("slim",r.getBoolean(3));out.addProperty("fallbackHash",Objects.toString(r.getString(4),""));out.addProperty("fallbackSlim",r.getBoolean(5));}}}return out;});}
 public byte[] bytes(String hash)throws Exception{if(!hash.matches("[0-9a-f]{64}"))throw new IllegalArgumentException("Invalid skin hash");return db.communityTransaction(()->{try(var q=db.connection().prepareStatement("SELECT png FROM skin_images WHERE hash=?")){q.setString(1,hash);try(var r=q.executeQuery()){if(!r.next())throw new IllegalArgumentException("Скин удалён");return r.getBytes(1);}}});}
 public void upload(UUID owner,String name,boolean slim,byte[] data)throws Exception{
  if(!settings.enabled())throw new IllegalArgumentException("Скины выключены");if(name.isBlank()||name.length()>40||name.codePoints().anyMatch(Character::isISOControl))throw new IllegalArgumentException("Название: 1–40 символов");
  byte[] png=SkinImage.normalize(data,settings.maxBytes());String hash=Hashes.sha256(png);
  db.communityTransaction(()->{lock();profile(owner);UUID id=null;int count=0;try(var q=db.connection().prepareStatement("SELECT id,hash FROM skin_library WHERE owner=?")){q.setObject(1,owner);try(var r=q.executeQuery()){while(r.next()){count++;if(hash.equals(r.getString(2)))id=r.getObject(1,UUID.class);}}}if(id==null){if(count>=settings.maxSkinsPerPlayer())throw new IllegalArgumentException("Лимит скинов достигнут");id=UUID.randomUUID();image(hash,png);try(var q=db.connection().prepareStatement("INSERT INTO skin_library(id,owner,hash,name,slim,position) VALUES(?,?,?,?,?,(SELECT coalesce(max(position),-1)+1 FROM skin_library WHERE owner=?))")){q.setObject(1,id);q.setObject(2,owner);q.setString(3,hash);q.setString(4,name);q.setBoolean(5,slim);q.setObject(6,owner);q.executeUpdate();}}else{try(var q=db.connection().prepareStatement("UPDATE skin_library SET slim=? WHERE id=?")){q.setBoolean(1,slim);q.setObject(2,id);q.executeUpdate();}}setActive(owner,id);return null;});
 }
 private void setActive(UUID owner,UUID id)throws Exception{try(var q=db.connection().prepareStatement("UPDATE skin_profiles SET active=? WHERE owner=?")){q.setObject(1,id);q.setObject(2,owner);q.executeUpdate();}}
 public void change(UUID owner,String op,String id,boolean slim)throws Exception{db.communityTransaction(()->{lock();if(!settings.enabled())throw new IllegalArgumentException("Скины выключены");profile(owner);UUID key=id.isEmpty()?null:UUID.fromString(id);if(key==null){if(!op.equals("select"))throw new IllegalArgumentException("Выберите скин");setActive(owner,null);return null;}try(var q=db.connection().prepareStatement("SELECT 1 FROM skin_library WHERE owner=? AND id=?")){q.setObject(1,owner);q.setObject(2,key);try(var r=q.executeQuery()){if(!r.next())throw new IllegalArgumentException("Скин не найден");}}
  switch(op){case "select"->setActive(owner,key);case "model"->{try(var q=db.connection().prepareStatement("UPDATE skin_library SET slim=? WHERE id=?")){q.setBoolean(1,slim);q.setObject(2,key);q.executeUpdate();}}case "delete"->{try(var q=db.connection().prepareStatement("DELETE FROM skin_library WHERE id=?")){q.setObject(1,key);q.executeUpdate();}clean();}default->throw new IllegalArgumentException("Неизвестное действие");}return null;});}
 public void move(UUID owner,String id,int direction)throws Exception{
  if(direction!=1&&direction!=-1)throw new IllegalArgumentException("Invalid direction");
  db.communityTransaction(()->{lock();if(!settings.enabled())throw new IllegalArgumentException("Скины выключены");var ids=new ArrayList<UUID>();try(var q=db.connection().prepareStatement("SELECT id FROM skin_library WHERE owner=? ORDER BY position,name,id")){q.setObject(1,owner);try(var r=q.executeQuery()){while(r.next())ids.add(r.getObject(1,UUID.class));}}int index=ids.indexOf(UUID.fromString(id));if(index<0)throw new IllegalArgumentException("Скин не найден");int target=index+direction;if(target<0||target>=ids.size())return null;Collections.swap(ids,index,target);try(var q=db.connection().prepareStatement("UPDATE skin_library SET position=? WHERE owner=? AND id=?")){for(int i=0;i<ids.size();i++){q.setInt(1,i);q.setObject(2,owner);q.setObject(3,ids.get(i));q.addBatch();}q.executeBatch();}return null;});
 }
 public void rename(UUID owner,String id,String name)throws Exception{
  if(!settings.enabled())throw new IllegalArgumentException("Скины выключены");
  name=name.strip();if(name.isBlank()||name.length()>40||name.codePoints().anyMatch(Character::isISOControl))throw new IllegalArgumentException("Название: 1–40 символов");
  final String label=name;UUID key=UUID.fromString(id);
  db.communityTransaction(()->{lock();try(var q=db.connection().prepareStatement("UPDATE skin_library SET name=? WHERE owner=? AND id=?")){q.setString(1,label);q.setObject(2,owner);q.setObject(3,key);if(q.executeUpdate()!=1)throw new IllegalArgumentException("Скин не найден");}return null;});
 }
 public long checked(UUID owner,String source)throws Exception{return db.communityTransaction(()->{try(var q=db.connection().prepareStatement("SELECT checked FROM skin_profiles WHERE owner=? AND source=?")){q.setObject(1,owner);q.setString(2,source);try(var r=q.executeQuery()){return r.next()?r.getLong(1):0;}}});}
 public void fallback(UUID owner,String source,byte[] data,boolean slim,long now)throws Exception{byte[] png=data==null?null:SkinImage.normalize(data,1024*1024);String hash=png==null?null:Hashes.sha256(png);db.communityTransaction(()->{lock();profile(owner);if(png!=null)image(hash,png);try(var q=db.connection().prepareStatement("UPDATE skin_profiles SET fallback=?,slim=?,source=?,checked=? WHERE owner=?")){q.setString(1,hash);q.setBoolean(2,slim);q.setString(3,source);q.setLong(4,now);q.setObject(5,owner);q.executeUpdate();}clean();return null;});}
}
