package dev.abros.rivet.server;
import static dev.abros.rivet.server.ServerManagement.*;

import com.google.gson.*;
import com.mojang.brigadier.arguments.*;
import dev.abros.rivet.core.*;
import dev.abros.rivet.network.Protocol;
import net.minecraft.commands.Commands;
import net.minecraft.commands.CommandSourceStack;
import net.minecraft.network.chat.Component;
import net.minecraft.server.MinecraftServer;
import net.minecraft.server.level.ServerPlayer;
import net.neoforged.neoforge.common.NeoForge;
import net.neoforged.neoforge.network.PacketDistributor;
import java.nio.file.*;
import java.util.*;
import java.util.concurrent.*;

public final class ServerFeatures {
    public static dev.abros.rivet.core.SparkTimeline.AlertSettings sparkAlerts(){return ServerDatabase.settings().sparkAlerts();}
    private static final Map<UUID,JsonObject> clients=new HashMap<>();
    private static final Map<UUID,Long> joined=new HashMap<>();
    private static final Map<String,Long> requests=new HashMap<>();
    private static ExecutorService STORAGE;
    private static ExecutorService CONTROL;
    private static ExecutorService READS;
    private static java.util.concurrent.atomic.AtomicBoolean delivering=new java.util.concurrent.atomic.AtomicBoolean();
    static void storage(Runnable task){STORAGE.execute(task);}
    static void control(Runnable task){CONTROL.execute(task);}
    static void read(Runnable task){READS.execute(task);}
    private static final dev.abros.rivet.core.LatencyHistory latencyHistory=new dev.abros.rivet.core.LatencyHistory();
    private static void auditAsync(String actor,String action,String detail){try{storage(()->{try{ServerExtras.audit(actor,action,detail);}catch(Exception ex){com.mojang.logging.LogUtils.getLogger().error("Cannot persist Rivet audit",ex);}});}catch(RejectedExecutionException ex){com.mojang.logging.LogUtils.getLogger().error("Rivet audit queue is full");}}

    private record Subscription(String section,String id,long expires,long resynced){}
    private static final FailureTracker failures=new FailureTracker();
    private static final Map<UUID,Subscription> subscriptions=new HashMap<>();
    private static final Set<UUID> menuClients=new HashSet<>();
    private static CommunityStore community;
    private static JsonObject communityConfig;
    private static final Map<UUID,Integer> unread=new HashMap<>();
    private static final Map<UUID,Long> popupSequence=new HashMap<>();
    private static long lastPush,nextChatCleanup;
    private static java.util.concurrent.atomic.AtomicBoolean chatCleanup=new java.util.concurrent.atomic.AtomicBoolean();
    private static Path settings;
    private static long lastPrune,lastStatePush;private static java.util.concurrent.atomic.AtomicBoolean refreshing=new java.util.concurrent.atomic.AtomicBoolean();
    public static void install(){
        Protocol.featureRequest=ServerFeatures::request;
        NeoForge.EVENT_BUS.addListener(ServerFeatures::commands);
        NeoForge.EVENT_BUS.addListener(ServerFeatures::login);
        NeoForge.EVENT_BUS.addListener(ServerFeatures::logout);
        NeoForge.EVENT_BUS.addListener(ServerFeatures::tick);
    }
    static void start(net.neoforged.neoforge.event.server.ServerStartingEvent e){STORAGE=new dev.abros.rivet.core.LocalizedExecutor(4,4,0L,TimeUnit.MILLISECONDS,new ArrayBlockingQueue<>(256),r->{Thread t=new Thread(r,"Rivet storage");t.setDaemon(true);return t;},new ThreadPoolExecutor.AbortPolicy());CONTROL=new dev.abros.rivet.core.LocalizedExecutor(1,1,0L,TimeUnit.MILLISECONDS,new ArrayBlockingQueue<>(64),r->{var thread=new Thread(r,"Rivet server changes");thread.setDaemon(true);return thread;},new ThreadPoolExecutor.AbortPolicy());READS=new dev.abros.rivet.core.LocalizedExecutor(2,2,0L,TimeUnit.MILLISECONDS,new ArrayBlockingQueue<>(64),r->{var thread=new Thread(r,"Rivet menu reads");thread.setDaemon(true);return thread;},new ThreadPoolExecutor.AbortPolicy());latencyHistory.clear();
        nextChatCleanup=0;chatCleanup=new java.util.concurrent.atomic.AtomicBoolean();delivering=new java.util.concurrent.atomic.AtomicBoolean();refreshing=new java.util.concurrent.atomic.AtomicBoolean();
        failures.clear();originalMotd=e.getServer().getMotd();lastPrune=0;lastStatePush=0;
        menuClients.clear();subscriptions.clear();clients.clear();joined.clear();requests.clear();lastPush=0;
        var database=ServerDatabase.get();
        settings=net.neoforged.fml.loading.FMLPaths.GAMEDIR.get().resolve("rivet");
        try{

            communityConfig=ServerDatabase.settings().modules().sections(ServerDatabase.settings().community());community=new CommunityStore(database,communityConfig,ServerDatabase.settings().taskLimits(),ServerDatabase.settings().modules());community.retention(ServerDatabase.settings().number("retention.reportDays"),ServerDatabase.settings().number("retention.trashDays"),ServerDatabase.settings().number("retention.auditEntries"));unread.clear();popupSequence.clear();
            ServerExtras.start(settings,community);
        }
        catch(Exception ex){throw new IllegalStateException("Cannot initialize Rivet server features",ex);}
    }
    static void stop(){community=null;ModuleWorkers.stop(CONTROL,READS,STORAGE);CONTROL=null;READS=null;STORAGE=null;ServerExtras.stop();community=null;menuClients.clear();subscriptions.clear();clients.clear();joined.clear();requests.clear();unread.clear();popupSequence.clear();latencyHistory.clear();}
    public static void integrationNotice(ServerPlayer player,String title,String body,String route,String event){
        var store=community;if(store==null||!AuthServer.authenticated(player))return;String id=player.getUUID().toString();
        try{STORAGE.execute(()->{try{store.integrationNotice(id,title,body,route,event);}catch(Exception failure){com.mojang.logging.LogUtils.getLogger().warn("Cannot persist integration notification",failure);}});}catch(RejectedExecutionException full){com.mojang.logging.LogUtils.getLogger().warn("Integration notification queue is full");}
    }
    static CommunityStore communityStore(){return community;}
    public static boolean mayDiagnose(ServerPlayer p){return ServerCommands.allowed(p,"rivet.diagnostics");}
    public static JsonObject sparkRuntime(){var j=new JsonObject();j.addProperty("writeQueue",((ThreadPoolExecutor)STORAGE).getQueue().size());j.addProperty("readQueue",((ThreadPoolExecutor)READS).getQueue().size());var history=latencyHistory.snapshot();if(!history.isEmpty()){var last=history.get(history.size()-1).getAsJsonObject();j.add("syncMillis",last.get("totalMs"));j.add("databaseMillis",last.get("databaseMs"));}return j;}
    public static boolean admin(ServerPlayer p){return p.hasPermissions(2)||ServerIntegration.luckPermsEnabled()&&LuckPermsAdapter.profile(p).getAsJsonObject("capabilities").get("rivet.admin").getAsBoolean();}
    public static boolean mayJoin(com.mojang.authlib.GameProfile profile,MinecraftServer server){
        return !maintenance||server.getPlayerList().isOp(profile)||(ServerIntegration.luckPermsEnabled()&&LuckPermsAdapter.profile(profile.getId()).getAsJsonObject("capabilities").get("rivet.admin").getAsBoolean());
    }
    public static Component maintenanceMessage(){return ServerManagement.maintenanceMessage();}
    public static void record(UUID id,JsonObject state){var safe=new JsonObject();for(String k:List.of("coreVersion","packHash")){String value=Json.opt(state,k,"");safe.addProperty(k,value.substring(0,Math.min(256,value.length())));}clients.put(id,safe);}
    private static void login(net.neoforged.neoforge.event.entity.player.PlayerEvent.PlayerLoggedInEvent e){if(e.getEntity() instanceof ServerPlayer p){joined.put(p.getUUID(),System.currentTimeMillis());var actor=actor(p);String role=role(p);var store=community;try{STORAGE.execute(()->{try{store.seen(actor,role);}catch(Exception ex){com.mojang.logging.LogUtils.getLogger().warn("Cannot record player",ex);}});}catch(RejectedExecutionException busy){com.mojang.logging.LogUtils.getLogger().warn("Rivet: player activity queue is full");}sendState(p,false);invalidate(p.server);}}
    private static void logout(net.neoforged.neoforge.event.entity.player.PlayerEvent.PlayerLoggedOutEvent e){if(e.getEntity() instanceof ServerPlayer p&&community!=null){var store=community;var leaving=actor(p);String playerRole=role(p);try{STORAGE.execute(()->{try{store.seen(leaving,playerRole);}catch(Exception failure){com.mojang.logging.LogUtils.getLogger().warn("Cannot record last player activity",failure);}});}catch(RejectedExecutionException busy){com.mojang.logging.LogUtils.getLogger().warn("Rivet: player activity queue is full");}}UUID id=e.getEntity().getUUID();menuClients.remove(id);subscriptions.remove(id);clients.remove(id);joined.remove(id);unread.remove(id);popupSequence.remove(id);requests.keySet().removeIf(key->key.startsWith(id.toString()+":"));if(e.getEntity() instanceof ServerPlayer p)p.server.execute(dev.abros.rivet.core.Messages.capture(()->invalidate(p.server)));}
    static boolean currentPlayer(ServerPlayer p){return p.server.getPlayerList().getPlayer(p.getUUID())==p&&p.connection.isAcceptingMessages();}
    static void send(ServerPlayer p,JsonObject j){
        try(var locale=dev.abros.rivet.core.Messages.locale(p.clientInformation().language())){sendLocalized(p,dev.abros.rivet.core.LocalizedText.localize(j).getAsJsonObject());}
    }
    private static void sendLocalized(ServerPlayer p,JsonObject j){
        if(!currentPlayer(p))return;
        if(!p.connection.hasChannel(Protocol.FeatureState.TYPE)||!ServerIntegration.supports(p,"menu"))return;
        String encoded=Json.GSON.toJson(j);if(encoded.length()>32767){var failure=message("result",dev.abros.rivet.core.Messages.text("rivet.core.response_is_too_large_narrow_the_e4986e4a"));failure.addProperty("request",Json.opt(j,"request",""));failure.addProperty("error",true);failure.addProperty("code","UNAVAILABLE");failure.addProperty("recovery","retry");encoded=Json.GSON.toJson(failure);}
        PacketDistributor.sendToPlayer(p,new Protocol.FeatureState(encoded));
    }
    static JsonObject message(String kind,String text){var j=new JsonObject();j.addProperty("kind",kind);j.addProperty("text",text);return j;}
    static void notice(MinecraftServer server,String text){for(ServerPlayer p:server.getPlayerList().getPlayers()){if(p.connection.hasChannel(Protocol.FeatureState.TYPE))send(p,noticeMessage(text, false));else p.sendSystemMessage(Component.literal(text));}}
    static void urgentNotice(MinecraftServer server,String text){for(ServerPlayer p:server.getPlayerList().getPlayers()){if(p.connection.hasChannel(Protocol.FeatureState.TYPE)){var j=noticeMessage(text,false);j.addProperty("priority","urgent");send(p,j);}else p.sendSystemMessage(Component.literal(text));}}
    static void notice(MinecraftServer server,dev.abros.rivet.core.LocalizedText text){localizedNotice(server,text,false);}
    static void urgentNotice(MinecraftServer server,dev.abros.rivet.core.LocalizedText text){localizedNotice(server,text,true);}
    private static void localizedNotice(MinecraftServer server,dev.abros.rivet.core.LocalizedText text,boolean urgent){
        for(ServerPlayer player:server.getPlayerList().getPlayers())try(var locale=dev.abros.rivet.core.Messages.locale(player.clientInformation().language())){
            String rendered=text.render();
            if(player.connection.hasChannel(Protocol.FeatureState.TYPE)){var packet=noticeMessage(rendered,false);if(urgent)packet.addProperty("priority","urgent");send(player,packet);}
            else player.sendSystemMessage(Component.literal(rendered));
        }
    }
    private static JsonObject noticeMessage(String text,boolean optional){var j=message("notice",text);j.addProperty("optional",optional);j.addProperty("priority","important");return j;}
    private static void announcement(MinecraftServer server,String text){for(ServerPlayer p:server.getPlayerList().getPlayers()){if(p.connection.hasChannel(Protocol.FeatureState.TYPE))send(p,noticeMessage(text,true));else p.sendSystemMessage(Component.literal(text));}}
    static void invalidate(MinecraftServer server){invalidate(server,"","");}
    static void invalidate(MinecraftServer server,String section,String id){if(section.isEmpty()||section.equals("groups"))ServerMapPlayers.changed(server);
        long now=System.currentTimeMillis();subscriptions.values().removeIf(v->v.expires<now);
        for(var player:server.getPlayerList().getPlayers()){var sub=subscriptions.get(player.getUUID());if(sub==null)continue;
            if(!section.isEmpty()&&!sub.section.equals(section)&&!(sub.section.equals("home")&&Set.of("home","groups","events","players").contains(section))&&!sub.section.equals("notifications"))continue;
            if(!id.isEmpty()&&!sub.id.isEmpty()&&!sub.id.equals(id))continue;
            var hint=message("changed","");hint.addProperty("section",section);hint.addProperty("id",id);send(player,hint);
        }
    }
    private static void deliverChanges(MinecraftServer server){
        var delivering=ServerFeatures.delivering;
        var store=community;if(store==null||!delivering.compareAndSet(false,true))return;
        try{CONTROL.execute(()->{try{var events=store.pendingChanges();server.execute(dev.abros.rivet.core.Messages.capture(()->{
            if(community!=store){delivering.set(false);return;}
            try{
                long now=System.currentTimeMillis();subscriptions.values().removeIf(sub->sub.expires<now);
                for(var player:server.getPlayerList().getPlayers()){
                    var sub=subscriptions.get(player.getUUID());if(sub==null||!AuthServer.authenticated(player))continue;
                    boolean changed=false;String changedTopic="",changedId="";int changedCount=0;
                    for(var element:events){var event=element.getAsJsonObject();String recipient=Json.str(event,"recipient"),topic=Json.str(event,"topic"),id=Json.str(event,"entity");
                        if(!recipient.isEmpty()&&!recipient.equals(player.getUUID().toString()))continue;
                        if(!sub.section.equals(topic)&&!(sub.section.equals("home")&&Set.of("home","groups","events","players").contains(topic)))continue;
                        if(!sub.id.isEmpty()&&!sub.id.equals(id))continue;changed=true;changedTopic=topic;changedId=id;changedCount++;
                    }
                    if(changed){var hint=message("changed","");if(changedCount==1){hint.addProperty("section",changedTopic);hint.addProperty("id",changedId);}send(player,hint);}
                }
                CONTROL.execute(()->{try{store.acknowledgeChanges(events);}catch(Exception ex){com.mojang.logging.LogUtils.getLogger().warn("Cannot acknowledge Rivet changes; delivery will retry",ex);}finally{delivering.set(false);}});
            }catch(Exception ex){delivering.set(false);com.mojang.logging.LogUtils.getLogger().warn("Cannot deliver Rivet changes; delivery will retry",ex);}
        }));}catch(Exception ex){delivering.set(false);com.mojang.logging.LogUtils.getLogger().warn("Cannot read Rivet changes; delivery will retry",ex);}});}catch(RejectedExecutionException busy){delivering.set(false);}
    }
    public static void adapterStateChanged(net.minecraft.server.MinecraftServer server){for(var p:server.getPlayerList().getPlayers())sendState(p,false);}
    static void sendState(ServerPlayer p,boolean open){try(var locale=dev.abros.rivet.core.Messages.locale(p.clientInformation().language())){sendStateLocalized(p,open);}}
    private static void sendStateLocalized(ServerPlayer p,boolean open){
        if(!p.connection.hasChannel(Protocol.FeatureState.TYPE)||!ServerIntegration.supports(p,"menu"))return;
        var j=message("state","");j.addProperty("menuReady",menuClients.contains(p.getUUID()));j.add("modules",ServerDatabase.settings().modules().state());j.addProperty("authReset",AuthServer.mayReset(p));j.add("actions",ServerExtras.actions(p));j.addProperty("open",open);var profile=ServerIntegration.luckPermsEnabled()?LuckPermsAdapter.profile(p):null;j.addProperty("admin",p.hasPermissions(2)||profile!=null&&profile.getAsJsonObject("capabilities").get("rivet.admin").getAsBoolean());if(j.get("admin").getAsBoolean())j.add("adapters",dev.abros.rivet.server.compat.CompatibilityRegistry.diagnostics());j.addProperty("name",p.getGameProfile().getName());j.addProperty("uuid",p.getUUID().toString());if(ServerPlayerStatistics.store()!=null&&ServerPlayerStatistics.store().settings().session())j.addProperty("sessionSeconds",Math.max(0,(System.currentTimeMillis()-joined.getOrDefault(p.getUUID(),System.currentTimeMillis()))/1000));
        if(SimpleVoiceChatAdapter.available())j.addProperty("simpleVoiceMuted",dev.abros.rivet.compat.voice.SimpleVoiceBridge.muted(p.getUUID()));j.add("map",ServerMap.policy());j.addProperty("tabMode",ServerDatabase.settings().text("display.tab"));j.addProperty("nameplateMode",ServerDatabase.settings().text("display.nameplates"));j.addProperty("nameplatesEnabled",ServerDatabase.settings().text("display.nameplates").equals("rivet"));j.addProperty("chatLocalName",ServerDatabase.settings().text("chat.localName"));j.addProperty("chatGlobalName",ServerDatabase.settings().text("chat.globalName"));j.addProperty("chatLocalRadius",ServerDatabase.settings().number("chat.localRadius"));for(String channel:List.of("local","global","group"))j.addProperty("chat"+Character.toUpperCase(channel.charAt(0))+channel.substring(1)+"Color",ServerDatabase.settings().text("chat."+channel+"Color"));j.addProperty("chatFormat",ServerDatabase.settings().text("chat.format"));j.addProperty("chatChannelFormat",ServerDatabase.settings().text("chat.channelFormat"));j.addProperty("chatAllowCoordinates",ServerDatabase.settings().flag("chat.coordinates"));j.addProperty("chatEnabled",ServerDatabase.settings().flag("chat.enabled"));j.addProperty("chatLocalEnabled",ServerDatabase.settings().flag("chat.local"));j.addProperty("chatGroupEnabled",ServerDatabase.settings().flag("chat.group")&&ServerDatabase.settings().modules().enabled("groups"));
        j.addProperty("timezone",java.time.ZoneId.systemDefault().getId());j.addProperty("help",ServerIntegration.helpText());j.addProperty("hasLinks",!ServerExtras.menu().getAsJsonArray("links").isEmpty());j.addProperty("online",p.server.getPlayerCount());j.addProperty("maximum",p.server.getMaxPlayers());
        var permissions=new JsonObject();boolean full=p.hasPermissions(2)||profile!=null&&profile.getAsJsonObject("capabilities").get("rivet.admin").getAsBoolean();for(String right:ServerCommands.RIGHTS){var caps=profile==null?null:profile.getAsJsonObject("capabilities");permissions.addProperty(right,full||caps!=null&&caps.has(right)&&caps.get(right).getAsBoolean());}j.addProperty("staff",full||ServerCommands.RIGHTS.stream().filter(k->!k.startsWith("rivet.stats.")).anyMatch(k->permissions.get(k).getAsBoolean()));j.add("capabilities",permissions);j.addProperty("pinned",pinnedUntil>System.currentTimeMillis());if(permissions.get("rivet.announce").getAsBoolean()){j.addProperty("pinnedText",pinnedUntil>System.currentTimeMillis()?pinnedText:"");j.addProperty("pinnedUntil",pinnedUntil);}
        j.addProperty("maintenance",maintenance);j.addProperty("maintenanceReason",maintenanceReason);j.addProperty("maintenanceUntil",maintenanceUntil);j.addProperty("restartAt",restartAt);j.addProperty("restartReason",restartReason);
        if(ServerIntegration.supports(p,"moderation-votes"))j.add("moderationVotes",ServerModerationVotes.configuration(p.server));j.addProperty("menuProtocol",MenuProtocol.VERSION);j.addProperty("serverRivetVersion",dev.abros.rivet.Rivet.VERSION);j.addProperty("unread",unread.getOrDefault(p.getUUID(),0));j.addProperty("popupSequence",popupSequence.getOrDefault(p.getUUID(),0L));var visible=communityConfig.deepCopy();var sections=new JsonArray();for(var section:visible.getAsJsonArray("sections"))if(ServerIntegration.supports(p,section.getAsString()))sections.add(section);visible.add("sections",sections);j.add("communityConfig",visible);var supported=new JsonArray();for(String feature:ConnectionCompatibility.FEATURES)if(ServerIntegration.supports(p,feature))supported.add(feature);j.add("features",supported);if(profile!=null)j.add("profile",profile);send(p,j);
    }
    private static void tick(net.neoforged.neoforge.event.tick.ServerTickEvent.Post e){
        long now=System.currentTimeMillis();if(community==null||now-lastPush<1000)return;lastPush=now;deliverChanges(e.getServer());
        if(now>=nextChatCleanup){var gate=chatCleanup;if(gate.compareAndSet(false,true)){
            var history=new ChatHistory(ServerDatabase.get(),0,ServerDatabase.settings().number("chat.historyDays"));nextChatCleanup=now+60000;
            try{STORAGE.execute(()->{try{history.cleanup(System.currentTimeMillis());}catch(Exception failure){com.mojang.logging.LogUtils.getLogger().warn("Chat archive cleanup failed",failure);}finally{gate.set(false);}});}catch(RejectedExecutionException full){gate.set(false);nextChatCleanup=now+5000;}
        }}
        if(now-lastPrune>=3600000){var store=community;try{STORAGE.submit(()->{try{store.purgeDeleted(System.currentTimeMillis());}catch(Exception ex){com.mojang.logging.LogUtils.getLogger().warn("Rivet document cleanup failed",ex);}});lastPrune=now;}catch(RejectedExecutionException busy){lastPrune=now-3600000+60000;}}
        if(now-lastStatePush>=5000){lastStatePush=now;for(ServerPlayer p:e.getServer().getPlayerList().getPlayers())sendState(p,false);var store=community;var ids=List.copyOf(joined.keySet());var refreshing=ServerFeatures.refreshing;if(!refreshing.compareAndSet(false,true))return;try{STORAGE.submit(()->{try{long sampleStart=System.nanoTime();ServerManagement.publish(now,ids);store.reminders(now);var counts=new HashMap<UUID,Integer>();var sequences=new HashMap<UUID,Long>();for(var entry:store.notificationSummary(ids).entrySet()){counts.put(entry.getKey(),entry.getValue().unread());sequences.put(entry.getKey(),entry.getValue().sequence());}long databaseMillis=(System.nanoTime()-sampleStart)/1000000;e.getServer().execute(dev.abros.rivet.core.Messages.capture(()->{if(community==store){latencyHistory.add(now,(System.nanoTime()-sampleStart)/1000000,databaseMillis);unread.putAll(counts);popupSequence.putAll(sequences);}}));}catch(Exception ex){com.mojang.logging.LogUtils.getLogger().warn("Community reminders failed",ex);}finally{refreshing.set(false);}});}catch(RejectedExecutionException ignored){refreshing.set(false);}}
    }
    static boolean allowedAction(ServerPlayer player,String action){String right=MenuCommands.administrativePermission(action);return right.equals("rivet.admin")?admin(player):ServerCommands.allowed(player,right);}
    private static JsonObject diagnostics(MinecraftServer server){var j=message("diagnostics","");var rows=new JsonArray();for(ServerPlayer p:server.getPlayerList().getPlayers()){
        if(rows.size()>=30)break;var row=clients.getOrDefault(p.getUUID(),new JsonObject()).deepCopy();row.addProperty("player",p.getGameProfile().getName());row.addProperty("matching",Json.opt(ServerPack.status(),"hash","").equals(Json.opt(row,"packHash","")));rows.add(row);
    }j.add("players",rows);j.addProperty("total",server.getPlayerCount());return j;}
    private static void request(JsonObject j,net.neoforged.neoforge.network.handling.IPayloadContext context){
        if(!(context.player() instanceof ServerPlayer player))return;
        try(var locale=dev.abros.rivet.core.Messages.locale(player.clientInformation().language())){requestLocalized(j,context);}
    }
    private static void requestLocalized(JsonObject j,net.neoforged.neoforge.network.handling.IPayloadContext context){
        if(ServerSocial.handle(j,context))return;
        if(dev.abros.rivet.server.compat.CompatibilityRegistry.handle(j,context))return;
        if(!(context.player() instanceof ServerPlayer p)||!AuthServer.authenticated(p)||!ServerIntegration.supports(p,"menu"))return;

        try{
            MenuCommands.validate(j);String action=Json.str(j,"action");
            ServerDatabase.settings().modules().serverRequest(j);
            if(!MenuCommands.known(action))throw new IllegalArgumentException(dev.abros.rivet.core.Messages.text("rivet.core.unknown_action_a7c5e121"));
            boolean positions=action.equals("community")&&Json.opt(j,"op","").equals("mapPositionPeers");String rateKey=p.getUUID()+":"+(positions?"mapPositions":action);long now=System.currentTimeMillis();if(now-requests.getOrDefault(rateKey,0L)<(positions?(ServerIntegration.supports(p,dev.abros.rivet.core.map.MapPositionPage.FEATURE)?1000:250):500)){sendError(p,j,dev.abros.rivet.core.Messages.text("rivet.core.wait_a_moment_before_retrying_f6240679"));return;}requests.put(rateKey,now);
            if(action.equals("subscribe")){String section=Json.opt(j,"section","");if(section.isEmpty()){subscriptions.remove(p.getUUID());return;}if(!Set.of("home","board","groups","events","polls","ideas","notifications","players","reports","myReports","history","links").contains(section))throw new IllegalArgumentException(dev.abros.rivet.core.Messages.text("rivet.message.error_f1c482bb7136"));ServerDatabase.settings().modules().require(section.equals("myReports")?"reports":section);String id=Json.opt(j,"id","");if(id.length()>36)throw new IllegalArgumentException(dev.abros.rivet.core.Messages.text("rivet.message.error_c9b69a17d44b"));var previous=subscriptions.get(p.getUUID());boolean resync=previous==null||!previous.section.equals(section)||!previous.id.equals(id)||now-previous.resynced>=30000;subscriptions.put(p.getUUID(),new Subscription(section,id,now+30000,resync?now:previous.resynced));if(resync)send(p,MenuChangeHint.subscription(section,id));return;}
            if(action.equals("state")){if(!j.has("menuProtocol")||j.get("menuProtocol").getAsInt()!=MenuProtocol.VERSION){int clientProtocol=j.has("menuProtocol")?j.get("menuProtocol").getAsInt():0;
                com.mojang.logging.LogUtils.getLogger().warn("Rivet: несовместимый протокол меню игрока {}: клиент {}, сервер {}. Проверьте обновления Rivet на сервере и совместимость клиента.",p.getGameProfile().getName(),clientProtocol,MenuProtocol.VERSION);
                send(p,message("incompatible",clientProtocol<MenuProtocol.VERSION?dev.abros.rivet.core.Messages.text("rivet.core.update_rivet_to_open_this_server_f67308ff"):dev.abros.rivet.core.Messages.text("rivet.core.this_rivet_version_is_not_yet_cf6b444c")));return;}menuClients.add(p.getUUID());if(j.has("client"))record(p.getUUID(),j.getAsJsonObject("client"));sendState(p,false);return;}
            if(!menuClients.contains(p.getUUID())){send(p,message("incompatible",dev.abros.rivet.core.Messages.text("rivet.core.rivet_version_must_be_negotiated_first_43e3df09")));return;}
            if(action.equals("community")&&!ServerIntegration.supports(p,Json.opt(j,"section",""))){sendError(p,j,dev.abros.rivet.core.Messages.text("rivet.core.section_unavailable_in_this_rivet_version_19e2ba39"));return;}
            if(action.equals("players")&&!ServerIntegration.supports(p,"players"))return;
            if(ServerReportsModule.handle(p,j))return;
            if(action.equals("community")){
                String operation=Json.str(j,"op");if(operation.startsWith("mapPosition")){if(!ServerIntegration.supports(p,"map-positions")||!ServerMapPlayers.allowed())throw new CommunityFailure(CommunityFailure.Code.FORBIDDEN,dev.abros.rivet.core.Messages.text("rivet.core.map_positions_unavailable_adf8c092"));if(operation.equals("mapPositionSave"))ServerMapPlayers.changed(p.server);}if(operation.startsWith("mapExchange"))throw new CommunityFailure(CommunityFailure.Code.FORBIDDEN,dev.abros.rivet.core.Messages.text("rivet.core.explored_map_sharing_has_been_removed_9cefb8da"));if((Set.of("groupMap","plusTerritorySave").contains(operation)||operation.equals("mapActivities")&&Json.opt(j,"source","").equals("groupmarkers"))&&!ServerIntegration.supports(p,"group-map"))throw new IllegalArgumentException(dev.abros.rivet.core.Messages.text("rivet.core.update_rivet_to_use_group_maps_d77a9a41"));if(Set.of("mapActivities","workLocation").contains(operation)&&!ServerIntegration.supports(p,"map-activities"))throw new IllegalArgumentException(dev.abros.rivet.core.Messages.text("rivet.core.update_rivet_to_use_task_and_6b9ecdf9"));if(Set.of("mapActivities","groupMap","plusTerritorySave").contains(operation)&&!ServerDatabase.settings().flag("map.enabled"))throw new CommunityFailure(CommunityFailure.Code.FORBIDDEN,dev.abros.rivet.core.Messages.text("rivet.core.map_is_disabled_on_the_server_97ff8ddd"));if(operation.startsWith("space"))throw new IllegalArgumentException(dev.abros.rivet.core.Messages.text("rivet.core.unknown_action_ea069893"));if(operation.startsWith("tools")&&!ServerIntegration.supports(p,"player-tools"))throw new IllegalArgumentException(dev.abros.rivet.core.Messages.text("rivet.core.feature_unavailable_b7ec5840"));
                if(Set.of("workDependencies","workReserve","workRepeat").contains(operation)&&!ServerIntegration.supports(p,"community-extensions"))throw new IllegalArgumentException(dev.abros.rivet.core.Messages.text("rivet.core.update_rivet_to_use_task_scheduling_7888a930"));if(operation.startsWith("work")&&!ServerIntegration.supports(p,"task-tools"))throw new IllegalArgumentException(dev.abros.rivet.core.Messages.text("rivet.core.update_rivet_to_use_tasks_0ab419ae"));if(operation.startsWith("plus")&&!ServerIntegration.supports(p,"community-plus"))throw new IllegalArgumentException(dev.abros.rivet.core.Messages.text("rivet.core.feature_unavailable_b7ec5840"));
                if(j.has("territory")&&!j.get("territory").isJsonNull()){var territory=dev.abros.rivet.core.map.MapTerritoryJson.read(j.getAsJsonObject("territory"),UUID.fromString(Json.str(j,"id")));var dimension=net.minecraft.resources.ResourceKey.create(net.minecraft.core.registries.Registries.DIMENSION,net.minecraft.resources.ResourceLocation.parse(territory.dimension()));if(p.server.getLevel(dimension)==null)throw new IllegalArgumentException(dev.abros.rivet.core.Messages.text("rivet.core.this_dimension_does_not_exist_on_bf336bbd"));}
                if(j.has("location")&&!j.get("location").isJsonNull()){var location=CommunityLocation.read(j.getAsJsonObject("location"));var dimension=net.minecraft.resources.ResourceKey.create(net.minecraft.core.registries.Registries.DIMENSION,net.minecraft.resources.ResourceLocation.parse(location.dimension()));if(p.server.getLevel(dimension)==null)throw new IllegalArgumentException(dev.abros.rivet.core.Messages.text("rivet.core.this_dimension_does_not_exist_on_bf336bbd"));}if(MenuRequests.mutation(j)){UUID.fromString(Json.str(j,"operationId"));if(!j.has("issuedAt"))throw new IllegalArgumentException(dev.abros.rivet.core.Messages.text("rivet.message.error_f0e73bc222ba"));}
                var actor=actor(p);var copy=j.deepCopy();copy.remove("groupSnapshot");if(operation.equals("groupMap")&&ServerIntegration.supports(p,dev.abros.rivet.core.map.MapGroupPages.FEATURE))copy.addProperty("groupSnapshot",true);copy.remove("positionCandidates");copy.remove("positionEpoch");copy.remove("positionNext");copy.remove("positionCompact");if(operation.equals("mapPositionPeers"))ServerMapPlayers.prepare(p,copy);copy.remove("stockView");if(operation.equals("hud")&&copy.has("holograms")&&copy.get("holograms").getAsBoolean()){var view=new JsonObject();view.addProperty("dimension",p.serverLevel().dimension().location().toString());view.addProperty("x",p.getX());view.addProperty("y",p.getY());view.addProperty("z",p.getZ());copy.add("stockView",view);}var store=community;var selfStats=ServerPlayerStatistics.store();var live=ServerPlayerStatistics.live();var selfId=p.getUUID();
                // Position reads use the immutable actor captured above on the game thread.
                // Session, actor and position revision are checked again before any coordinates leave the server.
                // Keep the pre-execution check for mutations and other community requests.
                (MenuRequests.read(j)?READS:STORAGE).submit(()->{try{var currentActor=operation.equals("mapPositionPeers")?actor:p.server.submit(()->{
                    if(!p.connection.getConnection().isConnected()||!AuthServer.authenticated(p))throw new CommunityFailure(CommunityFailure.Code.FORBIDDEN,dev.abros.rivet.core.Messages.text("rivet.core.session_ended_a40ca6d3"));
                    return actor(p);
                }).get(2,TimeUnit.SECONDS);
                var result=store.request(currentActor,copy);var groupPages=operation.equals("groupMap")&&copy.has("groupSnapshot")?dev.abros.rivet.core.map.MapGroupPages.split(result):null;if(operation.equals("list")&&Json.opt(copy,"section","").equals("home")&&selfStats!=null){var stats=selfStats.read(List.of(selfId),live);if(stats.containsKey(selfId))result.add("selfStatistics",stats.get(selfId));}p.server.execute(dev.abros.rivet.core.Messages.capture(()->{if(community==store&&p.server.getPlayerList().getPlayer(p.getUUID())==p&&p.connection.isAcceptingMessages()&&AuthServer.authenticated(p)&&p.connection.hasChannel(Protocol.FeatureState.TYPE)){if(!currentActor.equals(actor(p))){sendFailure(p,copy,new CommunityFailure(CommunityFailure.Code.FORBIDDEN,dev.abros.rivet.core.Messages.text("rivet.core.permissions_changed_refresh_this_section_f90d78d0")));return;}if(operation.equals("mapPositionSave"))ServerMapPlayers.changed(p.server);if(operation.equals("mapPositionPeers")){for(var page:ServerMapPlayers.fill(p,copy,result))PacketDistributor.sendToPlayer(p,new Protocol.FeatureState(dev.abros.rivet.core.map.MapPositionPage.wire(page)));return;}
                if(groupPages!=null){for(var page:groupPages)send(p,page);return;}if(result.has("groups"))for(var entry:result.getAsJsonArray("groups")){var group=entry.getAsJsonObject();if(group.has("memberIds")){int online=0;for(var id:group.getAsJsonArray("memberIds"))if(p.server.getPlayerList().getPlayer(UUID.fromString(id.getAsString()))!=null)online++;group.addProperty("onlineCount",online);group.remove("memberIds");}}if(result.has("tasks")&&copy.has("knownTaskRows")&&copy.get("knownTaskRows").isJsonObject()&&copy.getAsJsonObject("knownTaskRows").size()<=100&&ServerIntegration.supports(p,"menu-deltas")){result.add("tasksDelta",RowDelta.encode(result.getAsJsonArray("tasks"),copy.getAsJsonObject("knownTaskRows")));result.remove("tasks");}send(p,result);if(MenuRequests.invalidatesCommunity(copy))invalidate(p.server,Json.opt(copy,"section",""),Json.opt(copy,"id",""));}}));}
                catch(Exception ex){p.server.execute(dev.abros.rivet.core.Messages.capture(()->{sendFailure(p,copy,ex);}));}});return;
            }
            if(action.equals("moderationVote")){if(!ServerIntegration.supports(p,"moderation-votes"))throw new IllegalArgumentException(dev.abros.rivet.core.Messages.text("rivet.core.feature_unavailable_b7ec5840"));ServerModerationVotes.request(p,j,result->send(p,result),failure->sendFailure(p,j,failure));return;}
            if(action.equals("players")){
                int page=bounded(j,"page",1000);String query=Json.opt(j,"query","");if(query.length()>32)throw new IllegalArgumentException(dev.abros.rivet.core.Messages.text("rivet.message.error_f7725b9809ed"));
                boolean onlineOnly=!j.has("all")||!j.get("all").getAsBoolean();var online=new HashMap<String,String>();var metadata=new HashMap<String,JsonObject>();for(var player:p.server.getPlayerList().getPlayers()){online.put(player.getUUID().toString(),player.getGameProfile().getName());if(ServerIntegration.luckPermsEnabled())metadata.put(player.getUUID().toString(),LuckPermsAdapter.profile(player));}var actions=ServerExtras.actions(p);var store=community;var statsStore=ServerPlayerStatistics.store();var liveStats=ServerPlayerStatistics.live();boolean showStats=ServerIntegration.supports(p,"player-statistics");
                READS.submit(()->{try{var data=message("players","");data.addProperty("page",page);data.addProperty("request",Json.opt(j,"request",""));var rows=new JsonArray();if(onlineOnly){var onlineRows=new JsonArray();String scope="online:"+query,after=PlayerCursor.after(Json.opt(j,"cursor",""),scope);online.entrySet().stream().filter(x->x.getKey().compareTo(after)>0&&x.getValue().toLowerCase(java.util.Locale.ROOT).contains(query.toLowerCase(java.util.Locale.ROOT))).sorted(Map.Entry.comparingByKey()).limit(21).forEach(x->{var row=new JsonObject();row.addProperty("uuid",x.getKey());row.addProperty("name",x.getValue());row.addProperty("online",true);onlineRows.add(row);});var batch=PlayerCursor.page(onlineRows,scope);rows=batch.getAsJsonArray("entries");data.add("nextCursor",batch.get("nextCursor"));}else{var batch=store.peopleCursor(query,Json.opt(j,"cursor",""));rows=batch.getAsJsonArray("entries");data.add("nextCursor",batch.get("nextCursor"));for(var row:rows)row.getAsJsonObject().addProperty("online",online.containsKey(Json.str(row.getAsJsonObject(),"uuid")));}for(var element:rows){var row=element.getAsJsonObject();var meta=metadata.get(Json.str(row,"uuid"));if(meta!=null){row.addProperty("prefix",Json.opt(meta,"prefix",""));row.addProperty("suffix",Json.opt(meta,"suffix",""));}}if(showStats&&statsStore!=null){var ids=new ArrayList<UUID>();for(var row:rows)ids.add(UUID.fromString(Json.str(row.getAsJsonObject(),"uuid")));var stats=statsStore.read(ids,liveStats);for(var row:rows){var item=row.getAsJsonObject();var view=stats.get(UUID.fromString(Json.str(item,"uuid")));if(view!=null)item.add("statistics",view);}}store.profiles(rows);store.filterProfiles(rows,p.getUUID().toString());data.add("players",rows);data.add("actions",actions);p.server.execute(dev.abros.rivet.core.Messages.capture(()->send(p,data)));}catch(Exception ex){p.server.execute(dev.abros.rivet.core.Messages.capture(()->sendFailure(p,j,ex)));}});return;
            }
            if(action.equals("moderate")){UUID.fromString(Json.str(j,"operationId"));ServerExtras.moderate(p,j);invalidate(p.server);return;}
            if(action.equals("menuData")){var data=message("menuData","");data.addProperty("request",Json.opt(j,"request",""));data.add("menu",ServerExtras.menu());send(p,data);return;}
            if(!allowedAction(p,action))throw new IllegalArgumentException(dev.abros.rivet.core.Messages.text("rivet.core.insufficient_permissions_3f48d3d9"));
            switch(action){
                case "scheduledAnnouncements" -> {var copy=j.deepCopy();String author=p.getGameProfile().getName(),actor=p.getUUID().toString();var store=community;STORAGE.execute(()->{try{if(!p.server.submit(()->AuthServer.authenticated(p)&&allowedAction(p,action)).get(2,TimeUnit.SECONDS))throw new CommunityFailure(CommunityFailure.Code.FORBIDDEN,dev.abros.rivet.core.Messages.text("rivet.core.insufficient_permissions_3f48d3d9"));var result=new ScheduledAnnouncements(store).request(actor,author,copy,System.currentTimeMillis());p.server.execute(dev.abros.rivet.core.Messages.capture(()->{if(community==store&&AuthServer.authenticated(p)&&allowedAction(p,action))send(p,result);}));}catch(Exception ex){p.server.execute(dev.abros.rivet.core.Messages.capture(()->sendFailure(p,copy,ex)));}});return;}
                case "playerAdministration" -> {
                    if(!ServerIntegration.supports(p,"admin-tools"))throw new IllegalArgumentException(dev.abros.rivet.core.Messages.text("rivet.core.feature_unavailable_b7ec5840"));
                    UUID targetId=UUID.fromString(Json.str(j,"target"));var target=p.server.getPlayerList().getPlayer(targetId);var data=message("playerAdministration","");data.addProperty("request",Json.opt(j,"request",""));data.addProperty("online",target!=null);
                    data.add("permissions",ServerIntegration.luckPermsEnabled()?LuckPermsAdapter.profile(targetId):new JsonObject());data.add("actions",target==null?new JsonArray():ServerExtras.actions(target));String cursor=Json.opt(j,"cursor","");var store=community;
                    READS.execute(()->{try{if(store.modules().enabled("reports"))data.add("history",store.recordCursor("moderation-history",targetId.toString(),cursor,10));else {var empty=new JsonObject();empty.add("entries",new JsonArray());empty.addProperty("nextCursor","");data.add("history",empty);}p.server.execute(dev.abros.rivet.core.Messages.capture(()->{if(p.connection.getConnection().isConnected()&&AuthServer.authenticated(p)&&admin(p))send(p,data);}));}catch(Exception failure){p.server.execute(dev.abros.rivet.core.Messages.capture(()->sendFailure(p,j,failure)));}});
                }
                case "pinAnnouncement","exportCommunity" -> {
                    if(!ServerIntegration.supports(p,"admin-tools"))throw new IllegalArgumentException(dev.abros.rivet.core.Messages.text("rivet.core.feature_unavailable_b7ec5840"));var copy=j.deepCopy();var db=ServerDatabase.get();var store=community;
                    CONTROL.execute(()->{try{
                        if(!p.server.submit(()->p.connection.getConnection().isConnected()&&AuthServer.authenticated(p)&&allowedAction(p,action)).get(2,TimeUnit.SECONDS))throw new CommunityFailure(CommunityFailure.Code.FORBIDDEN,dev.abros.rivet.core.Messages.text("rivet.core.insufficient_permissions_3f48d3d9"));
                        var administration=new CommunityAdministration(db,store);String answer;
                        if(action.equals("pinAnnouncement")){administration.pin(p.getGameProfile().getName(),Json.str(copy,"text"),bounded(copy,"minutes",10080));answer=dev.abros.rivet.core.Messages.text("rivet.core.announcement_saved_5f9980bd");long expiry=copy.get("text").getAsString().isBlank()?0:System.currentTimeMillis()+copy.get("minutes").getAsLong()*60000;p.server.execute(dev.abros.rivet.core.Messages.capture(()->{pinnedUntil=expiry;pinnedText=Json.str(copy,"text");for(var player:p.server.getPlayerList().getPlayers())sendState(player,false);}));}
                        else{var path=administration.export(settings.resolve("exports"),p.getGameProfile().getName(),Json.opt(copy,"section",""));answer=dev.abros.rivet.core.Messages.text("rivet.core.export_saved_on_server_rivet_exports_ed4a326d")+path.getFileName();}
                        p.server.execute(dev.abros.rivet.core.Messages.capture(()->{if(allowedAction(p,action))send(p,message("result",answer));invalidate(p.server,"home","");}));
                    }catch(Exception failure){p.server.execute(dev.abros.rivet.core.Messages.capture(()->sendFailure(p,copy,failure)));}});
                }
                case "serverConfig" -> {var copy=j.deepCopy();boolean apply=Json.opt(copy,"op","").equals("apply");var root=net.neoforged.fml.loading.FMLPaths.GAMEDIR.get().toAbsolutePath().normalize();READS.execute(()->{try{var file=root.resolve("config/rivet-server.toml");dev.abros.rivet.core.ServerSettings.load(root);byte[] contents=java.nio.file.Files.readAllBytes(file);if(contents.length>65536)throw new IllegalArgumentException(dev.abros.rivet.core.Messages.text("rivet.core.settings_exceed_64_kib_65bbce1c"));var candidate=dev.abros.rivet.core.ServerSettings.parse(new String(contents,java.nio.charset.StandardCharsets.UTF_8));String hash=dev.abros.rivet.core.Hashes.sha256(contents);if(apply&&!hash.equals(Json.str(copy,"hash")))throw new CommunityFailure(CommunityFailure.Code.CONFLICT,dev.abros.rivet.core.Messages.text("rivet.core.settings_changed_review_the_new_changes_2b5552c4"));p.server.execute(dev.abros.rivet.core.Messages.capture(()->{try{if(!p.connection.getConnection().isConnected()||!AuthServer.authenticated(p)||!allowedAction(p,"serverConfig"))return;var current=ServerDatabase.settings();var result=current.preview(candidate);result.addProperty("kind","community");result.addProperty("request",Json.opt(copy,"request",""));result.addProperty("hash",hash);if(apply){var live=current.liveFrom(candidate);communityConfig=live.modules().sections(live.community());community.configure(communityConfig);ServerExtras.menu(live.menu());ServerDatabase.liveSettings(live);result.addProperty("applied",true);auditAsync(p.getGameProfile().getName(),"settings reload","menu/community");invalidate(p.server);for(var player:p.server.getPlayerList().getPlayers())sendState(player,false);}send(p,result);}catch(Exception failure){sendFailure(p,copy,failure);}}));}catch(Exception failure){p.server.execute(dev.abros.rivet.core.Messages.capture(()->sendFailure(p,copy,failure)));}});}
                case "reloadMenu" -> {throw new IllegalArgumentException(dev.abros.rivet.core.Messages.text("rivet.core.rivet_server_toml_settings_take_effect_b51ad260"));}
                case "history" -> {int page=bounded(j,"page",100);READS.submit(()->{try{var data=message("history","");data.addProperty("page",page);data.addProperty("request",Json.opt(j,"request",""));var batch=community.recordCursor("audit","",Json.opt(j,"cursor",""),10);data.add("entries",batch.get("entries"));data.add("nextCursor",batch.get("nextCursor"));p.server.execute(dev.abros.rivet.core.Messages.capture(()->{if(admin(p))send(p,data);}));}catch(Exception ex){p.server.execute(dev.abros.rivet.core.Messages.capture(()->sendFailure(p,j,ex)));}});}
                case "rolePreview" -> {if(!ServerIntegration.supports(p,"community-extensions"))throw new IllegalArgumentException(dev.abros.rivet.core.Messages.text("rivet.core.update_rivet_c8ba6105"));var result=message("community","");result.addProperty("request",Json.opt(j,"request",""));var roles=ServerIntegration.luckPermsEnabled()?LuckPermsAdapter.roles():new JsonArray();if(!ServerIntegration.luckPermsEnabled()){for(String name:List.of(dev.abros.rivet.core.Messages.text("rivet.map.tool.player"),dev.abros.rivet.core.Messages.text("rivet.core.level_2_operator_caa8df20"))){var row=new JsonObject();row.addProperty("name",name);var caps=new JsonObject();for(String right:ServerCommands.RIGHTS)caps.addProperty(right,!name.equals(dev.abros.rivet.core.Messages.text("rivet.map.tool.player")));caps.addProperty("rivet.admin",!name.equals(dev.abros.rivet.core.Messages.text("rivet.map.tool.player")));caps.addProperty("rivet.events",!name.equals(dev.abros.rivet.core.Messages.text("rivet.map.tool.player")));row.add("capabilities",caps);roles.add(row);}}result.add("roles",roles);result.addProperty("context",ServerIntegration.luckPermsEnabled()?dev.abros.rivet.core.Messages.text("rivet.core.luckperms_roles_without_world_context_personal_1cdef742"):dev.abros.rivet.core.Messages.text("rivet.core.preview_of_standard_minecraft_roles_your_0dc5b3a2"));send(p,result);}
                case "adminDashboard" -> {var vote=new JsonObject();vote.addProperty("available",true);var store=ServerReportsModule.store();READS.execute(()->{try{long checkStarted=System.nanoTime();var data=store==null?new JsonObject():store.dashboard();data.addProperty("databaseLatencyMs",(System.nanoTime()-checkStarted)/1000000);data.addProperty("databaseHealthy",true);data.add("latencyHistory",latencyHistory.snapshot());data.addProperty("packReady",Json.opt(ServerPack.status(),"status","").equals("published"));data.addProperty("kind","community");data.addProperty("request",Json.opt(j,"request",""));data.add("vote",vote);data.add("recentErrors",failures.snapshot());data.add("retention",community.retentionPreview(System.currentTimeMillis()));data.addProperty("storageQueue",((ThreadPoolExecutor)STORAGE).getQueue().size());data.addProperty("readQueue",((ThreadPoolExecutor)READS).getQueue().size());data.addProperty("restartAt",restartAt);data.addProperty("maintenanceUntil",maintenanceUntil);p.server.execute(dev.abros.rivet.core.Messages.capture(()->{if(admin(p))send(p,data);}));}catch(Exception ex){p.server.execute(dev.abros.rivet.core.Messages.capture(()->sendFailure(p,j,ex)));}});}

                case "diagnostics" -> {
                    var snapshot=diagnostics(p.server);snapshot.addProperty("version",dev.abros.rivet.Rivet.VERSION);snapshot.add("recentErrors",failures.snapshot());snapshot.addProperty("luckPerms",ServerIntegration.luckPermsEnabled());snapshot.addProperty("plasmoVoice",net.neoforged.fml.ModList.get().isLoaded("plasmovoice"));snapshot.addProperty("simpleVoiceChat",net.neoforged.fml.ModList.get().isLoaded("voicechat"));
                    READS.execute(()->{long began=System.nanoTime();try{ServerDatabase.get().transaction(()->{try(var q=ServerDatabase.get().connection().createStatement()){q.execute("SELECT 1");}return null;});dev.abros.rivet.core.LocalizedText.key("rivet.core.available_e9ce37f1").put(snapshot,"database");snapshot.addProperty("databaseMillis",TimeUnit.NANOSECONDS.toMillis(System.nanoTime()-began));}catch(Exception failure){dev.abros.rivet.core.LocalizedText.key("rivet.core.unavailable_b0beb52f").put(snapshot,"database");}p.server.execute(dev.abros.rivet.core.Messages.capture(()->{if(p.connection.getConnection().isConnected()&&AuthServer.authenticated(p)&&allowedAction(p,action))send(p,snapshot);}));});
                }
                case "announce" -> {String text=Json.str(j,"text").strip();if(text.isEmpty()||text.length()>500)throw new IllegalArgumentException(dev.abros.rivet.core.Messages.text("rivet.message.error_103aa77aa869"));if(j.has("urgent")&&j.get("urgent").getAsBoolean())urgentNotice(p.server,text);else announcement(p.server,text);}
                case "maintenance" -> maintenance(p.server,j.get("enabled").getAsBoolean(),bounded(j,"minutes",1440),Json.str(j,"text"),p.createCommandSourceStack());
                case "restart" -> restart(p.server,bounded(j,"seconds",86400),Json.opt(j,"text",""),p.createCommandSourceStack());
                default -> throw new IllegalArgumentException(dev.abros.rivet.core.Messages.text("rivet.core.unknown_action_a7c5e121"));
            }
            if(Set.of("announce","reloadMenu").contains(action)){auditAsync(p.getGameProfile().getName(),action,Json.GSON.toJson(j));send(p,message("result",Set.of("maintenance","restart").contains(action)?"Change queued; confirmation follows after saving":"Action completed"));}
        }catch(RejectedExecutionException busy){sendError(p,j,"Server storage is busy; try again shortly");}catch(Exception ex){sendFailure(p,j,ex);}
    }
    static void sendFailure(ServerPlayer p,JsonObject request,Exception ex){
        String code=ex instanceof CommunityFailure failure?failure.code().name():ex instanceof IllegalArgumentException?"INVALID":"UNAVAILABLE";
        String diagnostic=UUID.randomUUID().toString();
        if(code.equals("UNAVAILABLE")){var incident=failures.record(Json.opt(request,"action","request"),ex,System.currentTimeMillis());diagnostic=incident.id();if(incident.log())com.mojang.logging.LogUtils.getLogger().error("Rivet request failed [{}] action={} type={} count={}",diagnostic,incident.operation(),incident.type(),incident.count());}
        var result=message(Json.opt(request,"action","").equals("community")?"community":"result",safeError(ex));result.addProperty("request",Json.opt(request,"request",""));result.addProperty("error",true);result.addProperty("code",code);result.addProperty("recovery",code.equals("CONFLICT")?"refresh":code.equals("INVALID")?"edit":code.equals("FORBIDDEN")?"close":"retry");result.addProperty("diagnosticId",diagnostic);send(p,result);
    }
    static String safeError(Exception ex){return ex instanceof IllegalArgumentException?ex.getMessage():dev.abros.rivet.core.Messages.text("rivet.core.storage_is_temporarily_unavailable_try_again_6701e740");}
    private static void sendError(ServerPlayer p,JsonObject request,String text){var result=message(Json.opt(request,"action","").equals("community")?"community":"result",text);result.addProperty("request",Json.opt(request,"request",""));result.addProperty("error",true);send(p,result);}
    private static String role(ServerPlayer p){return ServerIntegration.luckPermsEnabled()?Json.opt(LuckPermsAdapter.profile(p),"primaryGroup","Игрок"):admin(p)?"Администратор":"Игрок";}
    private static CommunityStore.Actor actor(ServerPlayer p){return new CommunityStore.Actor(p.getUUID().toString(),p.getGameProfile().getName(),admin(p),p.hasPermissions(2)||ServerIntegration.luckPermsEnabled()&&LuckPermsAdapter.profile(p).getAsJsonObject("capabilities").get("rivet.events").getAsBoolean());}
    static int bounded(JsonObject j,String key,int max){int value=j.get(key).getAsInt();if(value<0||value>max)throw new IllegalArgumentException("Invalid "+key);return value;}
    private interface Work {void run(CommandSourceStack source)throws Exception;}
    private static int execute(CommandSourceStack source,String command,Work work){try(var locale=dev.abros.rivet.core.Messages.locale(source.getEntity() instanceof ServerPlayer player?player.clientInformation().language():"ru_ru")){work.run(source);if(!command.matches("/?rivet (maintenance|restart)( .*|$)"))auditAsync(source.getTextName(),"/rivet", command);return 1;}catch(Exception ex){try(var locale=dev.abros.rivet.core.Messages.locale(source.getEntity() instanceof ServerPlayer player?player.clientInformation().language():"ru_ru")){source.sendFailure(Component.literal(safeError(ex)));}return 0;}}
    private static boolean admin(CommandSourceStack source){return source.hasPermission(2)||source.getEntity() instanceof ServerPlayer p&&admin(p);}
    private static void commands(net.neoforged.neoforge.event.RegisterCommandsEvent e){
        ServerCommands.register(e.getDispatcher());
        var announce=Commands.literal("announce").requires(s->ServerDatabase.settings().modules().enabled("server")&&ServerCommands.allowed(s,"rivet.announce"))
            .then(Commands.literal("pin").then(Commands.argument("minutes",IntegerArgumentType.integer(1,10080)).suggests((c,b)->net.minecraft.commands.SharedSuggestionProvider.suggest(List.of("15","60","1440"),b)).then(Commands.argument("text",StringArgumentType.greedyString()).executes(c->pin(c.getSource(),StringArgumentType.getString(c,"text"),IntegerArgumentType.getInteger(c,"minutes"))))))
            .then(Commands.literal("urgent").then(Commands.argument("text",StringArgumentType.greedyString()).executes(c->execute(c.getSource(),c.getInput(),s->{String text=StringArgumentType.getString(c,"text").strip();if(text.isEmpty()||text.length()>500)throw new IllegalArgumentException(dev.abros.rivet.core.Messages.text("rivet.core.message_1_500_characters_c3b83910"));urgentNotice(s.getServer(),text);ServerCommands.reply(s,dev.abros.rivet.core.Messages.text("rivet.core.critical_alert_sent_fceaa0d9"));}))))
            .then(Commands.literal("unpin").executes(c->pin(c.getSource(),"",1)))
            .then(Commands.argument("text",StringArgumentType.greedyString()).executes(c->execute(c.getSource(),c.getInput(),s->{String text=StringArgumentType.getString(c,"text").strip();if(text.isEmpty()||text.length()>500)throw new IllegalArgumentException(dev.abros.rivet.core.Messages.text("rivet.core.message_1_500_characters_c3b83910"));announcement(s.getServer(),text);ServerCommands.reply(s,dev.abros.rivet.core.Messages.text("rivet.core.announcement_sent_236d7b03"));})));
        e.getDispatcher().register(Commands.literal("rivet").executes(c->execute(c.getSource(),c.getInput(),s->{var p=s.getPlayerOrException();if(!p.connection.hasChannel(Protocol.FeatureState.TYPE))throw new IllegalArgumentException(dev.abros.rivet.core.Messages.text("rivet.core.install_rivet_to_open_the_menu_bd3fda0e"));sendState(p,true);}))
            .then(communityLinkCommand("share",true)).then(communityLinkCommand("open",false))
            .then(Commands.literal("status").requires(s->ServerCommands.allowed(s,"rivet.diagnostics")).executes(c->status(c.getSource())))
            .then(announce)
            .then(Commands.literal("maintenance").requires(s->ServerDatabase.settings().modules().enabled("server")&&ServerCommands.allowed(s,"rivet.maintenance"))
                .then(Commands.literal("off").executes(c->execute(c.getSource(),c.getInput(),s->maintenance(s.getServer(),false,0,"",s))))
                .then(Commands.literal("on").then(Commands.argument("minutes",IntegerArgumentType.integer(0,1440)).suggests((c,b)->net.minecraft.commands.SharedSuggestionProvider.suggest(List.of("0","15","30","60"),b)).then(Commands.argument("reason",StringArgumentType.greedyString()).executes(c->execute(c.getSource(),c.getInput(),s->maintenance(s.getServer(),true,IntegerArgumentType.getInteger(c,"minutes"),StringArgumentType.getString(c,"reason"),s)))))))
            .then(Commands.literal("restart").requires(s->ServerDatabase.settings().modules().enabled("server")&&ServerCommands.allowed(s,"rivet.restart"))
                .then(Commands.literal("cancel").executes(c->execute(c.getSource(),c.getInput(),s->restart(s.getServer(),0,"",s))))
                .then(Commands.argument("seconds",IntegerArgumentType.integer(1,86400)).suggests((c,b)->net.minecraft.commands.SharedSuggestionProvider.suggest(List.of("60","300","600"),b)).then(Commands.argument("reason",StringArgumentType.greedyString()).executes(c->execute(c.getSource(),c.getInput(),s->restart(s.getServer(),IntegerArgumentType.getInteger(c,"seconds"),StringArgumentType.getString(c,"reason"),s))))))
            .then(Commands.literal("reports").requires(s->ServerDatabase.settings().modules().enabled("reports")&&ServerCommands.allowed(s,"rivet.reports")).executes(c->{var source=c.getSource();try(var locale=dev.abros.rivet.core.Messages.locale(source.getEntity() instanceof ServerPlayer localePlayer?localePlayer.clientInformation().language():"ru_ru")){READS.execute(()->{try{var rows=ServerReportsModule.store().list(0);var lines=new ArrayList<String>();for(var item:rows){var j=item.getAsJsonObject();String text=Json.str(j,"message").replace('\n',' ');lines.add(Json.str(j,"id")+" · "+Json.str(j,"player")+" · "+(Json.str(j,"status").equals("open")?dev.abros.rivet.core.Messages.text("rivet.server.status.open"):dev.abros.rivet.core.Messages.text("rivet.ui.closed_fc98a6f2"))+"\n"+text.substring(0,Math.min(160,text.length())));}source.getServer().execute(dev.abros.rivet.core.Messages.capture(()->{if(ServerCommands.allowed(source,"rivet.reports"))ServerCommands.reply(source,lines.isEmpty()?dev.abros.rivet.core.Messages.text("rivet.core.no_reports_89915a5a"):String.join("\n\n",lines)+dev.abros.rivet.core.Messages.text("rivet.core.replies_and_other_reports_are_in_f13e7cf1"));}));}catch(Exception ex){source.getServer().execute(dev.abros.rivet.core.Messages.capture(()->ServerCommands.error(source,ex)));}});return 1;}catch(Exception ex){ServerCommands.error(source,ex);return 0;}})));
    }
    private static com.mojang.brigadier.builder.LiteralArgumentBuilder<CommandSourceStack> communityLinkCommand(String name,boolean broadcast){
        return Commands.literal(name).then(Commands.argument("section",StringArgumentType.word()).suggests((c,b)->net.minecraft.commands.SharedSuggestionProvider.suggest(List.of("tasks","board","groups","events","polls","ideas"),b)).then(Commands.argument("id",StringArgumentType.word()).executes(c->{var source=c.getSource();try(var locale=dev.abros.rivet.core.Messages.locale(source.getEntity() instanceof ServerPlayer localePlayer?localePlayer.clientInformation().language():"ru_ru")){var player=source.getPlayerOrException();if(!AuthServer.authenticated(player)||!ServerIntegration.supports(player,"community-plus"))throw new IllegalArgumentException(dev.abros.rivet.core.Messages.text("rivet.core.action_unavailable_c7b956d7"));String section=StringArgumentType.getString(c,"section"),id=StringArgumentType.getString(c,"id");UUID.fromString(id);String key=player.getUUID()+":share";long now=System.currentTimeMillis();if(now-requests.getOrDefault(key,0L)<(broadcast?5000:500))throw new IllegalArgumentException(dev.abros.rivet.core.Messages.text("rivet.core.wait_before_sending_again_4269bdfb"));requests.put(key,now);var sender=actor(player);var recipients=new java.util.LinkedHashMap<UUID,CommunityStore.Actor>();for(var recipient:source.getServer().getPlayerList().getPlayers())if(AuthServer.authenticated(recipient)&&ServerIntegration.supports(recipient,"community-plus")&&(broadcast||recipient==player))recipients.put(recipient.getUUID(),actor(recipient));var store=community;
            READS.execute(()->{try{var reference=store.sharedReference(sender,section,id);String title=Json.str(reference,"title");var allowed=new java.util.HashSet<UUID>();for(var recipient:recipients.entrySet())try{store.sharedEntry(recipient.getValue(),section,id);allowed.add(recipient.getKey());}catch(CommunityFailure denied){}
                source.getServer().execute(dev.abros.rivet.core.Messages.capture(()->{for(var target:allowed){var recipient=source.getServer().getPlayerList().getPlayer(target);if(recipient==null||!AuthServer.authenticated(recipient))continue;if(broadcast)recipient.sendSystemMessage(Component.literal(sender.name()+" · ").append(Component.literal("["+title+"]").withStyle(style->style.withColor(0x82B6F2).withUnderlined(true).withClickEvent(new net.minecraft.network.chat.ClickEvent(net.minecraft.network.chat.ClickEvent.Action.RUN_COMMAND,"/rivet open "+section+" "+id)))));else{var packet=message("openCommunity","");packet.addProperty("section",section);packet.addProperty("id",id);if(section.equals("tasks"))packet.addProperty("group",Json.opt(reference,"group",""));send(recipient,packet);}}}));
            }catch(Exception ex){source.getServer().execute(dev.abros.rivet.core.Messages.capture(()->ServerCommands.error(source,ex)));}});return 1;}catch(Exception ex){ServerCommands.error(source,ex);return 0;}})));
    }
    private static int pin(CommandSourceStack source,String text,int minutes){try(var locale=dev.abros.rivet.core.Messages.locale(source.getEntity() instanceof ServerPlayer player?player.clientInformation().language():"ru_ru")){CONTROL.execute(()->{try{if(!source.getServer().submit(()->ServerCommands.allowed(source,"rivet.announce")).get(2,TimeUnit.SECONDS))throw new IllegalArgumentException(dev.abros.rivet.core.Messages.text("rivet.core.permissions_changed_980f6f62"));new CommunityAdministration(ServerDatabase.get(),community).pin(source.getTextName(),text,minutes);source.getServer().execute(dev.abros.rivet.core.Messages.capture(()->{pinnedUntil=text.isBlank()?0:System.currentTimeMillis()+minutes*60000L;pinnedText=text;for(var player:source.getServer().getPlayerList().getPlayers())sendState(player,false);ServerCommands.reply(source,text.isBlank()?dev.abros.rivet.core.Messages.text("rivet.core.unpinned_0eda0f2c"):dev.abros.rivet.core.Messages.text("rivet.core.announcement_pinned_097c9745"));invalidate(source.getServer(),"home","");}));}catch(Exception ex){source.getServer().execute(dev.abros.rivet.core.Messages.capture(()->ServerCommands.error(source,ex)));}});return 1;}catch(Exception ex){ServerCommands.error(source,ex);return 0;}}
    private static int status(CommandSourceStack source){try(var locale=dev.abros.rivet.core.Messages.locale(source.getEntity() instanceof ServerPlayer player?player.clientInformation().language():"ru_ru")){return statusLocalized(source);}}
    private static int statusLocalized(CommandSourceStack source){
        String base="Rivet "+dev.abros.rivet.Rivet.VERSION+"\nAuth: "+(AuthServer.enabled()?dev.abros.rivet.core.Messages.text("rivet.ui.enabled_bbbf3850"):dev.abros.rivet.core.Messages.text("rivet.ui.disabled_0b48cc87"))+"\nLuckPerms: "+(ServerIntegration.luckPermsEnabled()?dev.abros.rivet.core.Messages.text("rivet.core.integration_enabled_a01d0fab"):dev.abros.rivet.core.Messages.text("rivet.core.integration_disabled_43d5f24c"))+"\nPlasmo Voice: "+(net.neoforged.fml.ModList.get().isLoaded("plasmovoice")?dev.abros.rivet.core.Messages.text("rivet.ui.installed_62843b26"):dev.abros.rivet.core.Messages.text("rivet.ui.not_installed_32ab765c"))+"\nSimple Voice Chat: "+(net.neoforged.fml.ModList.get().isLoaded("voicechat")?dev.abros.rivet.core.Messages.text("rivet.ui.installed_62843b26"):dev.abros.rivet.core.Messages.text("rivet.ui.not_installed_32ab765c"))+dev.abros.rivet.core.Messages.text("rivet.core.players_59cfba06")+source.getServer().getPlayerCount()+dev.abros.rivet.core.Messages.text("rivet.core.pack_c7ff3d0c")+ServerIntegration.requiredHash();
        try{READS.execute(()->{String database;try{ServerDatabase.get().transaction(()->{try(var q=ServerDatabase.get().connection().createStatement()){q.execute("SELECT 1");}return null;});database=dev.abros.rivet.core.Messages.text("rivet.core.available_e9ce37f1");}catch(Exception ex){database=dev.abros.rivet.core.Messages.text("rivet.core.unavailable_b0beb52f");}String text=base+dev.abros.rivet.core.Messages.text("rivet.core.database_e7691b20")+database;source.getServer().execute(dev.abros.rivet.core.Messages.capture(()->{if(ServerCommands.allowed(source,"rivet.diagnostics"))ServerCommands.reply(source,text);}));});return 1;}catch(Exception ex){ServerCommands.error(source,ex);return 0;}
    }
}
