package dev.abros.rivet.server;

import com.google.gson.*;
import dev.abros.rivet.core.Json;
import dev.abros.rivet.network.Protocol;
import net.minecraft.commands.Commands;
import net.minecraft.network.chat.*;
import net.minecraft.server.level.ServerPlayer;
import net.neoforged.neoforge.common.NeoForge;
import net.neoforged.neoforge.network.PacketDistributor;
import java.util.*;

/** Server-owned identities, presence and audience selection. No client supplies recipient UUIDs. */
final class ServerSocial {
 private record Presence(net.minecraft.world.phys.Vec3 position,float yaw,long active){}
 private record Membership(long until,Map<String,String> groups){}
 private record Metadata(long until,JsonObject value,String context){}
 private static final Map<UUID,Metadata> metadata=new HashMap<>();
 private static JsonObject metadata(ServerPlayer p){long now=System.currentTimeMillis();var saved=metadata.get(p.getUUID());if(saved!=null&&saved.until>now&&saved.context.equals(p.level().dimension().location().toString()+":"+LuckPermsAdapter.revision()))return saved.value;var row=ServerIntegration.luckPermsEnabled()?LuckPermsAdapter.profile(p):new JsonObject();metadata.put(p.getUUID(),new Metadata(now+2000,row,p.level().dimension().location().toString()+":"+LuckPermsAdapter.revision()));return row;}
 private static final Map<UUID,Presence> presence=new HashMap<>();
 private static final Map<UUID,Membership> groups=new HashMap<>();
 private static final Set<UUID> loading=new HashSet<>();
 private static final Set<UUID> emptyLocalWarned=new HashSet<>();
 private static final Map<String,Long> rates=new HashMap<>();
 private static long sample;private static Object generation=new Object();
 static void install(){
  NeoForge.EVENT_BUS.addListener((net.neoforged.neoforge.event.server.ServerStartedEvent e)->{presence.clear();metadata.clear();groups.clear();loading.clear();emptyLocalWarned.clear();rates.clear();sample=0;generation=new Object();});
  NeoForge.EVENT_BUS.addListener((net.neoforged.neoforge.event.server.ServerStoppedEvent e)->{generation=new Object();presence.clear();metadata.clear();groups.clear();loading.clear();emptyLocalWarned.clear();rates.clear();});
  NeoForge.EVENT_BUS.addListener((net.neoforged.neoforge.event.entity.player.PlayerEvent.PlayerLoggedOutEvent e)->{UUID id=e.getEntity().getUUID();presence.remove(id);metadata.remove(id);groups.remove(id);loading.remove(id);emptyLocalWarned.remove(id);rates.keySet().removeIf(k->k.startsWith(id.toString()));});
  NeoForge.EVENT_BUS.addListener((net.neoforged.neoforge.event.tick.ServerTickEvent.Post e)->{long now=System.currentTimeMillis();if(now<sample)return;sample=now+1000;var settings=ServerDatabase.settings();if(settings.flag("chat.enabled")&&settings.flag("chat.local")){int radius=settings.number("chat.localRadius");emptyLocalWarned.removeIf(id->{var sender=e.getServer().getPlayerList().getPlayer(id);return sender==null||e.getServer().getPlayerList().getPlayers().stream().anyMatch(recipient->recipient!=sender&&localRecipient(sender,recipient,radius));});}for(var p:e.getServer().getPlayerList().getPlayers()){var old=presence.get(p.getUUID());boolean moved=old==null||old.position.distanceToSqr(p.position())>.01||old.yaw!=p.getYRot();presence.put(p.getUUID(),new Presence(p.position(),p.getYRot(),moved?now:old.active));}});
  NeoForge.EVENT_BUS.addListener(ServerSocial::chat);
  NeoForge.EVENT_BUS.addListener(ServerSocial::commands);
 }
 private static void memberships(ServerPlayer p){long now=System.currentTimeMillis();UUID id=p.getUUID();if(groups.containsKey(id)&&groups.get(id).until>now||!loading.add(id))return;var store=ServerFeatures.communityStore();if(store==null){loading.remove(id);return;}Object epoch=generation;
  try{ServerFeatures.storage(()->{Map<String,String> result=new LinkedHashMap<>();try{for(var row:store.playerGroups(id.toString()))result.put(Json.str(row,"id"),Json.str(row,"title"));}catch(Exception error){com.mojang.logging.LogUtils.getLogger().warn("Cannot load chat memberships",error);}var data=Map.copyOf(result);p.server.execute(()->{if(epoch!=generation)return;loading.remove(id);if(p.server.getPlayerList().getPlayer(id)==p)groups.put(id,new Membership(System.currentTimeMillis()+15000,data));});});}catch(java.util.concurrent.RejectedExecutionException full){loading.remove(id);}
 }
 private static boolean rate(ServerPlayer p,String op,long interval){String key=p.getUUID()+":"+op;long now=System.currentTimeMillis();if(now-rates.getOrDefault(key,0L)<interval)return false;rates.put(key,now);return true;}
 static boolean handle(JsonObject j,net.neoforged.neoforge.network.handling.IPayloadContext context){if(!Json.opt(j,"action","").equals("social"))return false;context.enqueueWork(()->{
  if(!(context.player() instanceof ServerPlayer p)||!AuthServer.authenticated(p)||!ServerIntegration.supports(p,"social-display")||!rate(p,"social",250))return;
  int page=j.has("page")?Math.max(0,Math.min(100,j.get("page").getAsInt())):0;var players=p.server.getPlayerList().getPlayers().stream().filter(AuthServer::authenticated).sorted(Comparator.comparing(v->v.getUUID().toString())).toList();var array=new JsonArray();for(int i=page*32;i<Math.min(players.size(),page*32+32);i++){var target=players.get(i);memberships(target);var row=new JsonObject();row.addProperty("id",target.getUUID().toString());row.addProperty("name",target.getGameProfile().getName());var lp=metadata(target);for(String k:List.of("prefix","suffix","primaryGroup")){String v=Json.opt(lp,k,"");row.addProperty(k,v.substring(0,Math.min(80,v.length())));}var state=presence.get(target.getUUID());row.addProperty("status",state==null?"":System.currentTimeMillis()-state.active>=300000?"Отошёл":"");var membership=groups.get(target.getUUID());row.addProperty("group",membership==null?"":membership.groups.values().stream().findFirst().orElse(""));array.add(row);}
  var out=new JsonObject();out.addProperty("kind","social");out.addProperty("request",Json.opt(j,"request",""));out.addProperty("page",page);out.addProperty("more",(page+1)*32<players.size());out.add("players",array);memberships(p);var own=groups.get(p.getUUID());var chatGroups=new JsonArray();if(ServerDatabase.settings().flag("chat.enabled")&&ServerDatabase.settings().flag("chat.group")&&own!=null)own.groups.values().stream().distinct().sorted(String.CASE_INSENSITIVE_ORDER).forEach(chatGroups::add);out.add("chatGroups",chatGroups);out.addProperty("chatGroupsReady",own!=null);PacketDistributor.sendToPlayer(p,new Protocol.FeatureState(out.toString()));
 });return true;}
 private static Component name(ServerPlayer p){var lp=metadata(p);return dev.abros.rivet.network.ChatPresentation.identity(Json.opt(lp,"prefix",""),p.getGameProfile().getName(),Json.opt(lp,"suffix",""));}
 private static Component formatted(ServerPlayer p,String label,Component content,String colorKey){var settings=ServerDatabase.settings();return dev.abros.rivet.network.ChatPresentation.format(settings.text("chat.format"),settings.text("chat.channelFormat"),label,p.getUUID(),name(p),content,dev.abros.rivet.core.ChatChannels.color(settings.text("chat."+colorKey)));}
 private static Component sender(Component message,ServerPlayer p){return message.copy().withStyle(style->style.withHoverEvent(new HoverEvent(HoverEvent.Action.SHOW_ENTITY,new HoverEvent.EntityTooltipInfo(net.minecraft.world.entity.EntityType.PLAYER,p.getUUID(),name(p)))));}
 private static void active(ServerPlayer p){presence.put(p.getUUID(),new Presence(p.position(),p.getYRot(),System.currentTimeMillis()));}
 private static void chat(net.neoforged.neoforge.event.ServerChatEvent e){
  var player=e.getPlayer();if(!AuthServer.authenticated(player)||e.isCanceled()||!ServerDatabase.settings().flag("chat.enabled"))return;active(player);
  var parsed=dev.abros.rivet.core.ChatChannels.parse(e.getRawText(),ServerDatabase.settings().flag("chat.local"));
  if(parsed.text().isBlank()){e.setCanceled(true);return;}
  if(parsed.channel()==dev.abros.rivet.core.ChatChannels.Channel.LOCAL){e.setCanceled(true);channel(player,"local",parsed.text());return;}
  if(parsed.channel()==dev.abros.rivet.core.ChatChannels.Channel.GROUP){e.setCanceled(true);groupChat(player,parsed);return;}
  // Keep Minecraft's signed broadcast for the global channel.
  if(e.getMessage().getString().equals(e.getRawText()))e.setMessage(sender(content(player,parsed.text()),player));
 }
 private static void groupChat(ServerPlayer player,dev.abros.rivet.core.ChatChannels.Message message){
  if(!ServerDatabase.settings().flag("chat.group")){player.sendSystemMessage(Component.literal("Чат объединений выключен на сервере."));return;}
  var store=ServerFeatures.communityStore();if(store==null)return;Object epoch=generation;
  try{ServerFeatures.storage(()->{try{var own=store.playerGroups(player.getUUID().toString());var matches=own.stream().filter(row->message.group().isBlank()||Json.str(row,"title").equalsIgnoreCase(message.group())||Json.str(row,"id").equals(message.group())).toList();
   player.server.execute(()->{if(epoch!=generation||player.server.getPlayerList().getPlayer(player.getUUID())!=player||!AuthServer.authenticated(player))return;
    if(matches.size()==1)channel(player,Json.str(matches.getFirst(),"id"),message.text());
    else player.sendSystemMessage(Component.literal(matches.isEmpty()?"Объединение не найдено или вы не состоите в нём.":"Укажите объединение: #Название: сообщение. Доступны: "+own.stream().map(row->Json.str(row,"title")).collect(java.util.stream.Collectors.joining(", "))));
   });}catch(Exception failure){player.server.execute(()->{if(epoch==generation)player.sendSystemMessage(Component.literal("Не удалось проверить участие в объединении. Повторите сообщение."));});}});
  }catch(java.util.concurrent.RejectedExecutionException full){player.sendSystemMessage(Component.literal("Чат занят. Повторите сообщение."));}
 }
 private static Component content(ServerPlayer p,String message){var out=Component.empty();String[] parts=message.split("(?<=\\[pos\\])|(?=\\[pos\\])");for(String part:parts){if(part.equals("[pos]")&&ServerDatabase.settings().flag("chat.coordinates")){var place=Component.literal("[").append(dev.abros.rivet.network.DimensionLabels.name(p.level().dimension().location().toString())).append(" · "+p.getBlockX()+", "+p.getBlockY()+", "+p.getBlockZ()+"]");out.append(place.withStyle(s->s.withColor(0x83C6C4).withUnderlined(true).withHoverEvent(new HoverEvent(HoverEvent.Action.SHOW_TEXT,Component.literal("Место от "+p.getGameProfile().getName()+".\nНажмите, чтобы начать навигацию."))).withClickEvent(new ClickEvent(ClickEvent.Action.RUN_COMMAND,"/rivet direction "+p.level().dimension().location()+" "+p.getBlockX()+" "+p.getBlockZ()+" "+p.getBlockY()+" "+p.getGameProfile().getName()))));}else out.append(Component.literal(part));}return out;}
 private static boolean localRecipient(ServerPlayer sender,ServerPlayer recipient,int radius){return AuthServer.authenticated(recipient)&&recipient.level()==sender.level()&&recipient.distanceToSqr(sender)<=radius*(double)radius;}
 private static int channel(ServerPlayer p,String channel,String message){if(!ServerDatabase.settings().flag("chat.enabled")||!AuthServer.authenticated(p)||message.isBlank()||message.length()>256)return 0;active(p);var settings=ServerDatabase.settings();
  if(channel.equals("local")){if(!settings.flag("chat.local"))return 0;int radius=settings.number("chat.localRadius");var audience=p.server.getPlayerList().getPlayers().stream().filter(v->localRecipient(p,v,radius)).toList();deliver(p,settings.text("chat.localName"),message,audience);boolean alone=audience.stream().noneMatch(recipient->recipient!=p);if(!alone)emptyLocalWarned.remove(p.getUUID());if(alone&&emptyLocalWarned.add(p.getUUID()))p.sendSystemMessage(Component.literal("Рядом нет игроков. Для общего чата начните сообщение с !").withStyle(style->style.withColor(0xE2BE75)));return audience.size();}
  if(!settings.flag("chat.group"))return 0;try{UUID.fromString(channel);}catch(IllegalArgumentException bad){return 0;}var store=ServerFeatures.communityStore();if(store==null)return 0;Object epoch=generation;var body=content(p,message);
  try{ServerFeatures.storage(()->{try{var members=store.chatMembers(channel,p.getUUID().toString());var own=store.playerGroups(p.getUUID().toString());String label=own.stream().filter(j->Json.str(j,"id").equals(channel)).map(j->Json.str(j,"title")).findFirst().orElse("Объединение");p.server.execute(()->{if(epoch!=generation||p.server.getPlayerList().getPlayer(p.getUUID())!=p||!AuthServer.authenticated(p))return;var audience=p.server.getPlayerList().getPlayers().stream().filter(v->AuthServer.authenticated(v)&&members.contains(v.getUUID().toString())).toList();var formatted=formatted(p,label,body,"groupColor");for(var recipient:audience)recipient.sendSystemMessage(sender(formatted,p));com.mojang.logging.LogUtils.getLogger().info("[Rivet group] {}: {}",p.getGameProfile().getName(),message);});}catch(Exception denied){p.server.execute(()->{if(epoch==generation)p.sendSystemMessage(Component.literal("Сообщение не отправлено: проверьте участие в объединении."));});}});}catch(java.util.concurrent.RejectedExecutionException full){p.sendSystemMessage(Component.literal("Чат занят. Повторите сообщение."));return 0;}return 1;
 }
 private static void deliver(ServerPlayer p,String label,String message,List<ServerPlayer> audience){var line=formatted(p,label,content(p,message),"localColor");for(var recipient:audience)recipient.sendSystemMessage(sender(line,p));com.mojang.logging.LogUtils.getLogger().info("[Rivet {}] {}: {}",label,p.getGameProfile().getName(),message);}
 private static int direction(com.mojang.brigadier.context.CommandContext<net.minecraft.commands.CommandSourceStack> c,boolean withY)throws com.mojang.brigadier.exceptions.CommandSyntaxException{var p=c.getSource().getPlayerOrException();if(!AuthServer.authenticated(p)||!ServerIntegration.supports(p,"social-display"))return 0;var dimension=net.minecraft.commands.arguments.ResourceLocationArgument.getId(c,"dimension");if(dimension==null)return 0;var j=new JsonObject();j.addProperty("kind","socialDirection");String author="";try{author=com.mojang.brigadier.arguments.StringArgumentType.getString(c,"author");}catch(IllegalArgumentException absent){/* Old coordinate links have no author. */}if(author.matches("[A-Za-z0-9_]{1,16}"))j.addProperty("name","Место от "+author);j.addProperty("dimension",dimension.toString());j.addProperty("y",withY?com.mojang.brigadier.arguments.IntegerArgumentType.getInteger(c,"y"):p.getBlockY());j.addProperty("x",com.mojang.brigadier.arguments.IntegerArgumentType.getInteger(c,"x"));j.addProperty("z",com.mojang.brigadier.arguments.IntegerArgumentType.getInteger(c,"z"));PacketDistributor.sendToPlayer(p,new Protocol.FeatureState(j.toString()));return 1;}

 private static void commands(net.neoforged.neoforge.event.RegisterCommandsEvent e){var root=Commands.literal("rivet");root.then(Commands.literal("direction").then(Commands.argument("dimension",net.minecraft.commands.arguments.ResourceLocationArgument.id()).then(Commands.argument("x",com.mojang.brigadier.arguments.IntegerArgumentType.integer(-30000000,30000000)).then(Commands.argument("z",com.mojang.brigadier.arguments.IntegerArgumentType.integer(-30000000,30000000)).executes(c->direction(c,false)).then(Commands.argument("y",com.mojang.brigadier.arguments.IntegerArgumentType.integer(-2048,2048)).executes(c->direction(c,true)).then(Commands.argument("author",com.mojang.brigadier.arguments.StringArgumentType.word()).executes(c->direction(c,true))))))));
  var chat=Commands.literal("chat").requires(source->ServerDatabase.settings().flag("chat.enabled"));chat.then(Commands.literal("local").then(Commands.argument("message",com.mojang.brigadier.arguments.StringArgumentType.greedyString()).executes(c->channel(c.getSource().getPlayerOrException(),"local",com.mojang.brigadier.arguments.StringArgumentType.getString(c,"message")))));chat.then(Commands.literal("group").then(Commands.argument("group",com.mojang.brigadier.arguments.StringArgumentType.word()).suggests((c,b)->{var p=c.getSource().getPlayer();if(p!=null){memberships(p);var m=groups.get(p.getUUID());if(m!=null)m.groups.keySet().forEach(b::suggest);}return b.buildFuture();}).then(Commands.argument("message",com.mojang.brigadier.arguments.StringArgumentType.greedyString()).executes(c->channel(c.getSource().getPlayerOrException(),com.mojang.brigadier.arguments.StringArgumentType.getString(c,"group"),com.mojang.brigadier.arguments.StringArgumentType.getString(c,"message"))))));root.then(chat);e.getDispatcher().register(root);
 }
}
