package dev.abros.rivet.client;
import com.google.gson.*;import dev.abros.rivet.core.*;import net.minecraft.client.Minecraft;import net.minecraft.client.gui.screens.TitleScreen;import net.minecraft.client.gui.components.AbstractWidget;import net.neoforged.api.distmarker.Dist;import net.neoforged.bus.api.SubscribeEvent;import net.neoforged.fml.common.EventBusSubscriber;import net.neoforged.neoforge.client.event.ScreenEvent;
@EventBusSubscriber(modid="rivet",value=Dist.CLIENT)
public final class ApprovedUiHarness {
 private static final java.util.List<VisualMatrixHarness.Frame> FRAMES=VisualMatrixHarness.samples(5,0,1);
 private static final int TOTAL=FRAMES.size();
 private static int step=-1;private static long at;
 @SubscribeEvent public static void render(ScreenEvent.Render.Post event){String output=System.getenv("RIVET_APPROVED_UI");if(output==null||step>TOTAL)return;var mc=Minecraft.getInstance();if(step<0){if(!(mc.screen instanceof TitleScreen))return;CommunityUiHarness.open("normal");ServerMenuClient.previewTransport=q->{var r=new JsonObject();r.addProperty("kind","community");r.add("request",q.get("request"));if(Json.opt(q,"action","").equals("scheduledAnnouncements")){var rows=new JsonArray();for(int n=0;n<50;n++){var row=new JsonObject();row.addProperty("id",java.util.UUID.nameUUIDFromBytes(("announcement"+n).getBytes()).toString());row.addProperty("revision",1);row.addProperty("at",1791000000000L+n*60000);row.addProperty("author","Администратор с очень длинным именем");row.addProperty("text","Объявление с длинным текстом и проверкой обрезания названия "+n);rows.add(row);}r.add("announcements",rows);}else if(Json.opt(q,"action","").equals("adminDashboard")){r.addProperty("databaseHealthy",true);r.addProperty("databaseLatencyMs",9);r.addProperty("storageQueue",0);r.addProperty("readQueue",0);r.add("recentErrors",new JsonArray());var history=new LatencyHistory();for(int n=0;n<120;n++)history.add(n*1000L,n%17+3,n%9);r.add("latencyHistory",history.snapshot());}mc.execute(()->ServerMenuClient.receive(r));};new java.io.File(output).mkdirs();step=0;at=System.currentTimeMillis()+500;}
 if(System.currentTimeMillis()<at)return;at=System.currentTimeMillis()+300;try{if(step>0){verify();net.minecraft.client.Screenshot.grab(new java.io.File(output),String.format("approved-%03d.png",step),mc.getMainRenderTarget(),m->{});}if(step==TOTAL){step++;System.out.println("RIVET_APPROVED_UI_OK: frames="+TOTAL+", all themes sampled; default/light/high contrast flows, three scales");mc.stop();return;}var frame=FRAMES.get(step);frame.apply();switch(frame.scene()){case 0->mc.setScreen(new ThemePreviewScreen(null));case 1->{var before=new JsonObject();before.addProperty("description","Старый текст");var after=new JsonObject();after.addProperty("description","Очень длинный текст с пробелами ".repeat(150));mc.setScreen(new ChangePreviewScreen(null,ChangeSummary.between(before,after,java.util.Map.of("description","Описание")),()->{}));}case 2->mc.setScreen(new ScheduledAnnouncementsScreen(null));case 3->mc.setScreen(new AdminDashboardScreen(null,true));case 4->mc.setScreen(new AccessibilityScreen(null));}step++;if(step%30==0)System.out.println("RIVET_APPROVED_UI_PROGRESS: "+step+"/"+TOTAL);}catch(Throwable ex){System.out.println("RIVET_APPROVED_UI_FAILED step="+step);ex.printStackTrace();step=TOTAL+1;mc.stop();}}
 private static void verify(){var screen=Minecraft.getInstance().screen;UiGeometryHarness.verify(screen);var widgets=screen.children().stream().filter(e->e instanceof AbstractWidget).map(e->(AbstractWidget)e).filter(w->w.visible).toList();for(var w:widgets)if(w.getX()<0||w.getY()<0||w.getX()+w.getWidth()>screen.width||w.getY()+w.getHeight()>screen.height||w.getWidth()<1||w.getHeight()<1)throw new IllegalStateException("Escaped screen: "+w.getMessage().getString());for(int i=0;i<widgets.size();i++)for(int n=i+1;n<widgets.size();n++){var a=widgets.get(i);var b=widgets.get(n);if(a.getX()<b.getX()+b.getWidth()&&b.getX()<a.getX()+a.getWidth()&&a.getY()<b.getY()+b.getHeight()&&b.getY()<a.getY()+a.getHeight())throw new IllegalStateException("Overlap: "+a.getMessage().getString()+" / "+b.getMessage().getString());}}
}
