package dev.abros.rivet.client;

import net.minecraft.client.Minecraft;
import net.minecraft.client.gui.components.Button;
import net.minecraft.client.gui.screens.*;
import net.minecraft.client.multiplayer.ServerData;
import net.minecraft.client.multiplayer.resolver.ServerAddress;
import net.minecraft.world.entity.*;
import net.minecraft.world.entity.item.ItemEntity;
import net.minecraft.world.item.*;
import net.neoforged.api.distmarker.Dist;
import net.neoforged.bus.api.SubscribeEvent;
import net.neoforged.fml.common.EventBusSubscriber;
import java.util.*;

/** Native module navigation, entity filters, PNG contents and all settings sections. */
@EventBusSubscriber(modid="rivet",value=Dist.CLIENT)
public final class MapModuleHarness {
 private static final String ADDRESS=System.getenv("RIVET_MAP_MODULE_ADDRESS");
 private static final List<VisualMatrixHarness.Frame> FRAMES=VisualMatrixHarness.samples(12,0,10);
 private static int stage,tick,frame,checks;private static boolean connected,done;private static long deadline;private static WorldMapScreen map;private static MapExport.Job job;private static com.google.gson.JsonObject saved;private static final List<Entity> entities=new ArrayList<>();
 private static void check(boolean ok,String message){if(!ok)throw new IllegalStateException(message);checks++;}
 private static void press(String label){var mc=Minecraft.getInstance();((Button)mc.screen.children().stream().filter(c->c instanceof Button b&&b.getMessage().getString().equals(label)).findFirst().orElseThrow()).onPress();}
 private static void capture(String name){String path=System.getenv("RIVET_MAP_MODULE_SCREENSHOTS");if(path!=null){var folder=new java.io.File(path);folder.mkdirs();UiCaptureHarness.grab(folder,name+".png",Minecraft.getInstance().getMainRenderTarget(),m->{});}}
 private static void radar(){var mc=Minecraft.getInstance();var r=MapRenderSettings.INSTANCE;var zombie=EntityType.ZOMBIE.create(mc.level);var cow=EntityType.COW.create(mc.level);var item=new ItemEntity(mc.level,mc.player.getX(),mc.player.getY(),mc.player.getZ(),new ItemStack(Items.DIAMOND));entities.add(zombie);entities.add(cow);entities.add(item);
  for(var type:List.of(EntityType.PIG,EntityType.SHEEP,EntityType.WOLF,EntityType.CHICKEN,EntityType.RABBIT,EntityType.VILLAGER,EntityType.SKELETON,EntityType.CREEPER))entities.add(type.create(mc.level));
  for(String skin:List.of("steve","alex")){var texture=net.minecraft.resources.ResourceLocation.withDefaultNamespace("textures/entity/player/"+(skin.equals("alex")?"slim/":"wide/")+skin+".png");var player=new net.minecraft.client.player.RemotePlayer(mc.level,new com.mojang.authlib.GameProfile(UUID.randomUUID(),"Radar_"+skin)){@Override public net.minecraft.client.resources.PlayerSkin getSkin(){return new net.minecraft.client.resources.PlayerSkin(texture,null,null,null,skin.equals("alex")?net.minecraft.client.resources.PlayerSkin.Model.SLIM:net.minecraft.client.resources.PlayerSkin.Model.WIDE,false);}};entities.add(player);}
for(int i=0;i<entities.size();i++){var e=entities.get(i);e.setId(1900000000+i);e.setPos(mc.player.getX()+i+2,mc.player.getY(),mc.player.getZ()+3);mc.level.addEntity(e);}
  for(var e:entities)if(e instanceof net.minecraft.client.player.RemotePlayer)check(MapRadar.included(e),"Player missing from radar");
  check(!MapRadar.included(EntityType.ARMOR_STAND.create(mc.level)),"Non-mob object shown");check(MapRadar.category(zombie)==MapRadar.Category.HOSTILE&&MapRadar.category(cow)==MapRadar.Category.FRIENDLY&&MapRadar.category(item)==MapRadar.Category.ITEM,"Wrong radar categories");check(MapRadar.included(zombie)&&MapRadar.included(cow)&&!MapRadar.included(item),"Visible client entities absent");r.hostile=false;check(!MapRadar.included(zombie)&&MapRadar.included(cow),"Radar category filter leaks");r.hostile=true;zombie.setInvisible(true);check(!MapRadar.included(zombie),"Invisible entity shown");zombie.setInvisible(false);zombie.setPos(zombie.getX(),mc.player.getY()+129,zombie.getZ());check(!MapRadar.included(zombie),"Radar ignores vertical limit");zombie.setPos(zombie.getX(),mc.player.getY(),zombie.getZ());var policy=ServerMenuClient.state.getAsJsonObject("map");var before=policy.get("radar");policy.addProperty("radar",false);check(!MapRadar.allowed(),"Server radar denial ignored");if(before==null)policy.remove("radar");else policy.add("radar",before);
 }
 private static void restore(){var mc=Minecraft.getInstance();for(var e:entities)e.discard();if(saved!=null)MapRenderSettings.INSTANCE.load(saved);MapSettings.INSTANCE.save();}
 @SubscribeEvent public static void tick(net.neoforged.neoforge.client.event.ClientTickEvent.Post event){if(ADDRESS==null||done)return;var mc=Minecraft.getInstance();try{
  if(!connected&&mc.screen instanceof TitleScreen){connected=true;deadline=System.currentTimeMillis()+180000;mc.options.pauseOnLostFocus=false;mc.options.guiScale().set(2);mc.resizeDisplay();ConnectScreen.startConnecting(mc.screen,mc,ServerAddress.parseString(ADDRESS),new ServerData("Map module check",ADDRESS,ServerData.Type.OTHER),false,null);}
  if(connected&&System.currentTimeMillis()>deadline)throw new IllegalStateException("Module check timed out stage="+stage);
  if(!WorldMapClient.ready()||!WorldMapClient.markersReady())return;
  if(stage==0){if(++tick<80)return;saved=MapRenderSettings.INSTANCE.json();MapRenderSettings.INSTANCE.copy(new MapRenderSettings());radar();map=new WorldMapScreen(null);mc.setScreen(map);check(map.children().stream().noneMatch(c->c instanceof Button b&&b.getMessage().equals(Client.tr("map.caves"))),"Caves still in toolbar");press(Client.tr("map.settings").getString());check(mc.screen instanceof MapSettingsScreen,"Gear did not open unified map settings");var settings=mc.screen;press("Поиск…");UiGeometryHarness.verify(mc.screen);check(mc.screen.children().stream().filter(c->c instanceof Button b&&b.getMessage().getString().contains(" · ")).allMatch(c->{String label=((Button)c).getMessage().getString();return label.startsWith("Карта · ")||label.startsWith("Навигация · ");}),"Map search includes unrelated settings");mc.screen.onClose();check(mc.screen==settings,"Search lost settings parent");press(Client.tr("map.caves").getString());check(mc.screen==settings,"Caves opened a nested dialog instead of section");check(mc.screen.children().stream().anyMatch(c->c instanceof net.minecraft.client.gui.components.EditBox),"Cave section has no height control");press("Миникарта");check(mc.screen.children().stream().noneMatch(c->c instanceof Button b&&(b.getMessage().getString().contains("Расположение и размер")||b.getMessage().getString().startsWith("Клавиша увеличения"))),"Duplicate minimap actions remain");press("Клавиши…");check(mc.screen instanceof net.minecraft.client.gui.screens.options.controls.KeyBindsScreen,"Shared controls action missing");mc.screen.onClose();check(mc.screen==settings,"Controls lost settings parent");((MapSettingsScreen)settings).revealSetting("caveMiniDelay");check(mc.screen.children().stream().anyMatch(c->c instanceof Button b&&b.getMessage().getString().startsWith(Client.tr("map.caveMiniDelay").getString())),"Search did not reveal cave setting");mc.screen.onClose();check(mc.screen==map,"Closing settings lost map");mc.setScreen(new AccessibilityScreen(null));check(mc.screen.children().stream().noneMatch(c->c instanceof Button b&&(b.getMessage().getString().equals("Навигация")||b.getMessage().getString().equals("Карта"))),"Server settings retain duplicate map sections");mc.setScreen(map);stage=1;tick=0;}
  else if(stage==1){if(++tick<40)return;var layer=MapCaves.layer(map.selectedDimension());int x=mc.player.getBlockX()-32,z=mc.player.getBlockZ()-32;job=MapExport.export(layer,new MapExport.Area(x,z,64,64));stage=2;}
  else if(stage==2){if(!job.done)return;check(job.file!=null&&job.error.isEmpty(),"PNG export failed: "+job.error);try(var image=com.mojang.blaze3d.platform.NativeImage.read(java.nio.file.Files.newInputStream(job.file))){check(image.getWidth()==64&&image.getHeight()==64,"Wrong PNG dimensions");boolean data=false;for(int y=0;y<64;y++)for(int x=0;x<64;x++)data|=(image.getPixelRGBA(x,y)>>>24)!=0;check(data,"PNG lost explored terrain");}var area=new MapExport.Area(-123,-345,65536,32000);check(area.pixelsX()<=4096&&area.pixelsZ()<=4096,"Unbounded export texture");job=MapExport.export(MapCaves.layer(map.selectedDimension()),new MapExport.Area(2000000,2000000,16,16));stage=6;tick=0;}
  else if(stage==6){if(!job.done)return;check(job.file!=null,"Unknown-area export failed");try(var image=com.mojang.blaze3d.platform.NativeImage.read(java.nio.file.Files.newInputStream(job.file))){for(int y=0;y<16;y++)for(int x=0;x<16;x++)check(image.getPixelRGBA(x,y)==0,"Unknown terrain is not transparent");}var r=MapRenderSettings.INSTANCE;r.markerScale=1.5f;r.markerMinZoom=.5f;r.slopes=3;r.radarNames=true;var json=r.json();r.copy(new MapRenderSettings());r.load(json);check(r.markerScale==1.5f&&r.markerMinZoom==.5f&&r.slopes==3&&r.radarNames,"Map display preferences did not round-trip");r.copy(new MapRenderSettings());stage=3;tick=0;}
  else if(stage==3){if(++tick%8!=0)return;if(frame>0){UiGeometryHarness.verify(mc.screen);capture("module-"+frame);mc.screen.onClose();check(mc.screen==map,"Settings return lost parent");}if(frame<FRAMES.size()){var f=FRAMES.get(frame++);f.apply();map=new WorldMapScreen(null);mc.setScreen(map);var options=new MapSettingsScreen(map,f.scene()/2);mc.setScreen(options);if(f.scene()%2==1){options.revealRow(20);options.rebuildWidgets();}UiGeometryHarness.verify(options);checks++;}else{mc.setScreen(new MapExportScreen(map));UiGeometryHarness.verify(mc.screen);stage=4;tick=0;}}
  else if(stage==4){if(++tick<12)return;capture("export");mc.screen.onClose();check(mc.screen==map,"Export return lost map");mc.getWindow().setWindowed(640,480);mc.options.guiScale().set(3);mc.resizeDisplay();for(int category=0;category<MapSettingsScreen.CATEGORIES.size();category++){var options=new MapSettingsScreen(map,category);mc.setScreen(options);UiGeometryHarness.verify(options);options.revealRow(20);options.rebuildWidgets();UiGeometryHarness.verify(options);checks+=2;}mc.setScreen(new HudInteractionScreen(false,null));stage=5;tick=0;}
  else if(stage==5){if(++tick<25)return;capture("radar");mc.getWindow().setWindowed(1280,1024);mc.options.guiScale().set(2);mc.resizeDisplay();mc.setScreen(new Portraits());stage=7;tick=0;}
  else if(stage==7){if(++tick<20)return;capture("portraits");restore();done=true;System.out.println("RIVET_MAP_MODULE_OK checks="+checks+" frames="+frame+" radar=true export=true settings=true");mc.stop();}
 }catch(Throwable e){done=true;System.out.println("RIVET_MAP_MODULE_FAILED stage="+stage+" frame="+frame);e.printStackTrace();restore();mc.stop();}}
 private static final class Portraits extends Screen {
  Portraits(){super(net.minecraft.network.chat.Component.literal("Проверка иконок радара"));}
  @Override public void render(net.minecraft.client.gui.GuiGraphics g,int mx,int my,float d){g.fill(0,0,width,height,0xff20262a);g.drawString(font,title,20,16,0xffffffff);int n=0;for(var e:entities){if(e instanceof ItemEntity)continue;int x=70+(n%5)*115,y=75+(n/5)*140;g.pose().pushPose();g.pose().translate(x,y,0);g.pose().scale(4,4,1);if(!MapRadar.portrait(g,e,0,0))throw new IllegalStateException("Missing fixture portrait: "+e.getType());g.pose().popPose();MapRadar.portrait(g,e,x,y+42);g.drawCenteredString(font,e.getDisplayName(),x,y+60,0xffffffff);n++;}}
 }

}
