package dev.abros.rivet.client;
import com.google.gson.*;
import dev.abros.rivet.core.*;
import dev.abros.rivet.core.map.MapPositionPolicy;
import net.minecraft.client.Minecraft;
import net.minecraft.client.gui.components.Button;
import net.minecraft.client.gui.screens.*;
import net.minecraft.client.multiplayer.ServerData;
import net.minecraft.client.multiplayer.resolver.ServerAddress;
import net.neoforged.api.distmarker.Dist;
import net.neoforged.bus.api.SubscribeEvent;
import net.neoforged.fml.common.EventBusSubscriber;
import java.util.*;
@EventBusSubscriber(modid="rivet",value=Dist.CLIENT)
public final class MapPositionsHarness {
 private static final String ADDRESS=System.getenv("RIVET_POSITIONS_ADDRESS");
 private static final List<VisualMatrixHarness.Frame> FLOWS=VisualMatrixHarness.flows(1,1),FRAMES=VisualMatrixHarness.samples(1,0);
 private static boolean connected,done,wire,wirePositions,peerVisible;private static final String PEER=new UUID(0,987).toString();private static int stage,ticks,flow,frame,checks;private static long deadline;
 private static int peerRequests,requestsBefore,fixtureCount=1;private static long trafficAt;private static boolean largeBatch;private static int fragments;private static long wireBytes;
 private static JsonObject savedLayers,state;private static java.util.function.Consumer<JsonObject> network,fallback;private static MapPositionPolicy choice=MapPositionPolicy.defaults();private static MapSettingsScreen settings;
 private static void check(boolean v,String text){if(!v)throw new IllegalStateException(text);checks++;}
 private static boolean press(String text){for(var c:Minecraft.getInstance().screen.children())if(c instanceof Button b&&b.active&&b.getMessage().getString().startsWith(text)){b.onPress();return true;}return false;}
 private static void fixture(JsonObject q){String op=Json.opt(q,"op","");if(!op.startsWith("mapPosition")){fallback.accept(q);return;}var out=new JsonObject();out.addProperty("kind","community");out.addProperty("section","home");out.add("request",q.get("request"));if(op.equals("mapPositionPeers")){peerRequests++;out.addProperty("positionRevision",1);var peers=new JsonArray();if(peerVisible){String cursor=Json.opt(q,"cursor","");boolean compact=ServerMenuClient.supports(dev.abros.rivet.core.map.MapPositionPage.FEATURE);int limit=compact?4096:64;int first=cursor.isEmpty()?0:(int)(UUID.fromString(cursor).getLeastSignificantBits()-987+1);if(first>0)check(MapPositions.points().isEmpty(),"Partial snapshot published before final page");for(int i=first;i<Math.min(fixtureCount,first+limit);i++){var p=new JsonObject();p.addProperty("uuid",new UUID(0,987+i).toString());p.addProperty("name","TestPeer"+i);p.addProperty("dimension","minecraft:overworld");p.addProperty("x",100000+i);p.addProperty("y",70);p.addProperty("z",100000);peers.add(p);}if(!compact&&first+64<fixtureCount)out.addProperty("nextCursor",new UUID(0,987+first+63).toString());}out.add("peers",peers);}else{if(op.equals("mapPositionSave"))choice=MapPositionPolicy.read(q.getAsJsonObject("settings"));out.add("positionSettings",choice.json());out.addProperty("positionGroups",true);}if(op.equals("mapPositionPeers")&&ServerMenuClient.supports(dev.abros.rivet.core.map.MapPositionPage.FEATURE)){var rows=out.getAsJsonArray("peers");out.remove("peers");var pages=dev.abros.rivet.core.map.MapPositionPage.split(out,rows);for(int i=0;i<pages.size();i++){var packet=wire(pages.get(i));int index=i;java.util.concurrent.CompletableFuture.delayedExecutor(largeBatch?500+i*50:0,java.util.concurrent.TimeUnit.MILLISECONDS).execute(()->Minecraft.getInstance().execute(()->{if(done)return;if(largeBatch&&peerRequests==requestsBefore+1&&index<pages.size()-1)check(MapPositions.points().isEmpty(),"Partial batch published");fragments++;ServerMenuClient.receive(packet);if(largeBatch&&stage==15&&index<pages.size()-1){try{var f=MapPositions.class.getDeclaredField("session");f.setAccessible(true);check(((RequestSession)f.get(null)).pending(),"Request completed before final fragment");}catch(ReflectiveOperationException ex){throw new IllegalStateException(ex);}}}));}}else Minecraft.getInstance().execute(()->ServerMenuClient.receive(out));}
 private static JsonObject wire(JsonObject packet){var buffer=new net.minecraft.network.FriendlyByteBuf(io.netty.buffer.Unpooled.buffer());try{dev.abros.rivet.network.Protocol.FeatureState.CODEC.encode(buffer,new dev.abros.rivet.network.Protocol.FeatureState(dev.abros.rivet.core.map.MapPositionPage.wire(packet)));wireBytes+=buffer.readableBytes();return Json.parse(dev.abros.rivet.network.Protocol.FeatureState.CODEC.decode(buffer).json());}catch(java.io.IOException ex){throw new IllegalStateException(ex);}finally{buffer.release();}}
 @SubscribeEvent public static void tick(net.neoforged.neoforge.client.event.ClientTickEvent.Post event){if(ADDRESS==null||done)return;var mc=Minecraft.getInstance();try{
  if(!connected&&mc.screen instanceof TitleScreen){connected=true;deadline=System.currentTimeMillis()+180000;ConnectScreen.startConnecting(mc.screen,mc,ServerAddress.parseString(ADDRESS),new ServerData("Positions",ADDRESS,ServerData.Type.OTHER),false,null);}
  if(connected&&System.currentTimeMillis()>deadline)throw new IllegalStateException("Timeout stage="+stage);
  if(!WorldMapClient.ready()||++ticks%5!=0)return;
  if(stage==0){savedLayers=MapSettings.INSTANCE.layers.json();check(MapPositions.available(),"Feature not negotiated");check(!ServerMenuClient.supports("map-exchange"),"Removed exchange still advertised");check(!MapSettingsScreen.categories().contains("Обмен"),"Exchange category remains");check(SettingsCatalog.entries().stream().noneMatch(e->e.id().equals("exchange")),"Exchange search entry remains");network=dev.abros.rivet.network.Protocol.featureState;dev.abros.rivet.network.Protocol.featureState=j->{network.accept(j);if(j.has("positionRows")){check(ServerMenuClient.supports(dev.abros.rivet.core.map.MapPositionPage.FEATURE),"Compact reply not negotiated");wirePositions=true;}if(j.has("positionSettings")){check(MapPositionPolicy.read(j.getAsJsonObject("positionSettings")).equals(MapPositionPolicy.defaults()),"Real defaults are not full/all");wire=true;}};mc.setScreen(new MapSharingScreen(new WorldMapScreen(null)));stage++;return;}
  if(stage==1){if(!wire||!wirePositions)return;System.out.println("RIVET_POSITIONS_WIRE_OK");state=ServerMenuClient.state.deepCopy();dev.abros.rivet.network.Protocol.featureState=j->{};CommunityUiHarness.open("normal");ServerMenuClient.state.add("map",state.get("map").deepCopy());ServerMenuClient.state.add("features",state.get("features").deepCopy());fallback=ServerMenuClient.previewTransport;ServerMenuClient.previewTransport=MapPositionsHarness::fixture;MapPositions.reset();stage++;}
  if(stage==2){FLOWS.get(flow).apply();choice=MapPositionPolicy.defaults();settings=new MapSettingsScreen(new WorldMapScreen(null));mc.setScreen(settings);settings.revealSetting("positionPrivacy");check(mc.screen==settings,"Unexpected nested privacy screen");verifySidebar(settings);stage++;return;}
  if(stage==3){if(!press("Режим: На всей карте"))return;check(press("Только рядом"),"Nearby choice absent");stage++;return;}
  if(stage==4){UiGeometryHarness.verify(mc.screen);check(press("Кто видит:"),"Audience control absent");check(press("Участники моих объединений"),"Group audience absent");check(press("Сохранить"),"Save disabled");stage++;return;}
  if(stage==5){if(!choice.equals(new MapPositionPolicy("nearby","groups")))return;var parent=settings.parentScreen();mc.screen.onClose();check(mc.screen==parent,"Parent lost");settings=new MapSettingsScreen(parent);mc.setScreen(settings);settings.revealSetting("positionPrivacy");stage++;return;}
  if(stage==6){if(!press("Режим: Только рядом"))return;check(press("Скрыто"),"Hidden absent");check(press("Кто видит:"),"Audience absent");check(press("Никто"),"Nobody absent");check(press("Сохранить"),"Save absent");stage++;return;}
  if(stage==7){if(!choice.equals(new MapPositionPolicy("hidden","none")))return;UiGeometryHarness.verify(mc.screen);mc.screen.onClose();if(++flow<FLOWS.size()){stage=2;return;}stage++;}
  if(stage==8){if(frame>0){UiGeometryHarness.verify(mc.screen);String path=System.getenv("RIVET_POSITIONS_SCREENSHOTS");if(path!=null){var folder=new java.io.File(path);folder.mkdirs();UiCaptureHarness.grab(folder,"positions-"+frame+".png",mc.getMainRenderTarget(),m->{});}}if(frame==FRAMES.size()){MapPositions.reset();peerVisible=true;stage=9;return;}FRAMES.get(frame++).apply();choice=MapPositionPolicy.defaults();mc.setScreen(new MapSharingScreen(new WorldMapScreen(null)));}
  if(stage==9){if(MapPositions.points().isEmpty())return;check(MapPositions.points().size()==1,"Server player snapshot absent");var peer=MapPositions.points().getFirst();check(peer.location().x()==100000,"Full-map coordinate changed");var local=new net.minecraft.client.player.RemotePlayer(mc.level,new com.mojang.authlib.GameProfile(UUID.fromString(PEER),"TestPeer"));local.setPos(mc.player.getX()+1,mc.player.getY(),mc.player.getZ());check(!MapRadar.included(local),"Local radar bypassed privacy");MapPositions.navigate(peer);check(DirectionCue.hasTarget(),"Player route absent");peerVisible=false;var revoke=new JsonObject();revoke.addProperty("kind","mapPositionsChanged");ServerMenuClient.receive(revoke);check(MapPositions.points().isEmpty(),"Revoked position stayed visible");check(!DirectionCue.hasTarget(),"Revoked route remained");MapPositions.reset();peerVisible=true;stage=10;return;}
  if(stage==10){if(MapPositions.points().isEmpty())return;var expires=MapPositions.class.getDeclaredField("expires");expires.setAccessible(true);expires.setLong(null,0);check(MapPositions.points().isEmpty(),"Expired positions survived");var groups=new JsonObject();ServerMenuClient.state.add("modules",groups);groups.addProperty("groups",false);check(MapPositions.available(),"All-player positions depend on groups");ServerMenuClient.state.getAsJsonObject("map").addProperty("positions",false);check(!MapPositions.available(),"Server prohibition ignored");check(!MapLayers.available(MapLayers.Layer.PEERS),"Duplicate player layer present");ServerMenuClient.state.getAsJsonObject("map").addProperty("positions",true);MapSettings.INSTANCE.layers.set(MapLayers.Layer.PLAYERS,false,false);MapPositions.reset();requestsBefore=peerRequests;trafficAt=System.currentTimeMillis();stage=11;return;}

  if(stage==11){if(System.currentTimeMillis()-trafficAt<1200)return;check(peerRequests==requestsBefore,"Hidden player layer still polls");MapSettings.INSTANCE.layers.set(MapLayers.Layer.PLAYERS,false,true);stage=12;return;}
  if(stage==12){if(MapPositions.points().isEmpty())return;MapPositions.navigate(MapPositions.points().getFirst());MapSettings.INSTANCE.layers.set(MapLayers.Layer.PLAYERS,false,false);requestsBefore=peerRequests;trafficAt=System.currentTimeMillis();stage=13;return;}
  if(stage==13){if(System.currentTimeMillis()-trafficAt<1500)return;check(peerRequests>requestsBefore,"Hidden layer stopped active player navigation refresh");check(DirectionCue.hasTarget(),"Player navigation lost target while hidden");DirectionCue.clear();MapSettings.INSTANCE.layers.set(MapLayers.Layer.PLAYERS,false,true);fixtureCount=100;ServerMenuClient.state.getAsJsonArray("features").remove(new JsonPrimitive(dev.abros.rivet.core.map.MapPositionPage.FEATURE));MapPositions.reset();requestsBefore=peerRequests;trafficAt=System.currentTimeMillis();stage=14;return;}
  if(stage==14){if(MapPositions.points().size()!=100)return;check(peerRequests-requestsBefore==2,"100-player snapshot did not use exactly two pages");check(System.currentTimeMillis()-trafficAt<7000,"Snapshot exceeded TTL");System.out.println("RIVET_POSITIONS_PAGING_OK players=100 pages="+(peerRequests-requestsBefore)+" elapsedMs="+(System.currentTimeMillis()-trafficAt));ServerMenuClient.state.getAsJsonArray("features").add(dev.abros.rivet.core.map.MapPositionPage.FEATURE);largeBatch=true;mc.setScreen(new WorldMapScreen(null));fixtureCount=4096;MapPositions.reset();requestsBefore=peerRequests;fragments=0;wireBytes=0;trafficAt=System.currentTimeMillis();stage=15;return;}
  if(stage==15){if(MapPositions.points().size()!=4096)return;check(peerRequests-requestsBefore==1,"Batch used multiple requests");check(fragments==11,"Unexpected compact fragment count");check(System.currentTimeMillis()-trafficAt<7000,"Batch expired");System.out.println("RIVET_POSITIONS_BATCH_OK players=4096 requests=1 fragments="+fragments+" bytes="+wireBytes+" elapsedMs="+(System.currentTimeMillis()-trafficAt));trafficAt=System.currentTimeMillis();stage=16;return;}
  if(stage==16){check(MapPositions.points().size()==4096,"Positions disappeared between refreshes");if(System.currentTimeMillis()-trafficAt<9000)return;check(peerRequests-requestsBefore>=4,"Batch refresh stopped");MapPositions.reset();stage=17;return;}
  if(stage==17){var field=MapPositions.class.getDeclaredField("batch");field.setAccessible(true);var value=field.get(null);if(value==null)return;var number=value.getClass().getDeclaredField("page");number.setAccessible(true);if(number.getInt(value)==0)return;peerVisible=false;var revoked=new JsonObject();revoked.addProperty("kind","mapPositionsChanged");ServerMenuClient.receive(revoked);check(MapPositions.points().isEmpty(),"Revoked partial batch published");trafficAt=System.currentTimeMillis();stage=18;return;}
  if(stage==18){check(MapPositions.points().isEmpty(),"Delayed revoked packet republished positions");if(System.currentTimeMillis()-trafficAt<1500)return;verifyRetries();done=true;restore();System.out.println("RIVET_POSITIONS_OK checks="+checks+" flows="+flow+" frames="+frame+" idleTraffic=false navigationRefresh=true delayedBatch=true partialRevocation=true boundedRetries=true");mc.stop();return;}
 }catch(Throwable ex){done=true;System.out.println("RIVET_POSITIONS_FAILED stage="+stage);ex.printStackTrace();restore();mc.stop();}}
 private static void verifyRetries()throws Exception{
  MapPositions.reset();var next=MapPositions.class.getDeclaredField("next");next.setAccessible(true);
  var sent=new java.util.concurrent.atomic.AtomicInteger();var failing=new java.util.concurrent.atomic.AtomicBoolean(true);
  ServerMenuClient.previewTransport=q->{sent.incrementAndGet();var out=new JsonObject();out.addProperty("kind","community");out.add("request",q.get("request"));if(failing.get())out.addProperty("error","busy");else{out.addProperty("positionRevision",1);out=dev.abros.rivet.core.map.MapPositionPage.split(out,new JsonArray()).getFirst();}check(MapPositions.receive(out),"Retry response not accepted");};
  var expected=new dev.abros.rivet.core.map.MapPositionPoll();var id=Minecraft.getInstance().player.getUUID();
  for(int i=0;i<5;i++){
   next.setLong(null,1);long before=System.currentTimeMillis();MapPositions.tick();long after=System.currentTimeMillis();long delay=expected.failed(id);check(next.getLong(null)>=before+delay&&next.getLong(null)<=after+delay,"Backoff changed or escaped bound");check(MapPositions.points().isEmpty(),"Error retained stale snapshot");int count=sent.get();MapPositions.tick();check(sent.get()==count,"Retry ignored scheduled delay");
  }
  failing.set(false);next.setLong(null,1);MapPositions.tick();expected.reset();
  failing.set(true);next.setLong(null,1);long before=System.currentTimeMillis();MapPositions.tick();long after=System.currentTimeMillis();long delay=expected.failed(id);check(next.getLong(null)>=before+delay&&next.getLong(null)<=after+delay,"Success did not reset retry delay");
  MapPositions.reset();int count=sent.get();MapPositions.tick();long phase=dev.abros.rivet.core.map.MapPositionPoll.initialDelay(id);if(phase>0)check(sent.get()==count,"Initial request ignored player phase");
 }
 static void verifySidebar(MapSettingsScreen screen){
  var sidebar=screen.children().stream().filter(c->c instanceof UiSettingsSidebar).map(c->(UiSettingsSidebar)c).findFirst();if(sidebar.isEmpty())return;
  var nav=sidebar.get();int x=nav.getX()+2,y=nav.getY()+2;int content=screen.firstRow;check(screen.mouseScrolled(x,y,0,20),"Sidebar cannot scroll up");check(screen.children().stream().anyMatch(c->c instanceof SidebarButton b&&b.getMessage().getString().equals("Отрисовка")),"Top section unreachable");check(screen.firstRow==content,"Sidebar scroll moved settings contents");check(screen.mouseScrolled(x,y,0,-20),"Sidebar cannot scroll down");check(screen.children().stream().anyMatch(c->c instanceof SidebarButton b&&b.getMessage().getString().equals("Видимость")),"Last section unreachable");
  int footer=screen.children().stream().filter(c->c instanceof Button b&&b.getMessage().getString().equals("Клавиши…")).mapToInt(c->((Button)c).getY()).min().orElseThrow();for(var c:screen.children())if(c instanceof SidebarButton b)check(b.getY()+b.getHeight()<=footer-4,"Section overlaps pinned action");
  check(screen.mouseClicked(nav.getX()+nav.getWidth()-2,nav.getY()+2,0),"Scrollbar thumb not clickable");check(screen.mouseDragged(nav.getX()+nav.getWidth()-2,nav.getY()+nav.getHeight()-2,0,0,50),"Scrollbar drag stopped after rebuild");screen.mouseReleased(x,y,0);
 }
 private static void restore(){if(savedLayers!=null)MapSettings.INSTANCE.layers.load(savedLayers);MapPositions.reset();ServerMenuClient.previewTransport=null;if(network!=null)dev.abros.rivet.network.Protocol.featureState=network;if(state!=null)ServerMenuClient.state=state;UiPalette.preview(0);Minecraft.getInstance().options.guiScale().set(2);Minecraft.getInstance().resizeDisplay();}
}
