package dev.abros.rivet.client;

import dev.abros.rivet.core.NativeLayout;
import dev.abros.rivet.core.map.*;
import net.minecraft.client.Minecraft;
import net.minecraft.client.gui.components.*;
import net.minecraft.client.gui.screens.*;
import net.minecraft.client.multiplayer.ServerData;
import net.minecraft.client.multiplayer.resolver.ServerAddress;
import net.neoforged.api.distmarker.Dist;
import net.neoforged.bus.api.SubscribeEvent;
import net.neoforged.fml.common.EventBusSubscriber;
import java.util.*;

/** Actual-world minimap, settings and HUD flow. Opt-in, absent from production. */
@EventBusSubscriber(modid="rivet",value=Dist.CLIENT)
public final class MinimapHarness {
 private static final List<VisualMatrixHarness.Frame> FRAMES="true".equals(System.getenv("RIVET_MINIMAP_TEST_QUICK"))?List.of(new VisualMatrixHarness.Frame(0,3,false,0)):VisualMatrixHarness.flows(1,1);
 private static int step=-1,profile,ticks,checks,normalSize;private static boolean positioned,done;
 private static UUID marker,farMarker;private static NativeLayout.Box before;private static com.google.gson.JsonObject serverState;private static String capture="";
 private static long deadline;
 @SubscribeEvent public static void tick(net.neoforged.neoforge.client.event.ClientTickEvent.Post e){
  var address=System.getenv("RIVET_MINIMAP_TEST_ADDRESS");if(address==null||done)return;var mc=Minecraft.getInstance();var s=MapSettings.INSTANCE;
  try{
   if(step==-1){if(!(mc.screen instanceof TitleScreen))return;deadline=System.currentTimeMillis()+240000;ConnectScreen.startConnecting(mc.screen,mc,ServerAddress.parseString(address),new ServerData("Minimap test",address,ServerData.Type.OTHER),false,null);step=0;return;}
   if(System.currentTimeMillis()>deadline)throw new IllegalStateException("Minimap timed out at "+step);
   if(!WorldMapClient.ready()||!WorldMapClient.markersReady())return;
   if(!positioned){positioned=true;mc.player.connection.sendCommand("tp @s 14 83 -35");mc.player.connection.sendCommand("gamemode creative");ticks=0;return;}
   if(++ticks%12!=0||ticks<100)return;
   switch(step){
    case 0->{if(profile<FRAMES.size())FRAMES.get(profile).apply();else{UiPalette.preview(0);mc.getWindow().setWindowed(profile==FRAMES.size()?960:640,profile==FRAMES.size()?540:480);mc.options.guiScale().set(3);mc.resizeDisplay();}s.reset();if(!s.rotate)throw new IllegalStateException("Rotation must default on");HudPlacement.reset();s.round=true;mc.setScreen(new HudInteractionScreen(false,null));step++;}
    case 1->{if(!Minimap.visible())throw new IllegalStateException("Minimap not visible");box();before=Minimap.bounds;normalSize=before.width();if(!Minimap.contains(before.x()+normalSize/2d,before.y()+normalSize/2d)||Minimap.contains(before.x(),before.y()))throw new IllegalStateException("Wrong circle hit mask");s.round=false;Minimap.invalidate();checks+=2;step++;}
    case 2->{if(!Minimap.contains(Minimap.bounds.x()+1,Minimap.bounds.y()+1))throw new IllegalStateException("Square corners excluded");s.rotate=true;mc.player.setYRot(90);Minimap.invalidate();checks++;step++;}
    case 3->{box();mc.screen.keyPressed(org.lwjgl.glfw.GLFW.GLFW_KEY_Z,0,0);step++;}
    case 4->{if(Minimap.bounds.width()<=normalSize)throw new IllegalStateException("Hold did not enlarge minimap");box();mc.screen.keyReleased(org.lwjgl.glfw.GLFW.GLFW_KEY_Z,0,0);mc.setScreen(new ChatScreen(""));checks++;step++;}
    case 5->{if(!Minimap.visible()||Minimap.bounds.width()!=normalSize)throw new IllegalStateException("Chat hid minimap or released key did not restore size");s.enabled=false;checks++;step++;}
    case 6->{if(Minimap.bounds.width()!=0||Minimap.visible())throw new IllegalStateException("Player-disabled minimap visible");s.enabled=true;mc.setScreen(new MapSettingsScreen(null));checks++;step++;}
    case 7->{var settings=(MapSettingsScreen)mc.screen;for(var entry:SettingsCatalog.section(7)){settings.revealSetting(entry.id());widgets(mc.screen);}settings.revealSetting("enabled");((Button)settings.children().stream().filter(c->c instanceof UiToggle b&&b.getMessage().getString().equals("Показывать миникарту")).findFirst().orElseThrow()).onPress();if(s.enabled)throw new IllegalStateException("Settings toggle failed");var json=dev.abros.rivet.core.Json.read(mc.gameDirectory.toPath().resolve("rivet/map-settings.json"));if(json.get("enabled").getAsBoolean())throw new IllegalStateException("Settings not saved");if(SettingsSearchScreen.search("миникарта").size()<10)throw new IllegalStateException("Map settings absent from search");s.enabled=true;s.round=true;s.rotate=false;s.biome=s.time=s.weather=true;mc.setScreen(new HudInteractionScreen(true,null));checks+=3;step++;}
    case 8->{box();before=Minimap.bounds;mc.screen.mouseClicked(before.x()+before.width()/2d,before.y()+before.width()/2d,0);mc.screen.mouseDragged(before.x()+before.width()/2d+20,before.y()+before.width()/2d+24,0,20,24);mc.screen.mouseReleased(before.x()+before.width()/2d+20,before.y()+before.width()/2d+24,0);step++;}
    case 9->{box();if(before.x()==Minimap.bounds.x()&&before.y()==Minimap.bounds.y())throw new IllegalStateException("HUD editor did not move minimap");int old=s.size;mc.screen.mouseScrolled(Minimap.bounds.x()+Minimap.bounds.width()/2d,Minimap.bounds.y()+Minimap.bounds.width()/2d,0,1);if(s.size!=old+8)throw new IllegalStateException("HUD editor did not resize minimap");var hud=HudSettings.INSTANCE;for(String item:List.of("widget","chat","direction","notices")){
     if(!HudPlacement.resize(item,1))throw new IllegalStateException("Missing HUD resize: "+item);
    }var saved=dev.abros.rivet.core.Json.read(mc.gameDirectory.toPath().resolve("rivet/hud.json"));if(saved.get("scale").getAsFloat()<=HudSettings.DEFAULT_SCALE||saved.get("hintScale").getAsFloat()<=1||dev.abros.rivet.core.Json.read(mc.gameDirectory.toPath().resolve("rivet/map-settings.json")).getAsJsonObject("hud").get("directionScale").getAsFloat()<=1||saved.get("toastScale").getAsFloat()<=1)throw new IllegalStateException("HUD sizes not persisted");checks+=6;step++;}
    case 10->{box();s.reset();if(!s.rotate)throw new IllegalStateException("Rotation must default on");HudPlacement.reset();marker=UUID.randomUUID();var m=new MapMarker(marker,mc.level.dimension().location().toString(),"Minimap marker",mc.player.getBlockX()-20,mc.player.getBlockY(),mc.player.getBlockZ()+15,0xff87d59c,"pin_green");WorldMapClient.put(m);mc.setScreen(new HudInteractionScreen(false,null));step++;}
    case 11->{var m=WorldMapClient.markers().stream().filter(v->v.id().equals(marker)).findFirst().orElseThrow();var p=new MinimapProjection(mc.player.getX(),mc.player.getZ(),s.zoom,mc.player.getYRot(),s.rotate);double x=Minimap.bounds.x()+Minimap.bounds.width()/2d+p.screenX(m.x()+.5,m.z()+.5),y=Minimap.bounds.y()+Minimap.bounds.width()/2d+p.screenY(m.x()+.5,m.z()+.5);mc.screen.mouseClicked(x,y,0);if(!(mc.screen instanceof WorldMapScreen map)||map.draftMarker()==null||!map.draftMarker().id().equals(marker))throw new IllegalStateException("Minimap marker did not open its card");checks++;step++;}
    case 12->{mc.screen.onClose();if(!(mc.screen instanceof HudInteractionScreen))throw new IllegalStateException("Card did not return to cursor mode");step++;}
    case 13->{double old=s.zoom;mc.screen.mouseScrolled(Minimap.bounds.x()+Minimap.bounds.width()/2d,Minimap.bounds.y()+Minimap.bounds.width()/2d,0,1);if(s.zoom<=old)throw new IllegalStateException("Cursor wheel did not zoom minimap");WorldMapClient.delete(marker);serverState=ServerMenuClient.state;ServerMenuClient.state=serverState.deepCopy();try{ServerMenuClient.state.getAsJsonObject("map").addProperty("enabled",false);if(Minimap.visible())throw new IllegalStateException("Server-disabled minimap visible");}finally{ServerMenuClient.state=serverState;}checks+=2;farMarker=UUID.randomUUID();WorldMapClient.put(new MapMarker(farMarker,mc.level.dimension().location().toString(),"Far marker",mc.player.getBlockX()+10000,mc.player.getBlockY(),mc.player.getBlockZ()-4000,0xffe2be75,"pin_blue"));step=14;}
    case 14->{var m=WorldMapClient.markers().stream().filter(v->v.id().equals(farMarker)).findFirst().orElseThrow();var projection=new MinimapProjection(mc.player.getX(),mc.player.getZ(),s.zoom,mc.player.getYRot(),s.rotate);var pin=MinimapProjection.pin(projection.screenX(m.x()+.5,m.z()+.5),projection.screenY(m.x()+.5,m.z()+.5),Minimap.bounds.width()/2-2,s.round);double outside=(Minimap.bounds.width()/2d+3)/(Minimap.bounds.width()/2d-2),clickX=Minimap.bounds.x()+Minimap.bounds.width()/2d+pin[0]*outside,clickY=Minimap.bounds.y()+Minimap.bounds.width()/2d+pin[1]*outside;if(Minimap.contains(clickX,clickY))throw new IllegalStateException("Far marker test must click outside rim");mc.screen.mouseClicked(clickX,clickY,0);if(!(mc.screen instanceof WorldMapScreen map)||map.draftMarker()==null||!map.draftMarker().id().equals(farMarker))throw new IllegalStateException("Offscreen marker missing from edge");if(Minimap.captions().stream().noneMatch(v->v.startsWith("Мир · ")))throw new IllegalStateException("Dimension caption missing");WorldMapClient.delete(farMarker);mc.setScreen(new HudInteractionScreen(true,null));checks+=2;step=15;}
    case 15->{for(var b:List.of(ChatHints.bounds,DirectionCue.bounds,HudRenderer.noticeBounds)){if(b.width()<=0||b.height()<=0||b.x()<0||b.y()<0||b.right()>mc.screen.width||b.bottom()>mc.screen.height)throw new IllegalStateException("Resized HUD outside viewport: "+b);}checks+=3;step=16;}
    case 16->{s.reset();if(!s.rotate)throw new IllegalStateException("Rotation must default on");HudPlacement.reset();mc.setScreen(null);if(++profile<=FRAMES.size()+1){step=0;ticks=0;}else{System.out.println("RIVET_MINIMAP_UI_OK checks="+checks+("true".equals(System.getenv("RIVET_MINIMAP_TEST_QUICK"))?" profiles=default scales=3":" profiles=default,light,contrast scales=1,2,3")+" compact=true serverPolicy=true");done=true;mc.stop();}}
   }
  }catch(Throwable ex){System.out.println("RIVET_MINIMAP_UI_FAILED step="+step+" profile="+profile);ex.printStackTrace();done=true;mc.stop();}
 }
 private static void box(){var b=Minimap.bounds;var mc=Minecraft.getInstance();if(b.width()<32||b.x()<0||b.y()<0||b.right()>mc.getWindow().getGuiScaledWidth()||b.bottom()>mc.getWindow().getGuiScaledHeight())throw new IllegalStateException("Minimap outside viewport: "+b);checks++;}
 private static void widgets(Screen screen){var a=screen.children().stream().filter(c->c instanceof AbstractWidget w&&w.visible).map(c->(AbstractWidget)c).toList();for(var w:a){if(w.getX()<0||w.getY()<0||w.getX()+w.getWidth()>screen.width||w.getY()+w.getHeight()>screen.height)throw new IllegalStateException("Settings out of bounds");for(var v:a)if(v!=w&&w.getX()<v.getX()+v.getWidth()&&v.getX()<w.getX()+w.getWidth()&&w.getY()<v.getY()+v.getHeight()&&v.getY()<w.getY()+w.getHeight())throw new IllegalStateException("Settings overlap: "+w.getMessage()+" / "+v.getMessage());}checks++;}
 @SubscribeEvent public static void render(net.neoforged.neoforge.client.event.ScreenEvent.Render.Post e){String folder=System.getenv("RIVET_MINIMAP_SCREENSHOTS");if(folder==null||done||System.getenv("RIVET_MINIMAP_TEST_ADDRESS")==null||ticks%12!=1||capture.equals(profile+"-"+step))return;capture=profile+"-"+step;var output=new java.io.File(folder);output.mkdirs();UiCaptureHarness.grab(output,"minimap-"+capture+".png",Minecraft.getInstance().getMainRenderTarget(),m->{});}
}
