package dev.abros.rivet.client;
import net.minecraft.client.Minecraft;
import net.minecraft.client.gui.components.*;
import net.minecraft.client.gui.screens.*;
import net.neoforged.neoforge.client.event.ScreenEvent;
import net.neoforged.bus.api.SubscribeEvent;
import net.neoforged.fml.common.EventBusSubscriber;
import net.neoforged.api.distmarker.Dist;
import java.util.*;
@EventBusSubscriber(modid="rivet",value=Dist.CLIENT)
public final class NativeUiHarness {
 private static final List<VisualMatrixHarness.Frame> FRAMES=VisualMatrixHarness.flows(6,2);
 private static int total(){return FRAMES.size();}
 private static int step=-1;private static long at;
 @SubscribeEvent public static void tick(ScreenEvent.Render.Post event){String output=System.getenv("RIVET_NATIVE_UI");boolean preview=System.getenv("RIVET_NATIVE_PREVIEW")!=null,checkOnly=System.getenv("RIVET_NATIVE_CHECK_ONLY")!=null;if(output==null&&!preview&&!checkOnly||step>total())return;var mc=Minecraft.getInstance();if(step<0){if(!(mc.screen instanceof TitleScreen))return;try{int selected=UiPalette.selected();for(int theme=0;theme<UiPalette.names().size();theme++){UiPalette.preview(theme);verifyContrast();}UiPalette.preview(selected);System.out.println("RIVET_THEME_ROLES_OK: contrast and repeated tint, all configured themes");if(checkOnly){step=total()+1;mc.stop();return;}}catch(Throwable failure){System.out.println("RIVET_NATIVE_FAILED initialization");step=total()+1;failure.printStackTrace();mc.stop();return;}CommunityUiHarness.open("normal");DialogUiHarness.verifyContracts();verifyNavigation();verifyPendingExit();CommunityUiHarness.open("normal");var original=ServerMenuClient.previewTransport;ServerMenuClient.previewTransport=q->{if(dev.abros.rivet.core.Json.opt(q,"op","").startsWith("work"))NextUiHarness.request(q);else original.accept(q);};step=preview?total()+1:0;if(preview){UiPalette.preview(0);mc.options.guiScale().set(3);mc.resizeDisplay();mc.setScreen(new TaskScreen(null,"",""));System.out.println("RIVET_NATIVE_PREVIEW_READY");}at=System.currentTimeMillis()+700;return;}if(System.currentTimeMillis()<at)return;at=System.currentTimeMillis()+500;try{if(step>0){bounds();var dir=new java.io.File(output);dir.mkdirs();UiCaptureHarness.grab(dir,String.format("native-%03d.png",step),mc.getMainRenderTarget(),m->{});}if(step==total()){System.out.println("RIVET_NATIVE_OK: frames="+total()+", default/light/high contrast flows, three scales, inline create/save");step++;mc.stop();return;}var frame=FRAMES.get(step);frame.apply();int local=frame.scene();switch(local){case 0->{mc.setScreen(new TaskScreen(null,"",""));}case 1->{for(var c:mc.screen.children())if(c instanceof CommunityCard card){card.onPress();break;}}case 2->press("Раздел задачи", "Обзор ▾");case 3->{mc.setScreen(new TaskScreen(null,"",""));}case 4->press("Новая задача","Новая задача");case 5->{for(var c:mc.screen.children())if(c instanceof EditBox box)box.setValue("Проверка нативной формы");press("Сохранить","Сохранить");}}step++;}catch(Throwable failure){System.out.println("RIVET_NATIVE_FAILED step="+step);step=total()+1;failure.printStackTrace();mc.stop();}}
 private static void verifyNavigation(){try{var mc=Minecraft.getInstance();mc.setScreen(new TitleScreen());UiNavigation.clear();var outside=mc.screen;var board=new CommunityScreen(null,"board","");var method=CommunityUiHarness.class.getDeclaredMethod("entry",String.class,int.class);method.setAccessible(true);var entries=new com.google.gson.JsonArray();for(int n=0;n<100;n++)entries.add((com.google.gson.JsonObject)method.invoke(null,"board",n));board.data.add("entries",entries);var query=CommunityScreen.class.getDeclaredField("query");query.setAccessible(true);query.set(board,"Сохранённый поиск");board.mine=true;mc.setScreen(board);board.restoreScroll(7);board.refreshUi();var selected=CommunityScreen.class.getDeclaredField("expanded");selected.setAccessible(true);var detail=new CommunityScreen(board,"board",dev.abros.rivet.core.Json.str(entries.get(7).getAsJsonObject(),"id"));detail.data.add("detail",entries.get(7).deepCopy());var prepare=CommunityScreen.class.getDeclaredMethod("prepareInline",CommunityScreen.class);prepare.setAccessible(true);prepare.invoke(detail,board);((java.util.Map<String,CommunityScreen>)selected.get(board)).put(detail.itemId,detail);UiNavigation.open(board,"events");UiNavigation.open(mc.screen,"board");if(mc.screen!=board||!board.mine||!query.get(board).equals("Сохранённый поиск")||board.firstRow!=7||!((java.util.Map<?,?>)selected.get(board)).containsKey(detail.itemId))throw new IllegalStateException("Navigation lost filters, selection or position");mc.setScreen(new ChoicePopup(board,"Проверка возврата",java.util.List.of("Один"),n->{}));mc.screen.onClose();if(mc.screen!=board)throw new IllegalStateException("Popup did not restore workspace");if(UiNavigation.exitCommand(detail,board)!=UiActions.Command.BACK)throw new IllegalStateException("Nested entry lost Back");mc.setScreen(detail);detail.onClose();if(mc.screen!=board)throw new IllegalStateException("Detail did not return to parent");press("root exit",Client.tr(UiActions.Command.CLOSE.label).getString());if(mc.screen!=outside)throw new IllegalStateException("Close returned to a previous section");
for(String key:java.util.List.of("home","tasks","groups","players","help","admin")){mc.setScreen(new CommunityScreen(null,"home",""));UiNavigation.open(mc.screen,key);var root=mc.screen;if(root.children().stream().noneMatch(c->c instanceof Button b&&UiActions.commandOf(b)==UiActions.Command.CLOSE))throw new IllegalStateException("Missing root Close: "+key);mc.setScreen(new ChoicePopup(root,"Проверка возврата",java.util.List.of("Один"),n->{}));mc.screen.onClose();if(mc.screen!=root)throw new IllegalStateException("Nested dialog lost parent: "+key);press("root exit",Client.tr(UiActions.Command.CLOSE.label).getString());if(mc.screen!=outside)throw new IllegalStateException("Close did not leave Rivet: "+key);}
var root=new CommunityScreen(null,"home","");mc.setScreen(root);
for(Screen nested:java.util.List.of(new ServerMenuScreen(root,"help"),new FeatureListScreen(root,"players"),new TaskScreen(root,"",""))){mc.setScreen(nested);UiInputHarness.escape(nested);if(mc.screen!=root)throw new IllegalStateException("Escape skipped nested parent: "+nested.getClass().getSimpleName());}
var editor=new TaskEditScreen(root,"Проверка отмены",java.util.List.of(new CommunityScreen.Field("title","Название",100)),new com.google.gson.JsonObject(),j->{});mc.setScreen(editor);for(var c:editor.children())if(c instanceof EditBox box)box.setValue("Несохранённый текст");UiInputHarness.escape(editor);if(!(mc.screen instanceof UiConfirmDialog))throw new IllegalStateException("Escape discarded unsaved input without confirmation");UiInputHarness.escape(mc.screen);if(mc.screen!=editor)throw new IllegalStateException("Escape did not cancel the discard dialog");
mc.setScreen(root);UiInputHarness.escape(root);if(mc.screen!=outside)throw new IllegalStateException("Root Escape did not close Rivet");
UiNavigation.clear();System.out.println("RIVET_NAVIGATION_MEMORY_OK: query, filter, selection, scroll, root Close and nested Back");}catch(ReflectiveOperationException ex){throw new IllegalStateException(ex);}}
 private static void verifyPendingExit(){try{var mc=Minecraft.getInstance();var root=new CommunityScreen(null,"home","");mc.setScreen(root);var task=new TaskScreen(root,"","");mc.setScreen(task);var field=TaskScreen.class.getDeclaredField("workspace");field.setAccessible(true);var workspace=(dev.abros.rivet.core.TaskWorkspace)field.get(task);workspace.cancelRead();var busy=dev.abros.rivet.core.TaskWorkspace.class.getDeclaredField("busy");busy.setAccessible(true);var op=dev.abros.rivet.core.TaskWorkspace.class.getDeclaredField("operation");op.setAccessible(true);op.set(workspace,"workStatus");busy.setBoolean(workspace,true);press("pending task inbox",MenuSidebar.inboxLabel(task.width));if(mc.screen!=task)throw new IllegalStateException("Inbox interrupted task mutation");UiInputHarness.escape(task);if(mc.screen!=task||!workspace.busy())throw new IllegalStateException("Esc interrupted task mutation");busy.setBoolean(workspace,false);op.set(workspace,"workList");busy.setBoolean(workspace,true);press("reading task inbox",MenuSidebar.inboxLabel(task.width));if(!(mc.screen instanceof NotificationPopup)||workspace.busy())throw new IllegalStateException("Inbox did not cancel background task read");mc.screen.onClose();if(mc.screen!=task)throw new IllegalStateException("Inbox did not restore task parent");task.onClose();if(mc.screen!=root)throw new IllegalStateException("Completed task could not close");var group=new CommunityScreen(root,"groups","");mc.setScreen(group);var modelField=CommunityScreen.class.getDeclaredField("model");modelField.setAccessible(true);var model=(dev.abros.rivet.core.CommunityWorkspace)modelField.get(group);model.close();busy=dev.abros.rivet.core.CommunityWorkspace.class.getDeclaredField("busy");busy.setAccessible(true);op=dev.abros.rivet.core.CommunityWorkspace.class.getDeclaredField("operation");op.setAccessible(true);op.set(model,"join");busy.setBoolean(model,true);press("pending community inbox",MenuSidebar.inboxLabel(group.width));if(mc.screen!=group)throw new IllegalStateException("Inbox interrupted community mutation");UiInputHarness.escape(group);if(mc.screen!=group||!model.busy())throw new IllegalStateException("Esc interrupted community mutation");busy.setBoolean(model,false);group.onClose();if(mc.screen!=root)throw new IllegalStateException("Completed community could not close");UiNavigation.clear();System.out.println("RIVET_PENDING_EXIT_OK: mutation cannot lose its response on Escape");}catch(ReflectiveOperationException failure){throw new IllegalStateException(failure);}}
 private static double luminance(int color){double result=0;double[] weights={0.0722,0.7152,0.2126};for(int n=0;n<3;n++){double c=((color>>(n*8))&255)/255.0;result+=weights[n]*(c<=0.04045?c/12.92:Math.pow((c+0.055)/1.055,2.4));}return result;}
 private static double contrast(int a,int b){double x=luminance(a),y=luminance(b);return (Math.max(x,y)+0.05)/(Math.min(x,y)+0.05);}
 static void verifyContrast(){for(int source:new int[]{0xFFE0E9EE,0xFFA4B5C0,0xFFD5F4EB,0xFF79CBA6,0xFF82B6F2,0xFFF0A77C,0xFFB49AE8,0xFFEF7777}){int color=UiPalette.color(source);if(UiPalette.color(color)!=color)throw new IllegalStateException("Repeated text tint: "+UiPalette.name());if(contrast(color,UiKit.surface())<4.5)throw new IllegalStateException("Text role contrast: "+UiPalette.name()+" "+Integer.toHexString(source));}if(contrast(UiKit.text(),UiKit.surface())<4.5||contrast(UiKit.text(),UiPalette.inputSurface())<4.5||contrast(UiKit.muted(),UiKit.surface())<4.5)throw new IllegalStateException("Insufficient contrast: "+UiPalette.name());}
 private static void press(String context,String label){for(var c:Minecraft.getInstance().screen.children())if(c instanceof Button b&&b.active&&b.getMessage().getString().equals(label)){b.onPress();return;}if(!label.equals("Обзор ▾"))throw new IllegalStateException("Missing action: "+context);}
 private static void bounds(){var s=Minecraft.getInstance().screen;UiGeometryHarness.verify(s);var widgets=s.children().stream().filter(c->c instanceof AbstractWidget).map(c->(AbstractWidget)c).filter(w->w.visible).toList();for(var w:widgets)if(w.getX()<0||w.getY()<0||w.getX()+w.getWidth()>s.width||w.getY()+w.getHeight()>s.height||w.getHeight()<=0||w.getWidth()<=0)throw new IllegalStateException(s.getClass().getSimpleName()+" invalid bounds: "+w.getMessage().getString());for(int i=0;i<widgets.size();i++)for(int n=i+1;n<widgets.size();n++){var a=widgets.get(i);var b=widgets.get(n);if(a.getX()<b.getX()+b.getWidth()&&b.getX()<a.getX()+a.getWidth()&&a.getY()<b.getY()+b.getHeight()&&b.getY()<a.getY()+a.getHeight())throw new IllegalStateException(s.getClass().getSimpleName()+" overlaps: "+a.getMessage().getString()+" / "+b.getMessage().getString());}}
}
