package dev.abros.rivet.client;
import net.minecraft.client.Minecraft;
import net.minecraft.client.gui.components.*;
import net.minecraft.client.gui.screens.*;
import net.neoforged.neoforge.client.event.ScreenEvent;
import net.neoforged.bus.api.SubscribeEvent;
import net.neoforged.fml.common.EventBusSubscriber;
import net.neoforged.api.distmarker.Dist;
import java.util.*;
@EventBusSubscriber(modid="rivet",value=Dist.CLIENT)
public final class NativeUiHarness {
 private static int total(){return UiPalette.names().size()*18;}
 private static int step=-1;private static long at;
 @SubscribeEvent public static void tick(ScreenEvent.Render.Post event){String output=System.getenv("RIVET_NATIVE_UI");boolean preview=System.getenv("RIVET_NATIVE_PREVIEW")!=null,checkOnly=System.getenv("RIVET_NATIVE_CHECK_ONLY")!=null;if(output==null&&!preview&&!checkOnly||step>=total())return;var mc=Minecraft.getInstance();if(step<0){if(!(mc.screen instanceof TitleScreen))return;try{int selected=UiPalette.selected();for(int theme=0;theme<UiPalette.names().size();theme++){UiPalette.preview(theme);verifyContrast();}UiPalette.preview(selected);System.out.println("RIVET_THEME_ROLES_OK: contrast and repeated tint, all configured themes");if(checkOnly){step=total();mc.stop();return;}}catch(Throwable failure){step=total();failure.printStackTrace();mc.stop();return;}CommunityUiHarness.open("normal");DialogUiHarness.verifyContracts();verifyNavigation();var original=ServerMenuClient.previewTransport;ServerMenuClient.previewTransport=q->{if(dev.abros.rivet.core.Json.opt(q,"op","").startsWith("work"))NextUiHarness.request(q);else original.accept(q);};step=preview?total():0;if(preview){UiPalette.preview(0);mc.options.guiScale().set(3);mc.resizeDisplay();mc.setScreen(new TaskScreen(null,"",""));System.out.println("RIVET_NATIVE_PREVIEW_READY");}at=System.currentTimeMillis()+700;return;}if(System.currentTimeMillis()<at)return;at=System.currentTimeMillis()+500;try{if(step>0){bounds();var dir=new java.io.File(output);dir.mkdirs();net.minecraft.client.Screenshot.grab(dir,String.format("native-%03d.png",step),mc.getMainRenderTarget(),m->{});}int local=step%6,group=step/6;UiPalette.preview(group%UiPalette.names().size());verifyContrast();switch(local){case 0->{mc.options.guiScale().set(2+group/UiPalette.names().size());mc.resizeDisplay();mc.setScreen(new TaskScreen(null,"",""));}case 1->{for(var c:mc.screen.children())if(c instanceof CommunityCard card){card.onPress();break;}}case 2->press("Раздел задачи", "Обзор ▾");case 3->{mc.setScreen(new TaskScreen(null,"",""));}case 4->press("Новая задача","Новая задача");case 5->{for(var c:mc.screen.children())if(c instanceof EditBox box)box.setValue("Проверка нативной формы");press("Сохранить","Сохранить");}}step++;if(step==total()){bounds();System.out.println("RIVET_NATIVE_OK: all themes, three GUI scales, inline create/save");mc.stop();}}catch(Throwable failure){System.out.println("RIVET_NATIVE_FAILED step="+step);step=total();failure.printStackTrace();mc.stop();}}
 private static void verifyNavigation(){try{var mc=Minecraft.getInstance();var board=new CommunityScreen(null,"board","");var method=CommunityUiHarness.class.getDeclaredMethod("entry",String.class,int.class);method.setAccessible(true);var entries=new com.google.gson.JsonArray();for(int n=0;n<100;n++)entries.add((com.google.gson.JsonObject)method.invoke(null,"board",n));board.data.add("entries",entries);var query=CommunityScreen.class.getDeclaredField("query");query.setAccessible(true);query.set(board,"Сохранённый поиск");board.mine=true;mc.setScreen(board);board.restoreScroll(7);board.refreshUi();var selected=CommunityScreen.class.getDeclaredField("expanded");selected.setAccessible(true);var detail=new CommunityScreen(board,"board",dev.abros.rivet.core.Json.str(entries.get(7).getAsJsonObject(),"id"));detail.data.add("detail",entries.get(7).deepCopy());var prepare=CommunityScreen.class.getDeclaredMethod("prepareInline",CommunityScreen.class);prepare.setAccessible(true);prepare.invoke(detail,board);((java.util.Map<String,CommunityScreen>)selected.get(board)).put(detail.itemId,detail);UiNavigation.open(board,"events");UiNavigation.open(mc.screen,"board");if(mc.screen!=board||!board.mine||!query.get(board).equals("Сохранённый поиск")||board.firstRow!=7||!((java.util.Map<?,?>)selected.get(board)).containsKey(detail.itemId))throw new IllegalStateException("Navigation lost filters, selection or position");UiNavigation.clear();System.out.println("RIVET_NAVIGATION_MEMORY_OK: query, filter, selected entry and scroll");}catch(ReflectiveOperationException ex){throw new IllegalStateException(ex);}}
 private static double luminance(int color){double result=0;double[] weights={0.0722,0.7152,0.2126};for(int n=0;n<3;n++){double c=((color>>(n*8))&255)/255.0;result+=weights[n]*(c<=0.04045?c/12.92:Math.pow((c+0.055)/1.055,2.4));}return result;}
 private static double contrast(int a,int b){double x=luminance(a),y=luminance(b);return (Math.max(x,y)+0.05)/(Math.min(x,y)+0.05);}
 static void verifyContrast(){for(int source:new int[]{0xFFE0E9EE,0xFFA4B5C0,0xFFD5F4EB,0xFF79CBA6,0xFF82B6F2,0xFFF0A77C,0xFFB49AE8,0xFFEF7777}){int color=UiPalette.color(source);if(UiPalette.color(color)!=color)throw new IllegalStateException("Repeated text tint: "+UiPalette.name());if(contrast(color,UiKit.surface())<4.5)throw new IllegalStateException("Text role contrast: "+UiPalette.name()+" "+Integer.toHexString(source));}if(contrast(UiKit.text(),UiKit.surface())<4.5||contrast(UiKit.text(),UiPalette.inputSurface())<4.5||contrast(UiKit.muted(),UiKit.surface())<4.5)throw new IllegalStateException("Insufficient contrast: "+UiPalette.name());}
 private static void press(String context,String label){for(var c:Minecraft.getInstance().screen.children())if(c instanceof Button b&&b.active&&b.getMessage().getString().equals(label)){b.onPress();return;}if(!label.equals("Обзор ▾"))throw new IllegalStateException("Missing action: "+context);}
 private static void bounds(){var s=Minecraft.getInstance().screen;UiGeometryHarness.verify(s);var widgets=s.children().stream().filter(c->c instanceof AbstractWidget).map(c->(AbstractWidget)c).filter(w->w.visible).toList();for(var w:widgets)if(w.getX()<0||w.getY()<0||w.getX()+w.getWidth()>s.width||w.getY()+w.getHeight()>s.height||w.getHeight()<=0||w.getWidth()<=0)throw new IllegalStateException(s.getClass().getSimpleName()+" invalid bounds: "+w.getMessage().getString());for(int i=0;i<widgets.size();i++)for(int n=i+1;n<widgets.size();n++){var a=widgets.get(i);var b=widgets.get(n);if(a.getX()<b.getX()+b.getWidth()&&b.getX()<a.getX()+a.getWidth()&&a.getY()<b.getY()+b.getHeight()&&b.getY()<a.getY()+a.getHeight())throw new IllegalStateException(s.getClass().getSimpleName()+" overlaps: "+a.getMessage().getString()+" / "+b.getMessage().getString());}}
}
