package dev.abros.rivet.client;
import com.google.gson.*;
import dev.abros.rivet.core.*;
import net.minecraft.client.Minecraft;
import net.minecraft.client.gui.components.*;
import net.minecraft.client.gui.screens.*;
import net.minecraft.network.chat.Component;
import net.neoforged.bus.api.SubscribeEvent;
import net.neoforged.fml.common.EventBusSubscriber;
import net.neoforged.api.distmarker.Dist;
import net.neoforged.neoforge.client.event.ScreenEvent;
import java.util.*;
@EventBusSubscriber(modid="rivet",value=Dist.CLIENT)
public final class RemainingUiHarness {
 private static int total(){return UiPalette.names().size()*36;}
 private static int step=-1;private static long at;private static java.util.function.Consumer<JsonObject> original;
 private static final String TASK=new UUID(0,42).toString();
 private static void request(JsonObject q){String op=Json.opt(q,"op",""),action=Json.opt(q,"action","");if(!op.startsWith("space")&&!Set.of("reports","reportManage","rolePreview").contains(action)){if(op.startsWith("work")||op.startsWith("tools")||action.equals("adminDashboard")){NextUiHarness.request(q);return;}original.accept(q);return;}var out=new JsonObject();out.addProperty("kind","community");out.addProperty("request",Json.opt(q,"request",""));
 if(action.equals("reports")){out.addProperty("kind","reports");var rows=new JsonArray();for(int n=0;n<12;n++){var e=new JsonObject();e.addProperty("id",new UUID(0,900+n).toString());e.addProperty("player","Игрок "+n);e.addProperty("message","Не удаётся подключиться к серверу");e.addProperty("status","open");e.addProperty("priority",n%2==0?"high":"normal");e.addProperty("revision",1);e.addProperty("createdAt",System.currentTimeMillis());e.addProperty("nextStep","Проверить журнал подключения");rows.add(e);}out.add("reports",rows);}
 else if(action.equals("rolePreview")){var rows=new JsonArray();var role=new JsonObject();role.addProperty("name","Модератор");var caps=new JsonObject();for(String right:List.of("rivet.admin","rivet.events","rivet.reports","rivet.restart","rivet.stats.view"))caps.addProperty(right,!right.equals("rivet.admin"));role.add("capabilities",caps);rows.add(role);out.add("roles",rows);out.addProperty("context","Предпросмотр; ваши права не меняются");}
 else if(action.equals("reportManage")){out.addProperty("affected",2);out.addProperty("skipped",1);out.addProperty("applied",false);var rows=new JsonArray();for(int n=0;n<3;n++){var r=new JsonObject();r.addProperty("title","Обращение игрока "+n);r.addProperty("reason",n==2?"Изменилось после выбора":"");rows.add(r);}out.add("preview",rows);}
 java.util.concurrent.CompletableFuture.delayedExecutor(80,java.util.concurrent.TimeUnit.MILLISECONDS).execute(()->Minecraft.getInstance().execute(()->ServerMenuClient.receive(out)));
 }
 @SubscribeEvent public static void tick(ScreenEvent.Render.Post event){String output=System.getenv("RIVET_REMAINING_UI");if(output==null||step>=total())return;var mc=Minecraft.getInstance();if(step<0){if(!(mc.screen instanceof TitleScreen))return;CommunityUiHarness.open("normal");DialogUiHarness.verifyContracts();for(int theme=0;theme<UiPalette.names().size();theme++){UiPalette.preview(theme);NativeUiHarness.verifyContrast();}UiPalette.preview(0);if(!MenuSidebar.sections().equals(List.of("home","players","tasks","board","groups","events","polls","ideas","help","admin")))throw new IllegalStateException("Unexpected navigation order: "+MenuSidebar.sections());original=ServerMenuClient.previewTransport;ServerMenuClient.previewTransport=RemainingUiHarness::request;step=System.getenv("RIVET_REMAINING_FROM")==null?0:Integer.parseInt(System.getenv("RIVET_REMAINING_FROM"));at=System.currentTimeMillis()+1000;return;}if(System.currentTimeMillis()<at)return;at=System.currentTimeMillis()+350;try{if(step>0){bounds();var dir=new java.io.File(output);dir.mkdirs();UiCaptureHarness.grab(dir,String.format("remaining-%03d.png",step),mc.getMainRenderTarget(),m->{});}int local=step%12,group=step/12;UiPalette.preview(group%UiPalette.names().size());dev.abros.rivet.network.Protocol.supportedFeatures=dev.abros.rivet.core.ConnectionCompatibility.FEATURES;ServerMenuClient.state.add("features",dev.abros.rivet.core.ConnectionCompatibility.features());if(local==0){mc.options.guiScale().set(1+group/UiPalette.names().size());mc.resizeDisplay();}
 switch(local){case 0->mc.setScreen(new CommunityScreen(null,"home",""));case 1->mc.setScreen(new CommunityScreen(null,"board",""));case 2->{var s=new TaskScreen(null,"","");mc.setScreen(s);}case 3->{for(var c:mc.screen.children())if(c instanceof CommunityCard card){card.onPress();break;}}case 4->FeatureListScreen.open(null,"players");case 5->mc.setScreen(new ReportQueueScreen(null,"new"));case 6->mc.setScreen(new RolePreviewScreen(null));case 7->mc.setScreen(new UiKitShowcaseScreen(null));case 8->mc.setScreen(new TaskScreen(null,"",TASK));case 9->{for(var c:mc.screen.children())if(c instanceof Button b&&b.getMessage().getString().endsWith(" ▾")&&b.getMessage().getString().startsWith("Обзор")){b.onPress();break;}}case 10->mc.setScreen(new PlacesScreen(null));case 11->mc.setScreen(new HomeWidgetsScreen(null));}step++;if(step==total()){bounds();System.out.println("RIVET_REMAINING_OK: all themes, three GUI scales");UiPalette.preview(0);mc.stop();}}
 catch(Throwable failure){System.out.println("RIVET_REMAINING_FAILED step="+step);step=total();failure.printStackTrace();mc.stop();}}
 private static void bounds(){var s=Minecraft.getInstance().screen;UiGeometryHarness.verify(s);var widgets=s.children().stream().filter(c->c instanceof AbstractWidget).map(c->(AbstractWidget)c).filter(w->w.visible).toList();for(var w:widgets)if(w.getX()<0||w.getY()<0||w.getX()+w.getWidth()>s.width||w.getY()+w.getHeight()>s.height)throw new IllegalStateException(s.getClass().getSimpleName()+" out of bounds: "+w.getMessage().getString());for(int i=0;i<widgets.size();i++)for(int n=i+1;n<widgets.size();n++){var a=widgets.get(i);var b=widgets.get(n);if(a.getX()<b.getX()+b.getWidth()&&b.getX()<a.getX()+a.getWidth()&&a.getY()<b.getY()+b.getHeight()&&b.getY()<a.getY()+a.getHeight())throw new IllegalStateException(s.getClass().getSimpleName()+" overlaps: "+a.getMessage().getString()+" / "+b.getMessage().getString());}}
}
