package dev.abros.rivet.client;
import java.util.*;
import com.google.gson.*;
import net.minecraft.client.Minecraft;
import net.minecraft.client.gui.screens.*;
import net.minecraft.client.gui.components.Button;
import net.neoforged.api.distmarker.Dist;
import net.neoforged.bus.api.SubscribeEvent;
import net.neoforged.fml.common.EventBusSubscriber;
import net.neoforged.neoforge.client.event.ScreenEvent;
@EventBusSubscriber(modid="rivet",value=Dist.CLIENT)
public final class ReorderUiHarness {
 private static final List<VisualMatrixHarness.Frame> FRAMES=VisualMatrixHarness.samples(5,0,1,2,3,4);
 private static int step;private static long at;private static boolean ready;
 @SubscribeEvent public static void render(ScreenEvent.Render.Post event){String output=System.getenv("RIVET_REORDER_UI");if(output==null||step>FRAMES.size())return;var mc=Minecraft.getInstance();if(System.currentTimeMillis()<at)return;at=System.currentTimeMillis()+500;
 try{if(!ready){if(!(mc.screen instanceof TitleScreen))return;ready=true;new java.io.File(output).mkdirs();System.out.println("RIVET_REORDER_UI_PLAN: frames="+FRAMES.size());}else{UiGeometryHarness.verify(mc.screen);net.minecraft.client.Screenshot.grab(new java.io.File(output),String.format("order-%03d.png",step),mc.getMainRenderTarget(),m->{});}
 if(step==FRAMES.size()){System.out.println("RIVET_REORDER_UI_OK: frames="+step+", input events, drag cancellation, valid drop, HUD save failure and rollback, GUI 1–3 and three profiles");step++;mc.stop();return;}
 var frame=FRAMES.get(step++);frame.apply();switch(frame.scene()){case 0->home(mc);case 1->hud(mc);case 2->skins(mc);case 3->hudFailure(mc);case 4->homeFailure(mc);}
 }catch(Throwable failure){System.out.println("RIVET_REORDER_UI_FAILED: step="+step);failure.printStackTrace();step=FRAMES.size()+1;mc.stop();}}
 private static void home(Minecraft mc)throws Exception{var before=HomeLayout.order();var visible=new HashMap<String,Boolean>();before.forEach(k->visible.put(k,HomeLayout.visible(k)));var screen=new HomeWidgetsScreen(null);mc.setScreen(screen);var b=screen.scrollLayout().content();double x=b.right()-12,y=b.y()+10;int target=Math.min(2,screen.visibleRows-1);if(target<1)throw new IllegalStateException("No home drop rows");double end=y+target*32;
 try{screen.mouseClicked(x,y,0);screen.mouseDragged(x,end,0,0,end-y);UiInputHarness.cancelDrag(screen);screen.mouseReleased(x,end,0);if(!HomeLayout.order().equals(before))throw new IllegalStateException("Esc changed home order");screen.mouseClicked(x,y,0);screen.mouseReleased(0,0,0);if(!HomeLayout.order().equals(before))throw new IllegalStateException("Outside changed home order");screen.mouseClicked(x,y,0);screen.mouseDragged(x,end,0,0,end-y);screen.mouseReleased(x,end,0);var expected=new ArrayList<>(before);expected.add(target,expected.remove(0));if(!HomeLayout.order().equals(expected))throw new IllegalStateException("Home drop failed");for(var k:before)if(HomeLayout.visible(k)!=visible.get(k))throw new IllegalStateException("Drag changed visibility");}finally{for(int n=0;n<before.size();n++)HomeLayout.moveTo(before.get(n),n);}screen.rebuildWidgets();screen.mouseClicked(x,y,0);screen.mouseDragged(x,end,0,0,end-y);}
 private static void hud(Minecraft mc){var before=new ArrayList<>(HudSettings.INSTANCE.order);var screen=new HudOrderScreen(null);mc.setScreen(screen);var b=screen.scrollLayout().content();double x=b.right()-12,y=b.y()+10,end=y+26;
 try{screen.mouseClicked(x,y,0);UiInputHarness.cancelDrag(screen);screen.mouseReleased(x,end,0);if(!HudSettings.INSTANCE.order.equals(before))throw new IllegalStateException("Esc changed HUD order");screen.mouseClicked(x,y,0);screen.mouseReleased(0,0,0);if(!HudSettings.INSTANCE.order.equals(before))throw new IllegalStateException("Outside changed HUD order");screen.mouseClicked(x,y,0);screen.mouseReleased(x,end,0);var expected=new ArrayList<>(before);expected.add(1,expected.remove(0));if(!HudSettings.INSTANCE.order.equals(expected))throw new IllegalStateException("HUD drop failed");}finally{HudSettings.INSTANCE.order.clear();HudSettings.INSTANCE.order.addAll(before);HudSettings.INSTANCE.save();}screen.mouseClicked(x,y,0);screen.mouseDragged(x,end,0,0,26);}
 private static void skins(Minecraft mc)throws Exception{var lib=new JsonObject();var entries=new JsonArray();for(int n=0;n<3;n++){var row=new JsonObject();row.addProperty("id",new UUID(0,n+1).toString());row.addProperty("name","Скин "+(n+1));row.addProperty("hash","");row.addProperty("slim",false);entries.add(row);}lib.add("entries",entries);SkinClient.library=lib;SkinClient.busy=false;dev.abros.rivet.network.Protocol.supportedFeatures=Set.of("skins","skin-names","skin-order");var screen=new SkinsScreen(null);mc.setScreen(screen);for(var child:screen.children())if(child instanceof Button button&&Set.of("↑","↓").contains(button.getMessage().getString()))throw new IllegalStateException("Arrow controls returned");var b=screen.scrollLayout().content();double x=b.right()-12,y=b.y()+AccessibilityScreen.skinStride()+10,end=y+AccessibilityScreen.skinStride();if(!screen.mouseClicked(x,y,0))throw new IllegalStateException("Skin grip unavailable");UiInputHarness.cancelDrag(screen);screen.mouseReleased(x,end,0);if(SkinClient.busy)throw new IllegalStateException("Esc sent skin request");screen.mouseClicked(x,y,0);screen.mouseReleased(0,0,0);if(SkinClient.busy)throw new IllegalStateException("Outside sent skin request");screen.mouseClicked(x,y,0);screen.mouseReleased(x,y,0);if(SkinClient.busy)throw new IllegalStateException("Same row sent skin request");screen.mouseClicked(x,y,0);screen.mouseReleased(x,end,0);if(!SkinClient.busy)throw new IllegalStateException("Valid skin drop did not request reorder");UiInputHarness.escape(screen);if(mc.screen!=screen)throw new IllegalStateException("Escape interrupted a pending skin reorder");screen.onClose();if(mc.screen!=screen)throw new IllegalStateException("Close interrupted a pending skin reorder");var targetField=SkinsScreen.class.getDeclaredField("moveTarget");targetField.setAccessible(true);targetField.setInt(screen,2);var first=entries.get(0);entries.set(0,entries.get(1));entries.set(1,first);skinReply("");if(!SkinClient.busy)throw new IllegalStateException("Skin reorder stopped before reaching its target");screen.onClose();if(mc.screen!=screen)throw new IllegalStateException("Close interrupted the second skin move");first=entries.get(1);entries.set(1,entries.get(2));entries.set(2,first);skinReply("");screen.onClose();if(mc.screen==screen)throw new IllegalStateException("Completed skin reorder blocked exit");screen=new SkinsScreen(null);mc.setScreen(screen);screen.mouseClicked(x,y,0);screen.mouseReleased(x,end,0);skinReply("Ошибка тестового запроса");screen.onClose();if(mc.screen==screen)throw new IllegalStateException("Skin error blocked exit");SkinClient.status="";var pending=SkinClient.class.getDeclaredField("session");pending.setAccessible(true);((dev.abros.rivet.core.RequestSession)pending.get(null)).cancel();SkinClient.busy=false;screen=new SkinsScreen(null);mc.setScreen(screen);screen.mouseClicked(x,y,0);screen.mouseDragged(x,end,0,0,end-y);}
 private static void skinReply(String error)throws Exception{var pending=SkinClient.class.getDeclaredField("pending");pending.setAccessible(true);var reply=new JsonObject();reply.addProperty("request",(String)pending.get(null));reply.addProperty("kind",error.isEmpty()?"library":"error");if(error.isEmpty()){reply.add("entries",SkinClient.library.getAsJsonArray("entries"));var profile=new JsonObject();profile.addProperty("owner",new UUID(0,0).toString());profile.addProperty("hash","");profile.addProperty("active","");reply.add("profile",profile);}else reply.addProperty("text",error);var receive=SkinClient.class.getDeclaredMethod("receive",JsonObject.class);receive.setAccessible(true);receive.invoke(null,reply);}
 private static void hudFailure(Minecraft mc)throws Exception{
  var settings=HudSettings.INSTANCE;var before=new ArrayList<>(settings.order);String oldError=settings.error;
  var screen=new HudOrderScreen(null);mc.setScreen(screen);var bounds=screen.scrollLayout().content();double x=bounds.right()-12,y=bounds.y()+10;
  var file=mc.gameDirectory.toPath().resolve("rivet/hud.json");var backup=file.resolveSibling("hud-reorder-test-"+UUID.randomUUID()+".backup");boolean existed=java.nio.file.Files.exists(file);boolean blocked=false;
  java.nio.file.Files.createDirectories(file.getParent());if(existed)java.nio.file.Files.move(file,backup);
  try{java.nio.file.Files.createDirectory(file);blocked=true;java.nio.file.Files.writeString(file.resolve("blocked"),"Intentional test of a failed save");screen.mouseClicked(x,y,0);screen.mouseReleased(x,y+26,0);if(!settings.order.equals(before))throw new IllegalStateException("Failed save did not roll back HUD order");var notice=HudOrderScreen.class.getDeclaredField("notice");notice.setAccessible(true);if(((String)notice.get(screen)).isEmpty()||settings.error.isEmpty())throw new IllegalStateException("Failed save did not report an error");}
  finally{if(blocked){java.nio.file.Files.deleteIfExists(file.resolve("blocked"));java.nio.file.Files.deleteIfExists(file);}if(existed)java.nio.file.Files.move(backup,file);settings.order.clear();settings.order.addAll(before);settings.error=oldError;}
 }

 private static void homeFailure(Minecraft mc)throws Exception{
  var original=HomeLayout.order();var originalVisibility=new HashMap<String,Boolean>();original.forEach(k->originalVisibility.put(k,HomeLayout.visible(k)));var orderField=HomeLayout.class.getDeclaredField("order");orderField.setAccessible(true);var hiddenField=HomeLayout.class.getDeclaredField("hidden");hiddenField.setAccessible(true);var originalHidden=new HashSet<>((Set<String>)hiddenField.get(null));var custom=new ArrayList<>(original);Collections.reverse(custom);orderField.set(null,custom);var customHidden=new HashSet<>(originalHidden);customHidden.add(custom.get(0));hiddenField.set(null,customHidden);var before=HomeLayout.order();var visibility=new HashMap<String,Boolean>();before.forEach(k->visibility.put(k,HomeLayout.visible(k)));
  var file=mc.gameDirectory.toPath().resolve("rivet/home-layout.json");var backup=file.resolveSibling("home-test-"+UUID.randomUUID()+".backup");boolean existed=java.nio.file.Files.exists(file),blocked=false;
  java.nio.file.Files.createDirectories(file.getParent());if(existed)java.nio.file.Files.move(file,backup);
  try{java.nio.file.Files.createDirectory(file);blocked=true;java.nio.file.Files.writeString(file.resolve("blocked"),"Intentional failed save");
   for(int action=0;action<3;action++){boolean failed=false;try{switch(action){case 0->HomeLayout.toggle(before.get(0));case 1->HomeLayout.reset();case 2->HomeLayout.moveTo(before.get(0),1);}}catch(Exception expected){failed=true;}if(!failed)throw new IllegalStateException("Home save unexpectedly succeeded");if(!HomeLayout.order().equals(before))throw new IllegalStateException("Failed home save changed order");for(var key:before)if(HomeLayout.visible(key)!=visibility.get(key))throw new IllegalStateException("Failed home save changed visibility");}
  }finally{if(blocked){java.nio.file.Files.deleteIfExists(file.resolve("blocked"));java.nio.file.Files.deleteIfExists(file);}if(existed)java.nio.file.Files.move(backup,file);orderField.set(null,new ArrayList<>(original));hiddenField.set(null,originalHidden);}
  mc.setScreen(new HomeWidgetsScreen(null));
 }

}
