package dev.abros.rivet.client;
import com.google.gson.*;
import com.mojang.blaze3d.platform.InputConstants;
import net.minecraft.client.Minecraft;
import net.minecraft.client.gui.GuiGraphics;
import net.minecraft.client.gui.screens.*;
import net.minecraft.network.chat.Component;
import net.neoforged.api.distmarker.Dist;
import net.neoforged.bus.api.SubscribeEvent;
import net.neoforged.fml.common.EventBusSubscriber;
import java.util.*;
/** Opt-in regression matrix for selected release UI improvements. Excluded from release JARs. */
@EventBusSubscriber(modid="rivet",value=Dist.CLIENT)
public final class RivetReleaseReviewHarness {
 private static boolean connecting;private static int stage,step,theme;private static long next;private static InputConstants.Key oldKey;
 private static final int[][] WINDOWS={{960,600},{1600,1000},{2560,1080}};
 private static final String[] SCENES={"themes","search","appearance","widget","notifications","tab","chat","navigation","admin","hud-editor"};
 @SubscribeEvent public static void tick(net.neoforged.neoforge.client.event.ClientTickEvent.Post e){if(System.getenv("RIVET_RELEASE_REVIEW")==null)return;var mc=Minecraft.getInstance();long now=System.currentTimeMillis();try{
  if(!connecting&&mc.screen instanceof TitleScreen){connecting=true;mc.options.pauseOnLostFocus=false;var data=new net.minecraft.client.multiplayer.ServerData("Rivet test","127.0.0.1:25569",net.minecraft.client.multiplayer.ServerData.Type.OTHER);ConnectScreen.startConnecting(mc.screen,mc,net.minecraft.client.multiplayer.resolver.ServerAddress.parseString(data.ip),data,false,null);}
  if(mc.player==null||!SocialClient.available()||SocialClient.players.isEmpty()||now<next)return;
  if(stage==0){theme=UiPalette.selected();mc.player.connection.sendCommand("time set day");check(SettingsSearchScreen.search("прозрачность TAB").stream().anyMatch(v->v.section()==3&&v.id().equals("opacity")),"Settings search failed");check(ChatHints.lines("!привет").getFirst().contains("общий"),"Global contextual hint");check(ChatHints.lines("[pos]").getLast().contains("Xaero"),"Navigation contextual hint");check(ChatHints.lines("/help").isEmpty(),"Hints cover commands");check(ChatHints.channel("#Город: привет").contains("Город"),"Group channel state");check(UiKit.fit(mc.font,"long",0).isEmpty(),"Zero width fit");stage=1;next=now+500;return;}
  if(stage==1){if(step>=120){step=0;stage=3;return;}int group=step/10,window=group/4,scale=group%4+1;org.lwjgl.glfw.GLFW.glfwSetWindowSize(mc.getWindow().getWindow(),WINDOWS[window][0],WINDOWS[window][1]);mc.options.guiScale().set(scale);mc.resizeDisplay();mc.setScreen(scene(step%10));stage=2;next=now+220;return;}
  if(stage==2){verify(mc.screen);capture("layout-"+step+"-"+SCENES[step%10]+".png");step++;stage=1;next=now+30;return;}
  if(stage==3){if(step>=UiPalette.names().size()){UiPalette.preview(theme);step=0;stage=5;return;}mc.options.guiScale().set(3);org.lwjgl.glfw.GLFW.glfwSetWindowSize(mc.getWindow().getWindow(),1600,1000);mc.resizeDisplay();UiPalette.preview(step);for(int color:new int[]{UiKit.text(),UiKit.muted(),UiPalette.color(0xFFEF7777),UiPalette.color(0xFF79CBA6),UiPalette.color(0xFF82909C)})check(contrast(color,UiKit.surface())>=3,"Low semantic contrast "+UiPalette.id()+" "+Integer.toHexString(color));mc.setScreen(new StatesScreen());stage=4;next=now+220;return;}
  if(stage==4){capture("states-"+UiPalette.id()+".png");step++;stage=3;next=now+30;return;}
  if(stage==5){oldKey=RivetHud.INTERACT.getKey();RivetHud.INTERACT.setKey(InputConstants.Type.KEYSYM.getOrCreate(80));net.minecraft.client.KeyMapping.resetMapping();mc.setScreen(null);mc.options.keyPlayerList.setDown(true);net.minecraft.client.KeyMapping.click(RivetHud.INTERACT.getKey());RivetHud.tick();check(mc.screen instanceof HudInteractionScreen c&&c.tabVisible(),"TAB cursor activation");mc.options.keyPlayerList.setDown(false);stage=6;next=now+250;return;}
  if(stage==6){check(!RivetTab.hits.isEmpty(),"TAB hit targets missing");capture("cursor.png");mc.screen.keyPressed(80,0,0);check(mc.screen==null,"Cursor toggle close");mc.setScreen(new HudInteractionScreen(false,null,true));mc.setScreen(new net.minecraft.client.gui.screens.inventory.InventoryScreen(mc.player));check(!RivetHud.INTERACT.isDown(),"Cursor key stuck after inventory");mc.setScreen(new HudInteractionScreen(false,null,false));mc.screen.keyPressed(256,0,0);check(mc.screen==null,"Cursor escape");RivetHud.INTERACT.setKey(oldKey);net.minecraft.client.KeyMapping.resetMapping();mc.player.connection.sendCommand("setblock 0 -60 0 minecraft:chest[facing=north,type=single]");mc.player.connection.sendCommand("tp @s 0.5 -60 -5 0 5");stage=7;step=0;next=now+800;return;}
  if(stage==7){capture("stock-"+step+".png");switch(step){case 0->mc.player.connection.sendCommand("tp @s 5 -60 0.5 90 5");case 1->{mc.player.connection.sendCommand("fill 2 -60 -1 2 -56 1 minecraft:stone");}case 2->{mc.player.connection.sendCommand("fill 2 -60 -1 2 -56 1 minecraft:air");mc.player.connection.sendCommand("setblock 0 -60 0 minecraft:barrel");}case 3->{mc.player.connection.sendCommand("setblock 0 -60 0 minecraft:chest[facing=north,type=left]");mc.player.connection.sendCommand("setblock 1 -60 0 minecraft:chest[facing=north,type=right]");}case 4->mc.player.connection.sendCommand("tp @s 16 -60 0.5 90 5");case 5->mc.player.connection.sendCommand("tp @s 1000 -60 0.5 90 5");default->{StockHologramRenderer.clear();mc.player.connection.sendCommand("tp @s 5 -60 0.5 90 5");UiPalette.preview(theme);mc.options.guiScale().set(3);org.lwjgl.glfw.GLFW.glfwSetWindowSize(mc.getWindow().getWindow(),1600,1000);mc.resizeDisplay();mc.setScreen(new AccessibilityScreen(null));System.out.println("RIVET_RELEASE_REVIEW_OK 120 layouts + 20 semantic palettes + cursor lifecycle + stocks visible/occluded/barrel/double/range/unloaded");stage=8;return;}}step++;next=now+650;return;}
 }catch(Throwable failure){System.out.println("RIVET_RELEASE_REVIEW_FAILED stage="+stage+" step="+step);failure.printStackTrace();stage=99;next=Long.MAX_VALUE;}}
 private static Screen scene(int n){return switch(n){case 0->new UiThemePicker(null);case 1->new SettingsSearchScreen(null);case 2->new AccessibilityScreen(null);case 3->new HudSettingsScreen(null);case 4->new HudSettingsScreen(null,3);case 5->new SocialSettingsScreen(null,0);case 6->new SocialSettingsScreen(null,1);case 7->new NavigationSettingsScreen(null);case 8->new ServerMenuScreen(null,"admin");default->new HudInteractionScreen(true,null);};}
 private static void verify(Screen screen){UiGeometryHarness.verify(screen);for(var child:screen.children())if(child instanceof net.minecraft.client.gui.components.AbstractWidget w&&w.visible)check(w.getX()>=0&&w.getY()>=0&&w.getX()+w.getWidth()<=screen.width&&w.getY()+w.getHeight()<=screen.height,"Widget outside screen "+screen.getClass().getSimpleName()+" "+w.getMessage());}
 @SubscribeEvent public static void render(net.neoforged.neoforge.client.event.RenderLevelStageEvent e){if(System.getenv("RIVET_RELEASE_REVIEW")==null||stage!=7)return;var row=new JsonObject();row.addProperty("dimension","minecraft:overworld");row.addProperty("x",.5);row.addProperty("y",-58.5);row.addProperty("z",.5);row.addProperty("title","Хранилище · Материалы для моста");row.addProperty("remainingTypes",0);var item=new JsonObject();item.addProperty("item","minecraft:stone");item.addProperty("have",32);item.addProperty("amount",64);item.addProperty("missing",32);var items=new JsonArray();items.add(item);row.add("resources",items);var panels=new JsonArray();panels.add(row);var snapshot=new JsonObject();snapshot.add("holograms",panels);StockHologramRenderer.receive(snapshot);}
 private static final class StatesScreen extends Screen {
  StatesScreen(){super(Component.literal("Проверка длинного текста и состояний"));}
  @Override protected void init(){String longText="Очень длинное название объединения и сервера ".repeat(6);addRenderableWidget(new UiSummaryCard(24,36,Math.min(width-48,320),longText,longText,List.of(longText,longText),0xFF79CBA6,()->{}));var disabled=UiActions.button(Component.literal("Недоступное действие"),UiActions.Tone.NORMAL,"",b->{}).bounds(24,132,180,20).build();disabled.active=false;addRenderableWidget(disabled);}
  @Override public void render(GuiGraphics g,int x,int y,float d){g.fill(0,0,width,height,UiKit.surface());super.render(g,x,y,d);UiState.draw(g,font,UiState.Kind.ERROR,"Не удалось загрузить","Обновите раздел или повторите позже.",24,166,Math.min(width-48,320),height-8);Ui.text(g,font,"Ошибка · Успех · Выключено",24,12,UiKit.text(),false);}
 }
 private static void capture(String name){var dir=new java.io.File("/private/tmp/rivet-release-review");dir.mkdirs();var mc=Minecraft.getInstance();UiCaptureHarness.grab(dir,name,mc.getMainRenderTarget(),m->{});}
 private static double luminance(int color){double result=0;double[] w={.0722,.7152,.2126};for(int n=0;n<3;n++){double c=((color>>(8*n))&255)/255d;result+=w[n]*(c<=.04045?c/12.92:Math.pow((c+.055)/1.055,2.4));}return result;}
 private static double contrast(int a,int b){double x=luminance(a),y=luminance(b);return (Math.max(x,y)+.05)/(Math.min(x,y)+.05);}
 private static void check(boolean ok,String text){if(!ok)throw new IllegalStateException(text);}
}
