package dev.abros.rivet.client;
import net.minecraft.client.Minecraft;
import net.minecraft.client.gui.screens.*;
import net.minecraft.network.chat.Component;
import net.neoforged.api.distmarker.Dist;
import net.neoforged.bus.api.SubscribeEvent;
import net.neoforged.fml.common.EventBusSubscriber;
@EventBusSubscriber(modid="rivet",value=Dist.CLIENT)
public final class RivetAdapterHarness {
 private static boolean connecting,done;
 @SubscribeEvent public static void tick(net.neoforged.neoforge.client.event.ClientTickEvent.Post e){if(System.getenv("RIVET_ADAPTER_REVIEW")==null||done)return;var mc=Minecraft.getInstance();if(!connecting&&mc.screen instanceof TitleScreen){connecting=true;mc.options.pauseOnLostFocus=false;var data=new net.minecraft.client.multiplayer.ServerData("Rivet test","127.0.0.1:25569",net.minecraft.client.multiplayer.ServerData.Type.OTHER);ConnectScreen.startConnecting(mc.screen,mc,net.minecraft.client.multiplayer.resolver.ServerAddress.parseString(data.ip),data,false,null);}if(mc.player==null||!SocialClient.available()||SocialClient.players.isEmpty())return;done=true;try{boolean installed=net.neoforged.fml.ModList.get().isLoaded("xaerominimap");if(ClientCompatibilityRegistry.xaeroAvailable()!=installed)throw new IllegalStateException("Xaero availability mismatch");if(!installed){ClientCompatibilityRegistry.updateMap(new com.google.gson.JsonArray(),new com.google.gson.JsonArray());ClientCompatibilityRegistry.clearMap();}if(!net.neoforged.fml.ModList.get().isLoaded("plasmovoice")&&!ClientCompatibilityRegistry.voice().getFirst().contains("Не установлен"))throw new IllegalStateException("Voice absence mismatch");if(net.neoforged.fml.ModList.get().isLoaded("plasmovoice")){var voice=ClientCompatibilityRegistry.voice();if(voice.getFirst().contains("Несовместимый")||voice.getFirst().contains("Ошибка"))throw new IllegalStateException("Voice diagnostics failed: "+voice);System.out.println("RIVET_VOICE_CLIENT_OK "+voice);}if(installed&&!ClientCompatibilityRegistry.xaeroEditorAvailable())throw new IllegalStateException("Xaero editor contract unsupported");boolean worldMap=net.neoforged.fml.ModList.get().isLoaded("xaeroworldmap");if(ClientCompatibilityRegistry.worldMapAvailable()!=worldMap)throw new IllegalStateException("World Map availability mismatch: "+ClientCompatibilityRegistry.status());ClientCompatibilityRegistry.reset();mc.setScreen(new ServerMenuScreen(null,"home"));System.out.println("RIVET_ADAPTER_REVIEW_OK xaero="+installed+" "+ClientCompatibilityRegistry.status());}catch(Throwable failure){System.out.println("RIVET_ADAPTER_REVIEW_FAILED");failure.printStackTrace();}}
}
