package dev.abros.rivet.client;
import com.google.gson.JsonObject;
import net.minecraft.client.Minecraft;
import net.minecraft.client.gui.screens.*;
import net.minecraft.network.chat.Component;
import net.neoforged.api.distmarker.Dist;
import net.neoforged.bus.api.SubscribeEvent;
import net.neoforged.fml.common.EventBusSubscriber;
@EventBusSubscriber(modid="rivet",value=Dist.CLIENT)
public final class RivetChatIdentityHarness {
 private static boolean connecting;private static int stage;private static long next;
 @SubscribeEvent public static void tick(net.neoforged.neoforge.client.event.ClientTickEvent.Post event){
  if(System.getenv("RIVET_CHAT_IDENTITY_REVIEW")==null||stage==10)return;var mc=Minecraft.getInstance();long now=System.currentTimeMillis();
  if(!connecting&&mc.screen instanceof TitleScreen){connecting=true;mc.options.pauseOnLostFocus=false;var server=new net.minecraft.client.multiplayer.ServerData("Rivet test","127.0.0.1:25569",net.minecraft.client.multiplayer.ServerData.Type.OTHER);ConnectScreen.startConnecting(mc.screen,mc,net.minecraft.client.multiplayer.resolver.ServerAddress.parseString(server.ip),server,false,null);}
  if(mc.player==null||!SocialClient.available()||now<next)return;
  if(stage==0){mc.options.guiScale().set(3);mc.resizeDisplay();mc.getToasts().clear();mc.setScreen(new ChatScreen(""));stage=1;next=now+2500;return;}
  if(stage==1){ServerMenuClient.request("state");var request=new JsonObject();request.addProperty("action","community");request.addProperty("section","groups");request.addProperty("op","create");request.addProperty("title","RivetChatReview");request.addProperty("description","Local chat presentation review");request.addProperty("type","Команда");if(!RivetHud.snapshot.toString().contains("RivetChatReview"))ServerMenuClient.request(request);stage=2;next=now+2500;return;}
  if(stage==2){mc.player.connection.sendChat("Проверка локального канала [item] [pos]");stage=3;next=now+1300;return;}
  if(stage==3){SocialClient.players.clear();mc.player.connection.sendChat("!Проверка общего канала [pos]");stage=4;next=now+1300;return;}
  if(stage==4){mc.player.connection.sendChat("#RivetChatReview: Проверка канала объединения [pos]");stage=5;next=now+2500;return;}
  if(stage==5){var messages=((dev.abros.rivet.mixin.ChatHistoryAccessor)mc.gui.getChat()).rivet$messages();for(String label:java.util.List.of("локального","общего","объединения")){var message=messages.stream().filter(m->m.content().getString().contains("Проверка ")&&m.content().getString().contains(label)).findFirst().orElseThrow(()->new IllegalStateException("Missing channel: "+label));check(message.content().getString().contains("[ENGINEER] Dev [TEST]"),"Missing LP metadata: "+label+message.content().getString());var lines=mc.font.split(message.content(),160);check(mc.player.getUUID().equals(SocialClient.chatHead(lines.getFirst())),"Missing head: "+label);for(int n=1;n<lines.size();n++)check(SocialClient.chatHead(lines.get(n))==null,"Duplicate head on wrapped line");boolean heads=SocialSettings.INSTANCE.heads;SocialSettings.INSTANCE.heads=false;check(SocialClient.chatHead(lines.getFirst())==null,"Heads toggle ignored");SocialSettings.INSTANCE.heads=heads;}
   check(HudProfile.fullText().contains("[ENGINEER]")&&HudProfile.fullText().contains("[TEST]"),"HUD metadata absent");capture("all-chat-channels");mc.options.keyPlayerList.setDown(true);stage=6;next=now+1600;return;}
  if(stage==6){var profile=SocialClient.players.get(mc.player.getUUID());check(profile!=null&&profile.get("prefix").getAsString().contains("[ENGINEER]")&&profile.get("suffix").getAsString().contains("[TEST]"),"TAB metadata absent");mc.setScreen(new HudInteractionScreen(false,null,true));stage=7;next=now+300;return;}
  if(stage==7){capture("tab-widget-metadata");mc.options.keyPlayerList.setDown(false);mc.setScreen(new ChatScreen("#"));stage=8;next=now+400;return;}
  if(stage==8){var chat=(ChatScreen)mc.screen;var input=((dev.abros.rivet.mixin.ChatInputAccessor)chat).rivet$input();var nativeList=((dev.abros.rivet.mixin.ChatInputAccessor)chat).rivet$suggestions();check(SocialChatControls.groupSuggestions("#",1).getList().stream().anyMatch(v->v.getText().equals("RivetChatReview: ")),"Membership missing");check(nativeList.isVisible(),"Native completion list hidden");capture("group-suggestions");ServerMenuClient.state.addProperty("chatEnabled",false);check(!SocialSettings.INSTANCE.chat()&&SocialChatControls.groupSuggestions("#",1)==null,"Server disable ignored");ServerMenuClient.state.addProperty("chatEnabled",true);input.setValue("#RivetChatR");input.setCursorPosition(input.getValue().length());nativeList.updateCommandInfo();check(SocialChatControls.groupSuggestions(input.getValue(),input.getCursorPosition()).getList().size()==1,"Group filtering failed");check(chat.keyPressed(org.lwjgl.glfw.GLFW.GLFW_KEY_TAB,0,0)&&input.getValue().equals("#RivetChatReview: "),"Native Tab completion failed");check(SocialChatControls.groupSuggestions(input.getValue(),input.getCursorPosition())==null,"Suggestions interfere with body");input.setValue("/");input.setCursorPosition(1);nativeList.updateCommandInfo();mc.setScreen(new ChatScreen("#"));System.out.println("RIVET_CHAT_IDENTITY_OK native group suggestions + Tab completion + server switch + chat metadata");stage=9;next=now+1000;}
  if(stage==9){
   var chat=new ChatScreen("");mc.setScreen(chat);check(chat.charTyped('D',0)&&chat.charTyped('e',0),"Nickname typing failed");var input=((dev.abros.rivet.mixin.ChatInputAccessor)chat).rivet$input();var suggestions=((dev.abros.rivet.mixin.ChatInputAccessor)chat).rivet$suggestions();suggestions.updateCommandInfo();chat.keyPressed(org.lwjgl.glfw.GLFW.GLFW_KEY_TAB,0,0);if(!input.getValue().equals("Dev"))chat.keyPressed(org.lwjgl.glfw.GLFW.GLFW_KEY_TAB,0,0);System.out.println("RIVET_NATIVE_NICKNAME_TAB value="+input.getValue());check(input.getValue().equals("Dev"),"Vanilla nickname Tab completion failed");check(chat.charTyped('x',0),"Native typing failed");chat.keyPressed(org.lwjgl.glfw.GLFW.GLFW_KEY_BACKSPACE,0,0);check(input.getValue().equals("Dev"),"Native backspace failed");
   var root=mc.player.connection.getCommands().getRoot().getChild("rivet");var status=root.getChild("status");check(status!=null&&status.getChild("available")==null&&status.getChild("busy")==null&&status.getChild("help")==null&&status.getChild("afk")==null,"Manual status commands remain");
   var messages=((dev.abros.rivet.mixin.ChatHistoryAccessor)mc.gui.getChat()).rivet$messages();var local=messages.stream().filter(m->m.content().getString().contains("Проверка локального канала [item]")).findFirst().orElseThrow(()->new IllegalStateException("Item token was transformed"));var position=coordinateStyle(local.content());check(position!=null&&position.getClickEvent().getValue().endsWith(" Dev"),"Coordinates lack click or sender name");
   mc.player.connection.sendCommand("tp @s ~100 ~ ~100");stage=11;next=now+1000;return;
  }
  if(stage==11){var messages=((dev.abros.rivet.mixin.ChatHistoryAccessor)mc.gui.getChat()).rivet$messages();var message=messages.stream().filter(m->m.content().getString().contains("Проверка локального канала [item]")).findFirst().orElseThrow();var chat=new ChatScreen("");mc.setScreen(chat);try{var method=Screen.class.getDeclaredMethod("handleComponentClicked",net.minecraft.network.chat.Style.class);method.setAccessible(true);check((boolean)method.invoke(chat,coordinateStyle(message.content())),"Coordinate click not handled");}catch(ReflectiveOperationException error){throw new IllegalStateException(error);}stage=12;next=now+1200;return;}
  if(stage==12){check(DirectionCue.hasTarget(),"Coordinate click did not start navigation");check(DirectionCue.mapRows().get(0).getAsJsonObject().get("title").getAsString().equals("Место от Dev"),"Navigation sender missing");check(DirectionCue.bounds.width()>0,"Navigation not rendered with chat open");check(ChatHints.lines("@Dev").stream().noneMatch(line->line.contains("@")||line.contains("упомин")),"Mention hint remains");check(SettingsSearchScreen.search("упомин").isEmpty(),"Mention setting remains");capture("navigation-with-chat");var point=DirectionCue.mapRows().get(0).getAsJsonObject().getAsJsonObject("location").deepCopy();point.addProperty("name","Место от Dev");check(DirectionCue.click(DirectionCue.bounds.right()-9,DirectionCue.bounds.y()+8),"Stop button ignored");check(!DirectionCue.hasTarget()&&DirectionCue.mapRows().isEmpty(),"Stopped route remains active");DirectionCue.receive(point);check(DirectionCue.hasTarget(),"New route cannot start after stop");System.out.println("RIVET_FINAL_CHAT_OK native nickname completion + typing/backspace + literal item token + removed status commands + coordinate click/navigation with chat + manual stop + removed mention hints/settings");stage=10;mc.setScreen(new ChatScreen(""));return;}


 }

 private static net.minecraft.network.chat.Style coordinateStyle(Component component){var click=component.getStyle().getClickEvent();if(click!=null&&click.getValue().startsWith("/rivet direction "))return component.getStyle();for(var child:component.getSiblings()){var found=coordinateStyle(child);if(found!=null)return found;}return null;}
 private static void capture(String name){var dir=new java.io.File("/private/tmp/rivet-chat-identity");dir.mkdirs();var mc=Minecraft.getInstance();net.minecraft.client.Screenshot.grab(dir,name+".png",mc.getMainRenderTarget(),msg->{});}
 private static void check(boolean ok,String message){if(!ok)throw new IllegalStateException(message);}
}
