package dev.abros.rivet.client;
import com.google.gson.*;
import java.util.*;
import net.minecraft.client.Minecraft;
import net.minecraft.client.gui.screens.*;
import net.minecraft.client.multiplayer.PlayerInfo;
import net.minecraft.client.gui.GuiGraphics;
import net.minecraft.network.chat.Component;
import net.neoforged.api.distmarker.Dist;
import net.neoforged.bus.api.SubscribeEvent;
import net.neoforged.fml.common.EventBusSubscriber;
/** Opt-in real-server social fixture. Every class is excluded from release JARs. */
@EventBusSubscriber(modid="rivet",value=Dist.CLIENT)
public final class RivetSocialWorldHarness {
 private static boolean connecting;private static int stage,frame;private static long next;private static int originalTheme;private static boolean captured;
 private static final List<PlayerInfo> sample=new ArrayList<>();
 @SubscribeEvent public static void tick(net.neoforged.neoforge.client.event.ClientTickEvent.Post e){if(System.getenv("RIVET_SOCIAL_WORLD")==null)return;var mc=Minecraft.getInstance();long now=System.currentTimeMillis();if(!connecting&&mc.screen instanceof TitleScreen){connecting=true;var data=new net.minecraft.client.multiplayer.ServerData("Rivet test","127.0.0.1:25569",net.minecraft.client.multiplayer.ServerData.Type.OTHER);ConnectScreen.startConnecting(mc.screen,mc,net.minecraft.client.multiplayer.resolver.ServerAddress.parseString(data.ip),data,false,null);}if(mc.player==null||!SocialClient.available()||SocialClient.players.isEmpty())return;
  if(stage==0){mc.options.pauseOnLostFocus=false;check(ServerMenuClient.state.has("tabMode")&&ServerMenuClient.state.has("chatEnabled"),"Server display policy missing");String policy=SocialSettings.serverMode("tabMode");ServerMenuClient.state.addProperty("tabMode","compatible");check(!SocialSettings.INSTANCE.tab(),"Client ignored server compatible mode");ServerMenuClient.state.addProperty("tabMode",policy);System.out.println("RIVET_SERVER_DISPLAY_POLICY_OK");stage=1;next=now+7000;originalTheme=UiPalette.selected();mc.setScreen(new HudInteractionScreen(false,null,true));mc.player.connection.sendChat("!Проверка общего чата [pos]");mc.player.connection.sendChat("Локальный канал [pos]");mc.player.connection.sendCommand("rivet direction minecraft:overworld 10 10 -60");System.out.println("RIVET_SOCIAL_REAL_PACKETS_OK");}
  if(now<next)return;
  if(stage==1){check(DirectionCue.mapRows().size()==1&&DirectionCue.mapRows().get(0).getAsJsonObject().getAsJsonObject("location").get("y").getAsInt()==-60,"Server direction lost height");System.out.println("RIVET_DIRECTION_PACKET_OK exact height");check(SocialClient.players.containsKey(mc.player.getUUID()),"No self identity");check(SocialClient.players.get(mc.player.getUUID()).get("status").getAsString().isEmpty(),"Unexpected manual status");mc.setScreen(new ChatScreen(""));var chat=(ChatScreen)mc.screen;check(chat.charTyped('a',0),"Native chat refused first character");check(chat.charTyped('b',0),"Native chat refused second character");chat.keyPressed(259,0,0);check(((dev.abros.rivet.mixin.ChatInputAccessor)chat).rivet$input().getValue().equals("a"),"Native backspace did not delete");check(chat.children().stream().noneMatch(v->v instanceof net.minecraft.client.gui.components.Button),"Chat must have no extra buttons");System.out.println("RIVET_NATIVE_CHAT_INPUT_OK typing + backspace + no buttons");next=now+1000;stage=2;return;}
  if(stage==2){UiGeometryHarness.verify(mc.screen);capture(mc,"chat-native-controls.png");if(System.getenv("RIVET_SETTINGS_REVIEW")!=null){frame=0;stage=7;next=now+100;return;}for(int n=0;n<96;n++){UUID id=UUID.nameUUIDFromBytes(("tab-sample-"+n).getBytes(java.nio.charset.StandardCharsets.UTF_8));var profile=new com.mojang.authlib.GameProfile(id,"Player"+n);sample.add(new PlayerInfo(profile,false));var row=new JsonObject();row.addProperty("name",profile.getName());row.addProperty("prefix","&6Инженер очень длинной роли");row.addProperty("suffix","Мастер механизмов");row.addProperty("primaryGroup",n<32?"builder":n<64?"engineer":"player");row.addProperty("group","Город "+n%3);row.addProperty("status",n%4==0?"Отошёл":"");SocialClient.players.put(id,row);}stage=3;next=now+300;return;}
  if(stage==7){if(frame>=4){mc.options.guiScale().set(2);mc.resizeDisplay();mc.setScreen(new CommunityScreen(null,"home",""));var skins=mc.screen.children().stream().filter(v->v instanceof net.minecraft.client.gui.components.Button button&&button.getMessage().getString().equals("Скины")).findFirst().orElseThrow(()->new IllegalStateException("Skins library button missing"));((net.minecraft.client.gui.components.Button)skins).onPress();check(mc.screen instanceof SkinsScreen,"Skins button did not open library");UiGeometryHarness.verify(mc.screen);System.out.println("RIVET_SKINS_DIRECT_LIBRARY_OK");stage=72;next=now+300;return;}mc.options.guiScale().set(frame+1);mc.resizeDisplay();mc.setScreen(new ChatScreen(""));stage=71;next=now+350;return;}
  if(stage==72){capture(mc,"skins-direct-library.png");mc.options.guiScale().set(3);mc.resizeDisplay();mc.setScreen(new SocialSettingsScreen(null,0));stage=73;next=now+300;return;}
  if(stage==73){capture(mc,"settings-tab-final.png");mc.setScreen(new SocialSettingsScreen(null,1));stage=74;next=now+300;return;}
  if(stage==74){capture(mc,"settings-chat-final.png");if(System.getenv("RIVET_NAVIGATION_REVIEW")!=null){frame=0;stage=80;next=now+150;return;}mc.setScreen(null);stage=6;return;}
  if(stage==71){capture(mc,"chat-hint-gui-"+(frame+1)+".png");frame++;stage=7;next=now+150;return;}
  if(stage==3){if(frame>=UiPalette.names().size()*4){UiPalette.preview(originalTheme);mc.options.guiScale().set(3);mc.resizeDisplay();mc.setScreen(new SocialSettingsScreen(null));stage=4;next=now+800;return;}int scale=frame%4+1,theme=frame/4;UiPalette.preview(theme);mc.options.guiScale().set(scale);mc.resizeDisplay();RivetTab.reset();RivetTab.scroll(-12);mc.setScreen(new Preview());captured=false;next=now+350;stage=31;return;}
  if(stage==31){check(!RivetTab.hits.isEmpty(),"No rows");for(var hit:RivetTab.hits)check(hit.x()>=0&&hit.y()>=0&&hit.x()+hit.w()<=mc.screen.width&&hit.y()+hit.h()<=mc.screen.height,"TAB row escaped viewport");capture(mc,String.format("tab-theme-%02d-gui-%d.png",frame/4,frame%4+1));frame++;stage=3;next=now+200;return;}
  if(stage==4){UiGeometryHarness.verify(mc.screen);capture(mc,"settings-tab.png");frame=0;stage=40;next=now+300;return;}
  if(stage==40){if(frame>=28){mc.options.guiScale().set(3);mc.resizeDisplay();mc.setScreen(null);SocialClient.players.keySet().removeIf(id->mc.getConnection().getPlayerInfo(id)==null);System.out.println("RIVET_SOCIAL_GUI_MATRIX_OK all themes/scales + chat/settings");System.out.println("RIVET_SETTINGS_SHELL_OK 6 sections x GUI 1-4");stage=6;return;}int scale=frame%4+1,section=frame/4;mc.options.guiScale().set(scale);mc.resizeDisplay();mc.setScreen(section==6?new HudOrderScreen(null):UiSettingsShell.open(null,section));stage=41;next=now+300;return;}
  if(stage==41){UiGeometryHarness.verify(mc.screen);capture(mc,String.format("settings-section-%d-gui-%d.png",frame/4,frame%4+1));if(frame/4<6)check(mc.screen.children().stream().filter(v->v instanceof net.minecraft.client.gui.components.Button button&&UiSettingsShell.SECTIONS.contains(button.getMessage().getString())).count()==6,"Missing settings sections");if(frame/4==6){var screen=(HudOrderScreen)mc.screen;var b=screen.scrollLayout().content();var before=new ArrayList<>(HudSettings.INSTANCE.order);check(screen.mouseClicked(b.x()+12,b.y()+10,0),"Drag did not start");check(screen.mouseDragged(b.x()+12,b.y()+36,0,0,26),"Drag did not move");check(screen.mouseReleased(b.x()+12,b.y()+36,0),"Drop did not finish");check(HudSettings.INSTANCE.order.get(1).equals(before.getFirst()),"Drop did not reorder");HudSettings.INSTANCE.order.clear();HudSettings.INSTANCE.order.addAll(before);HudSettings.INSTANCE.save();System.out.println("RIVET_HUD_DRAG_OK GUI "+(frame%4+1));}frame++;stage=40;next=now+100;return;}

  if(stage==80){if(frame>=4){UiPalette.preview(originalTheme);mc.options.guiScale().set(3);mc.resizeDisplay();mc.setScreen(null);DirectionCue.clear();System.out.println("RIVET_NAVIGATION_REVIEW_OK GUI 1-4 + theme + disable + Xaero payload + dimension + opacity");stage=6;return;}mc.options.guiScale().set(frame+1);mc.resizeDisplay();UiPalette.preview(frame==3?1:originalTheme);mc.setScreen(new NavigationSettingsScreen(null));stage=81;next=now+350;return;}
  if(stage==81){UiGeometryHarness.verify(mc.screen);capture(mc,"navigation-settings-gui-"+(frame+1)+".png");DirectionCue.start(new dev.abros.rivet.core.CommunityLocation("Точка маршрута",mc.level.dimension().location().toString(),10,-60,10,false));var settings=HudSettings.INSTANCE;check(DirectionCue.mapRows().size()==1,"Missing Xaero route payload");check(DirectionCue.mapRows().get(0).getAsJsonObject().getAsJsonObject("location").get("y").getAsInt()==-60,"Route lost height");settings.directionXaero=false;check(DirectionCue.mapRows().isEmpty(),"Xaero toggle ignored");settings.directionXaero=true;settings.directionEnabled=false;check(DirectionCue.mapRows().isEmpty(),"Navigation disable ignored");settings.directionEnabled=true;settings.directionOpacity=frame==2?0:.85f;mc.setScreen(null);stage=82;next=now+1500;return;}
  if(stage==82){if(ClientCompatibilityRegistry.xaeroAvailable()){try{var field=ManagedXaeroLayer.class.getDeclaredField("previous");field.setAccessible(true);var layers=(java.util.Map<?,?>)field.get(null);var dataset=layers.get(net.minecraft.resources.ResourceLocation.fromNamespaceAndPath("rivet","navigation"));check(dataset!=null&&XaeroBridge.call(dataset,"get","active-navigation")!=null,"Xaero did not receive navigation waypoint");System.out.println("RIVET_XAERO_NAVIGATION_OK GUI "+(frame+1));}catch(ReflectiveOperationException ex){throw new IllegalStateException(ex);}}capture(mc,"navigation-cue-gui-"+(frame+1)+".png");HudSettings.INSTANCE.directionOpacity=.85f;if(frame==3){DirectionCue.start(new dev.abros.rivet.core.CommunityLocation("Другая точка","minecraft:the_nether",10,64,10,false));}mc.setScreen(new ChatScreen(""));stage=83;next=now+350;return;}
  if(stage==83){capture(mc,"chat-themed-gui-"+(frame+1)+".png");SocialSettings.INSTANCE.hints=false;mc.setScreen(new ChatScreen(""));stage=84;next=now+350;return;}
  if(stage==84){capture(mc,"chat-hints-off-gui-"+(frame+1)+".png");SocialSettings.INSTANCE.hints=true;frame++;stage=80;next=now+100;return;}

 }
 private static void capture(Minecraft mc,String name){net.minecraft.client.Screenshot.grab(new java.io.File("/private/tmp/rivet-social-preview"),name,mc.getMainRenderTarget(),msg->{});}
 private static void check(boolean valid,String text){if(!valid)throw new IllegalStateException(text);}
 private static final class Preview extends Screen {Preview(){super(Component.literal("TAB fixture"));}@Override public void render(GuiGraphics g,int x,int y,float d){RivetTab.draw(g,x,y,sample);}@Override public boolean isPauseScreen(){return false;}}
}
