package dev.abros.rivet.client;
import net.minecraft.client.Minecraft;
import net.minecraft.client.gui.screens.*;
import net.minecraft.client.gui.components.Button;
import dev.abros.rivet.core.CommunityLocation;
import net.neoforged.api.distmarker.Dist;
import net.neoforged.bus.api.SubscribeEvent;
import net.neoforged.fml.common.EventBusSubscriber;
/** Opt-in regression checks for page insets, editor navigation and destination arrival. */
@EventBusSubscriber(modid="rivet",value=Dist.CLIENT)
public final class RivetLayoutReviewHarness {
 private static boolean connecting;private static int stage,scale=2;private static long next;
 @SubscribeEvent public static void tick(net.neoforged.neoforge.client.event.ClientTickEvent.Post e){try{run(e);}catch(Throwable failure){System.out.println("RIVET_LAYOUT_REVIEW_FAILED stage="+stage);failure.printStackTrace();stage=9;Minecraft.getInstance().stop();}}
 private static void run(net.neoforged.neoforge.client.event.ClientTickEvent.Post e){
  if(System.getenv("RIVET_LAYOUT_REVIEW")==null||stage==9)return;var mc=Minecraft.getInstance();long now=System.currentTimeMillis();
  if(!connecting&&mc.screen instanceof TitleScreen){connecting=true;mc.options.pauseOnLostFocus=false;var data=new net.minecraft.client.multiplayer.ServerData("Rivet test","127.0.0.1:25569",net.minecraft.client.multiplayer.ServerData.Type.OTHER);ConnectScreen.startConnecting(mc.screen,mc,net.minecraft.client.multiplayer.resolver.ServerAddress.parseString(data.ip),data,false,null);}
  if(mc.player==null||!ServerMenuClient.available()||now<next)return;
  if(stage==0){mc.getToasts().clear();mc.options.guiScale().set(scale);mc.resizeDisplay();mc.setScreen(new ServerMenuScreen(null,"help"));stage=1;next=now+700;return;}
  if(stage==1){check(mc.screen instanceof ServerMenuScreen,"Help page missing");UiGeometryHarness.verify(mc.screen);capture("help-gui-"+scale);mc.setScreen(new SocialSettingsScreen(null,1));stage=2;next=now+300;return;}
  if(stage==2){UiGeometryHarness.verify(mc.screen);var owner=mc.screen;var buttons=owner.children().stream().filter(v->v instanceof Button).map(v->(Button)v).toList();var editors=buttons.stream().filter(v->v.getMessage().getString().equals("Редактор HUD…")).toList();if(!editors.isEmpty()){check(editors.size()==1,"Duplicate HUD editor");var button=editors.getFirst();var outer=UiDialog.fit(owner.width,owner.height,570,350);check(button.getBottom()==outer.body().bottom(),"HUD editor not pinned at bottom");for(var other:buttons)if(other!=button&&other.getX()==button.getX())check(other.getBottom()<=button.getY(),"Sidebar overlaps HUD editor");capture("settings-gui-"+scale);button.onPress();}else{var selector=buttons.stream().filter(v->v.getMessage().getString().endsWith(" ▾")).findFirst().orElseThrow(()->new IllegalStateException("Compact settings selector missing"));capture("settings-gui-"+scale);selector.onPress();check(mc.screen instanceof ChoicePopup,"Settings sections missing");var editor=mc.screen.children().stream().filter(v->v instanceof Button b&&b.getMessage().getString().equals("Редактор HUD")).map(v->(Button)v).findFirst().orElseThrow(()->new IllegalStateException("Compact HUD editor missing"));editor.onPress();}check(mc.screen instanceof HudInteractionScreen,"HUD editor did not open");mc.screen.onClose();check(mc.screen==owner,"HUD editor lost return screen");if(scale++<4){stage=0;return;}stage=3;}
  if(stage==3){var p=mc.player;var dim=mc.level.dimension().location().toString();int x=p.getBlockX(),y=p.getBlockY(),z=p.getBlockZ();DirectionCue.start(new CommunityLocation("Far","minecraft:the_nether",x,y,z,false));check(DirectionCue.hasTarget(),"Different dimension counted as arrival");DirectionCue.start(new CommunityLocation("Above",dim,x,y+20,z,false));check(DirectionCue.hasTarget(),"Wrong height counted as arrival");DirectionCue.start(new CommunityLocation("Far",dim,x+20,y,z,false));check(DirectionCue.hasTarget(),"Distant target cleared");DirectionCue.start(new CommunityLocation("Arrived",dim,x,y,z,false));check(!DirectionCue.hasTarget()&&DirectionCue.mapRows().isEmpty(),"Destination HUD or waypoint retained after arrival");check(SettingsSearchScreen.search("редактор hud").size()==1,"HUD search has stale duplicate links");mc.options.guiScale().set(3);mc.resizeDisplay();mc.player.connection.sendChat("!Проверка ссылки [pos]");mc.setScreen(new ChatScreen(""));stage=4;next=now+1500;return;}
  if(stage==4){var history=((dev.abros.rivet.mixin.ChatHistoryAccessor)mc.gui.getChat()).rivet$messages();var link=history.stream().filter(m->m.content().getString().contains("Проверка ссылки")).map(m->m.content().visit((style,text)->text.contains("↗")&&style.getClickEvent()!=null?java.util.Optional.of(style):java.util.Optional.<net.minecraft.network.chat.Style>empty(),net.minecraft.network.chat.Style.EMPTY)).filter(java.util.Optional::isPresent).map(java.util.Optional::get).findFirst().orElseThrow(()->new IllegalStateException("No coordinate link received"));check(link.isUnderlined()&&link.getHoverEvent()!=null&&link.getClickEvent().getAction()==net.minecraft.network.chat.ClickEvent.Action.RUN_COMMAND,"Coordinate link is not discoverable");check(mc.screen.handleComponentClicked(link),"Coordinate click not handled");capture("chat-coordinate-link");mc.setScreen(new ServerMenuScreen(null,"help"));System.out.println("RIVET_LAYOUT_REVIEW_OK GUI 2-4, HUD sidebar and return, arrival + dimension + height + live chat link");stage=9;}
 }
 private static void capture(String name){var output=new java.io.File("rivet-ui-layout");output.mkdirs();var mc=Minecraft.getInstance();UiCaptureHarness.grab(output,name+".png",mc.getMainRenderTarget(),msg->{});}
 private static void check(boolean ok,String message){if(!ok)throw new IllegalStateException(message);}
}
